#!/bin/bash
#

# This should not go into the dist file

git_colm=ssh://git@git.in.colm.net/colm.git
git_ragel=ssh://git@git.in.colm.net/ragel.git

dir=`mktemp -d /tmp/test.XXXXXX`

set -e

echo ========== STARTING ==========
echo working in $dir
echo

set -x
cd $dir

# Checkout colm and ragel.
mkdir git
cd git
git clone $git_colm
git clone $git_ragel
cd ..

#
# Build and install colm from dist, test the install.
#

cd git/colm
./autogen.sh
./configure --prefix=$dir/i1/colm
make dist
tar -zxvf colm-*.tar.gz
cd colm-*
./configure --prefix=$dir/i2/colm
make -j4
make install
cd ../test
COLM=$dir/i2/colm/bin/colm ./runtests.sh
cd ../../..

#
# Build and install ragel from dist, test the install.
#

cd git/ragel
./autogen.sh
./configure --prefix=$dir/i1/ragel --with-colm=$dir/i2/colm
make dist
tar -zxvf ragel-*.tar.gz
cd ragel-*
./configure --prefix=$dir/i2/ragel --with-colm=$dir/i2/colm
make -j4
make install
cd ../test
./autogen.sh
./configure \
		--prefix=$dir/i2/ragel-test-suite \
		--with-ragel=$dir/i2/ragel \
		--with-colm=$dir/i2/colm
make
./runtests
cd ../../..

echo ========== DONE ==========
echo files in $dir
echo 
