#!/bin/bash
#

# This should not go into the dist file

working=`mktemp -d /tmp/test.XXXXXX`

set -e

echo ========== STARTING ==========
echo working in $working
echo

# Go to the working directory, create the git dir.
set -x
cd $working
mkdir git

for package in colm ragel; do
	#
	# Make the dist, build and and install from the dist, then test the
	# install. Loop starts from working dir.
	#

	cd git
	git clone ssh://git@git.in.colm.net/$package.git

	cd $package
	./autogen.sh
	./configure \
			--prefix=$working/no-install \
			--with-deps=$working/targ
	make dist
	tar -zxvf $package-*.tar.gz
	cd $package-*
	./configure \
			--prefix=$working/targ \
			--with-deps=$working/targ
	make -j4
	make install
	cd ../test
	./autogen.sh
	./configure \
			--prefix=$working/no-install \
			--with-deps=$working/targ \
			--with-subject=$working/targ
	make
	./runtests
	cd ../../..
done

echo ========== DONE ==========
echo files in $working
echo 
