<start><_repeat_message><message><from_line>From thurston  Tue Jan  2 21:16:50 2007
</from_line><_repeat_header><header><header_name>Return-Path</header_name><colon>: </colon><header_content>&lt;unknown&gt;
</header_content></header><header><header_name>X-Spam-Level</header_name><colon>: </colon><header_content>*
</header_content></header><header><header_name>Received</header_name><colon>: </colon><header_content>from [109.111.71.111] (helo=twfmtr)
	by zifreax with smtp (Exim 4.43)
	id 1H1vfs-0005LN-HW; Tue, 2 Jan 2007 21:16:16 -0500
</header_content></header><header><header_name>Message-ID</header_name><colon>: </colon><header_content>&lt;459B113F.8050903@immoarthabitatge.com&gt;
</header_content></header><header><header_name>X-Keywords</header_name><colon>:                   </colon><header_content>
</header_content></header><header><header_name>X-UID</header_name><colon>: </colon><header_content>1
</header_content></header></_repeat_header><blank_line>
</blank_line><_repeat_simple_line><simple_line>Content-Type: text/html; charset=ISO-8859-1
</simple_line><simple_line>&lt;/body&gt;
</simple_line><simple_line>&lt;/html&gt;
</simple_line><simple_line>
</simple_line></_repeat_simple_line></message><message><from_line>From thurston  Wed Jan  3 02:35:48 2007
</from_line><_repeat_header><header><header_name>Return-Path</header_name><colon>: </colon><header_content>&lt;unknown&gt;
</header_content></header><header><header_name>X-Spam-Checker-Version</header_name><colon>: </colon><header_content>SpamAssassin 3.1.1 (2006-03-10) on mambo.cs.queensu.ca
</header_content></header><header><header_name>X-Spam-Level</header_name><colon>: </colon><header_content>**
</header_content></header><header><header_name>X-Spam-Status</header_name><colon>: </colon><header_content>No, score=2.9 required=5.0 tests=BAYES_20,EXTRA_MPART_TYPE,
	HTML_40_50,HTML_IMAGE_ONLY_16,HTML_MESSAGE,RCVD_IN_BL_SPAMCOP_NET 
	autolearn=no version=3.1.1
</header_content></header><header><header_name>X-Bogosity</header_name><colon>: </colon><header_content>Unsure, tests=bogofilter, spamicity=0.971708, version=1.0.2
</header_content></header><header><header_name>Status</header_name><colon>: </colon><header_content>RO
</header_content></header><header><header_name>X-UID</header_name><colon>: </colon><header_content>2
</header_content></header></_repeat_header><blank_line>
</blank_line><_repeat_simple_line><simple_line>------=_NextPart_000_0010_01C72F11.F137BD60
</simple_line><simple_line>	charset="windows-1252"
</simple_line><simple_line>Content-Transfer-Encoding: quoted-printable
</simple_line><simple_line>
</simple_line></_repeat_simple_line></message></_repeat_message></start>