<nested>
  <_repeat_id>
    <id>hello</id>
    <id>there</id>
    <id>and</id>
    <id>this</id>
    <id>is</id>
    <id>not</id>
  </_repeat_id>
</nested>
<nested>
  <_repeat_id>
    <id>hello</id>
    <_ignore_0001> </_ignore_0001>
    <id>there</id>
    <_ignore_0001> </_ignore_0001>
    <_T_nested_comment>
      <'('/>
      <_repeat_nc_item>
        <nc_item>
          <nc_data> </nc_data>
        </nc_item>
        <nc_item>
          <nested_comment>
            <'('/>
            <_repeat_nc_item>
              <nc_item>
                <nc_data>this is a nested comment /*sdf;asd_++_stuff</nc_data>
              </nc_item>
            </_repeat_nc_item>
            <')'/>
          </nested_comment>
        </nc_item>
        <nc_item>
          <nc_data> </nc_data>
        </nc_item>
      </_repeat_nc_item>
      <')'/>
    </_T_nested_comment>
    <_notoken/>
    <_ignore_0001> </_ignore_0001>
    <id>and</id>
    <_ignore_0001> </_ignore_0001>
    <id>this</id>
    <_ignore_0001> </_ignore_0001>
    <id>is</id>
    <_ignore_0001> </_ignore_0001>
    <id>not</id>
  </_repeat_id>
</nested>
hello there  and this is not
