#!/bin/bash
#

set -e
set -x

orig=../ragel/ragel-orig
cc=../ragel/ragel-cc
new=../ragel/ragel

CFLAGS="-O3 -Wall -Wno-unused-but-set-variable"

tc()
{
	ragel=$1
	cc=$2
	seconds=$3
	root=$4

	$ragel -F1 -o $root.cpp $root.rl
	$cc $CFLAGS -DPERF_TEST -I../aapl -DS=${seconds}ll -o $root.bin $root.cpp
	time ./$root.bin
}


t1=$cc
t2=$new

cases="mailbox1 strings1 strings2 rlscan cppscan1"

targ_time=10

for c in $cases; do
	( set +x; echo ---------------------------- )
	tc $t1 g++ $targ_time $c
	tc $t2 g++ $targ_time $c
	( set +x; echo )
	( set +x; echo )
done

