<start><_repeat_item><item><statement><call><id>print</id><_literal_000d>(</_literal_000d><_opt_arglist><arglist><primary><heredoc><_literal_0007>&lt;&lt;</_literal_0007><here_id>DATA1</here_id></heredoc></primary><_repeat_arglist_more><arglist_more><_literal_000b>,</_literal_000b><primary><id>more</id></primary></arglist_more><arglist_more><_literal_000b>,</_literal_000b><primary><heredoc><_literal_0007>&lt;&lt;</_literal_0007><here_id>DATA2</here_id></heredoc></primary></arglist_more><arglist_more><_literal_000b>,</_literal_000b><primary><number>99</number></primary></arglist_more></_repeat_arglist_more></arglist></_opt_arglist><_literal_000f>)</_literal_000f></call></statement><_literal_0011>!</_literal_0011></item><item><foobar>print( &lt;&lt;DATA1, more, &lt;&lt;DATA2, 99 )
"&amp;^#(@ almost
!arbitrary text!
DATA1
hello
world
DATA2
# error here
</foobar></item></_repeat_item></start>
