#!/bin/bash

# Default to all .d direcories.
DIRS=$(find -type d -name '*.d' | sort)

CORES=$(awk '/cpu cores/ { print $4; exit }'  /proc/cpuinfo)

if ! echo $CORES | grep -q '^[1-9][0-9]\?$'; then
	echo "warning: could not determine number of cores, using 2"
	CORES=2
fi

HERE=$(basename $(pwd))
if [ "${HERE%.d}" != "$HERE" ]; then
	# In a test directory. Set DIR to . and pass any arguments to the local
	# gentests.
	DIRS=.
	ARGS="$@"
elif [ $# != 0 ]; then
	# Args on the command line, but not in .d. Assume they are test cases.
	DIRS=$(find "$@" -type d -name '*.d')
fi

for D in $DIRS; do
	cd $D
	echo ------- $D
	./gentests $ARGS | xargs -n1 -P$CORES bash
	WORKING="$WORKING $D/working"
	cd $OLDPWD
done

echo ----  cases   ------
find $WORKING -name '*.sh' -not -size 0 | wc -l

echo ---- failures ------
find $WORKING -name '*.diff' -not -size 0 | wc -l
