#!/bin/bash
#

source TESTS

GENMF="$0"
COLM="`dirname $GENMF`/../colm/colm"

echo "#!/usr/bin/make -f "
echo
echo "SUBDIRS = " $SUBDIRS
echo

echo -n "TESTS ="
for t in $TESTS; do
	echo " \\"
	echo -n "	$t"
done
echo
echo

echo -n "DIFFS ="

shopt -s nullglob
for t in $TESTS; do
	root=${t%.lm}
	set -- ${root}*.in
	if [ $# = 0 ]; then
		echo " \\"
		echo -n "	$root.diff"
	else
		for i; do
			echo " \\"
			echo -n "	${i%.in}.diff"
		done
	fi
done
echo 
echo

echo 'all: runtests.mk $(DIFFS) $(SUBDIRS)'
echo
echo '.PHONY: clean $(SUBDIRS:%=%-clean)'
echo 'clean: $(SUBDIRS:%=%-clean)'
echo '	rm -f *.bin'
echo '$(SUBDIRS:%=%-clean):'
echo '	cd $(@:%-clean=%) && $(MAKE) -f runtests.mk clean'
echo
echo '.PHONY: $(SUBDIRS)'
echo '$(SUBDIRS):'
echo '	cd $@ && $(MAKE) -f runtests.mk'
echo
echo "runtests.mk: $GENMF TESTS"
echo "	$GENMF > runtests.mk"
echo


for t in $TESTS; do
	root=${t%.lm}
	input=${root}*.in

	# Are there any arguments.
	if test -f $root.args; then
		args=`cat $root.args`
	else
		args=""
	fi

	set -- ${root}*.in
	if [ $# = 0 ]; then
		echo "$root.diff: $root.out $root.exp"
		echo "	@diff -u $root.exp $root.out > $root.diff || ( cat $root.diff; rm $root.diff )"
		echo
		echo "$root.out: $root.bin"
		echo "	./$root.bin $args > $root.out"
		echo
	else
		for i; do
			i=${i%.in}
			echo "$i.diff: $i.out $i.exp"
			echo "	@diff -u $i.exp $i.out > $i.diff || ( cat $i.diff; rm $i.diff )"
			echo
			echo "$i.out: $root.bin"
			echo "	./$root.bin $args < $i.in > $i.out"
			echo
		done
	fi

	echo "$root.bin: $t $COLM"
	echo "	$COLM $t"
done
exit

