#!/bin/bash
#

COLM="../colm/colm"
TESTS="
	backtrack1.lm backtrack2.lm dns.lm accum1.lm accum2.lm accum3.lm
	mutualrec.lm argv1.lm argv2.lm exit.lm rubyhere.lm
	translate1.lm translate2.lm
	construct1.lm construct2.lm construct3.lm
	treecmp1.lm context1.lm context2.lm context3.lm
	undofrag1.lm undofrag2.lm undofrag3.lm
	nestedcomm.lm reparse.lm
	btscan1.lm btscan2.lm
"

echo -n "TESTS ="
for t in $TESTS; do
	echo " \\"
	echo -n "	$t"
done

echo
echo
echo 'BINS = $(TESTS:%.lm=%.bin)'
echo 'OUTS = $(TESTS:%.lm=%.out)'
echo 'DIFFS = $(TESTS:%.lm=%.diff)'
echo 
echo 'all: Makefile $(DIFFS)'
echo
echo 'Makefile: genmf'
echo '	./genmf > Makefile'
echo

for t in $TESTS; do
	root=${t%.lm}

	echo "$root.diff: $root.out $root.exp"
	echo "	@ diff -u $root.exp $root.out > $root.diff || ( cat $root.diff; rm $root.diff )"

	# Are there any arguments.
	if test -f $root.args; then
		args=`cat $root.args`
	else
		args=""
	fi

	echo "$root.out: $root.bin"
	if test -f "$root.in"; then
		echo "	./$root.bin $args < $root.in > $root.out"
	else
		echo "	./$root.bin $args > $root.out"
	fi
	echo "$root.bin: $t $COLM"
	echo "	$COLM $t"
done
