#!/bin/bash
#

COLM="../colm/colm"
TESTS="
	backtrack1.lm backtrack2.lm dns.lm accum.lm
	mutualrec.lm argv1.lm argv2.lm
"

for t in $TESTS; do
	root=${t%.lm}
	echo "testing $t"

	# Compile.
	$COLM $t

	# Are there any arguments.
	if test -f $root.args; then
		args=`cat $root.args`
	else
		args=""
	fi
	
	# Run. There may be an input file.
	if test -f "$root.in"; then
		./$root.bin $args < "$root.in" > $root.out
	else
		./$root.bin $args > $root.out
	fi

	# Test output.
	if ! diff -u $root.out $root.exp; then
		echo FAILURE
		exit 1
	fi
done
