#!/bin/bash
#

set -xe

TMP=$(mktemp -d /tmp/testing.XXXXXX)
CLONE=$TMP/testing

git clone . $CLONE

VERSION=$(git -C $CLONE log -n 1 master | sed -n '1{ s/commit \(........\).*/\1/; p }')

AWK='
	BEGIN { public = 1; }

	/^# *END PUBLIC/ { public = 0; }

	public { print $0; }

	/^# *BEGIN PUBLIC/ { public = 1; }
'

in_place_clean()
{
	for FN; do
		local TFN=$(mktemp /tmp/inplace.XXXXXX)
		cat $FN > $TFN
		awk "$AWK" $TFN > $FN
		rm $TFN
	done
}

in_place_clean $CLONE/autogen.sh $CLONE/configure.in $CLONE/Makefile.in

tar -C $TMP/testing --xform "s,^,testing-$VERSION/," -czf testing-$VERSION.tar.gz \
	autogen.sh configure.in Makefile.in runtests timed public

rm -Rf $TMP
