#!/bin/bash
#

set -xe

TMP=$(mktemp -d /tmp/testing.XXXXXX)
CLONE=$TMP/testing

git clone . $CLONE

VERSION=$(git -C $CLONE log -n 1 master | sed -n '1{ s/commit \(........\).*/\1/; p }')

in_place_clean()
{
	for FN; do
		local TFN=$(mktemp /tmp/inplace.XXXXXX)
		cat $FN > $TFN
		awk -f - $TFN <<-'EOF' > $FN
			BEGIN { public = 1; }
			/^# *END PUBLIC/ { public = 0; }
			public { print $0; }
			/^# *BEGIN PUBLIC/ { public = 1; }
		EOF
		rm $TFN
	done
}

in_place_clean $CLONE/autogen.sh $CLONE/configure.ac $CLONE/cases/Makefile.am

cat <<'EOF' >> $CLONE/configure.ac
AC_SUBST(SED_SUBST)
AC_OUTPUT([
	Makefile
	cases/Makefile
	cases/aapl.d/Makefile
	cases/colm.d/Makefile
	cases/ragel.d/Makefile
])
EOF

tar -C $TMP/testing --xform "s,^,testing-$VERSION/," -czf testing-$VERSION.tar.gz \
	autogen.sh configure.ac Makefile.am runtests timed sedsubst \
	cases/Makefile.am \
	cases/aapl.d \
	cases/colm.d \
	cases/ragel.d

rm -Rf $TMP
