#!/bin/bash

# Default to all .d direcories.
DIRS=$(find -type d -name '*.d')

HERE=$(basename $(pwd))
if [ "${HERE%.d}" != "$HERE" ]; then
	# In a test directory. Set DIR to . and pass any arguments to the local
	# gentests.
	DIRS=.
	ARGS="$@"
elif [ $# != 0 ]; then
	# Args on the command line, but not in .d. Assume they are test cases.
	DIRS="$@"
fi

for D in $DIRS; do
	cd $D
	echo ------- $D
	./gentests $ARGS | xargs -n1 -P4 bash
	WORKING="$WORKING $D/working"
	cd $OLDPWD
done

echo ----  cases   ------
find $WORKING -name '*.sh' -not -size 0 | wc -l

echo ---- failures ------
find $WORKING -name '*.diff' -not -size 0 | wc -l
