#!/bin/bash

PRIVATE_CASES=""

# START PRIVATE CASES
PRIVATE_CASES="
	cases/pcre-ragel.d
	cases/rlhc.d
	cases/trans.d
	cases/rlparse.d
	cases/pcre-colm.d
	cases/yellowbrick.d
	genf.d
"
# END PRIVATE CASES

DIRS="
	public/aapl.d
	public/ragel.d
	public/colm.d
	${PRIVATE_CASES}
"

HERE=$(basename $(pwd))
if [ "${HERE%.d}" != "$HERE" ]; then
	# In a test directory. Pass the arguments to the local gentests.
	ARGS="$@"
	DIRS=.
elif [ $# != 0 ]; then
	DIRS="$@"
fi

for D in $DIRS; do
	cd $D
	echo ------- $D
	./gentests $ARGS | xargs -n1 -P4 bash
	WORKING="$WORKING $D/working"
	cd $OLDPWD
done

echo ----  cases   ------
find $WORKING -name '*.sh' -not -size 0 | wc -l

echo ---- failures ------
find $WORKING -name '*.diff' -not -size 0 | wc -l
