#include <iostream>
#include <string.h>
using std::cout;
using std::endl;

static const char  _foo_actions [] = { 0, 2, 0, 4, 2, 1, 4, 2, 2, 4, 2, 3, 4, 3, 0, 3, 4, 3, 1, 2, 4, 0 ,  };
static const char  _foo_trans_keys [] = { 1, 0, 0, 2, 0, 2, 0, 2, 1, 0, 0 ,  };
static const char  _foo_char_class [] = { 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0 ,  };
static const char  _foo_index_offsets [] = { 0, 0, 3, 6, 9, 0 ,  };
static const char  _foo_indicies [] = { 0, 1, 2, 3, 1, 4, 5, 1, 6, 0 ,  };
static const char  _foo_index_defaults [] = { 0, 1, 1, 1, 1, 0 ,  };
static const char  _foo_trans_cond_spaces [] = { -1, -1, 2, -1, 0, -1, 1, 0 ,  };
static const char  _foo_trans_offsets [] = { 0, 1, 2, 6, 7, 9, 10, 0 ,  };
static const char  _foo_cond_targs [] = { 4, 0, 0, 2, 3, 1, 4, 0, 2, 4, 0, 3, 0 ,  };
static const char  _foo_cond_actions [] = { 17, 0, 0, 1, 10, 13, 4, 0, 1, 7, 0, 10, 0 ,  };
static const char  _foo_nfa_targs [] = { 0, 0 ,  };
static const char  _foo_nfa_offsets [] = { 0, 0, 0, 0, 0, 0 ,  };
static const char  _foo_nfa_push_actions [] = { 0, 0 ,  };
static const char  _foo_nfa_pop_trans [] = { 0, 0 ,  };
static const int  foo_start  = 1;
static const int  foo_first_final  = 4;
static const int  foo_en_main  = 1;
void test( const char *str )
{
	int cs = foo_start;
	int c = 0;
	const char *p = str;
	const char *pe = str + strlen( str );
	char last = '0';
	
	cout << "run:";
	
	{
		int _trans = 0;
		unsigned int _cond = 0;
		const char  *_acts;
		unsigned int _nacts;
		const char  *_keys;
		const char  *_inds;
		int _cpc;
		if ( p == pe  )
		goto _test_eof;
		
		if ( cs == 0  )
		goto _out;
		
		_resume :
		_keys = _foo_trans_keys + (cs<<1);
		_inds = _foo_indicies + _foo_index_offsets[cs];
		if ( ((*( p  ))
		)<= 57 && ((*( p  ))
		)>= 10  )
		{
			int _ic = ( int ) _foo_char_class[( int ) ((*( p  ))
			)- 10];
			if ( _ic <= ( int ) (*( _keys+1  ))
			&& _ic >= ( int ) (*( _keys  ))
			)
			_trans = ( int ) (*( _inds + ( int ) (_ic - ( int ) (*( _keys  ))
			) ))
			;
			
			else
			_trans = ( int ) _foo_index_defaults[cs];
			
		}
		
		else
		{
			_trans = ( int ) _foo_index_defaults[cs];
		}
		
		
		_cond = ( unsigned int  ) _foo_trans_offsets[_trans];
		_cpc = 0;
		switch ( _foo_trans_cond_spaces[_trans] ) {
			case 0 :
			if ( (c++ < 5) )
			_cpc += 1;
			
			
			break;
			case 1 :
			if ( (*p == last+1 ) )
			_cpc += 1;
			
			
			break;
			case 2 :
			if ( (c++ < 5) )
			_cpc += 1;
			
			if ( (*p == last+1 ) )
			_cpc += 2;
			
			
			break;
			
		}
		_cond += ( unsigned int  ) _cpc;
		goto _match_cond;
		
		_match_cond :
		cs = ( int ) _foo_cond_targs[_cond];
		if ( _foo_cond_actions[_cond]== 0  )
		goto _again;
		
		
		_acts = _foo_actions + _foo_cond_actions[_cond];
		_nacts = ( unsigned int  ) (*( _acts  ))
		;
		_acts += 1;
		while ( _nacts > 0  )
		{
			switch ( (*( _acts  ))
			) {
				case 0 :
				{
					cout << " d1"; 
				}
				
				break;
				case 1 :
				{
					cout << " see_five"; 
				}
				
				break;
				case 2 :
				{
					cout << " in_sequence"; 
				}
				
				break;
				case 3 :
				{
					last = *p; cout << " d2"; 
				}
				
				break;
				case 4 :
				{
					cout << " |";
				}
				
				break;
				
			}
			_nacts -= 1;
			_acts += 1;
		}
		
		
		
		
		_again :
		if ( cs == 0  )
		goto _out;
		
		p += 1;
		if ( p != pe  )
		goto _resume;
		
		
		_test_eof :
		{}
		
		_out :
		{}
		
	}
	if ( cs < foo_first_final )
	cout << " failure";
	cout << endl;
}

int main()
{
	test( "123456789012\n" );  // fails both
	test( "123456789\n" );  // fails five
	test( "1234\n" );  // fails five
	test( "13245\n" );  // fails sequence
	test( "12345\n" );  // succeeds in both
	return 0;
}

