const _foo_trans_keys = UInt8[1, 0, 2, 2, 2, 2, 0, 2, 1, 0, 0 , ]
const _foo_char_class = Int8[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0 , ]
const _foo_index_offsets = Int8[0, 0, 1, 2, 5, 0 , ]
const _foo_indicies = Int8[0, 2, 3, 1, 4, 0 , ]
const _foo_index_defaults = Int8[0, 1, 1, 1, 1, 0 , ]
const _foo_trans_cond_spaces = Int8[-1, -1, 0, 0, 0, 0 , ]
const _foo_trans_offsets = Int8[0, 1, 2, 4, 6, 0 , ]
const _foo_cond_targs = Int8[2, 0, 3, 2, 4, 0, 0, 3, 0 , ]
const _foo_cond_actions = Int8[1, 0, 1, 2, 0, 0, 0, 2, 0 , ]
const _foo_nfa_targs = Int8[0, 0 , ]
const _foo_nfa_offsets = Int8[0, 0, 0, 0, 0, 0 , ]
const _foo_nfa_push_actions = Int8[0, 0 , ]
const _foo_nfa_pop_trans = Int8[0, 0 , ]
const foo_start  = 1
const foo_first_final  = 4
const foo_error  = 0
const foo_en_main  = 1
function m( data::AbstractString )
	p = 0
	pe = length(data)
	eof = length(data)
	cs = 0
	buffer = ""
	i = 0;
	c = 0;
	
	cs = convert(Int, foo_start )
	_cpc= 0
	;
	_trans = 0;
	_have = 0;
	_cont = 1;
	_cond = 0;
	_keys = 0;
	_inds = 0;
	while _cont == 1 
		if cs == 0 
			_cont = 0
			
		end
		_have = 0
		if p == pe 
			if _have == 0 
				_cont = 0
				
			end
			
		end
		if _cont == 1 
			if _have == 0 
				_keys = (cs<<1)
				_inds = _foo_index_offsets[1+(cs)]
				if (data[1+(p )])<= 57 && (data[1+(p )])>= 10 
					_ic = convert(Int, _foo_char_class[1+(convert(Int, (data[1+(p )]) )- 10)] );
					if _ic <= convert(Int, _foo_trans_keys[1+(_keys+1 )] )&& _ic >= convert(Int, _foo_trans_keys[1+(_keys )] )
						_trans = convert(UInt, _foo_indicies[1+(_inds + convert(Int, (_ic - convert(Int, _foo_trans_keys[1+(_keys )] )) ))] )
						
					else
						_trans = convert(UInt, _foo_index_defaults[1+(cs)] )
						
					end
					
				else
					_trans = convert(UInt, _foo_index_defaults[1+(cs)] )
					
				end
				_cond = convert(UInt, _foo_trans_offsets[1+(_trans)] )
				_cpc = 0
				if _foo_trans_cond_spaces[1+(_trans)] == 0 
					if (i > 0)
						_cpc += 1
						
					end
					
				end
				_cond += convert(UInt, _cpc )
				
			end
			if _cont == 1 
				cs = convert(Int, _foo_cond_targs[1+(_cond)] )
				if _foo_cond_actions[1+(_cond)] == 2 
					i = i - 1;
					c = convert( Int, ( ((data[1+(p )])) ) ) 
					;
					print( "item: " );
					print( c );
					print( "\n" );
					
				elseif _foo_cond_actions[1+(_cond)] == 1 
					i = convert( Int, ( ((data[1+(p )])) - 48 ) ) 
					;
					print( "count: " );
					print( i );
					print( "\n" );
					
				end
				if cs == 0 
					_cont = 0
					
				end
				if _cont == 1 
					p += 1
					
				end
				
			end
			
		end
		
	end
	if ( cs >= foo_first_final )
		println( "ACCEPT" );
	else
		println( "FAIL" );
	end
end

m( "00\n" );
m( "019\n" );
m( "190\n" );
m( "1719\n" );
m( "1040000\n" );
m( "104000a\n" );
m( "104000\n" );
