const _curs1_actions = Int8[0, 1, 0, 1, 1, 1, 2, 1, 3, 0 , ]
const _curs1_key_offsets = Int8[0, 0, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 15, 15, 15, 0 , ]
const _curs1_trans_keys = UInt8[10, 49, 50, 117, 110, 117, 115, 101, 100, 111, 110, 101, 116, 119, 111, 0 , ]
const _curs1_single_lengths = Int8[0, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0 , ]
const _curs1_range_lengths = Int8[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 , ]
const _curs1_index_offsets = Int8[0, 0, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 29, 30, 31, 0 , ]
const _curs1_trans_cond_spaces = Int8[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0 , ]
const _curs1_trans_offsets = Int8[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 0 , ]
const _curs1_trans_lengths = Int8[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0 , ]
const _curs1_cond_keys = Int8[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 , ]
const _curs1_cond_targs = Int8[14, 14, 14, 0, 3, 0, 4, 0, 5, 0, 6, 0, 7, 0, 15, 0, 9, 0, 10, 0, 16, 0, 12, 0, 13, 0, 17, 0, 0, 0, 0, 0, 0 , ]
const _curs1_cond_actions = Int8[0, 5, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0 , ]
const _curs1_nfa_targs = Int8[0, 0 , ]
const _curs1_nfa_offsets = Int8[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 , ]
const _curs1_nfa_push_actions = Int8[0, 0 , ]
const _curs1_nfa_pop_trans = Int8[0, 0 , ]
const curs1_start  = 1
const curs1_first_final  = 14
const curs1_error  = 0
const curs1_en_unused  = 2
const curs1_en_one  = 8
const curs1_en_two  = 11
const curs1_en_main  = 1
function m( data::AbstractString )
	p = 0
	pe = length(data)
	eof = length(data)
	cs = 0
	buffer = ""
	return_to = 0;
	
	cs = convert(Int, curs1_start )
	_klen= 0
	;
	_ps= 0
	;
	_trans = 0;
	_cond = 0;
	_have = 0;
	_cont = 1;
	_acts = 0;
	_nacts= 0
	;
	_keys = 0;
	_ckeys = 0;
	_cpc= 0
	;
	while _cont == 1 
		if cs == 0 
			_cont = 0
			
		end
		_have = 0
		if p == pe 
			if _have == 0 
				_cont = 0
				
			end
			
		end
		if _cont == 1 
			if _have == 0 
				_keys = _curs1_key_offsets[1+(cs)]
				_trans = convert(UInt, _curs1_index_offsets[1+(cs)] )
				_have = 0
				_klen = convert(Int, _curs1_single_lengths[1+(cs)] )
				if _klen > 0 
					_lower = 0;
					_mid = 0;
					_upper = 0;
					_lower = _keys
					_upper = _keys + _klen - 1
					while _upper >= _lower && _have == 0 
						_mid = _lower + ((_upper-_lower)>> 1)
						if (data[1+(p )])< _curs1_trans_keys[1+(_mid )]
							_upper = _mid - 1
							
						elseif (data[1+(p )])> _curs1_trans_keys[1+(_mid )]
							_lower = _mid + 1
							
						else
							_trans += convert(UInt, (_mid - _keys) )
							_have = 1
							
						end
						
					end
					if _have == 0 
						_keys += _klen
						_trans += convert(UInt, _klen )
						
					end
					
				end
				if _have == 0 
					_klen = convert(Int, _curs1_range_lengths[1+(cs)] )
					if _klen > 0 
						_lower = 0;
						_mid = 0;
						_upper = 0;
						_lower = _keys
						_upper = _keys + (_klen<<1)- 2
						while _have == 0 && _lower <= _upper 
							_mid = _lower + (((_upper-_lower)>> 1)& ~1)
							if (data[1+(p )])< _curs1_trans_keys[1+(_mid )]
								_upper = _mid - 2
								
							elseif (data[1+(p )])> _curs1_trans_keys[1+(_mid + 1 )]
								_lower = _mid + 2
								
							else
								_trans += convert(UInt, ((_mid - _keys)>>1) )
								_have = 1
								
							end
							
						end
						if _have == 0 
							_trans += convert(UInt, _klen )
							
						end
						
					end
					
				end
				_ckeys = _curs1_trans_offsets[1+(_trans)]
				_klen = convert(Int, _curs1_trans_lengths[1+(_trans)] )
				_cond = convert(UInt, _curs1_trans_offsets[1+(_trans)] )
				_have = 0
				_cpc = 0
				_lower = 0;
				_mid = 0;
				_upper = 0;
				_lower = _ckeys
				_upper = _ckeys + _klen - 1
				while _have == 0 && _lower <= _upper 
					_mid = _lower + ((_upper-_lower)>> 1)
					if _cpc < convert(Int, _curs1_cond_keys[1+(_mid )] )
						_upper = _mid - 1
						
					elseif _cpc > convert(Int, _curs1_cond_keys[1+(_mid )] )
						_lower = _mid + 1
						
					else
						_cond += convert(UInt, (_mid - _ckeys) )
						_have = 1
						
					end
					
				end
				if _have == 0 
					cs = 0
					_cont = 0
					
				end
				
			end
			if _cont == 1 
				_ps = cs
				cs = convert(Int, _curs1_cond_targs[1+(_cond)] )
				if _curs1_cond_actions[1+(_cond)]!= 0 
					_acts = _curs1_cond_actions[1+(_cond)]
					_nacts = convert(UInt, _curs1_actions[1+(_acts )] )
					_acts += 1
					while _nacts > 0 
						if _curs1_actions[1+(_acts )] == 0 
							print( "one\n" );
							{
								cs = (return_to)
								
							}
							
						elseif _curs1_actions[1+(_acts )] == 1 
							print( "two\n" );
							{
								cs = (return_to)
								
							}
							
						elseif _curs1_actions[1+(_acts )] == 2 
							return_to = (_ps);
							{
								cs = 8
								
							}
							
						elseif _curs1_actions[1+(_acts )] == 3 
							return_to = (_ps);
							{
								cs = 11
								
							}
							
						end
						_nacts -= 1
						_acts += 1
						
					end
					
				end
				if cs == 0 
					_cont = 0
					
				end
				if _cont == 1 
					p += 1
					
				end
				
			end
			
		end
		
	end
	if ( cs >= curs1_first_final )
		println( "ACCEPT" );
	else
		println( "FAIL" );
	end
end

m( "1one2two1one\n" );
