#include <stdio.h>
#include <string.h>

/*
* After the fact start and ending transitions. Behaves like constructors of
* and destructors in c++.
*/

struct forder
{
	int cs;
};



static const char  _forder_key_offsets [] = { 0, 0, 1, 2, 3, 4, 5, 6, 0 ,  };
static const char  _forder_trans_keys [] = { 105, 110, 110, 101, 114, 10, 0 ,  };
static const char  _forder_single_lengths [] = { 0, 1, 1, 1, 1, 1, 1, 0, 0 ,  };
static const char  _forder_range_lengths [] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  };
static const char  _forder_index_offsets [] = { 0, 0, 2, 4, 6, 8, 10, 12, 0 ,  };
static const char  _forder_trans_cond_spaces [] = { -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0 ,  };
static const char  _forder_trans_offsets [] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0 ,  };
static const char  _forder_trans_lengths [] = { 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0 ,  };
static const char  _forder_cond_keys [] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  };
static const char  _forder_cond_targs [] = { 2, 0, 3, 0, 4, 0, 5, 0, 6, 0, 7, 0, 0, 0 ,  };
static const char  _forder_cond_actions [] = { 1, 0, 2, 0, 2, 0, 2, 0, 2, 0, 3, 0, 0, 0 ,  };
static const char  _forder_nfa_targs [] = { 0, 0 ,  };
static const char  _forder_nfa_offsets [] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  };
static const char  _forder_nfa_push_actions [] = { 0, 0 ,  };
static const char  _forder_nfa_pop_trans [] = { 0, 0 ,  };
static const int  forder_start  = 1;
static const int  forder_first_final  = 7;
static const int  forder_error  = 0;
static const int  forder_en_main  = 1;
void forder_init( struct forder *fsm )
{

	{
		(fsm->cs) = ( int ) forder_start;
	}
}

void forder_execute( struct forder *fsm, const char *_data, int _len )
{
	const char *p = _data;
	const char *pe = _data+_len;
	
	
	{
		int _klen;
		const char  *_keys;
		const char  *_ckeys;
		int _cpc;
		unsigned int _trans;
		unsigned int _cond = 0;
		unsigned int _have = 0;
		unsigned int _cont = 1;
		while ( _cont == 1  )
		{
		
			if ( (fsm->cs) == 0  )
			_cont = 0;
			
			_have = 0;
			if ( p == pe  )
			{
				if ( _have == 0  )
				_cont = 0;
				
			}
			
			if ( _cont == 1  )
			{
				if ( _have == 0  )
				{
					_keys = _forder_trans_keys + _forder_key_offsets[(fsm->cs)];
					_trans = ( unsigned int  ) _forder_index_offsets[(fsm->cs)];
					_have = 0;
					_klen = ( int ) _forder_single_lengths[(fsm->cs)];
					if ( _klen > 0  )
					{
						const char  *_lower;
						const char  *_mid;
						const char  *_upper;
						_lower = _keys;
						_upper = _keys + _klen - 1;
						while ( _upper >= _lower && _have == 0  )
						{
							_mid = _lower + ((_upper-_lower)>> 1);
							if ( ((*( p  ))
							)< (*( _mid  ))
							)
							_upper = _mid - 1;
							
							else if ( ((*( p  ))
							)> (*( _mid  ))
							)
							_lower = _mid + 1;
							
							else
							{
								_trans += ( unsigned int  ) (_mid - _keys);
								_have = 1;
							}
							
						}
						
						if ( _have == 0  )
						{
							_keys += _klen;
							_trans += ( unsigned int  ) _klen;
						}
						
					}
					
					
					if ( _have == 0  )
					{
						_klen = ( int ) _forder_range_lengths[(fsm->cs)];
						if ( _klen > 0  )
						{
							const char  *_lower;
							const char  *_mid;
							const char  *_upper;
							_lower = _keys;
							_upper = _keys + (_klen<<1)- 2;
							while ( _have == 0 && _lower <= _upper  )
							{
								_mid = _lower + (((_upper-_lower)>> 1)& ~1);
								if ( ((*( p  ))
								)< (*( _mid  ))
								)
								_upper = _mid - 2;
								
								else if ( ((*( p  ))
								)> (*( _mid + 1  ))
								)
								_lower = _mid + 2;
								
								else
								{
									_trans += ( unsigned int  ) ((_mid - _keys)>>1);
									_have = 1;
								}
								
							}
							
							if ( _have == 0  )
							_trans += ( unsigned int  ) _klen;
							
						}
						
					}
					
					
					_ckeys = _forder_cond_keys + _forder_trans_offsets[_trans];
					_klen = ( int ) _forder_trans_lengths[_trans];
					_cond = ( unsigned int  ) _forder_trans_offsets[_trans];
					_have = 0;
					_cpc = 0;
					{
						const char  *_lower;
						const char  *_mid;
						const char  *_upper;
						_lower = _ckeys;
						_upper = _ckeys + _klen - 1;
						while ( _have == 0 && _lower <= _upper  )
						{
							_mid = _lower + ((_upper-_lower)>> 1);
							if ( _cpc < ( int ) (*( _mid  ))
							)
							_upper = _mid - 1;
							
							else if ( _cpc > ( int ) (*( _mid  ))
							)
							_lower = _mid + 1;
							
							else
							{
								_cond += ( unsigned int  ) (_mid - _ckeys);
								_have = 1;
							}
							
						}
						
						if ( _have == 0  )
						{
							(fsm->cs) = 0;
							_cont = 0;
						}
						
					}
				}
				
				if ( _cont == 1  )
				{
					(fsm->cs) = ( int ) _forder_cond_targs[_cond];
					switch ( _forder_cond_actions[_cond] ) {
						case 2 :
						{
							printf("inside inner\n");
						}
						{
							printf("inside outter\n");
						}
						
						break;
						case 3 :
						{
							printf("leave inner\n");
						}
						{
							printf("leave outter\n");
						}
						
						break;
						case 1 :
						{
							printf("enter outter\n");
						}
						{
							printf("enter inner\n");
						}
						{
							printf("inside inner\n");
						}
						{
							printf("inside outter\n");
						}
						
						break;
						
					}
					if ( (fsm->cs) == 0  )
					_cont = 0;
					
					if ( _cont == 1  )
					p += 1;
					
				}
			}
			
		}
		
	}
}

int forder_finish( struct forder *fsm )
{
	if ( fsm->cs == forder_error )
	return -1;
	if ( fsm->cs >= forder_first_final )
	return 1;
	return 0;
}

struct forder fsm;

void test( char *buf )
{
	int len = strlen( buf );
	forder_init( &fsm );
	forder_execute( &fsm, buf, len );
	if ( forder_finish( &fsm ) > 0 )
	printf("ACCEPT\n");
	else
	printf("FAIL\n");
}


int main()
{
	test( "inner\n");
	
	test(
	"inner\n"
	"foobar\n"
	);
	
	test( "" );
	test( "\n" );
	test( "inn\n" );
	
	return 0;
}

