const _gotocallret_trans_keys = UInt8[1, 0, 2, 2, 0, 0, 0, 0, 0, 0, 4, 5, 3, 3, 3, 5, 1, 0, 4, 5, 3, 3, 0 , ]
const _gotocallret_char_class = Int8[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 1, 1, 1, 1, 1, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0 , ]
const _gotocallret_index_offsets = Int8[0, 0, 1, 2, 3, 4, 6, 7, 10, 10, 12, 0 , ]
const _gotocallret_indicies = Int8[1, 2, 4, 6, 8, 8, 9, 10, 0, 10, 8, 8, 9, 0 , ]
const _gotocallret_index_defaults = Int8[0, 0, 0, 3, 5, 7, 7, 0, 11, 7, 7, 0 , ]
const _gotocallret_trans_cond_spaces = Int8[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0 , ]
const _gotocallret_cond_targs = Int8[0, 2, 7, 4, 8, 4, 8, 0, 9, 10, 1, 0, 0 , ]
const _gotocallret_cond_actions = Int8[1, 2, 3, 5, 6, 0, 7, 8, 0, 0, 9, 0, 0 , ]
const _gotocallret_eof_actions = Int8[0, 1, 1, 4, 4, 8, 8, 0, 4, 0, 0, 0 , ]
const _gotocallret_nfa_targs = Int8[0, 0 , ]
const _gotocallret_nfa_offsets = Int8[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 , ]
const _gotocallret_nfa_push_actions = Int8[0, 0 , ]
const _gotocallret_nfa_pop_trans = Int8[0, 0 , ]
const gotocallret_start  = 7
const gotocallret_first_final  = 7
const gotocallret_error  = 0
const gotocallret_en_garble_line  = 3
const gotocallret_en_alp_comm  = 5
const gotocallret_en_dig_comm  = 6
const gotocallret_en_main  = 7
function m( data::AbstractString )
	p = 0
	pe = length(data)
	eof = length(data)
	cs = 0
	buffer = ""
	comm = 0;
	top = 0;
	stack = Int [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ];
	
	cs = convert(Int, gotocallret_start )
	top = 0
	_trans = 0;
	_have = 0;
	_cont = 1;
	_keys = 0;
	_inds = 0;
	while _cont == 1 
		if cs == 0 
			_cont = 0
			
		end
		_have = 0
		if p == pe 
			if p == eof 
				if _have == 0 
					if _gotocallret_eof_actions[1+(cs)] == 4 
						print( "error: failed to recover\n" );
						
					elseif _gotocallret_eof_actions[1+(cs)] == 8 
						{
							p = p - 1
							
						}
						{
							top-= 1
							cs = stack[1+(top)]
							
						}
						
					elseif _gotocallret_eof_actions[1+(cs)] == 1 
						{
							p = p - 1
							
						}
						{
							cs = 3
							
						}
						
					end
					
				end
				
			end
			if _have == 0 
				_cont = 0
				
			end
			
		end
		if _cont == 1 
			if _have == 0 
				_keys = (cs<<1)
				_inds = _gotocallret_index_offsets[1+(cs)]
				if (data[1+(p )])<= 122 && (data[1+(p )])>= 10 
					_ic = convert(Int, _gotocallret_char_class[1+(convert(Int, (data[1+(p )]) )- 10)] );
					if _ic <= convert(Int, _gotocallret_trans_keys[1+(_keys+1 )] )&& _ic >= convert(Int, _gotocallret_trans_keys[1+(_keys )] )
						_trans = convert(UInt, _gotocallret_indicies[1+(_inds + convert(Int, (_ic - convert(Int, _gotocallret_trans_keys[1+(_keys )] )) ))] )
						
					else
						_trans = convert(UInt, _gotocallret_index_defaults[1+(cs)] )
						
					end
					
				else
					_trans = convert(UInt, _gotocallret_index_defaults[1+(cs)] )
					
				end
				
			end
			if _cont == 1 
				cs = convert(Int, _gotocallret_cond_targs[1+(_trans)] )
				if _gotocallret_cond_actions[1+(_trans)] == 5 
					print( "error: garbling line\n" );
					
				elseif _gotocallret_cond_actions[1+(_trans)] == 7 
					{
						cs = 7
						
					}
					
				elseif _gotocallret_cond_actions[1+(_trans)] == 8 
					{
						p = p - 1
						
					}
					{
						top-= 1
						cs = stack[1+(top)]
						
					}
					
				elseif _gotocallret_cond_actions[1+(_trans)] == 9 
					comm = ((data[1+(p )]));
					
				elseif _gotocallret_cond_actions[1+(_trans)] == 3 
					print( "correct command\n" );
					
				elseif _gotocallret_cond_actions[1+(_trans)] == 1 
					{
						p = p - 1
						
					}
					{
						cs = 3
						
					}
					
				elseif _gotocallret_cond_actions[1+(_trans)] == 6 
					print( "error: garbling line\n" );
					{
						cs = 7
						
					}
					
				elseif _gotocallret_cond_actions[1+(_trans)] == 2 
					if ( comm >= 97 )
						{
							stack[1+(top)]= cs
							top += 1
							cs = 5
							
						}
					else
						{
							stack[1+(top)]= cs
							top += 1
							cs = 6
							
						}
					end
					print( "prints\n" );
					
				end
				if cs == 0 
					_cont = 0
					
				end
				if _cont == 1 
					p += 1
					
				end
				
			end
			
		end
		
	end
	if ( cs >= gotocallret_first_final )
		println( "ACCEPT" );
	else
		println( "FAIL" );
	end
end

m( "lkajsdf\n" );
m( "2134\n" );
m( "(\n" );
m( "\n" );
m( "*234234()0909 092 -234aslkf09`1 11\n" );
m( "1\n" );
m( "909\n" );
m( "1 a\n" );
m( "11 1\n" );
m( "a 1\n" );
m( "aa a\n" );
m( "1 1\n" );
m( "1 123456\n" );
m( "a a\n" );
m( "a abcdef\n" );
m( "h" );
m( "a aa1" );
