#include <string.h>
#include <stdio.h>



#define DEF 1

static const char  _atoi_actions [] = { 0, 1, 0, 0 ,  };
static const char  _atoi_trans_keys [] = { 1, 0, 3, 3, 2, 2, 4, 4, 4, 4, 5, 5, 0, 0, 1, 0, 0 ,  };
static const char  _atoi_char_class [] = { 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 3, 1, 1, 1, 4, 1, 1, 5, 0 ,  };
static const char  _atoi_index_offsets [] = { 0, 0, 1, 2, 3, 4, 5, 6, 0 ,  };
static const char  _atoi_indicies [] = { 0, 2, 3, 4, 5, 6, 0 ,  };
static const char  _atoi_index_defaults [] = { 0, 1, 1, 1, 1, 1, 1, 1, 0 ,  };
static const char  _atoi_trans_cond_spaces [] = { -1, -1, -1, -1, -1, -1, -1, 0 ,  };
static const char  _atoi_cond_targs [] = { 2, 0, 3, 4, 5, 6, 7, 0 ,  };
static const char  _atoi_cond_actions [] = { 0, 0, 0, 0, 0, 0, 1, 0 ,  };
static const char  _atoi_nfa_targs [] = { 0, 0 ,  };
static const char  _atoi_nfa_offsets [] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  };
static const char  _atoi_nfa_push_actions [] = { 0, 0 ,  };
static const char  _atoi_nfa_pop_trans [] = { 0, 0 ,  };
static const int  atoi_start  = 1;
static const int  atoi_first_final  = 7;
static const int  atoi_error  = 0;
static const int  atoi_en_main  = 1;
int cs;
int blen;
char buffer[1024];

void init()
{

	{
		cs = ( int ) atoi_start;
	}
}

void exec( char *data, int len )
{
	char *p = data;
	char *pe = data + len;
	
	{
		unsigned int _trans = 0;
		unsigned int _have = 0;
		unsigned int _cont = 1;
		const char  *_acts;
		unsigned int _nacts;
		const char  *_keys;
		const char  *_inds;
		while ( _cont == 1  )
		{
		
			if ( cs == 0  )
			_cont = 0;
			
			_have = 0;
			if ( p == pe  )
			{
				if ( _have == 0  )
				_cont = 0;
				
			}
			
			if ( _cont == 1  )
			{
				if ( _have == 0  )
				{
					_keys = _atoi_trans_keys + (cs<<1);
					_inds = _atoi_indicies + _atoi_index_offsets[cs];
					if ( ((*( p  ))
					)<= 111 && ((*( p  ))
					)>= 10  )
					{
						int _ic = ( int ) _atoi_char_class[( int ) ((*( p  ))
						)- 10];
						if ( _ic <= ( int ) (*( _keys+1  ))
						&& _ic >= ( int ) (*( _keys  ))
						)
						_trans = ( unsigned int  ) (*( _inds + ( int ) (_ic - ( int ) (*( _keys  ))
						) ))
						;
						
						else
						_trans = ( unsigned int  ) _atoi_index_defaults[cs];
						
					}
					
					else
					{
						_trans = ( unsigned int  ) _atoi_index_defaults[cs];
					}
					
					
				}
				
				if ( _cont == 1  )
				{
					cs = ( int ) _atoi_cond_targs[_trans];
					if ( _atoi_cond_actions[_trans]!= 0  )
					{
						_acts = _atoi_actions + _atoi_cond_actions[_trans];
						_nacts = ( unsigned int  ) (*( _acts  ))
						;
						_acts += 1;
						while ( _nacts > 0  )
						{
							switch ( (*( _acts  ))
							) {
								case 0 :
								{
									printf( "hello\n" ); 
								}
								
								break;
								
							}
							_nacts -= 1;
							_acts += 1;
						}
						
					}
					
					
					if ( cs == 0  )
					_cont = 0;
					
					if ( _cont == 1  )
					p += 1;
					
				}
			}
			
		}
		
	}
}

void finish( )
{
	if ( cs >= atoi_first_final )
	printf( "ACCEPT\n" );
	else
	printf( "FAIL\n" );
}

char *inp[] = {
	"hello\n",
};

int inplen = 9;

int main( )
{
	#ifndef DEF
	printf("DEF not defined -- noignore problem\n" );
	#else
	int i;
	for ( i = 0; i < inplen; i++ ) {
		init();
		exec( inp[i], strlen(inp[i]) );
		finish();
	}
	#endif
	return 0;
}

