package main
import "fmt"







var cs int;
var blen int;
var buffer [1024] byte;

var _state_act_actions [] int8  = [] int8  { 0, 1, 2, 1, 3, 1, 4, 1, 5, 1, 6, 2, 0, 2, 2, 1, 3, 0  }
var _state_act_trans_keys [] byte  = [] byte  { 1, 0, 3, 3, 0, 0, 2, 2, 2, 2, 2, 2, 0 }
var _state_act_char_class [] int8  = [] int8  { 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 0  }
var _state_act_index_offsets [] int8  = [] int8  { 0, 0, 1, 2, 3, 4, 0  }
var _state_act_indicies [] int8  = [] int8  { 0, 2, 3, 3, 3, 0  }
var _state_act_index_defaults [] int8  = [] int8  { 0, 1, 1, 1, 1, 1, 0  }
var _state_act_trans_cond_spaces [] int8  = [] int8  { -1, -1, -1, -1, 0  }
var _state_act_cond_targs [] int8  = [] int8  { 2, 0, 5, 1, 0  }
var _state_act_cond_actions [] int8  = [] int8  { 0, 0, 9, 0, 0  }
var _state_act_to_state_actions [] int8  = [] int8  { 0, 0, 5, 1, 11, 1, 0  }
var _state_act_from_state_actions [] int8  = [] int8  { 0, 0, 7, 3, 14, 3, 0  }
var _state_act_nfa_targs [] int8  = [] int8  { 0, 0  }
var _state_act_nfa_offsets [] int8  = [] int8  { 0, 0, 0, 0, 0, 0, 0  }
var _state_act_nfa_push_actions [] int8  = [] int8  { 0, 0  }
var _state_act_nfa_pop_trans [] int8  = [] int8  { 0, 0  }
var state_act_start  int  = 4
var state_act_first_final  int  = 4
var state_act_error  int  = 0
var state_act_en_main  int  = 4
var state_act_en_main_line_again  int  = 3
func prepare() {

	{
		cs = int(state_act_start);
	}
}

func exec(data string) {
	var p int = 0
	var pe int = len(data)
	
	{
		var  _trans  uint   = 0
		var  _have  uint   = 0
		var  _cont  uint   = 1
		var  _acts int
		var  _nacts uint 
		var  _keys int
		var  _inds int
		for _cont == 1  {
			{
			
				if cs == 0  {
					_cont = 0;
					
				}
				_have = 0;
				if p == pe  {
					{
						if _have == 0  {
							_cont = 0;
							
						}
					}
					
				}
				if _cont == 1  {
					{
						if _have == 0  {
							{
								_acts = int(_state_act_from_state_actions[cs] );
								_nacts = uint(_state_act_actions[_acts ]);
								_acts += 1;
								for _nacts > 0  {
									{
										switch _state_act_actions[_acts ] {
											case 1 :
											{fmt.Print( "a2\n" );}
											
											break;
											case 3 :
											{fmt.Print( "b2\n" );}
											
											break;
											case 5 :
											{fmt.Print( "c2\n" );}
											
											break;
											
										}
										_nacts -= 1;
										_acts += 1;
									}
									
									
								}
								_keys = int((cs<<1) );
								_inds = int(_state_act_index_offsets[cs] );
								switch {
									case ( data[p ]) <= 105 && ( data[p ]) >= 10 :
									{
										var  _ic  int   = int(_state_act_char_class[int(( data[p ]) )- 10])
										switch {
											case _ic <= int(_state_act_trans_keys[_keys+1 ])&& _ic >= int(_state_act_trans_keys[_keys ]):
											_trans = uint(_state_act_indicies[_inds + int(( _ic - int(_state_act_trans_keys[_keys ]))  )]);
											
											default:
											_trans = uint(_state_act_index_defaults[cs]);
											
										}
									}
									
									default:
									{
										_trans = uint(_state_act_index_defaults[cs]);
									}
									
									
								}
							}
							
						}
						if _cont == 1  {
							{
								cs = int(_state_act_cond_targs[_trans]);
								if _state_act_cond_actions[_trans] != 0  {
									{
										_acts = int(_state_act_cond_actions[_trans] );
										_nacts = uint(_state_act_actions[_acts ]);
										_acts += 1;
										for _nacts > 0  {
											{
												switch _state_act_actions[_acts ] {
													case 6 :
													{{cs = 3;
														}}
													
													break;
													
												}
												_nacts -= 1;
												_acts += 1;
											}
											
										}
									}
									
									
								}
								_acts = int(_state_act_to_state_actions[cs] );
								_nacts = uint(_state_act_actions[_acts ]);
								_acts += 1;
								for _nacts > 0  {
									{
										switch _state_act_actions[_acts ] {
											case 0 :
											{fmt.Print( "a1\n" );}
											
											break;
											case 2 :
											{fmt.Print( "b1\n" );}
											
											break;
											case 4 :
											{fmt.Print( "c1\n" );}
											
											break;
											
										}
										_nacts -= 1;
										_acts += 1;
									}
									
									
								}
								if cs == 0  {
									_cont = 0;
									
								}
								if _cont == 1  {
									p += 1;
									
								}
							}
						}
					}
					
				}
			}
			
		}
	}
}
func finish() {
	if cs >= state_act_first_final {
		fmt.Println("ACCEPT")
	} else {
		fmt.Println("FAIL")
	}
}
var inp []string = []string {
	"hi\nhi\n",
};

func main() {
	for _, data := range inp {
		prepare()
		exec(data)
		finish()
	}
}
