#!/bin/sh -e
#

# The location of aapl files.
PREFIX=../../aapl

# Vector
ln -fs $PREFIX/vectcommon.h vector/vectcommon.h
ln -fs $PREFIX/vector.h vector/vector.h
ln -fs $PREFIX/svectcommon.h vector/svectcommon.h
ln -fs $PREFIX/svector.h vector/svector.h

# AvlTree
ln -fs $PREFIX/avlcommon.h avltree/avlcommon.h
ln -fs $PREFIX/avltree.h avltree/avltree.h
ln -fs $PREFIX/avlmel.h avltree/avlmel.h
ln -fs $PREFIX/avlmelkey.h avltree/avlmelkey.h
ln -fs $PREFIX/avlmap.h avltree/avlmap.h
ln -fs $PREFIX/avlset.h avltree/avlset.h
ln -fs $PREFIX/avlbasic.h avltree/avlbasic.h
ln -fs $PREFIX/avlkeyless.h avltree/avlkeyless.h

# AvliTree
ln -fs $PREFIX/avlcommon.h avlitree/avlcommon.h
ln -fs $PREFIX/avlitree.h avlitree/avlitree.h
ln -fs $PREFIX/avlimel.h avlitree/avlimel.h
ln -fs $PREFIX/avlimelkey.h avlitree/avlimelkey.h
ln -fs $PREFIX/avlimap.h avlitree/avlimap.h
ln -fs $PREFIX/avliset.h avlitree/avliset.h
ln -fs $PREFIX/avlibasic.h avlitree/avlibasic.h
ln -fs $PREFIX/avlikeyless.h avlitree/avlikeyless.h

# Double List
ln -fs $PREFIX/dlcommon.h dlist/dlcommon.h
ln -fs $PREFIX/dlist.h dlist/dlist.h
ln -fs $PREFIX/dlistmel.h dlist/dlistmel.h
ln -fs $PREFIX/dlistval.h dlist/dlistval.h

# Binary Search Table
ln -fs $PREFIX/bstcommon.h bsttable/bstcommon.h
ln -fs $PREFIX/bsttable.h bsttable/bsttable.h
ln -fs $PREFIX/bstmap.h bsttable/bstmap.h
ln -fs $PREFIX/bstset.h bsttable/bstset.h
ln -fs $PREFIX/sbsttable.h bsttable/sbsttable.h
ln -fs $PREFIX/sbstmap.h bsttable/sbstmap.h
ln -fs $PREFIX/sbstset.h bsttable/sbstset.h

# Sorting
ln -fs $PREFIX/bubblesort.h sort/bubblesort.h
ln -fs $PREFIX/mergesort.h sort/mergesort.h
ln -fs $PREFIX/insertsort.h sort/insertsort.h
ln -fs $PREFIX/quicksort.h sort/quicksort.h

# String
test -d string || mkdir string
ln -fs $PREFIX/shrstr.h string/shrstr.h

# Compare
test -d compare || mkdir compare
ln -fs $PREFIX/compare.h compare/compare.h
