#
# @LANG: ruby
# @GENERATED: true
#






class << self
	attr_accessor :_state_chart_actions 
	private :_state_chart_actions, :_state_chart_actions=
end
self._state_chart_actions = [
0, 1, 0, 1, 2, 2, 0, 1, 2, 0, 2, 2, 3, 4, 0 , 
]

class << self
	attr_accessor :_state_chart_key_offsets 
	private :_state_chart_key_offsets, :_state_chart_key_offsets=
end
self._state_chart_key_offsets = [
0, 0, 2, 5, 0 , 
]

class << self
	attr_accessor :_state_chart_trans_keys 
	private :_state_chart_trans_keys, :_state_chart_trans_keys=
end
self._state_chart_trans_keys = [
48, 57, 10, 48, 57, 43, 45, 48, 57, 0 , 
]

class << self
	attr_accessor :_state_chart_single_lengths 
	private :_state_chart_single_lengths, :_state_chart_single_lengths=
end
self._state_chart_single_lengths = [
0, 0, 1, 2, 0 , 
]

class << self
	attr_accessor :_state_chart_range_lengths 
	private :_state_chart_range_lengths, :_state_chart_range_lengths=
end
self._state_chart_range_lengths = [
0, 1, 1, 1, 0 , 
]

class << self
	attr_accessor :_state_chart_index_offsets 
	private :_state_chart_index_offsets, :_state_chart_index_offsets=
end
self._state_chart_index_offsets = [
0, 0, 2, 5, 0 , 
]

class << self
	attr_accessor :_state_chart_trans_cond_spaces 
	private :_state_chart_trans_cond_spaces, :_state_chart_trans_cond_spaces=
end
self._state_chart_trans_cond_spaces = [
-1, -1, -1, -1, -1, -1, -1, -1, -1, 0 , 
]

class << self
	attr_accessor :_state_chart_trans_offsets 
	private :_state_chart_trans_offsets, :_state_chart_trans_offsets=
end
self._state_chart_trans_offsets = [
0, 1, 2, 3, 4, 5, 6, 7, 8, 0 , 
]

class << self
	attr_accessor :_state_chart_trans_lengths 
	private :_state_chart_trans_lengths, :_state_chart_trans_lengths=
end
self._state_chart_trans_lengths = [
1, 1, 1, 1, 1, 1, 1, 1, 1, 0 , 
]

class << self
	attr_accessor :_state_chart_cond_keys 
	private :_state_chart_cond_keys, :_state_chart_cond_keys=
end
self._state_chart_cond_keys = [
0, 0, 0, 0, 0, 0, 0, 0, 0, 0 , 
]

class << self
	attr_accessor :_state_chart_cond_targs 
	private :_state_chart_cond_targs, :_state_chart_cond_targs=
end
self._state_chart_cond_targs = [
2, 0, 3, 2, 0, 1, 1, 2, 0, 0 , 
]

class << self
	attr_accessor :_state_chart_cond_actions 
	private :_state_chart_cond_actions, :_state_chart_cond_actions=
end
self._state_chart_cond_actions = [
3, 0, 11, 3, 0, 1, 5, 8, 0, 0 , 
]

class << self
	attr_accessor :_state_chart_nfa_targs 
	private :_state_chart_nfa_targs, :_state_chart_nfa_targs=
end
self._state_chart_nfa_targs = [
0, 0 , 
]

class << self
	attr_accessor :_state_chart_nfa_offsets 
	private :_state_chart_nfa_offsets, :_state_chart_nfa_offsets=
end
self._state_chart_nfa_offsets = [
0, 0, 0, 0, 0 , 
]

class << self
	attr_accessor :_state_chart_nfa_push_actions 
	private :_state_chart_nfa_push_actions, :_state_chart_nfa_push_actions=
end
self._state_chart_nfa_push_actions = [
0, 0 , 
]

class << self
	attr_accessor :_state_chart_nfa_pop_trans 
	private :_state_chart_nfa_pop_trans, :_state_chart_nfa_pop_trans=
end
self._state_chart_nfa_pop_trans = [
0, 0 , 
]

class << self
	attr_accessor :state_chart_start 
end
self.state_chart_start  = 3;

class << self
	attr_accessor :state_chart_first_final 
end
self.state_chart_first_final  = 3;

class << self
	attr_accessor :state_chart_error 
end
self.state_chart_error  = 0;

class << self
	attr_accessor :state_chart_en_main 
end
self.state_chart_en_main  = 3;

def run_machine( data )
	p = 0
	pe = data.length
	eof = data.length
	cs = 0;
	_m = 
	_a = 
	buffer = Array.new
	blen = 0
	neg = 1
	value = 1
	value = 0;
	neg = 0;
	begin
		cs = state_chart_start;
		
	end
	begin
		_klen= 0
		;
		_trans = 0;
		_cond = 0;
		_have = 0;
		_cont = 1;
		_acts = 0;
		_nacts= 0
		;
		_keys = 0;
		_ckeys = 0;
		_cpc= 0
		;
		while ( _cont == 1  )
			begin
				if ( cs == 0  )
					_cont = 0;
					
				end
				_have = 0;
				if ( p == pe  )
					begin
						if ( _have == 0  )
							_cont = 0;
							
						end
						
					end
					
				end
				if ( _cont == 1  )
					begin
						if ( _have == 0  )
							begin
								_keys = _state_chart_key_offsets[cs] ;
								_trans = _state_chart_index_offsets[cs];
								_have = 0;
								_klen = _state_chart_single_lengths[cs];
								if ( _klen > 0  )
									begin
										_lower = 0;
										_mid = 0;
										_upper = 0;
										_lower = _keys;
										_upper = _keys + _klen - 1;
										while ( _upper >= _lower && _have == 0  )
											begin
												_mid = _lower + ((_upper-_lower) >> 1);
												if ( ( data[p ].ord) < _state_chart_trans_keys[_mid ] )
													_upper = _mid - 1;
													
													elsif ( ( data[p ].ord) > _state_chart_trans_keys[_mid ] )
													_lower = _mid + 1;
													
													else
													begin
														_trans += (_mid - _keys);
														_have = 1;
														
													end
													
												end
												
											end
											
										end
										if ( _have == 0  )
											begin
												_keys += _klen;
												_trans += _klen;
												
											end
											
										end
										
									end
									
								end
								if ( _have == 0  )
									begin
										_klen = _state_chart_range_lengths[cs];
										if ( _klen > 0  )
											begin
												_lower = 0;
												_mid = 0;
												_upper = 0;
												_lower = _keys;
												_upper = _keys + (_klen<<1) - 2;
												while ( _have == 0 && _lower <= _upper  )
													begin
														_mid = _lower + (((_upper-_lower) >> 1) & ~1);
														if ( ( data[p ].ord) < _state_chart_trans_keys[_mid ] )
															_upper = _mid - 2;
															
															elsif ( ( data[p ].ord) > _state_chart_trans_keys[_mid + 1 ] )
															_lower = _mid + 2;
															
															else
															begin
																_trans += ((_mid - _keys)>>1);
																_have = 1;
																
															end
															
														end
														
													end
													
												end
												if ( _have == 0  )
													_trans += _klen;
													
												end
												
											end
											
										end
										
									end
									
								end
								_ckeys = _state_chart_trans_offsets[_trans] ;
								_klen = _state_chart_trans_lengths[_trans];
								_cond = _state_chart_trans_offsets[_trans];
								_have = 0;
								_cpc = 0;
								begin
									_lower = 0;
									_mid = 0;
									_upper = 0;
									_lower = _ckeys;
									_upper = _ckeys + _klen - 1;
									while ( _have == 0 && _lower <= _upper  )
										begin
											_mid = _lower + ((_upper-_lower) >> 1);
											if ( _cpc < _state_chart_cond_keys[_mid ] )
												_upper = _mid - 1;
												
												elsif ( _cpc > _state_chart_cond_keys[_mid ] )
												_lower = _mid + 1;
												
												else
												begin
													_cond += (_mid - _ckeys);
													_have = 1;
													
												end
												
											end
											
										end
										
									end
									if ( _have == 0  )
										begin
											cs = 0;
											_cont = 0;
											
										end
										
									end
									
								end
								
							end
							
						end
						if ( _cont == 1  )
							begin
								cs = _state_chart_cond_targs[_cond];
								if ( _state_chart_cond_actions[_cond] != 0  )
									begin
										_acts = _state_chart_cond_actions[_cond] ;
										_nacts = _state_chart_actions[_acts ];
										_acts += 1;
										while ( _nacts > 0  )
											begin
												case  _state_chart_actions[_acts ] 
												when -2 then
												begin
												end
												when 0  then
												begin
													begin
														neg = 0;
														value = 0;
														
													end
													
												end
												when 1  then
												begin
													begin
														neg = 1;
														
													end
													
												end
												when 2  then
												begin
													begin
														value = value * 10 + ( ( data[p ].ord) - 48 )
														;
														
													end
													
												end
												when 3  then
												begin
													begin
														if ( neg != 0 )
															value = -1 * value;
															
														end
														
													end
													
												end
												when 4  then
												begin
													begin
														print( value );
														print( "\n" );
														
													end
													
													
												end
											end
											_nacts -= 1;
											_acts += 1;
											
										end
										
									end
									
								end
								
							end
							if ( cs == 0  )
								_cont = 0;
								
							end
							if ( _cont == 1  )
								p += 1;
								
							end
							
						end
						
					end
					
				end
				
			end
			
		end
		
	end
	
end
if cs >= state_chart_first_final
	puts "ACCEPT"
	else
	puts "FAIL"
end
end
	
	inp = [
	"1\n",
	"12\n",
	"222222\n",
	"+2123\n",
	"213 3213\n",
	"-12321\n",
	"--123\n",
	"-99\n",
	" -3000\n",
	]
	
	inplen = 9
	
	inp.each { |str| run_machine(str) }
	
