static mut neg : i8 = 0;
static mut value : i32 = 0;





static _atoi_actions: [i8 ; 16] = [ 0, 1, 0, 1, 2, 2, 0, 1, 2, 0, 2, 2, 3, 4, 0 , 0 ];
static _atoi_trans_keys: [u8 ; 12] = [ 1, 0, 2, 4, 4, 4, 0, 4, 1, 0, 0 , 0 ];
static _atoi_char_class: [i8 ; 50] = [ 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 3, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0 , 0 ];
static _atoi_index_offsets: [i8 ; 7] = [ 0, 0, 3, 4, 9, 0 , 0 ];
static _atoi_indicies: [i8 ; 11] = [ 0, 2, 3, 4, 5, 1, 1, 1, 4, 0 , 0 ];
static _atoi_index_defaults: [i8 ; 7] = [ 0, 1, 1, 1, 1, 0 , 0 ];
static _atoi_trans_cond_spaces: [i8 ; 8] = [ -1, -1, -1, -1, -1, -1, 0 , 0 ];
static _atoi_cond_targs: [i8 ; 8] = [ 2, 0, 2, 3, 3, 4, 0 , 0 ];
static _atoi_cond_actions: [i8 ; 8] = [ 1, 0, 5, 8, 3, 11, 0 , 0 ];
static _atoi_nfa_targs: [i8 ; 3] = [ 0, 0 , 0 ];
static _atoi_nfa_offsets: [i8 ; 7] = [ 0, 0, 0, 0, 0, 0 , 0 ];
static _atoi_nfa_push_actions: [i8 ; 3] = [ 0, 0 , 0 ];
static _atoi_nfa_pop_trans: [i8 ; 3] = [ 0, 0 , 0 ];
static atoi_start : i32 = 1;
static atoi_first_final : i32 = 4;
static atoi_error : i32 = 0;
static atoi_en_main : i32 = 1;
unsafe fn m( s: String )
{
	let data: &[u8] = s.as_bytes();
	let mut p:i32 = 0;
	let mut pe:i32 = s.len() as i32;
	let mut eof:i32 = s.len() as i32;
	let mut cs: i32 = 0;
	let mut buffer = String::new();
	value = 0;
	neg = 0;
	
	
	{
		cs = ( atoi_start ) as i32;
	}
	
	{
		let mut _trans  = 0;
		let mut _have  = 0;
		let mut _cont  = 1;
		let mut _acts :i32 = 0;
		let mut _nacts = 0;
		let mut _keys :i32 = 0;
		let mut _inds :i32 = 0;
		while ( _cont == 1  )
		{
		
			if ( cs == 0  ) {
				_cont = 0;
				
			}
			_have = 0;
			if ( p == pe  ) {
				{
					if ( _have == 0  ) {
						_cont = 0;
						
					}
				}
				
			}
			if ( _cont == 1  ) {
				{
					if ( _have == 0  ) {
						{
							_keys = ( (cs<<1)  ) as i32;
							_inds = ( _atoi_index_offsets[(cs) as usize] ) as i32;
							if ( ( data[(p ) as usize]
							) <= 57 && ( data[(p ) as usize]
							) >= 10  ) {
								{
									let mut _ic  = ( _atoi_char_class[(( ( data[(p ) as usize]
									)  ) as i32- 10) as usize] ) as i32;
									if ( _ic <= ( _atoi_trans_keys[(_keys+1 ) as usize]
									) as i32&& _ic >= ( _atoi_trans_keys[(_keys ) as usize]
									) as i32 ) {
										_trans = ( _atoi_indicies[(_inds + ( ( _ic - ( _atoi_trans_keys[(_keys ) as usize]
										) as i32)   ) as i32) as usize]
										) as u32;
										
									}
									else {
										_trans = ( _atoi_index_defaults[(cs) as usize] ) as u32;
										
									}
								}
								
							}
							else {
								{
									_trans = ( _atoi_index_defaults[(cs) as usize] ) as u32;
								}
								
								
							}
						}
						
					}
					if ( _cont == 1  ) {
						{
							cs = ( _atoi_cond_targs[(_trans) as usize] ) as i32;
							if ( _atoi_cond_actions[(_trans) as usize]!= 0  ) {
								{
									_acts = ( _atoi_cond_actions[(_trans) as usize] ) as i32;
									_nacts = ( _atoi_actions[(_acts ) as usize]
									) as u32;
									_acts += 1;
									while ( _nacts > 0  )
									{
										match ( _atoi_actions[(_acts ) as usize]
										) {
											0  => {
												{neg = 0;
													value = 0;
												}
												
											}
											1  => {
												{neg = 1;
												}
												
											}
											2  => {
												{value = value * 10 + ( ( (( data[(p ) as usize]
													)) - 48 ) as i32 ) 
													;
												}
												
											}
											3  => {
												{if ( neg != 0 )
													{
														value = -1 * value;
														
													} 
												}
												
											}
											4  => {
												{print!( "{}", value );
													print!( "{}", "\n" );
												}
												
											}
											
											_ => {}
										}
										_nacts -= 1;
										_acts += 1;
									}
									
								}
								
								
							}
							if ( cs == 0  ) {
								_cont = 0;
								
							}
							if ( _cont == 1  ) {
								p += 1;
								
							}
						}
					}
				}
				
			}
		}
		
	}
	if ( cs >= atoi_first_final ) {
		println!( "ACCEPT" );
	}
	else {
		println!( "FAIL" );
	}
}

fn main()
{
	unsafe { m( "1\n".to_string() ); }
	unsafe { m( "12\n".to_string() ); }
	unsafe { m( "222222\n".to_string() ); }
	unsafe { m( "+2123\n".to_string() ); }
	unsafe { m( "213 3213\n".to_string() ); }
	unsafe { m( "-12321\n".to_string() ); }
	unsafe { m( "--123\n".to_string() ); }
	unsafe { m( "-99\n".to_string() ); }
	unsafe { m( " -3000\n".to_string() ); }
}

