(*
* @LANG: ocaml
* @GENERATED: true
*)









let _eofact_trans_keys : int array = [|
1; 0; 3; 7; 2; 2; 4; 4; 4; 4; 5; 5; 3; 3; 2; 2; 6; 6; 2; 2; 0; 0; 1; 0; 1; 0; 0 ; 
|]
let _eofact_char_class : int array = [|
0; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 2; 1; 1; 3; 1; 1; 1; 4; 1; 1; 5; 1; 1; 6; 1; 7; 0 ; 
|]
let _eofact_index_offsets : int array = [|
0; 0; 5; 6; 7; 8; 9; 10; 11; 12; 13; 14; 14; 0 ; 
|]
let _eofact_indicies : int array = [|
0; 1; 1; 1; 2; 3; 4; 5; 6; 7; 8; 9; 10; 11; 0 ; 
|]
let _eofact_index_defaults : int array = [|
0; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 0 ; 
|]
let _eofact_trans_cond_spaces : int array = [|
-1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; 0 ; 
|]
let _eofact_cond_targs : int array = [|
2; 0; 6; 3; 4; 5; 10; 7; 8; 9; 12; 11; 0 ; 
|]
let _eofact_cond_actions : int array = [|
0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0 ; 
|]
let _eofact_eof_actions : int array = [|
0; 1; 2; 2; 2; 2; 3; 3; 3; 3; 4; 0; 5; 0 ; 
|]
let _eofact_nfa_targs : int array = [|
0; 0 ; 
|]
let _eofact_nfa_offsets : int array = [|
0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0 ; 
|]
let _eofact_nfa_push_actions : int array = [|
0; 0 ; 
|]
let _eofact_nfa_pop_trans : int array = [|
0; 0 ; 
|]
let eofact_start  : int  = 1
let eofact_first_final  : int  = 10
let eofact_error  : int  = 0
let eofact_en_main  : int  = 1
let exec data = 
let buffer = String.create(1024) in 
let blen :int ref = ref 0 in
let cs = ref 0 in
let p = ref 0 in
let pe = ref (String.length data) in
let eof = pe in
begin
	cs  := eofact_start;
	
end;
begin
	let _trans  : int  ref = ref 0 in
	let _have  : int  ref = ref 0 in
	let _cont  : int  ref = ref 1 in
	let _keys : int ref = ref 0 in
	let _inds : int ref = ref 0 in
	while _cont.contents= 1  do
	begin
		if cs.contents= 0  then
		begin
			_cont  := 0;
			
		end
		;_have  := 0;
		if p.contents= pe.contents then
		begin
			begin
				if p.contents= eof.contents then
				begin
					begin
						if _have.contents= 0  then
						begin
							begin
								if _eofact_eof_actions.(cs.contents) = 2  then
								begin
									begin
										print_string( "a1\n" );
										
									end;
									
								end
								else if _eofact_eof_actions.(cs.contents) = 4  then
								begin
									begin
										print_string( "a2\n" );
										
									end;
									
								end
								else if _eofact_eof_actions.(cs.contents) = 3  then
								begin
									begin
										print_string( "a3\n" );
										
									end;
									
								end
								else if _eofact_eof_actions.(cs.contents) = 5  then
								begin
									begin
										print_string( "a4\n" );
										
									end;
									
								end
								else if _eofact_eof_actions.(cs.contents) = 1  then
								begin
									begin
										print_string( "a1\n" );
										
									end;
									begin
										print_string( "a3\n" );
										
									end;
									
								end
								;
								
							end;
							
						end
						;
					end;
					
				end
				;if _have.contents= 0  then
				begin
					_cont  := 0;
					
				end
				;
			end;
			
		end
		;if _cont.contents= 1  then
		begin
			begin
				if _have.contents= 0  then
				begin
					begin
						_keys  := ( cs.contents lsl 1 );
						_inds  := _eofact_index_offsets.(cs.contents);
						if ( Char.code data.[p.contents] )<= 116 && ( Char.code data.[p.contents] )>= 10  then
						begin
							begin
								let _ic  : int  ref = ref _eofact_char_class.(( Char.code data.[p.contents] )- 10) in
								if _ic.contents<= _eofact_trans_keys.( _keys.contents+1  )&& _ic.contents>= _eofact_trans_keys.( _keys.contents ) then
								begin
									_trans  := _eofact_indicies.( _inds.contents+ ( _ic.contents- _eofact_trans_keys.( _keys.contents ) ) );
									
								end
								else
								begin
									_trans  := _eofact_index_defaults.(cs.contents);
									
								end
								;
							end;
							
						end
						else
						begin
							begin
								_trans  := _eofact_index_defaults.(cs.contents);
								
							end;
							
						end
						;
					end;
					
				end
				;if _cont.contents= 1  then
				begin
					begin
						cs  := _eofact_cond_targs.(_trans.contents);
						if cs.contents= 0  then
						begin
							_cont  := 0;
							
						end
						;if _cont.contents= 1  then
						begin
							p  := p.contents + 1;
							
						end
						;
					end;
					
				end
				;
			end;
			
		end
		;
	end;
	
	done;
	
end;
if !cs >= eofact_first_final then
print_string "ACCEPT\n"
else
print_string "FAIL\n"
;;

let () =
exec "";
exec "h";
exec "hell";
exec "hello";
exec "hello\n";
exec "t";
exec "ther";
exec "there";
exec "friend";
()
;;

