class eofact_java
{







	private static byte  _eofact_key_offsets [] = { 0, 0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 11, 0 ,  };
	private static char  _eofact_trans_keys [] = { 104, 116, 101, 108, 108, 111, 104, 101, 114, 101, 10, 0,  };
	private static byte  _eofact_single_lengths [] = { 0, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0 ,  };
	private static byte  _eofact_range_lengths [] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  };
	private static byte  _eofact_index_offsets [] = { 0, 0, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 22, 0 ,  };
	private static byte  _eofact_trans_cond_spaces [] = { -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0 ,  };
	private static byte  _eofact_trans_offsets [] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 0 ,  };
	private static byte  _eofact_trans_lengths [] = { 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0 ,  };
	private static byte  _eofact_cond_keys [] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  };
	private static byte  _eofact_cond_targs [] = { 2, 6, 0, 3, 0, 4, 0, 5, 0, 10, 0, 7, 0, 8, 0, 9, 0, 12, 0, 11, 0, 0, 0, 0 ,  };
	private static byte  _eofact_cond_actions [] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  };
	private static byte  _eofact_eof_actions [] = { 0, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 0, 5, 0 ,  };
	private static byte  _eofact_nfa_targs [] = { 0, 0 ,  };
	private static byte  _eofact_nfa_offsets [] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  };
	private static byte  _eofact_nfa_push_actions [] = { 0, 0 ,  };
	private static byte  _eofact_nfa_pop_trans [] = { 0, 0 ,  };
	private static int  eofact_start  = 1;
	private static int  eofact_first_final  = 10;
	private static int  eofact_error  = 0;
	private static int  eofact_en_main  = 1;
	int cs;
	
	void init()
	{
		{
			cs = (int)eofact_start;
			
		}
	}
	
	void exec( char data[], int len )
	{
		char buffer [] = new char[1024];
		int blen = 0;
		int p = 0;
		int pe = len;
		
		int eof = len;
		String _s;
		{
			int _klen;
			int _keys;
			int _ckeys;
			int _cpc;
			int _trans = 0;
			int _cond = 0;
			int _goto_targ = 0;
			_goto: while ( true ) {
				switch ( _goto_targ ) {
					case 0:
					if ( p == pe  )
					{
						_goto_targ = 5;
						if (true)
						continue _goto;
					}
					
					if ( cs == 0  )
					{
						_goto_targ = 6;
						if (true)
						continue _goto;
					}
					
					case 1:
					_keys = _eofact_key_offsets[cs] ;
					_trans = (int )_eofact_index_offsets[cs];
					_klen = (int)_eofact_single_lengths[cs];
					if ( _klen > 0  )
					{
						int _lower;
						int _mid;
						int _upper;
						_lower = _keys;
						_upper = _keys + _klen - 1;
						while ( true  )
						{
							if ( _upper < _lower  )
							break;
							
							
							_mid = _lower + ((_upper-_lower) >> 1);
							if ( ( data[p ]) < _eofact_trans_keys[_mid ] )
							_upper = _mid - 1;
							
							else if ( ( data[p ]) > _eofact_trans_keys[_mid ] )
							_lower = _mid + 1;
							
							else
							{
								_trans += (int )(_mid - _keys);
								{
									_goto_targ = 2;
									if (true)
									continue _goto;
								}
								
							}
							
							
						}
						
						_keys += _klen;
						_trans += (int )_klen;
						
					}
					
					_klen = (int)_eofact_range_lengths[cs];
					if ( _klen > 0  )
					{
						int _lower;
						int _mid;
						int _upper;
						_lower = _keys;
						_upper = _keys + (_klen<<1) - 2;
						while ( true  )
						{
							if ( _upper < _lower  )
							break;
							
							
							_mid = _lower + (((_upper-_lower) >> 1) & ~1);
							if ( ( data[p ]) < _eofact_trans_keys[_mid ] )
							_upper = _mid - 2;
							
							else if ( ( data[p ]) > _eofact_trans_keys[_mid + 1 ] )
							_lower = _mid + 2;
							
							else
							{
								_trans += (int )((_mid - _keys)>>1);
								{
									_goto_targ = 2;
									if (true)
									continue _goto;
								}
								
							}
							
							
						}
						
						_trans += (int )_klen;
						
					}
					
					
					case 2:
					_ckeys = _eofact_trans_offsets[_trans] ;
					_klen = (int)_eofact_trans_lengths[_trans];
					_cond = (int )_eofact_trans_offsets[_trans];
					_cpc = 0;
					{
						int _lower;
						int _mid;
						int _upper;
						_lower = _ckeys;
						_upper = _ckeys + _klen - 1;
						while ( true  )
						{
							if ( _upper < _lower  )
							break;
							
							
							_mid = _lower + ((_upper-_lower) >> 1);
							if ( _cpc < (int)_eofact_cond_keys[_mid ] )
							_upper = _mid - 1;
							
							else if ( _cpc > (int)_eofact_cond_keys[_mid ] )
							_lower = _mid + 1;
							
							else
							{
								_cond += (int )(_mid - _ckeys);
								{
									_goto_targ = 3;
									if (true)
									continue _goto;
								}
								
							}
							
							
						}
						
						cs = 0;
						{
							_goto_targ = 4;
							if (true)
							continue _goto;
						}
						
					}
					
					case 3:
					cs = (int)_eofact_cond_targs[_cond];
					
					case 4:
					if ( cs == 0  )
					{
						_goto_targ = 6;
						if (true)
						continue _goto;
					}
					
					p += 1;
					if ( p != pe  )
					{
						_goto_targ = 1;
						if (true)
						continue _goto;
					}
					
					
					case 5:
					{
					
					}
					if ( p == eof  )
					{
						switch ( _eofact_eof_actions[cs]  ) {
							case 2 :
							{
								System.out.print( "a1\n" );
								
							}
							
							break;
							case 4 :
							{
								System.out.print( "a2\n" );
								
							}
							
							break;
							case 3 :
							{
								System.out.print( "a3\n" );
								
							}
							
							break;
							case 5 :
							{
								System.out.print( "a4\n" );
								
							}
							
							break;
							case 1 :
							{
								System.out.print( "a1\n" );
								
							}
							{
								System.out.print( "a3\n" );
								
							}
							
							break;
							
						}
						
					}
					
					
					case 6:
					{
					
					}
					
					
				}
				break;
			}
			
		}
	}
	
	void finish( )
	{
		if ( cs >= eofact_first_final )
		System.out.println( "ACCEPT" );
		else
		System.out.println( "FAIL" );
	}
	
	static final String inp[] = {
		"",
		"h",
		"hell",
		"hello",
		"hello\n",
		"t",
		"ther",
		"there",
		"friend",
	};
	
	static final int inplen = 9;
	
	public static void main (String[] args)
	{
		eofact_java machine = new eofact_java();
		for ( int i = 0; i < inplen; i++ ) {
			machine.init();
			machine.exec( inp[i].toCharArray(), inp[i].length() );
			machine.finish();
		}
	}
}
