#
# @LANG: ruby
# @GENERATED: true
#








class << self
	attr_accessor :_eofact_key_offsets 
	private :_eofact_key_offsets, :_eofact_key_offsets=
end
self._eofact_key_offsets = [
0, 0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 11, 0 , 
]

class << self
	attr_accessor :_eofact_trans_keys 
	private :_eofact_trans_keys, :_eofact_trans_keys=
end
self._eofact_trans_keys = [
104, 116, 101, 108, 108, 111, 104, 101, 114, 101, 10, 0 , 
]

class << self
	attr_accessor :_eofact_single_lengths 
	private :_eofact_single_lengths, :_eofact_single_lengths=
end
self._eofact_single_lengths = [
0, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0 , 
]

class << self
	attr_accessor :_eofact_range_lengths 
	private :_eofact_range_lengths, :_eofact_range_lengths=
end
self._eofact_range_lengths = [
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 , 
]

class << self
	attr_accessor :_eofact_index_offsets 
	private :_eofact_index_offsets, :_eofact_index_offsets=
end
self._eofact_index_offsets = [
0, 0, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 22, 0 , 
]

class << self
	attr_accessor :_eofact_trans_cond_spaces 
	private :_eofact_trans_cond_spaces, :_eofact_trans_cond_spaces=
end
self._eofact_trans_cond_spaces = [
-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0 , 
]

class << self
	attr_accessor :_eofact_trans_offsets 
	private :_eofact_trans_offsets, :_eofact_trans_offsets=
end
self._eofact_trans_offsets = [
0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 0 , 
]

class << self
	attr_accessor :_eofact_trans_lengths 
	private :_eofact_trans_lengths, :_eofact_trans_lengths=
end
self._eofact_trans_lengths = [
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0 , 
]

class << self
	attr_accessor :_eofact_cond_keys 
	private :_eofact_cond_keys, :_eofact_cond_keys=
end
self._eofact_cond_keys = [
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 , 
]

class << self
	attr_accessor :_eofact_cond_targs 
	private :_eofact_cond_targs, :_eofact_cond_targs=
end
self._eofact_cond_targs = [
2, 6, 0, 3, 0, 4, 0, 5, 0, 10, 0, 7, 0, 8, 0, 9, 0, 12, 0, 11, 0, 0, 0, 0 , 
]

class << self
	attr_accessor :_eofact_cond_actions 
	private :_eofact_cond_actions, :_eofact_cond_actions=
end
self._eofact_cond_actions = [
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 , 
]

class << self
	attr_accessor :_eofact_eof_actions 
	private :_eofact_eof_actions, :_eofact_eof_actions=
end
self._eofact_eof_actions = [
0, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 0, 5, 0 , 
]

class << self
	attr_accessor :_eofact_nfa_targs 
	private :_eofact_nfa_targs, :_eofact_nfa_targs=
end
self._eofact_nfa_targs = [
0, 0 , 
]

class << self
	attr_accessor :_eofact_nfa_offsets 
	private :_eofact_nfa_offsets, :_eofact_nfa_offsets=
end
self._eofact_nfa_offsets = [
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 , 
]

class << self
	attr_accessor :_eofact_nfa_push_actions 
	private :_eofact_nfa_push_actions, :_eofact_nfa_push_actions=
end
self._eofact_nfa_push_actions = [
0, 0 , 
]

class << self
	attr_accessor :_eofact_nfa_pop_trans 
	private :_eofact_nfa_pop_trans, :_eofact_nfa_pop_trans=
end
self._eofact_nfa_pop_trans = [
0, 0 , 
]

class << self
	attr_accessor :eofact_start 
end
self.eofact_start  = 1;

class << self
	attr_accessor :eofact_first_final 
end
self.eofact_first_final  = 10;

class << self
	attr_accessor :eofact_error 
end
self.eofact_error  = 0;

class << self
	attr_accessor :eofact_en_main 
end
self.eofact_en_main  = 1;

def run_machine( data )
	p = 0
	pe = data.length
	eof = data.length
	cs = 0;
	_m = 
	_a = 
	buffer = Array.new
	blen = 0
	begin
		cs = eofact_start;
		
	end
	begin
		_klen= 0
		;
		_keys = 0;
		_ckeys = 0;
		_cpc= 0
		;
		_trans= 0
		;
		_cond = 0;
		_have = 0;
		_cont = 1;
		while ( _cont == 1  )
			begin
				if ( cs == 0  )
					_cont = 0;
					
				end
				_have = 0;
				if ( p == pe  )
					begin
						if ( p == eof  )
							begin
								if ( _have == 0  )
									begin
										case  _eofact_eof_actions[cs]  
										when -2 then
										begin
										end
										when 2  then
										begin
											begin
												print( "a1\n" );
												
											end
											
										end
										when 4  then
										begin
											begin
												print( "a2\n" );
												
											end
											
										end
										when 3  then
										begin
											begin
												print( "a3\n" );
												
											end
											
										end
										when 5  then
										begin
											begin
												print( "a4\n" );
												
											end
											
										end
										when 1  then
										begin
											begin
												print( "a1\n" );
												
											end
											begin
												print( "a3\n" );
												
											end
											
											
										end
									end
									
								end
								
							end
							
						end
						
					end
					if ( _have == 0  )
						_cont = 0;
						
					end
					
				end
				
			end
			if ( _cont == 1  )
				begin
					if ( _have == 0  )
						begin
							_keys = _eofact_key_offsets[cs] ;
							_trans = _eofact_index_offsets[cs];
							_have = 0;
							_klen = _eofact_single_lengths[cs];
							if ( _klen > 0  )
								begin
									_lower = 0;
									_mid = 0;
									_upper = 0;
									_lower = _keys;
									_upper = _keys + _klen - 1;
									while ( _upper >= _lower && _have == 0  )
										begin
											_mid = _lower + ((_upper-_lower) >> 1);
											if ( ( data[p ].ord) < _eofact_trans_keys[_mid ] )
												_upper = _mid - 1;
												
												elsif ( ( data[p ].ord) > _eofact_trans_keys[_mid ] )
												_lower = _mid + 1;
												
												else
												begin
													_trans += (_mid - _keys);
													_have = 1;
													
												end
												
											end
											
										end
										
									end
									if ( _have == 0  )
										begin
											_keys += _klen;
											_trans += _klen;
											
										end
										
									end
									
								end
								
							end
							if ( _have == 0  )
								begin
									_klen = _eofact_range_lengths[cs];
									if ( _klen > 0  )
										begin
											_lower = 0;
											_mid = 0;
											_upper = 0;
											_lower = _keys;
											_upper = _keys + (_klen<<1) - 2;
											while ( _have == 0 && _lower <= _upper  )
												begin
													_mid = _lower + (((_upper-_lower) >> 1) & ~1);
													if ( ( data[p ].ord) < _eofact_trans_keys[_mid ] )
														_upper = _mid - 2;
														
														elsif ( ( data[p ].ord) > _eofact_trans_keys[_mid + 1 ] )
														_lower = _mid + 2;
														
														else
														begin
															_trans += ((_mid - _keys)>>1);
															_have = 1;
															
														end
														
													end
													
												end
												
											end
											if ( _have == 0  )
												_trans += _klen;
												
											end
											
										end
										
									end
									
								end
								
							end
							_ckeys = _eofact_trans_offsets[_trans] ;
							_klen = _eofact_trans_lengths[_trans];
							_cond = _eofact_trans_offsets[_trans];
							_have = 0;
							_cpc = 0;
							begin
								_lower = 0;
								_mid = 0;
								_upper = 0;
								_lower = _ckeys;
								_upper = _ckeys + _klen - 1;
								while ( _have == 0 && _lower <= _upper  )
									begin
										_mid = _lower + ((_upper-_lower) >> 1);
										if ( _cpc < _eofact_cond_keys[_mid ] )
											_upper = _mid - 1;
											
											elsif ( _cpc > _eofact_cond_keys[_mid ] )
											_lower = _mid + 1;
											
											else
											begin
												_cond += (_mid - _ckeys);
												_have = 1;
												
											end
											
										end
										
									end
									
								end
								if ( _have == 0  )
									begin
										cs = 0;
										_cont = 0;
										
									end
									
								end
								
							end
							
						end
						
					end
					if ( _cont == 1  )
						begin
							cs = _eofact_cond_targs[_cond];
							if ( cs == 0  )
								_cont = 0;
								
							end
							if ( _cont == 1  )
								p += 1;
								
							end
							
						end
						
					end
					
				end
				
			end
			
		end
		
	end
	
end
if cs >= eofact_first_final
	puts "ACCEPT"
	else
	puts "FAIL"
end
end
	
	inp = [
	"",
	"h",
	"hell",
	"hello",
	"hello\n",
	"t",
	"ther",
	"there",
	"friend",
	]
	
	inplen = 9
	
	inp.each { |str| run_machine(str) }
	
