(*
* @LANG: ocaml
* @GENERATED: true
*)









let _erract_actions : int array = [|
0; 2; 0; 1; 2; 1; 2; 2; 1; 3; 4; 0; 4; 1; 5; 4; 1; 2; 5; 6; 4; 1; 3; 5; 7; 0 ; 
|]
let _erract_key_offsets : int array = [|
0; 0; 1; 2; 3; 4; 5; 6; 0 ; 
|]
let _erract_trans_keys : int array = [|
104; 101; 108; 108; 111; 10; 0 ; 
|]
let _erract_single_lengths : int array = [|
0; 1; 1; 1; 1; 1; 1; 0; 0 ; 
|]
let _erract_range_lengths : int array = [|
0; 0; 0; 0; 0; 0; 0; 0; 0 ; 
|]
let _erract_index_offsets : int array = [|
0; 0; 2; 4; 6; 8; 10; 12; 0 ; 
|]
let _erract_trans_cond_spaces : int array = [|
-1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; 0 ; 
|]
let _erract_trans_offsets : int array = [|
0; 1; 2; 3; 4; 5; 6; 7; 8; 9; 10; 11; 12; 0 ; 
|]
let _erract_trans_lengths : int array = [|
1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 0 ; 
|]
let _erract_cond_keys : int array = [|
0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0 ; 
|]
let _erract_cond_targs : int array = [|
2; 0; 3; 0; 4; 0; 5; 0; 6; 0; 7; 0; 0; 0 ; 
|]
let _erract_cond_actions : int array = [|
0; 1; 0; 4; 0; 4; 0; 4; 0; 4; 0; 7; 0; 0 ; 
|]
let _erract_eof_actions : int array = [|
0; 10; 15; 15; 15; 15; 20; 0; 0 ; 
|]
let _erract_nfa_targs : int array = [|
0; 0 ; 
|]
let _erract_nfa_offsets : int array = [|
0; 0; 0; 0; 0; 0; 0; 0; 0 ; 
|]
let _erract_nfa_push_actions : int array = [|
0; 0 ; 
|]
let _erract_nfa_pop_trans : int array = [|
0; 0 ; 
|]
let erract_start  : int  = 1
let erract_first_final  : int  = 7
let erract_error  : int  = 0
let erract_en_main  : int  = 1
let exec data = 
let buffer = String.create(1024) in 
let blen :int ref = ref 0 in
let cs = ref 0 in
let p = ref 0 in
let pe = ref (String.length data) in
let eof = pe in
begin
	cs  := erract_start;
	
end;
begin
	let _klen : int  ref = ref 0 in
	let _trans  : int  ref = ref 0 in
	let _cond  : int  ref = ref 0 in
	let _have  : int  ref = ref 0 in
	let _cont  : int  ref = ref 1 in
	let _acts : int ref = ref 0 in
	let _nacts : int  ref = ref 0 in
	let _keys : int ref = ref 0 in
	let _ckeys : int ref = ref 0 in
	let _cpc : int  ref = ref 0 in
	while _cont.contents= 1  do
	begin
		if cs.contents= 0  then
		begin
			_cont  := 0;
			
		end
		;_have  := 0;
		if p.contents= pe.contents then
		begin
			begin
				if p.contents= eof.contents then
				begin
					begin
						if _have.contents= 0  then
						begin
							begin
								let __acts : int ref = ref 0 in
								let __nacts : int  ref = ref 0 in
								__acts  := _erract_eof_actions.(cs.contents);
								__nacts  := _erract_actions.( __acts.contents );
								__acts  := __acts.contents + 1;
								while __nacts.contents> 0  do
								begin
									if _erract_actions.( __acts.contents ) = 0  then
									begin
										begin
											print_string( "err_start\n" );
											
										end;
										
									end
									else if _erract_actions.( __acts.contents ) = 1  then
									begin
										begin
											print_string( "err_all\n" );
											
										end;
										
									end
									else if _erract_actions.( __acts.contents ) = 2  then
									begin
										begin
											print_string( "err_middle\n" );
											
										end;
										
									end
									else if _erract_actions.( __acts.contents ) = 3  then
									begin
										begin
											print_string( "err_out\n" );
											
										end;
										
									end
									else if _erract_actions.( __acts.contents ) = 4  then
									begin
										begin
											print_string( "eof_start\n" );
											
										end;
										
									end
									else if _erract_actions.( __acts.contents ) = 5  then
									begin
										begin
											print_string( "eof_all\n" );
											
										end;
										
									end
									else if _erract_actions.( __acts.contents ) = 6  then
									begin
										begin
											print_string( "eof_middle\n" );
											
										end;
										
									end
									else if _erract_actions.( __acts.contents ) = 7  then
									begin
										begin
											print_string( "eof_out\n" );
											
										end;
										
									end
									;
									__nacts  := __nacts.contents - 1;
									__acts  := __acts.contents + 1;
									
								end;
								
								done;
								
							end;
							
						end
						;
					end;
					
				end
				;if _have.contents= 0  then
				begin
					_cont  := 0;
					
				end
				;
			end;
			
		end
		;if _cont.contents= 1  then
		begin
			begin
				if _have.contents= 0  then
				begin
					begin
						_keys  := _erract_key_offsets.(cs.contents);
						_trans  := _erract_index_offsets.(cs.contents);
						_have  := 0;
						_klen  := _erract_single_lengths.(cs.contents);
						if _klen.contents> 0  then
						begin
							begin
								let _lower : int ref = ref 0 in
								let _mid : int ref = ref 0 in
								let _upper : int ref = ref 0 in
								_lower  := _keys.contents;
								_upper  := _keys.contents+ _klen.contents- 1;
								while _upper.contents>= _lower.contents&& _have.contents= 0  do
								begin
									_mid  := _lower.contents+ ( ( _upper.contents-_lower.contents ) asr 1 );
									if ( Char.code data.[p.contents] )< _erract_trans_keys.( _mid.contents ) then
									begin
										_upper  := _mid.contents- 1;
										
									end
									else if ( Char.code data.[p.contents] )> _erract_trans_keys.( _mid.contents ) then
									begin
										_lower  := _mid.contents+ 1;
										
									end
									else
									begin
										begin
											_trans  := _trans.contents + ( _mid.contents- _keys.contents );
											_have  := 1;
											
										end;
										
									end
									;
								end;
								
								done;
								if _have.contents= 0  then
								begin
									begin
										_keys  := _keys.contents + _klen.contents;
										_trans  := _trans.contents + _klen.contents;
										
									end;
									
								end
								;
							end;
							
						end
						;if _have.contents= 0  then
						begin
							begin
								_klen  := _erract_range_lengths.(cs.contents);
								if _klen.contents> 0  then
								begin
									begin
										let _lower : int ref = ref 0 in
										let _mid : int ref = ref 0 in
										let _upper : int ref = ref 0 in
										_lower  := _keys.contents;
										_upper  := _keys.contents+ ( _klen.contents lsl 1 )- 2;
										while _have.contents= 0 && _lower.contents<= _upper.contents do
										begin
											_mid  := _lower.contents+ ( ( ( _upper.contents-_lower.contents ) asr 1 ) land  lnot 1 );
											if ( Char.code data.[p.contents] )< _erract_trans_keys.( _mid.contents ) then
											begin
												_upper  := _mid.contents- 2;
												
											end
											else if ( Char.code data.[p.contents] )> _erract_trans_keys.( _mid.contents+ 1  ) then
											begin
												_lower  := _mid.contents+ 2;
												
											end
											else
											begin
												begin
													_trans  := _trans.contents + ( ( _mid.contents- _keys.contents ) asr 1 );
													_have  := 1;
													
												end;
												
											end
											;
										end;
										
										done;
										if _have.contents= 0  then
										begin
											_trans  := _trans.contents + _klen.contents;
											
										end
										;
									end;
									
								end
								;
							end;
							
						end
						;_ckeys  := _erract_trans_offsets.(_trans.contents);
						_klen  := _erract_trans_lengths.(_trans.contents);
						_cond  := _erract_trans_offsets.(_trans.contents);
						_have  := 0;
						_cpc  := 0;
						begin
							let _lower : int ref = ref 0 in
							let _mid : int ref = ref 0 in
							let _upper : int ref = ref 0 in
							_lower  := _ckeys.contents;
							_upper  := _ckeys.contents+ _klen.contents- 1;
							while _have.contents= 0 && _lower.contents<= _upper.contents do
							begin
								_mid  := _lower.contents+ ( ( _upper.contents-_lower.contents ) asr 1 );
								if _cpc.contents< _erract_cond_keys.( _mid.contents ) then
								begin
									_upper  := _mid.contents- 1;
									
								end
								else if _cpc.contents> _erract_cond_keys.( _mid.contents ) then
								begin
									_lower  := _mid.contents+ 1;
									
								end
								else
								begin
									begin
										_cond  := _cond.contents + ( _mid.contents- _ckeys.contents );
										_have  := 1;
										
									end;
									
								end
								;
							end;
							
							done;
							if _have.contents= 0  then
							begin
								begin
									cs  := 0;
									_cont  := 0;
									
								end;
								
							end
							;
						end;
						
					end;
					
				end
				;if _cont.contents= 1  then
				begin
					begin
						cs  := _erract_cond_targs.(_cond.contents);
						if _erract_cond_actions.(_cond.contents)!= 0  then
						begin
							begin
								_acts  := _erract_cond_actions.(_cond.contents);
								_nacts  := _erract_actions.( _acts.contents );
								_acts  := _acts.contents + 1;
								while _nacts.contents> 0  do
								begin
									if _erract_actions.( _acts.contents ) = 0  then
									begin
										begin
											print_string( "err_start\n" );
											
										end;
										
									end
									else if _erract_actions.( _acts.contents ) = 1  then
									begin
										begin
											print_string( "err_all\n" );
											
										end;
										
									end
									else if _erract_actions.( _acts.contents ) = 2  then
									begin
										begin
											print_string( "err_middle\n" );
											
										end;
										
									end
									else if _erract_actions.( _acts.contents ) = 3  then
									begin
										begin
											print_string( "err_out\n" );
											
										end;
										
									end
									;
									_nacts  := _nacts.contents - 1;
									_acts  := _acts.contents + 1;
									
								end;
								
								done;
								
							end;
							
						end
						;if cs.contents= 0  then
						begin
							_cont  := 0;
							
						end
						;if _cont.contents= 1  then
						begin
							p  := p.contents + 1;
							
						end
						;
					end;
					
				end
				;
			end;
			
		end
		;
	end;
	
	done;
	
end;
if !cs >= erract_first_final then
print_string "ACCEPT\n"
else
print_string "FAIL\n"
;;

let () =
exec "";
exec "h";
exec "x";
exec "he";
exec "hx";
exec "hel";
exec "hex";
exec "hell";
exec "helx";
exec "hello";
exec "hellx";
exec "hello\n";
exec "hellox";
()
;;

