import crack.io cout;
import crack.lang Buffer;








const array[int16 ] _erract_key_offsets = [ 0, 0, 1, 2, 3, 4, 5, 6, 0 ,  ];
const array[byte ] _erract_trans_keys = [ 104, 101, 108, 108, 111, 10, 0,  ];
const array[int16 ] _erract_single_lengths = [ 0, 1, 1, 1, 1, 1, 1, 0, 0 ,  ];
const array[int16 ] _erract_range_lengths = [ 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  ];
const array[int16 ] _erract_index_offsets = [ 0, 0, 2, 4, 6, 8, 10, 12, 0 ,  ];
const array[int16 ] _erract_trans_cond_spaces = [ -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0 ,  ];
const array[int16 ] _erract_trans_offsets = [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0 ,  ];
const array[int16 ] _erract_trans_lengths = [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0 ,  ];
const array[int16 ] _erract_cond_keys = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  ];
const array[int16 ] _erract_cond_targs = [ 2, 0, 3, 0, 4, 0, 5, 0, 6, 0, 7, 0, 0, 0 ,  ];
const array[int16 ] _erract_cond_actions = [ 0, 2, 0, 4, 0, 4, 0, 4, 0, 4, 0, 6, 0, 0 ,  ];
const array[int16 ] _erract_eof_actions = [ 0, 1, 3, 3, 3, 3, 5, 0, 0 ,  ];
const array[int16 ] _erract_nfa_targs = [ 0, 0 ,  ];
const array[int16 ] _erract_nfa_offsets = [ 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  ];
const array[int16 ] _erract_nfa_push_actions = [ 0, 0 ,  ];
const array[int16 ] _erract_nfa_pop_trans = [ 0, 0 ,  ];
const int  erract_start  = 1;
const int  erract_first_final  = 7;
const int  erract_error  = 0;
const int  erract_en_main  = 1;
void m( String s )
{
	byteptr data = s.buffer;
	int p = 0;
	int pe = s.size;
	int cs;
	String buffer;
	int eof = pe;
	
	if ( 1 ) {
		cs = int ( erract_start );
		
	}
	if ( 1 ) {
		int _klen;
		int _keys = 0;
		int _ckeys = 0;
		int _cpc;
		uint32 _trans;
		uint32 _cond = 0;
		uint32 _have = 0;
		uint32 _cont = 1;
		while ( _cont == 1  )
		{
			if ( cs == 0  )
			_cont = 0;
			
			_have = 0;
			if ( p == pe  )
			{
				if ( p == eof  )
				{
					if ( _have == 0  )
					{
						if ( _erract_eof_actions[cs] == 1  ) {
							if ( 1 ) {
								cout.format( "err_start\n" );
								
							}
							if ( 1 ) {
								cout.format( "eof_start\n" );
								
							}
							if ( 1 ) {
								cout.format( "err_all\n" );
								
							}
							if ( 1 ) {
								cout.format( "eof_all\n" );
								
							}
							
						}
						else if ( _erract_eof_actions[cs] == 3  ) {
							if ( 1 ) {
								cout.format( "err_all\n" );
								
							}
							if ( 1 ) {
								cout.format( "err_middle\n" );
								
							}
							if ( 1 ) {
								cout.format( "eof_all\n" );
								
							}
							if ( 1 ) {
								cout.format( "eof_middle\n" );
								
							}
							
						}
						else if ( _erract_eof_actions[cs] == 5  ) {
							if ( 1 ) {
								cout.format( "err_all\n" );
								
							}
							if ( 1 ) {
								cout.format( "err_out\n" );
								
							}
							if ( 1 ) {
								cout.format( "eof_all\n" );
								
							}
							if ( 1 ) {
								cout.format( "eof_out\n" );
								
							}
							
						}
						;
						
					}
					
					
				}
				
				if ( _have == 0  )
				_cont = 0;
				
				
			}
			
			if ( _cont == 1  )
			{
				if ( _have == 0  )
				{
					_keys = _erract_key_offsets[cs];
					_trans = uint32  ( _erract_index_offsets[cs] );
					_have = 0;
					_klen = int ( _erract_single_lengths[cs] );
					if ( _klen > 0  )
					{
						int _lower = 0;
						int _mid = 0;
						int _upper = 0;
						_lower = _keys;
						_upper = _keys + _klen - 1;
						while ( _upper >= _lower && _have == 0  )
						{
							_mid = _lower + ((_upper-_lower)>> 1);
							if ( (data[p ])< _erract_trans_keys[_mid ] )
							_upper = _mid - 1;
							
							else if ( (data[p ])> _erract_trans_keys[_mid ] )
							_lower = _mid + 1;
							
							else
							{
								_trans += uint32  ( (_mid - _keys) );
								_have = 1;
								
							}
							
							
						}
						
						if ( _have == 0  )
						{
							_keys += _klen;
							_trans += uint32  ( _klen );
							
						}
						
						
					}
					
					if ( _have == 0  )
					{
						_klen = int ( _erract_range_lengths[cs] );
						if ( _klen > 0  )
						{
							int _lower = 0;
							int _mid = 0;
							int _upper = 0;
							_lower = _keys;
							_upper = _keys + (_klen<<1)- 2;
							while ( _have == 0 && _lower <= _upper  )
							{
								_mid = _lower + (((_upper-_lower)>> 1)& ~1);
								if ( (data[p ])< _erract_trans_keys[_mid ] )
								_upper = _mid - 2;
								
								else if ( (data[p ])> _erract_trans_keys[_mid + 1 ] )
								_lower = _mid + 2;
								
								else
								{
									_trans += uint32  ( ((_mid - _keys)>>1) );
									_have = 1;
									
								}
								
								
							}
							
							if ( _have == 0  )
							_trans += uint32  ( _klen );
							
							
						}
						
						
					}
					
					_ckeys = _erract_trans_offsets[_trans];
					_klen = int ( _erract_trans_lengths[_trans] );
					_cond = uint32  ( _erract_trans_offsets[_trans] );
					_have = 0;
					_cpc = 0;
					if ( 1 ) {
						int _lower = 0;
						int _mid = 0;
						int _upper = 0;
						_lower = _ckeys;
						_upper = _ckeys + _klen - 1;
						while ( _have == 0 && _lower <= _upper  )
						{
							_mid = _lower + ((_upper-_lower)>> 1);
							if ( _cpc < int ( _erract_cond_keys[_mid ] ) )
							_upper = _mid - 1;
							
							else if ( _cpc > int ( _erract_cond_keys[_mid ] ) )
							_lower = _mid + 1;
							
							else
							{
								_cond += uint32  ( (_mid - _ckeys) );
								_have = 1;
								
							}
							
							
						}
						
						if ( _have == 0  )
						{
							cs = 0;
							_cont = 0;
							
						}
						
						
					}
					
				}
				
				if ( _cont == 1  )
				{
					cs = int ( _erract_cond_targs[_cond] );
					if ( _erract_cond_actions[_cond] == 2  ) {
						if ( 1 ) {
							cout.format( "err_start\n" );
							
						}
						if ( 1 ) {
							cout.format( "err_all\n" );
							
						}
						
					}
					else if ( _erract_cond_actions[_cond] == 4  ) {
						if ( 1 ) {
							cout.format( "err_all\n" );
							
						}
						if ( 1 ) {
							cout.format( "err_middle\n" );
							
						}
						
					}
					else if ( _erract_cond_actions[_cond] == 6  ) {
						if ( 1 ) {
							cout.format( "err_all\n" );
							
						}
						if ( 1 ) {
							cout.format( "err_out\n" );
							
						}
						
					}
					;
					if ( cs == 0  )
					_cont = 0;
					
					if ( _cont == 1  )
					p += 1;
					
					
				}
				
				
			}
			
			
		}
		
		
	}
	if ( cs >= erract_first_final ) {
		cout `ACCEPT\n`;
	}
	else {
		cout `FAIL\n`;
	}
}

void main()
{
	m( "" );
	m( "h" );
	m( "x" );
	m( "he" );
	m( "hx" );
	m( "hel" );
	m( "hex" );
	m( "hell" );
	m( "helx" );
	m( "hello" );
	m( "hellx" );
	m( "hello\n" );
	m( "hellox" );
}

main();
