#include <stdio.h>
#include <string.h>



static const char  _foo_trans_keys [] = { 1, 0, 3, 3, 2, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0 ,  };
static const char  _foo_char_class [] = { 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 3, 0 ,  };
static const char  _foo_index_offsets [] = { 0, 0, 1, 2, 3, 4, 5, 0 ,  };
static const char  _foo_indicies [] = { 1, 2, 3, 4, 5, 0 ,  };
static const char  _foo_index_defaults [] = { 0, 0, 0, 0, 0, 0, 0, 0 ,  };
static const char  _foo_trans_cond_spaces [] = { -1, -1, -1, -1, -1, -1, 0 ,  };
static const char  _foo_cond_targs [] = { 0, 2, 3, 4, 5, 6, 0 ,  };
static const char  _foo_cond_actions [] = { 2, 3, 3, 3, 3, 3, 0 ,  };
static const char  _foo_to_state_actions [] = { 0, 1, 1, 1, 1, 1, 1, 0 ,  };
static const char  _foo_eof_actions [] = { 0, 2, 2, 2, 2, 2, 0, 0 ,  };
static const char  _foo_nfa_targs [] = { 0, 0 ,  };
static const char  _foo_nfa_offsets [] = { 0, 0, 0, 0, 0, 0, 0, 0 ,  };
static const char  _foo_nfa_push_actions [] = { 0, 0 ,  };
static const char  _foo_nfa_pop_trans [] = { 0, 0 ,  };
static const int  foo_start  = 1;
static const int  foo_first_final  = 6;
static const int  foo_error  = 0;
static const int  foo_en_main  = 1;
int main()
{
	int cs;
	char *p = "hello", *pe = p + strlen(p);
	char *eof = pe;
	
	{
		cs = ( int ) foo_start;
	}
	
	{
		unsigned int _trans = 0;
		unsigned int _have = 0;
		unsigned int _cont = 1;
		const char  *_keys;
		const char  *_inds;
		while ( _cont == 1  )
		{
		
			if ( cs == 0  )
			_cont = 0;
			
			_have = 0;
			if ( p == pe  )
			{
				if ( p == eof  )
				{
					if ( _have == 0  )
					{
						switch ( _foo_eof_actions[cs] ) {
							case 2 :
							{
								printf("err: %c\n", *p); 
							}
							
							break;
							
						}
					}
					
				}
				
				
				if ( _have == 0  )
				_cont = 0;
				
			}
			
			if ( _cont == 1  )
			{
				if ( _have == 0  )
				{
					_keys = _foo_trans_keys + (cs<<1);
					_inds = _foo_indicies + _foo_index_offsets[cs];
					if ( ((*( p  ))
					)<= 104 && ((*( p  ))
					)>= 88  )
					{
						int _ic = ( int ) _foo_char_class[( int ) ((*( p  ))
						)- 88];
						if ( _ic <= ( int ) (*( _keys+1  ))
						&& _ic >= ( int ) (*( _keys  ))
						)
						_trans = ( unsigned int  ) (*( _inds + ( int ) (_ic - ( int ) (*( _keys  ))
						) ))
						;
						
						else
						_trans = ( unsigned int  ) _foo_index_defaults[cs];
						
					}
					
					else
					{
						_trans = ( unsigned int  ) _foo_index_defaults[cs];
					}
					
					
				}
				
				if ( _cont == 1  )
				{
					cs = ( int ) _foo_cond_targs[_trans];
					switch ( _foo_cond_actions[_trans] ) {
						case 3 :
						{
							printf("char: %c\n", *p); 
						}
						
						break;
						case 2 :
						{
							printf("err: %c\n", *p); 
						}
						
						break;
						
					}
					switch ( _foo_to_state_actions[cs] ) {
						case 1 :
						{
							printf("to state: %c\n", *p); 
						}
						
						break;
						
					}
					if ( cs == 0  )
					_cont = 0;
					
					if ( _cont == 1  )
					p += 1;
					
				}
			}
			
		}
		
	}
	printf( "rest: %s\n", p );
	
	return 0;
}

