#include <string.h>
#include <stdio.h>








static const char  _erract_key_offsets [] = { 0, 0, 1, 2, 3, 4, 5, 6, 0 ,  };
static const char  _erract_trans_keys [] = { 104, 101, 108, 108, 111, 10, 0 ,  };
static const char  _erract_single_lengths [] = { 0, 1, 1, 1, 1, 1, 1, 0, 0 ,  };
static const char  _erract_range_lengths [] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  };
static const char  _erract_index_offsets [] = { 0, 0, 2, 4, 6, 8, 10, 12, 0 ,  };
static const char  _erract_trans_cond_spaces [] = { -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0 ,  };
static const char  _erract_trans_offsets [] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0 ,  };
static const char  _erract_trans_lengths [] = { 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0 ,  };
static const char  _erract_cond_keys [] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  };
static const char  _erract_cond_targs [] = { 2, 0, 3, 0, 4, 0, 5, 0, 6, 0, 7, 0, 0, 0 ,  };
static const char  _erract_cond_actions [] = { 0, 2, 0, 4, 0, 4, 0, 4, 0, 4, 0, 6, 0, 0 ,  };
static const char  _erract_eof_actions [] = { 0, 1, 3, 3, 3, 3, 5, 0, 0 ,  };
static const char  _erract_nfa_targs [] = { 0, 0 ,  };
static const char  _erract_nfa_offsets [] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  };
static const char  _erract_nfa_push_actions [] = { 0, 0 ,  };
static const char  _erract_nfa_pop_trans [] = { 0, 0 ,  };
static const int  erract_start  = 1;
static const int  erract_first_final  = 7;
static const int  erract_error  = 0;
static const int  erract_en_main  = 1;
int cs;
int blen;
char buffer[1024];

void init()
{

	{
		cs = ( int ) erract_start;
	}
}

void exec( char *data, int len )
{
	char *p = data;
	char *pe = data + len;
	char *eof = pe;
	
	{
		int _klen;
		const char  *_keys;
		const char  *_ckeys;
		int _cpc;
		unsigned int _trans;
		unsigned int _cond = 0;
		unsigned int _have = 0;
		unsigned int _cont = 1;
		while ( _cont == 1  )
		{
		
			if ( cs == 0  )
			_cont = 0;
			
			_have = 0;
			if ( p == pe  )
			{
				if ( p == eof  )
				{
					if ( _have == 0  )
					{
						switch ( _erract_eof_actions[cs] ) {
							case 1 :
							{
								printf( "%s", "err_start\n" );
								
							}
							{
								printf( "%s", "eof_start\n" );
								
							}
							{
								printf( "%s", "err_all\n" );
								
							}
							{
								printf( "%s", "eof_all\n" );
								
							}
							
							break;
							case 3 :
							{
								printf( "%s", "err_all\n" );
								
							}
							{
								printf( "%s", "err_middle\n" );
								
							}
							{
								printf( "%s", "eof_all\n" );
								
							}
							{
								printf( "%s", "eof_middle\n" );
								
							}
							
							break;
							case 5 :
							{
								printf( "%s", "err_all\n" );
								
							}
							{
								printf( "%s", "err_out\n" );
								
							}
							{
								printf( "%s", "eof_all\n" );
								
							}
							{
								printf( "%s", "eof_out\n" );
								
							}
							
							break;
							
						}
					}
					
				}
				
				
				if ( _have == 0  )
				_cont = 0;
				
			}
			
			if ( _cont == 1  )
			{
				if ( _have == 0  )
				{
					_keys = _erract_trans_keys + _erract_key_offsets[cs];
					_trans = ( unsigned int  ) _erract_index_offsets[cs];
					_have = 0;
					_klen = ( int ) _erract_single_lengths[cs];
					if ( _klen > 0  )
					{
						const char  *_lower;
						const char  *_mid;
						const char  *_upper;
						_lower = _keys;
						_upper = _keys + _klen - 1;
						while ( _upper >= _lower && _have == 0  )
						{
							_mid = _lower + ((_upper-_lower)>> 1);
							if ( ((*( p  ))
							)< (*( _mid  ))
							)
							_upper = _mid - 1;
							
							else if ( ((*( p  ))
							)> (*( _mid  ))
							)
							_lower = _mid + 1;
							
							else
							{
								_trans += ( unsigned int  ) (_mid - _keys);
								_have = 1;
							}
							
						}
						
						if ( _have == 0  )
						{
							_keys += _klen;
							_trans += ( unsigned int  ) _klen;
						}
						
					}
					
					
					if ( _have == 0  )
					{
						_klen = ( int ) _erract_range_lengths[cs];
						if ( _klen > 0  )
						{
							const char  *_lower;
							const char  *_mid;
							const char  *_upper;
							_lower = _keys;
							_upper = _keys + (_klen<<1)- 2;
							while ( _have == 0 && _lower <= _upper  )
							{
								_mid = _lower + (((_upper-_lower)>> 1)& ~1);
								if ( ((*( p  ))
								)< (*( _mid  ))
								)
								_upper = _mid - 2;
								
								else if ( ((*( p  ))
								)> (*( _mid + 1  ))
								)
								_lower = _mid + 2;
								
								else
								{
									_trans += ( unsigned int  ) ((_mid - _keys)>>1);
									_have = 1;
								}
								
							}
							
							if ( _have == 0  )
							_trans += ( unsigned int  ) _klen;
							
						}
						
					}
					
					
					_ckeys = _erract_cond_keys + _erract_trans_offsets[_trans];
					_klen = ( int ) _erract_trans_lengths[_trans];
					_cond = ( unsigned int  ) _erract_trans_offsets[_trans];
					_have = 0;
					_cpc = 0;
					{
						const char  *_lower;
						const char  *_mid;
						const char  *_upper;
						_lower = _ckeys;
						_upper = _ckeys + _klen - 1;
						while ( _have == 0 && _lower <= _upper  )
						{
							_mid = _lower + ((_upper-_lower)>> 1);
							if ( _cpc < ( int ) (*( _mid  ))
							)
							_upper = _mid - 1;
							
							else if ( _cpc > ( int ) (*( _mid  ))
							)
							_lower = _mid + 1;
							
							else
							{
								_cond += ( unsigned int  ) (_mid - _ckeys);
								_have = 1;
							}
							
						}
						
						if ( _have == 0  )
						{
							cs = 0;
							_cont = 0;
						}
						
					}
				}
				
				if ( _cont == 1  )
				{
					cs = ( int ) _erract_cond_targs[_cond];
					switch ( _erract_cond_actions[_cond] ) {
						case 2 :
						{
							printf( "%s", "err_start\n" );
							
						}
						{
							printf( "%s", "err_all\n" );
							
						}
						
						break;
						case 4 :
						{
							printf( "%s", "err_all\n" );
							
						}
						{
							printf( "%s", "err_middle\n" );
							
						}
						
						break;
						case 6 :
						{
							printf( "%s", "err_all\n" );
							
						}
						{
							printf( "%s", "err_out\n" );
							
						}
						
						break;
						
					}
					if ( cs == 0  )
					_cont = 0;
					
					if ( _cont == 1  )
					p += 1;
					
				}
			}
			
		}
		
	}
}

void finish( )
{
	if ( cs >= erract_first_final )
	printf( "ACCEPT\n" );
	else
	printf( "FAIL\n" );
}

char *inp[] = {
	"",
	"h",
	"x",
	"he",
	"hx",
	"hel",
	"hex",
	"hell",
	"helx",
	"hello",
	"hellx",
	"hello\n",
	"hellox",
};

int inplen = 13;

int main( )
{
	int i;
	for ( i = 0; i < inplen; i++ ) {
		init();
		exec( inp[i], strlen(inp[i]) );
		finish();
	}
	return 0;
}

