class erract2_java
{







	private static byte  _erract_actions [] = { 0, 2, 0, 1, 2, 1, 2, 2, 1, 3, 4, 0, 4, 1, 5, 4, 1, 2, 5, 6, 4, 1, 3, 5, 7, 0 ,  };
	private static byte  _erract_key_offsets [] = { 0, 0, 1, 2, 3, 4, 5, 6, 0 ,  };
	private static char  _erract_trans_keys [] = { 104, 101, 108, 108, 111, 10, 0,  };
	private static byte  _erract_single_lengths [] = { 0, 1, 1, 1, 1, 1, 1, 0, 0 ,  };
	private static byte  _erract_range_lengths [] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  };
	private static byte  _erract_index_offsets [] = { 0, 0, 2, 4, 6, 8, 10, 12, 0 ,  };
	private static byte  _erract_trans_cond_spaces [] = { -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0 ,  };
	private static byte  _erract_trans_offsets [] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0 ,  };
	private static byte  _erract_trans_lengths [] = { 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0 ,  };
	private static byte  _erract_cond_keys [] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  };
	private static byte  _erract_cond_targs [] = { 2, 0, 3, 0, 4, 0, 5, 0, 6, 0, 7, 0, 0, 0 ,  };
	private static byte  _erract_cond_actions [] = { 0, 1, 0, 4, 0, 4, 0, 4, 0, 4, 0, 7, 0, 0 ,  };
	private static byte  _erract_eof_actions [] = { 0, 10, 15, 15, 15, 15, 20, 0, 0 ,  };
	private static byte  _erract_nfa_targs [] = { 0, 0 ,  };
	private static byte  _erract_nfa_offsets [] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  };
	private static byte  _erract_nfa_push_actions [] = { 0, 0 ,  };
	private static byte  _erract_nfa_pop_trans [] = { 0, 0 ,  };
	private static int  erract_start  = 1;
	private static int  erract_first_final  = 7;
	private static int  erract_error  = 0;
	private static int  erract_en_main  = 1;
	int cs;
	
	void init()
	{
		{
			cs = (int)erract_start;
			
		}
	}
	
	void exec( char data[], int len )
	{
		char buffer [] = new char[1024];
		int blen = 0;
		int p = 0;
		int pe = len;
		
		int eof = len;
		String _s;
		{
			int _klen;
			int _trans = 0;
			int _cond = 0;
			int _have = 0;
			int _cont = 1;
			int _acts;
			int _nacts;
			int _keys;
			int _ckeys;
			int _cpc;
			while ( _cont == 1  )
			{
				if ( cs == 0  )
				_cont = 0;
				
				_have = 0;
				if ( p == pe  )
				{
					if ( p == eof  )
					{
						if ( _have == 0  )
						{
							int __acts;
							int __nacts;
							__acts = _erract_eof_actions[cs] ;
							__nacts = (int )_erract_actions[__acts ];
							__acts += 1;
							while ( __nacts > 0  )
							{
								switch ( _erract_actions[__acts ] ) {
									case 0 :
									{
										System.out.print( "err_start\n" );
										
									}
									
									break;
									case 1 :
									{
										System.out.print( "err_all\n" );
										
									}
									
									break;
									case 2 :
									{
										System.out.print( "err_middle\n" );
										
									}
									
									break;
									case 3 :
									{
										System.out.print( "err_out\n" );
										
									}
									
									break;
									case 4 :
									{
										System.out.print( "eof_start\n" );
										
									}
									
									break;
									case 5 :
									{
										System.out.print( "eof_all\n" );
										
									}
									
									break;
									case 6 :
									{
										System.out.print( "eof_middle\n" );
										
									}
									
									break;
									case 7 :
									{
										System.out.print( "eof_out\n" );
										
									}
									
									break;
									
								}
								__nacts -= 1;
								__acts += 1;
								
							}
							
							
						}
						
						
					}
					
					if ( _have == 0  )
					_cont = 0;
					
					
				}
				
				if ( _cont == 1  )
				{
					if ( _have == 0  )
					{
						_keys = _erract_key_offsets[cs] ;
						_trans = (int )_erract_index_offsets[cs];
						_have = 0;
						_klen = (int)_erract_single_lengths[cs];
						if ( _klen > 0  )
						{
							int _lower;
							int _mid;
							int _upper;
							_lower = _keys;
							_upper = _keys + _klen - 1;
							while ( _upper >= _lower && _have == 0  )
							{
								_mid = _lower + ((_upper-_lower) >> 1);
								if ( ( data[p ]) < _erract_trans_keys[_mid ] )
								_upper = _mid - 1;
								
								else if ( ( data[p ]) > _erract_trans_keys[_mid ] )
								_lower = _mid + 1;
								
								else
								{
									_trans += (int )(_mid - _keys);
									_have = 1;
									
								}
								
								
							}
							
							if ( _have == 0  )
							{
								_keys += _klen;
								_trans += (int )_klen;
								
							}
							
							
						}
						
						if ( _have == 0  )
						{
							_klen = (int)_erract_range_lengths[cs];
							if ( _klen > 0  )
							{
								int _lower;
								int _mid;
								int _upper;
								_lower = _keys;
								_upper = _keys + (_klen<<1) - 2;
								while ( _have == 0 && _lower <= _upper  )
								{
									_mid = _lower + (((_upper-_lower) >> 1) & ~1);
									if ( ( data[p ]) < _erract_trans_keys[_mid ] )
									_upper = _mid - 2;
									
									else if ( ( data[p ]) > _erract_trans_keys[_mid + 1 ] )
									_lower = _mid + 2;
									
									else
									{
										_trans += (int )((_mid - _keys)>>1);
										_have = 1;
										
									}
									
									
								}
								
								if ( _have == 0  )
								_trans += (int )_klen;
								
								
							}
							
							
						}
						
						_ckeys = _erract_trans_offsets[_trans] ;
						_klen = (int)_erract_trans_lengths[_trans];
						_cond = (int )_erract_trans_offsets[_trans];
						_have = 0;
						_cpc = 0;
						{
							int _lower;
							int _mid;
							int _upper;
							_lower = _ckeys;
							_upper = _ckeys + _klen - 1;
							while ( _have == 0 && _lower <= _upper  )
							{
								_mid = _lower + ((_upper-_lower) >> 1);
								if ( _cpc < (int)_erract_cond_keys[_mid ] )
								_upper = _mid - 1;
								
								else if ( _cpc > (int)_erract_cond_keys[_mid ] )
								_lower = _mid + 1;
								
								else
								{
									_cond += (int )(_mid - _ckeys);
									_have = 1;
									
								}
								
								
							}
							
							if ( _have == 0  )
							{
								cs = 0;
								_cont = 0;
								
							}
							
							
						}
						
					}
					
					if ( _cont == 1  )
					{
						cs = (int)_erract_cond_targs[_cond];
						if ( _erract_cond_actions[_cond] != 0  )
						{
							_acts = _erract_cond_actions[_cond] ;
							_nacts = (int )_erract_actions[_acts ];
							_acts += 1;
							while ( _nacts > 0  )
							{
								switch ( _erract_actions[_acts ] ) {
									case 0 :
									{
										System.out.print( "err_start\n" );
										
									}
									
									break;
									case 1 :
									{
										System.out.print( "err_all\n" );
										
									}
									
									break;
									case 2 :
									{
										System.out.print( "err_middle\n" );
										
									}
									
									break;
									case 3 :
									{
										System.out.print( "err_out\n" );
										
									}
									
									break;
									
								}
								_nacts -= 1;
								_acts += 1;
								
							}
							
							
						}
						
						if ( cs == 0  )
						_cont = 0;
						
						if ( _cont == 1  )
						p += 1;
						
						
					}
					
					
				}
				
				
			}
			
			
		}
	}
	
	void finish( )
	{
		if ( cs >= erract_first_final )
		System.out.println( "ACCEPT" );
		else
		System.out.println( "FAIL" );
	}
	
	static final String inp[] = {
		"",
		"h",
		"x",
		"he",
		"hx",
		"hel",
		"hex",
		"hell",
		"helx",
		"hello",
		"hellx",
		"hello\n",
		"hellox",
	};
	
	static final int inplen = 13;
	
	public static void main (String[] args)
	{
		erract2_java machine = new erract2_java();
		for ( int i = 0; i < inplen; i++ ) {
			machine.init();
			machine.exec( inp[i].toCharArray(), inp[i].length() );
			machine.finish();
		}
	}
}
