using System;
// Disables lots of warnings that appear in the test suite
#pragma warning disable 0168, 0169, 0219, 0162, 0414
namespace Test {
	class Test
	{
		char comm;
		int top;
		int [] stack = new int [32];
		
		
		
		
		static readonly sbyte  []_gotocallret_key_offsets = { 0, 0, 1, 2, 3, 4, 8, 10, 14, 14, 18, 0,  };
		static readonly char  []_gotocallret_trans_keys = { '\u0020', '\u000a', '\u000a', '\u000a', '\u0041', '\u005a', '\u0061', '\u007a', '\u0030', '\u0039', '\u0030', '\u0039', '\u0061', '\u007a', '\u0041', '\u005a', '\u0061', '\u007a', '\u0030', '\u0039', '\u0000',  };
		static readonly sbyte  []_gotocallret_single_lengths = { 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,  };
		static readonly sbyte  []_gotocallret_range_lengths = { 0, 0, 0, 0, 0, 2, 1, 2, 0, 2, 1, 0,  };
		static readonly sbyte  []_gotocallret_index_offsets = { 0, 0, 2, 4, 6, 8, 11, 13, 16, 17, 20, 0,  };
		static readonly sbyte  []_gotocallret_trans_cond_spaces = { -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0,  };
		static readonly sbyte  []_gotocallret_trans_offsets = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 0,  };
		static readonly sbyte  []_gotocallret_trans_lengths = { 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,  };
		static readonly sbyte  []_gotocallret_cond_keys = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  };
		static readonly sbyte  []_gotocallret_cond_targs = { 2, 0, 7, 0, 8, 4, 8, 4, 9, 9, 0, 10, 0, 1, 1, 0, 0, 9, 9, 0, 10, 0, 0,  };
		static readonly sbyte  []_gotocallret_cond_actions = { 2, 1, 3, 1, 6, 5, 7, 0, 0, 0, 8, 0, 8, 9, 9, 1, 0, 0, 0, 8, 0, 8, 0,  };
		static readonly sbyte  []_gotocallret_eof_actions = { 0, 1, 1, 4, 4, 8, 8, 0, 4, 0, 0, 0,  };
		static readonly sbyte  []_gotocallret_nfa_targs = { 0, 0,  };
		static readonly sbyte  []_gotocallret_nfa_offsets = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  };
		static readonly sbyte  []_gotocallret_nfa_push_actions = { 0, 0,  };
		static readonly sbyte  []_gotocallret_nfa_pop_trans = { 0, 0,  };
		static readonly int  gotocallret_start  = 7;
		static readonly int  gotocallret_first_final  = 7;
		static readonly int  gotocallret_error  = 0;
		static readonly int  gotocallret_en_garble_line  = 3;
		static readonly int  gotocallret_en_alp_comm  = 5;
		static readonly int  gotocallret_en_dig_comm  = 6;
		static readonly int  gotocallret_en_main  = 7;
		int cs;
		
		void init()
		{
		
			{
				cs = (int)gotocallret_start;
				top = 0;
			}
		}
		
		void exec( char[] data, int len )
		{
			int p = 0;
			int pe = len;
			int eof = len;
			string _s;
			char [] buffer = new char [1024];
			int blen = 0;
			
			{
				int _klen;
				int _keys;
				int _ckeys;
				int _cpc;
				uint _trans = 0;
				uint _cond = 0;
				if ( p == pe  )
				goto _test_eof;
				
				if ( cs == 0 )
				goto _out;
				
				_resume :
				_keys = _gotocallret_key_offsets[cs] ;
				_trans = (uint )_gotocallret_index_offsets[cs];
				_klen = (int)_gotocallret_single_lengths[cs];
				if ( _klen > 0 )
				{
					int _lower;
					int _mid;
					int _upper;
					_lower = _keys;
					_upper = _keys + _klen - 1;
					while ( true  )
					{
						if ( _upper < _lower  )
						break;
						
						
						_mid = _lower + ((_upper-_lower) >> 1);
						if ( ( data[p ]) < _gotocallret_trans_keys[_mid ] )
						_upper = _mid - 1;
						
						else if ( ( data[p ]) > _gotocallret_trans_keys[_mid ] )
						_lower = _mid + 1;
						
						else
						{
							_trans += (uint )(_mid - _keys);
							goto _match;
						}
						
					}
					
					_keys += _klen;
					_trans += (uint )_klen;
				}
				
				
				_klen = (int)_gotocallret_range_lengths[cs];
				if ( _klen > 0 )
				{
					int _lower;
					int _mid;
					int _upper;
					_lower = _keys;
					_upper = _keys + (_klen<<1) - 2;
					while ( true  )
					{
						if ( _upper < _lower  )
						break;
						
						
						_mid = _lower + (((_upper-_lower) >> 1) & ~1);
						if ( ( data[p ]) < _gotocallret_trans_keys[_mid ] )
						_upper = _mid - 2;
						
						else if ( ( data[p ]) > _gotocallret_trans_keys[_mid + 1] )
						_lower = _mid + 2;
						
						else
						{
							_trans += (uint )((_mid - _keys)>>1);
							goto _match;
						}
						
					}
					
					_trans += (uint )_klen;
				}
				
				
				
				_match :
				_ckeys = _gotocallret_trans_offsets[_trans] ;
				_klen = (int)_gotocallret_trans_lengths[_trans];
				_cond = (uint )_gotocallret_trans_offsets[_trans];
				_cpc = 0;
				{
					int _lower;
					int _mid;
					int _upper;
					_lower = _ckeys;
					_upper = _ckeys + _klen - 1;
					while ( true  )
					{
						if ( _upper < _lower  )
						break;
						
						
						_mid = _lower + ((_upper-_lower) >> 1);
						if ( _cpc < (int)_gotocallret_cond_keys[_mid ] )
						_upper = _mid - 1;
						
						else if ( _cpc > (int)_gotocallret_cond_keys[_mid ] )
						_lower = _mid + 1;
						
						else
						{
							_cond += (uint )(_mid - _ckeys);
							goto _match_cond;
						}
						
					}
					
					cs = 0;
					goto _again;
				}
				
				_match_cond :
				cs = (int)_gotocallret_cond_targs[_cond];
				if ( _gotocallret_cond_actions[_cond] == 0 )
				goto _again;
				
				
				switch ( _gotocallret_cond_actions[_cond]  ) {
					case 5:
					{Console.Write( "error: garbling line\n" );}
					
					break;
					case 7:
					{{cs = 7;
						}}
					
					break;
					case 8:
					{{p = p - 1;
						}{top-= 1;
							cs = stack[top];
						}}
					
					break;
					case 9:
					{comm = (( data[p ]));
					}
					
					break;
					case 3:
					{Console.Write( "correct command\n" );}
					
					break;
					case 1:
					{{p = p - 1;
						}{cs = 3;
						}}
					
					break;
					case 6:
					{Console.Write( "error: garbling line\n" );}
					{{cs = 7;
						}}
					
					break;
					case 2:
					{if ( comm >= 97 )
						{
							{stack[top] = cs;
								top += 1;
								cs = 5;
							}} 
						else {
							{stack[top] = cs;
								top += 1;
								cs = 6;
							}}
					}
					{Console.Write( "prints\n" );}
					
					break;
					
				}
				
				_again :
				if ( cs == 0 )
				goto _out;
				
				p += 1;
				if ( p != pe  )
				goto _resume;
				
				
				_test_eof :
				{}
				if ( p == eof  )
				{
					switch ( _gotocallret_eof_actions[cs]  ) {
						case 4:
						{Console.Write( "error: failed to recover\n" );}
						
						break;
						case 8:
						{{p = p - 1;
							}{top-= 1;
								cs = stack[top];
							}}
						
						break;
						case 1:
						{{p = p - 1;
							}{cs = 3;
							}}
						
						break;
						
					}
				}
				
				
				
				_out :
				{}
				
			}
		}
		
		void finish( )
		{
			if ( cs >= gotocallret_first_final )
			Console.WriteLine( "ACCEPT" );
			else
			Console.WriteLine( "FAIL" );
		}
		
		static readonly string[] inp = {
			"lkajsdf\n",
			"2134\n",
			"(\n",
			"\n",
			"*234234()0909 092 -234aslkf09`1 11\n",
			"1\n",
			"909\n",
			"1 a\n",
			"11 1\n",
			"a 1\n",
			"aa a\n",
			"1 1\n",
			"1 123456\n",
			"a a\n",
			"a abcdef\n",
			"h",
			"a aa1",
		};
		
		
		static readonly int inplen = 17;
		
		public static void Main (string[] args)
		{
			Test machine = new Test();
			for ( int i = 0; i < inplen; i++ ) {
				machine.init();
				machine.exec( inp[i].ToCharArray(), inp[i].Length );
				machine.finish();
			}
		}
	}
}
