(*
* @LANG: ocaml
* @GENERATED: true
*)

let comm = ref 0
let top = ref 0
let stack = Array.make 32 0






let _gotocallret_actions : int array = [|
0; 1; 0; 1; 1; 1; 2; 1; 3; 1; 5; 1; 7; 1; 8; 2; 0; 1; 2; 4; 6; 0 ; 
|]
let _gotocallret_key_offsets : int array = [|
0; 0; 1; 2; 3; 4; 8; 10; 14; 14; 18; 0 ; 
|]
let _gotocallret_trans_keys : int array = [|
32; 10; 10; 10; 65; 90; 97; 122; 48; 57; 48; 57; 97; 122; 65; 90; 97; 122; 48; 57; 0 ; 
|]
let _gotocallret_single_lengths : int array = [|
0; 1; 1; 1; 1; 0; 0; 0; 0; 0; 0; 0 ; 
|]
let _gotocallret_range_lengths : int array = [|
0; 0; 0; 0; 0; 2; 1; 2; 0; 2; 1; 0 ; 
|]
let _gotocallret_index_offsets : int array = [|
0; 0; 2; 4; 6; 8; 11; 13; 16; 17; 20; 0 ; 
|]
let _gotocallret_trans_cond_spaces : int array = [|
-1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; 0 ; 
|]
let _gotocallret_trans_offsets : int array = [|
0; 1; 2; 3; 4; 5; 6; 7; 8; 9; 10; 11; 12; 13; 14; 15; 16; 17; 18; 19; 20; 21; 0 ; 
|]
let _gotocallret_trans_lengths : int array = [|
1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 0 ; 
|]
let _gotocallret_cond_keys : int array = [|
0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0 ; 
|]
let _gotocallret_cond_targs : int array = [|
2; 0; 7; 0; 8; 4; 8; 4; 9; 9; 0; 10; 0; 1; 1; 0; 0; 9; 9; 0; 10; 0; 0 ; 
|]
let _gotocallret_cond_actions : int array = [|
18; 13; 11; 13; 15; 1; 3; 0; 0; 0; 7; 0; 7; 9; 9; 13; 0; 0; 0; 7; 0; 7; 0 ; 
|]
let _gotocallret_eof_actions : int array = [|
0; 13; 13; 5; 5; 7; 7; 0; 5; 0; 0; 0 ; 
|]
let _gotocallret_nfa_targs : int array = [|
0; 0 ; 
|]
let _gotocallret_nfa_offsets : int array = [|
0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0 ; 
|]
let _gotocallret_nfa_push_actions : int array = [|
0; 0 ; 
|]
let _gotocallret_nfa_pop_trans : int array = [|
0; 0 ; 
|]
let gotocallret_start  : int  = 7
let gotocallret_first_final  : int  = 7
let gotocallret_error  : int  = 0
let gotocallret_en_garble_line  : int  = 3
let gotocallret_en_alp_comm  : int  = 5
let gotocallret_en_dig_comm  : int  = 6
let gotocallret_en_main  : int  = 7
let exec data = 
let buffer = String.create(1024) in 
let blen :int ref = ref 0 in
let cs = ref 0 in
let p = ref 0 in
let pe = ref (String.length data) in
let eof = pe in
begin
	cs  := gotocallret_start;
	top  := 0;
	
end;
begin
	let _klen : int  ref = ref 0 in
	let _trans  : int  ref = ref 0 in
	let _cond  : int  ref = ref 0 in
	let _have  : int  ref = ref 0 in
	let _cont  : int  ref = ref 1 in
	let _acts : int ref = ref 0 in
	let _nacts : int  ref = ref 0 in
	let _keys : int ref = ref 0 in
	let _ckeys : int ref = ref 0 in
	let _cpc : int  ref = ref 0 in
	while _cont.contents= 1  do
	begin
		if cs.contents= 0  then
		begin
			_cont  := 0;
			
		end
		;_have  := 0;
		if p.contents= pe.contents then
		begin
			begin
				if p.contents= eof.contents then
				begin
					begin
						if _have.contents= 0  then
						begin
							begin
								let __acts : int ref = ref 0 in
								let __nacts : int  ref = ref 0 in
								__acts  := _gotocallret_eof_actions.(cs.contents);
								__nacts  := _gotocallret_actions.( __acts.contents );
								__acts  := __acts.contents + 1;
								while __nacts.contents> 0  do
								begin
									if _gotocallret_actions.( __acts.contents ) = 2  then
									begin
										begin
											print_string( "error: failed to recover\n" );
											
										end;
										
									end
									else if _gotocallret_actions.( __acts.contents ) = 3  then
									begin
										begin
											begin
												p  := p.contents- 1;
												
											end;
											begin
												top := top.contents - 1;
												cs  := stack.(top.contents);
												
											end;
											
										end;
										
									end
									else if _gotocallret_actions.( __acts.contents ) = 8  then
									begin
										begin
											begin
												p  := p.contents- 1;
												
											end;
											begin
												cs  := 3;
												
											end;
											
										end;
										
									end
									;
									__nacts  := __nacts.contents - 1;
									__acts  := __acts.contents + 1;
									
								end;
								
								done;
								
							end;
							
						end
						;
					end;
					
				end
				;if _have.contents= 0  then
				begin
					_cont  := 0;
					
				end
				;
			end;
			
		end
		;if _cont.contents= 1  then
		begin
			begin
				if _have.contents= 0  then
				begin
					begin
						_keys  := _gotocallret_key_offsets.(cs.contents);
						_trans  := _gotocallret_index_offsets.(cs.contents);
						_have  := 0;
						_klen  := _gotocallret_single_lengths.(cs.contents);
						if _klen.contents> 0  then
						begin
							begin
								let _lower : int ref = ref 0 in
								let _mid : int ref = ref 0 in
								let _upper : int ref = ref 0 in
								_lower  := _keys.contents;
								_upper  := _keys.contents+ _klen.contents- 1;
								while _upper.contents>= _lower.contents&& _have.contents= 0  do
								begin
									_mid  := _lower.contents+ ( ( _upper.contents-_lower.contents ) asr 1 );
									if ( Char.code data.[p.contents] )< _gotocallret_trans_keys.( _mid.contents ) then
									begin
										_upper  := _mid.contents- 1;
										
									end
									else if ( Char.code data.[p.contents] )> _gotocallret_trans_keys.( _mid.contents ) then
									begin
										_lower  := _mid.contents+ 1;
										
									end
									else
									begin
										begin
											_trans  := _trans.contents + ( _mid.contents- _keys.contents );
											_have  := 1;
											
										end;
										
									end
									;
								end;
								
								done;
								if _have.contents= 0  then
								begin
									begin
										_keys  := _keys.contents + _klen.contents;
										_trans  := _trans.contents + _klen.contents;
										
									end;
									
								end
								;
							end;
							
						end
						;if _have.contents= 0  then
						begin
							begin
								_klen  := _gotocallret_range_lengths.(cs.contents);
								if _klen.contents> 0  then
								begin
									begin
										let _lower : int ref = ref 0 in
										let _mid : int ref = ref 0 in
										let _upper : int ref = ref 0 in
										_lower  := _keys.contents;
										_upper  := _keys.contents+ ( _klen.contents lsl 1 )- 2;
										while _have.contents= 0 && _lower.contents<= _upper.contents do
										begin
											_mid  := _lower.contents+ ( ( ( _upper.contents-_lower.contents ) asr 1 ) land  lnot 1 );
											if ( Char.code data.[p.contents] )< _gotocallret_trans_keys.( _mid.contents ) then
											begin
												_upper  := _mid.contents- 2;
												
											end
											else if ( Char.code data.[p.contents] )> _gotocallret_trans_keys.( _mid.contents+ 1  ) then
											begin
												_lower  := _mid.contents+ 2;
												
											end
											else
											begin
												begin
													_trans  := _trans.contents + ( ( _mid.contents- _keys.contents ) asr 1 );
													_have  := 1;
													
												end;
												
											end
											;
										end;
										
										done;
										if _have.contents= 0  then
										begin
											_trans  := _trans.contents + _klen.contents;
											
										end
										;
									end;
									
								end
								;
							end;
							
						end
						;_ckeys  := _gotocallret_trans_offsets.(_trans.contents);
						_klen  := _gotocallret_trans_lengths.(_trans.contents);
						_cond  := _gotocallret_trans_offsets.(_trans.contents);
						_have  := 0;
						_cpc  := 0;
						begin
							let _lower : int ref = ref 0 in
							let _mid : int ref = ref 0 in
							let _upper : int ref = ref 0 in
							_lower  := _ckeys.contents;
							_upper  := _ckeys.contents+ _klen.contents- 1;
							while _have.contents= 0 && _lower.contents<= _upper.contents do
							begin
								_mid  := _lower.contents+ ( ( _upper.contents-_lower.contents ) asr 1 );
								if _cpc.contents< _gotocallret_cond_keys.( _mid.contents ) then
								begin
									_upper  := _mid.contents- 1;
									
								end
								else if _cpc.contents> _gotocallret_cond_keys.( _mid.contents ) then
								begin
									_lower  := _mid.contents+ 1;
									
								end
								else
								begin
									begin
										_cond  := _cond.contents + ( _mid.contents- _ckeys.contents );
										_have  := 1;
										
									end;
									
								end
								;
							end;
							
							done;
							if _have.contents= 0  then
							begin
								begin
									cs  := 0;
									_cont  := 0;
									
								end;
								
							end
							;
						end;
						
					end;
					
				end
				;if _cont.contents= 1  then
				begin
					begin
						cs  := _gotocallret_cond_targs.(_cond.contents);
						if _gotocallret_cond_actions.(_cond.contents)!= 0  then
						begin
							begin
								_acts  := _gotocallret_cond_actions.(_cond.contents);
								_nacts  := _gotocallret_actions.( _acts.contents );
								_acts  := _acts.contents + 1;
								while _nacts.contents> 0  do
								begin
									if _gotocallret_actions.( _acts.contents ) = 0  then
									begin
										begin
											print_string( "error: garbling line\n" );
											
										end;
										
									end
									else if _gotocallret_actions.( _acts.contents ) = 1  then
									begin
										begin
											begin
												cs  := 7;
												
											end;
											
										end;
										
									end
									else if _gotocallret_actions.( _acts.contents ) = 3  then
									begin
										begin
											begin
												p  := p.contents- 1;
												
											end;
											begin
												top := top.contents - 1;
												cs  := stack.(top.contents);
												
											end;
											
										end;
										
									end
									else if _gotocallret_actions.( _acts.contents ) = 4  then
									begin
										begin
											if comm .contents >= 97  then
											begin
												begin
													Array.set stack top.contents cs.contents;top  := top.contents + 1;
													cs  := 5;
													
												end;
											end 
											else
											begin
												begin
													Array.set stack top.contents cs.contents;top  := top.contents + 1;
													cs  := 6;
													
												end;
											end
											;
											
										end;
										
									end
									else if _gotocallret_actions.( _acts.contents ) = 5  then
									begin
										begin
											comm := (( Char.code data.[p.contents] ));
											
										end;
										
									end
									else if _gotocallret_actions.( _acts.contents ) = 6  then
									begin
										begin
											print_string( "prints\n" );
											
										end;
										
									end
									else if _gotocallret_actions.( _acts.contents ) = 7  then
									begin
										begin
											print_string( "correct command\n" );
											
										end;
										
									end
									else if _gotocallret_actions.( _acts.contents ) = 8  then
									begin
										begin
											begin
												p  := p.contents- 1;
												
											end;
											begin
												cs  := 3;
												
											end;
											
										end;
										
									end
									;
									_nacts  := _nacts.contents - 1;
									_acts  := _acts.contents + 1;
									
								end;
								
								done;
								
							end;
							
						end
						;if cs.contents= 0  then
						begin
							_cont  := 0;
							
						end
						;if _cont.contents= 1  then
						begin
							p  := p.contents + 1;
							
						end
						;
					end;
					
				end
				;
			end;
			
		end
		;
	end;
	
	done;
	
end;
if !cs >= gotocallret_first_final then
print_string "ACCEPT\n"
else
print_string "FAIL\n"
;;

let () =
exec "lkajsdf\n";
exec "2134\n";
exec "(\n";
exec "\n";
exec "*234234()0909 092 -234aslkf09`1 11\n";
exec "1\n";
exec "909\n";
exec "1 a\n";
exec "11 1\n";
exec "a 1\n";
exec "aa a\n";
exec "1 1\n";
exec "1 123456\n";
exec "a a\n";
exec "a abcdef\n";
exec "h";
exec "a aa1";
()
;;

