using System;
// Disables lots of warnings that appear in the test suite
#pragma warning disable 0168, 0169, 0219, 0162, 0414
namespace Test {
	class Test
	{
		char comm;
		int top;
		int [] stack = new int [32];
		
		
		
		
		static readonly sbyte  []_GotoCallRet_actions = { 0, 1, 0, 1, 1, 1, 2, 1, 3, 1, 4, 1, 5, 1, 6, 1, 7, 2, 0, 1, 0,  };
		static readonly sbyte  []_GotoCallRet_key_offsets = { 0, 0, 1, 2, 3, 4, 8, 10, 14, 14, 18, 0,  };
		static readonly char  []_GotoCallRet_trans_keys = { '\u0020', '\u000a', '\u000a', '\u000a', '\u0041', '\u005a', '\u0061', '\u007a', '\u0030', '\u0039', '\u0030', '\u0039', '\u0061', '\u007a', '\u0041', '\u005a', '\u0061', '\u007a', '\u0030', '\u0039', '\u0000',  };
		static readonly sbyte  []_GotoCallRet_single_lengths = { 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,  };
		static readonly sbyte  []_GotoCallRet_range_lengths = { 0, 0, 0, 0, 0, 2, 1, 2, 0, 2, 1, 0,  };
		static readonly sbyte  []_GotoCallRet_index_offsets = { 0, 0, 2, 4, 6, 8, 11, 13, 16, 17, 20, 0,  };
		static readonly sbyte  []_GotoCallRet_trans_cond_spaces = { -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0,  };
		static readonly sbyte  []_GotoCallRet_trans_offsets = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 0,  };
		static readonly sbyte  []_GotoCallRet_trans_lengths = { 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,  };
		static readonly sbyte  []_GotoCallRet_cond_keys = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  };
		static readonly sbyte  []_GotoCallRet_cond_targs = { 2, 0, 7, 0, 8, 4, 8, 4, 9, 9, 0, 10, 0, 1, 1, 0, 0, 9, 9, 0, 10, 0, 0,  };
		static readonly sbyte  []_GotoCallRet_cond_actions = { 9, 15, 13, 15, 17, 1, 3, 0, 0, 0, 7, 0, 7, 11, 11, 15, 0, 0, 0, 7, 0, 7, 0,  };
		static readonly sbyte  []_GotoCallRet_eof_actions = { 0, 15, 15, 5, 5, 7, 7, 0, 5, 0, 0, 0,  };
		static readonly sbyte  []_GotoCallRet_nfa_targs = { 0, 0,  };
		static readonly sbyte  []_GotoCallRet_nfa_offsets = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  };
		static readonly sbyte  []_GotoCallRet_nfa_push_actions = { 0, 0,  };
		static readonly sbyte  []_GotoCallRet_nfa_pop_trans = { 0, 0,  };
		static readonly int  GotoCallRet_start  = 7;
		static readonly int  GotoCallRet_first_final  = 7;
		static readonly int  GotoCallRet_error  = 0;
		static readonly int  GotoCallRet_en_garble_line  = 3;
		static readonly int  GotoCallRet_en_alp_comm  = 5;
		static readonly int  GotoCallRet_en_dig_comm  = 6;
		static readonly int  GotoCallRet_en_main  = 7;
		int cs;
		
		void init()
		{
		
			{
				cs = (int)GotoCallRet_start;
				top = 0;
			}
		}
		
		void exec( char[] data, int len )
		{
			int p = 0;
			int pe = len;
			int eof = len;
			string _s;
			char [] buffer = new char [1024];
			int blen = 0;
			
			{
				int _klen;
				uint _trans = 0;
				uint _cond = 0;
				int _acts;
				uint _nacts;
				int _keys;
				int _ckeys;
				int _cpc;
				if ( p == pe  )
				goto _test_eof;
				
				if ( cs == 0 )
				goto _out;
				
				_resume :
				_keys = _GotoCallRet_key_offsets[cs] ;
				_trans = (uint )_GotoCallRet_index_offsets[cs];
				_klen = (int)_GotoCallRet_single_lengths[cs];
				if ( _klen > 0 )
				{
					int _lower;
					int _mid;
					int _upper;
					_lower = _keys;
					_upper = _keys + _klen - 1;
					while ( true  )
					{
						if ( _upper < _lower  )
						break;
						
						
						_mid = _lower + ((_upper-_lower) >> 1);
						if ( ( data[p ]) < _GotoCallRet_trans_keys[_mid ] )
						_upper = _mid - 1;
						
						else if ( ( data[p ]) > _GotoCallRet_trans_keys[_mid ] )
						_lower = _mid + 1;
						
						else
						{
							_trans += (uint )(_mid - _keys);
							goto _match;
						}
						
					}
					
					_keys += _klen;
					_trans += (uint )_klen;
				}
				
				
				_klen = (int)_GotoCallRet_range_lengths[cs];
				if ( _klen > 0 )
				{
					int _lower;
					int _mid;
					int _upper;
					_lower = _keys;
					_upper = _keys + (_klen<<1) - 2;
					while ( true  )
					{
						if ( _upper < _lower  )
						break;
						
						
						_mid = _lower + (((_upper-_lower) >> 1) & ~1);
						if ( ( data[p ]) < _GotoCallRet_trans_keys[_mid ] )
						_upper = _mid - 2;
						
						else if ( ( data[p ]) > _GotoCallRet_trans_keys[_mid + 1] )
						_lower = _mid + 2;
						
						else
						{
							_trans += (uint )((_mid - _keys)>>1);
							goto _match;
						}
						
					}
					
					_trans += (uint )_klen;
				}
				
				
				
				_match :
				_ckeys = _GotoCallRet_trans_offsets[_trans] ;
				_klen = (int)_GotoCallRet_trans_lengths[_trans];
				_cond = (uint )_GotoCallRet_trans_offsets[_trans];
				_cpc = 0;
				{
					int _lower;
					int _mid;
					int _upper;
					_lower = _ckeys;
					_upper = _ckeys + _klen - 1;
					while ( true  )
					{
						if ( _upper < _lower  )
						break;
						
						
						_mid = _lower + ((_upper-_lower) >> 1);
						if ( _cpc < (int)_GotoCallRet_cond_keys[_mid ] )
						_upper = _mid - 1;
						
						else if ( _cpc > (int)_GotoCallRet_cond_keys[_mid ] )
						_lower = _mid + 1;
						
						else
						{
							_cond += (uint )(_mid - _ckeys);
							goto _match_cond;
						}
						
					}
					
					cs = 0;
					goto _again;
				}
				
				_match_cond :
				cs = (int)_GotoCallRet_cond_targs[_cond];
				if ( _GotoCallRet_cond_actions[_cond] == 0 )
				goto _again;
				
				
				_acts = _GotoCallRet_cond_actions[_cond] ;
				_nacts = (uint )_GotoCallRet_actions[_acts ];
				_acts += 1;
				while ( _nacts > 0 )
				{
					switch ( _GotoCallRet_actions[_acts ] ) {
						case 0:
						{Console.Write( "error: garbling line\n" );}
						
						break;
						case 1:
						{{cs = 7;
								goto _again;}}
						
						break;
						case 3:
						{{p = p - 1;
							}{top-= 1;
								cs = stack[top];
								goto _again;}}
						
						break;
						case 4:
						{if ( comm >= 'a' )
							{
								{stack[top] = cs;
									top += 1;
									cs = 5;
									goto _again;}} 
							else {
								{stack[top] = cs;
									top += 1;
									cs = 6;
									goto _again;}}
						}
						
						break;
						case 5:
						{comm = (( data[p ]));
						}
						
						break;
						case 6:
						{Console.Write( "correct command\n" );}
						
						break;
						case 7:
						{{p = p - 1;
							}{cs = 3;
								goto _again;}}
						
						break;
						
					}
					_nacts -= 1;
					_acts += 1;
				}
				
				
				
				
				_again :
				if ( cs == 0 )
				goto _out;
				
				p += 1;
				if ( p != pe  )
				goto _resume;
				
				
				_test_eof :
				{}
				if ( p == eof  )
				{
					int __acts;
					uint __nacts;
					__acts = _GotoCallRet_eof_actions[cs] ;
					__nacts = (uint )_GotoCallRet_actions[__acts ];
					__acts += 1;
					while ( __nacts > 0 )
					{
						switch ( _GotoCallRet_actions[__acts ] ) {
							case 2:
							{Console.Write( "error: failed to recover\n" );}
							
							break;
							case 3:
							{{p = p - 1;
								}{top-= 1;
									cs = stack[top];
									goto _again;}}
							
							break;
							case 7:
							{{p = p - 1;
								}{cs = 3;
									goto _again;}}
							
							break;
							
						}
						__nacts -= 1;
						__acts += 1;
					}
					
				}
				
				
				
				_out :
				{}
				
			}
		}
		
		void finish( )
		{
			if ( cs >= GotoCallRet_first_final )
			Console.WriteLine( "ACCEPT" );
			else
			Console.WriteLine( "FAIL" );
		}
		
		static readonly string[] inp = {
			"lkajsdf\n",
			"2134\n",
			"(\n",
			"\n",
			"*234234()0909 092 -234aslkf09`1 11\n",
			"1\n",
			"909\n",
			"1 a\n",
			"11 1\n",
			"a 1\n",
			"aa a\n",
			"1 1\n",
			"1 123456\n",
			"a a\n",
			"a abcdef\n",
			"h",
			"a aa1",
		};
		
		
		static readonly int inplen = 17;
		
		public static void Main (string[] args)
		{
			Test machine = new Test();
			for ( int i = 0; i < inplen; i++ ) {
				machine.init();
				machine.exec( inp[i].ToCharArray(), inp[i].Length );
				machine.finish();
			}
		}
	}
}
