const _atoi_actions = Int8[0, 1, 0, 0 , ]
const _atoi_key_offsets = Int8[0, 0, 3, 5, 8, 0 , ]
const _atoi_trans_keys = UInt8[45, 48, 57, 48, 57, 46, 48, 57, 0 , ]
const _atoi_single_lengths = Int8[0, 1, 0, 1, 0, 0 , ]
const _atoi_range_lengths = Int8[0, 1, 1, 1, 0, 0 , ]
const _atoi_index_offsets = Int8[0, 0, 3, 5, 8, 0 , ]
const _atoi_trans_cond_spaces = Int8[-1, -1, -1, -1, -1, -1, -1, -1, -1, 0 , ]
const _atoi_trans_offsets = Int8[0, 1, 2, 3, 4, 5, 6, 7, 8, 0 , ]
const _atoi_trans_lengths = Int8[1, 1, 1, 1, 1, 1, 1, 1, 1, 0 , ]
const _atoi_cond_keys = Int8[0, 0, 0, 0, 0, 0, 0, 0, 0, 0 , ]
const _atoi_cond_targs = Int8[2, 3, 0, 3, 0, 4, 3, 0, 0, 0 , ]
const _atoi_cond_actions = Int8[0, 0, 0, 0, 0, 1, 0, 0, 0, 0 , ]
const _atoi_nfa_targs = Int8[0, 0 , ]
const _atoi_nfa_offsets = Int8[0, 0, 0, 0, 0, 0 , ]
const _atoi_nfa_push_actions = Int8[0, 0 , ]
const _atoi_nfa_pop_trans = Int8[0, 0 , ]
const atoi_start  = 1
const atoi_first_final  = 4
const atoi_error  = 0
const atoi_en_main  = 1
function test( data::String )
	p = 0
	pe = length(data)
	eof = length(data)
	cs = 0
	
	cs = convert(Int, atoi_start )
	_klen= 0
	;
	_trans = 0;
	_cond = 0;
	_have = 0;
	_cont = 1;
	_acts = 0;
	_nacts= 0
	;
	_keys = 0;
	_ckeys = 0;
	_cpc= 0
	;
	while _cont == 1 
		if cs == 0 
			_cont = 0
			
		end
		_have = 0
		if p == pe 
			if _have == 0 
				_cont = 0
				
			end
			
		end
		if _cont == 1 
			if _have == 0 
				_keys = _atoi_key_offsets[1+(cs)]
				_trans = convert(UInt, _atoi_index_offsets[1+(cs)] )
				_have = 0
				_klen = convert(Int, _atoi_single_lengths[1+(cs)] )
				if _klen > 0 
					_lower = 0;
					_mid = 0;
					_upper = 0;
					_lower = _keys
					_upper = _keys + _klen - 1
					while _upper >= _lower && _have == 0 
						_mid = _lower + ((_upper-_lower)>> 1)
						if (data[1+(p )])< _atoi_trans_keys[1+(_mid )]
							_upper = _mid - 1
							
						elseif (data[1+(p )])> _atoi_trans_keys[1+(_mid )]
							_lower = _mid + 1
							
						else
							_trans += convert(UInt, (_mid - _keys) )
							_have = 1
							
						end
						
					end
					if _have == 0 
						_keys += _klen
						_trans += convert(UInt, _klen )
						
					end
					
				end
				if _have == 0 
					_klen = convert(Int, _atoi_range_lengths[1+(cs)] )
					if _klen > 0 
						_lower = 0;
						_mid = 0;
						_upper = 0;
						_lower = _keys
						_upper = _keys + (_klen<<1)- 2
						while _have == 0 && _lower <= _upper 
							_mid = _lower + (((_upper-_lower)>> 1)& ~1)
							if (data[1+(p )])< _atoi_trans_keys[1+(_mid )]
								_upper = _mid - 2
								
							elseif (data[1+(p )])> _atoi_trans_keys[1+(_mid + 1 )]
								_lower = _mid + 2
								
							else
								_trans += convert(UInt, ((_mid - _keys)>>1) )
								_have = 1
								
							end
							
						end
						if _have == 0 
							_trans += convert(UInt, _klen )
							
						end
						
					end
					
				end
				_ckeys = _atoi_trans_offsets[1+(_trans)]
				_klen = convert(Int, _atoi_trans_lengths[1+(_trans)] )
				_cond = convert(UInt, _atoi_trans_offsets[1+(_trans)] )
				_have = 0
				_cpc = 0
				_lower = 0;
				_mid = 0;
				_upper = 0;
				_lower = _ckeys
				_upper = _ckeys + _klen - 1
				while _have == 0 && _lower <= _upper 
					_mid = _lower + ((_upper-_lower)>> 1)
					if _cpc < convert(Int, _atoi_cond_keys[1+(_mid )] )
						_upper = _mid - 1
						
					elseif _cpc > convert(Int, _atoi_cond_keys[1+(_mid )] )
						_lower = _mid + 1
						
					else
						_cond += convert(UInt, (_mid - _ckeys) )
						_have = 1
						
					end
					
				end
				if _have == 0 
					cs = 0
					_cont = 0
					
				end
				
			end
			if _cont == 1 
				cs = convert(Int, _atoi_cond_targs[1+(_cond)] )
				if _atoi_cond_actions[1+(_cond)]!= 0 
					_acts = _atoi_cond_actions[1+(_cond)]
					_nacts = convert(UInt, _atoi_actions[1+(_acts )] )
					_acts += 1
					while _nacts > 0 
						if _atoi_actions[1+(_acts )] == 0 
							println( "match" );
							
						end
						_nacts -= 1
						_acts += 1
						
					end
					
				end
				if cs == 0 
					_cont = 0
					
				end
				if _cont == 1 
					p += 1
					
				end
				
			end
			
		end
		
	end
end


test( "-99." )
test( "100." )
test( "100x." )
test( "1000." )

