#include <stdio.h>
#include <string.h>

struct min
{
	int cs;
};



static const char  _min_key_offsets [] = { 0, 0, 2, 5, 0 ,  };
static const char  _min_trans_keys [] = { 97, 98, 10, 97, 98, 0 ,  };
static const char  _min_single_lengths [] = { 0, 0, 1, 0, 0 ,  };
static const char  _min_range_lengths [] = { 0, 1, 1, 0, 0 ,  };
static const char  _min_index_offsets [] = { 0, 0, 2, 5, 0 ,  };
static const char  _min_trans_cond_spaces [] = { -1, -1, -1, -1, -1, -1, 0 ,  };
static const char  _min_trans_offsets [] = { 0, 1, 2, 3, 4, 5, 0 ,  };
static const char  _min_trans_lengths [] = { 1, 1, 1, 1, 1, 1, 0 ,  };
static const char  _min_cond_keys [] = { 0, 0, 0, 0, 0, 0, 0 ,  };
static const char  _min_cond_targs [] = { 2, 0, 3, 2, 0, 0, 0 ,  };
static const char  _min_cond_actions [] = { 0, 0, 0, 1, 0, 0, 0 ,  };
static const char  _min_nfa_targs [] = { 0, 0 ,  };
static const char  _min_nfa_offsets [] = { 0, 0, 0, 0, 0 ,  };
static const char  _min_nfa_push_actions [] = { 0, 0 ,  };
static const char  _min_nfa_pop_trans [] = { 0, 0 ,  };
static const int  min_start  = 1;
static const int  min_first_final  = 3;
static const int  min_error  = 0;
static const int  min_en_main  = 1;
void min_init( struct min *fsm )
{

	{
		(fsm->cs) = ( int ) min_start;
	}
}

void min_execute( struct min *fsm, const char *_data, int _len )
{
	const char *p = _data;
	const char *pe = _data+_len;
	
	
	{
		int _klen;
		const char  *_keys;
		const char  *_ckeys;
		int _cpc;
		unsigned int _trans;
		unsigned int _cond = 0;
		unsigned int _have = 0;
		unsigned int _cont = 1;
		while ( _cont == 1  )
		{
		
			if ( (fsm->cs) == 0  )
			_cont = 0;
			
			_have = 0;
			if ( p == pe  )
			{
				if ( _have == 0  )
				_cont = 0;
				
			}
			
			if ( _cont == 1  )
			{
				if ( _have == 0  )
				{
					_keys = _min_trans_keys + _min_key_offsets[(fsm->cs)];
					_trans = ( unsigned int  ) _min_index_offsets[(fsm->cs)];
					_have = 0;
					_klen = ( int ) _min_single_lengths[(fsm->cs)];
					if ( _klen > 0  )
					{
						const char  *_lower;
						const char  *_mid;
						const char  *_upper;
						_lower = _keys;
						_upper = _keys + _klen - 1;
						while ( _upper >= _lower && _have == 0  )
						{
							_mid = _lower + ((_upper-_lower)>> 1);
							if ( ((*( p  ))
							)< (*( _mid  ))
							)
							_upper = _mid - 1;
							
							else if ( ((*( p  ))
							)> (*( _mid  ))
							)
							_lower = _mid + 1;
							
							else
							{
								_trans += ( unsigned int  ) (_mid - _keys);
								_have = 1;
							}
							
						}
						
						if ( _have == 0  )
						{
							_keys += _klen;
							_trans += ( unsigned int  ) _klen;
						}
						
					}
					
					
					if ( _have == 0  )
					{
						_klen = ( int ) _min_range_lengths[(fsm->cs)];
						if ( _klen > 0  )
						{
							const char  *_lower;
							const char  *_mid;
							const char  *_upper;
							_lower = _keys;
							_upper = _keys + (_klen<<1)- 2;
							while ( _have == 0 && _lower <= _upper  )
							{
								_mid = _lower + (((_upper-_lower)>> 1)& ~1);
								if ( ((*( p  ))
								)< (*( _mid  ))
								)
								_upper = _mid - 2;
								
								else if ( ((*( p  ))
								)> (*( _mid + 1  ))
								)
								_lower = _mid + 2;
								
								else
								{
									_trans += ( unsigned int  ) ((_mid - _keys)>>1);
									_have = 1;
								}
								
							}
							
							if ( _have == 0  )
							_trans += ( unsigned int  ) _klen;
							
						}
						
					}
					
					
					_ckeys = _min_cond_keys + _min_trans_offsets[_trans];
					_klen = ( int ) _min_trans_lengths[_trans];
					_cond = ( unsigned int  ) _min_trans_offsets[_trans];
					_have = 0;
					_cpc = 0;
					{
						const char  *_lower;
						const char  *_mid;
						const char  *_upper;
						_lower = _ckeys;
						_upper = _ckeys + _klen - 1;
						while ( _have == 0 && _lower <= _upper  )
						{
							_mid = _lower + ((_upper-_lower)>> 1);
							if ( _cpc < ( int ) (*( _mid  ))
							)
							_upper = _mid - 1;
							
							else if ( _cpc > ( int ) (*( _mid  ))
							)
							_lower = _mid + 1;
							
							else
							{
								_cond += ( unsigned int  ) (_mid - _ckeys);
								_have = 1;
							}
							
						}
						
						if ( _have == 0  )
						{
							(fsm->cs) = 0;
							_cont = 0;
						}
						
					}
				}
				
				if ( _cont == 1  )
				{
					(fsm->cs) = ( int ) _min_cond_targs[_cond];
					switch ( _min_cond_actions[_cond] ) {
						case 1 :
						{
							printf("a or b\n"); 
						}
						
						break;
						
					}
					if ( (fsm->cs) == 0  )
					_cont = 0;
					
					if ( _cont == 1  )
					p += 1;
					
				}
			}
			
		}
		
	}
}

int min_finish( struct min *fsm )
{
	if ( fsm->cs == min_error )
	return -1;
	if ( fsm->cs >= min_first_final )
	return 1;
	return 0;
}

struct min fsm;

void test( char *buf )
{
	int len = strlen( buf );
	min_init( &fsm );
	min_execute( &fsm, buf, len );
	if ( min_finish( &fsm ) > 0 )
	printf("ACCEPT\n");
	else
	printf("FAIL\n");
}


int main()
{
	test( "aaaaaa\n" );
	test( "a\n" );
	test( "abc\n" );
	return 0;
}

