const _ncall1_actions = Int8[0, 1, 0, 1, 1, 1, 2, 1, 3, 0 , ]
const _ncall1_trans_keys = UInt8[1, 0, 10, 10, 6, 6, 10, 10, 8, 8, 5, 5, 4, 4, 7, 7, 6, 6, 5, 5, 9, 9, 11, 11, 7, 7, 0, 3, 1, 0, 1, 0, 1, 0, 0 , ]
const _ncall1_char_class = Int8[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 5, 1, 1, 1, 1, 1, 1, 1, 1, 6, 7, 1, 1, 1, 8, 9, 10, 1, 11, 0 , ]
const _ncall1_index_offsets = Int8[0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 16, 16, 16, 0 , ]
const _ncall1_indicies = Int8[0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 0 , ]
const _ncall1_index_defaults = Int8[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0 , ]
const _ncall1_trans_cond_spaces = Int8[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0 , ]
const _ncall1_cond_targs = Int8[2, 0, 3, 4, 5, 6, 14, 8, 9, 15, 11, 12, 16, 13, 13, 13, 0 , ]
const _ncall1_cond_actions = Int8[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 3, 0, 5, 7, 0 , ]
const _ncall1_nfa_targs = Int8[0, 0 , ]
const _ncall1_nfa_offsets = Int8[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 , ]
const _ncall1_nfa_push_actions = Int8[0, 0 , ]
const _ncall1_nfa_pop_trans = Int8[0, 0 , ]
const ncall1_start  = 13
const ncall1_first_final  = 13
const ncall1_error  = 0
const ncall1_en_unused  = 1
const ncall1_en_one  = 7
const ncall1_en_two  = 10
const ncall1_en_main  = 13
function m( data::AbstractString )
	p = 0
	pe = length(data)
	eof = length(data)
	cs = 0
	buffer = ""
	top = 0;
	stack = Int [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ];
	target = 0;
	
	cs = convert(Int, ncall1_start )
	top = 0
	_trans = 0;
	_have = 0;
	_cont = 1;
	_acts = 0;
	_nacts= 0
	;
	_keys = 0;
	_inds = 0;
	while _cont == 1 
		if cs == 0 
			_cont = 0
			
		end
		_have = 0
		if p == pe 
			if _have == 0 
				_cont = 0
				
			end
			
		end
		if _cont == 1 
			if _have == 0 
				_keys = (cs<<1)
				_inds = _ncall1_index_offsets[1+(cs)]
				if (data[1+(p )])<= 119 && (data[1+(p )])>= 10 
					_ic = convert(Int, _ncall1_char_class[1+(convert(Int, (data[1+(p )]) )- 10)] );
					if _ic <= convert(Int, _ncall1_trans_keys[1+(_keys+1 )] )&& _ic >= convert(Int, _ncall1_trans_keys[1+(_keys )] )
						_trans = convert(UInt, _ncall1_indicies[1+(_inds + convert(Int, (_ic - convert(Int, _ncall1_trans_keys[1+(_keys )] )) ))] )
						
					else
						_trans = convert(UInt, _ncall1_index_defaults[1+(cs)] )
						
					end
					
				else
					_trans = convert(UInt, _ncall1_index_defaults[1+(cs)] )
					
				end
				
			end
			if _cont == 1 
				cs = convert(Int, _ncall1_cond_targs[1+(_trans)] )
				if _ncall1_cond_actions[1+(_trans)]!= 0 
					_acts = _ncall1_cond_actions[1+(_trans)]
					_nacts = convert(UInt, _ncall1_actions[1+(_acts )] )
					_acts += 1
					while _nacts > 0 
						if _ncall1_actions[1+(_acts )] == 0 
							print( "one\n" );
							{
								top-= 1
								cs = stack[1+(top)]
								
							}
							
						elseif _ncall1_actions[1+(_acts )] == 1 
							print( "two\n" );
							{
								top-= 1
								cs = stack[1+(top)]
								
							}
							
						elseif _ncall1_actions[1+(_acts )] == 2 
							target = 7;
							{
								stack[1+(top)]= cs
								top += 1
								cs = (target)
								
							}
							
						elseif _ncall1_actions[1+(_acts )] == 3 
							target = 10;
							{
								stack[1+(top)]= cs
								top += 1
								cs = (target)
								
							}
							
						end
						_nacts -= 1
						_acts += 1
						
					end
					
				end
				if cs == 0 
					_cont = 0
					
				end
				if _cont == 1 
					p += 1
					
				end
				
			end
			
		end
		
	end
	if ( cs >= ncall1_first_final )
		println( "ACCEPT" );
	else
		println( "FAIL" );
	end
end

m( "1one2two1one\n" );
