import crack.io cout;
import crack.lang Buffer;

int target;
int last;





const array[int16 ] _next2_actions = [ 0, 1, 0, 1, 1, 1, 2, 1, 3, 1, 4, 1, 5, 0 ,  ];
const array[int16 ] _next2_key_offsets = [ 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 22, 22, 22, 22, 0 ,  ];
const array[byte ] _next2_trans_keys = [ 120, 117, 110, 117, 115, 101, 100, 111, 110, 101, 116, 119, 111, 116, 104, 114, 101, 101, 10, 49, 50, 51, 0,  ];
const array[int16 ] _next2_single_lengths = [ 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 0, 0, 0, 0, 0 ,  ];
const array[int16 ] _next2_range_lengths = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  ];
const array[int16 ] _next2_index_offsets = [ 0, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 41, 42, 43, 44, 0 ,  ];
const array[int16 ] _next2_trans_cond_spaces = [ -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0 ,  ];
const array[int16 ] _next2_trans_offsets = [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 0 ,  ];
const array[int16 ] _next2_trans_lengths = [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0 ,  ];
const array[int16 ] _next2_cond_keys = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  ];
const array[int16 ] _next2_cond_targs = [ 19, 0, 3, 0, 4, 0, 5, 0, 6, 0, 7, 0, 20, 0, 9, 0, 10, 0, 21, 0, 12, 0, 13, 0, 22, 0, 15, 0, 16, 0, 17, 0, 18, 0, 23, 0, 19, 19, 19, 1, 0, 0, 0, 0, 0, 0 ,  ];
const array[int16 ] _next2_cond_actions = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 7, 9, 11, 0, 0, 0, 0, 0, 0 ,  ];
const array[int16 ] _next2_nfa_targs = [ 0, 0 ,  ];
const array[int16 ] _next2_nfa_offsets = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  ];
const array[int16 ] _next2_nfa_push_actions = [ 0, 0 ,  ];
const array[int16 ] _next2_nfa_pop_trans = [ 0, 0 ,  ];
const int  next2_start  = 19;
const int  next2_first_final  = 19;
const int  next2_error  = 0;
const int  next2_en_unused  = 2;
const int  next2_en_one  = 8;
const int  next2_en_two  = 11;
const int  next2_en_three  = 14;
const int  next2_en_main  = 19;
void m( String s )
{
	byteptr data = s.buffer;
	int p = 0;
	int pe = s.size;
	int cs;
	String buffer;
	
	if ( 1 ) {
		cs = int ( next2_start );
		
	}
	if ( 1 ) {
		int _klen;
		uint32 _trans = 0;
		uint32 _cond = 0;
		uint32 _have = 0;
		uint32 _cont = 1;
		int _acts = 0;
		uint32 _nacts;
		int _keys = 0;
		int _ckeys = 0;
		int _cpc;
		while ( _cont == 1  )
		{
			if ( cs == 0  )
			_cont = 0;
			
			_have = 0;
			if ( p == pe  )
			{
				if ( _have == 0  )
				_cont = 0;
				
				
			}
			
			if ( _cont == 1  )
			{
				if ( _have == 0  )
				{
					_keys = _next2_key_offsets[cs];
					_trans = uint32  ( _next2_index_offsets[cs] );
					_have = 0;
					_klen = int ( _next2_single_lengths[cs] );
					if ( _klen > 0  )
					{
						int _lower = 0;
						int _mid = 0;
						int _upper = 0;
						_lower = _keys;
						_upper = _keys + _klen - 1;
						while ( _upper >= _lower && _have == 0  )
						{
							_mid = _lower + ((_upper-_lower)>> 1);
							if ( (data[p ])< _next2_trans_keys[_mid ] )
							_upper = _mid - 1;
							
							else if ( (data[p ])> _next2_trans_keys[_mid ] )
							_lower = _mid + 1;
							
							else
							{
								_trans += uint32  ( (_mid - _keys) );
								_have = 1;
								
							}
							
							
						}
						
						if ( _have == 0  )
						{
							_keys += _klen;
							_trans += uint32  ( _klen );
							
						}
						
						
					}
					
					if ( _have == 0  )
					{
						_klen = int ( _next2_range_lengths[cs] );
						if ( _klen > 0  )
						{
							int _lower = 0;
							int _mid = 0;
							int _upper = 0;
							_lower = _keys;
							_upper = _keys + (_klen<<1)- 2;
							while ( _have == 0 && _lower <= _upper  )
							{
								_mid = _lower + (((_upper-_lower)>> 1)& ~1);
								if ( (data[p ])< _next2_trans_keys[_mid ] )
								_upper = _mid - 2;
								
								else if ( (data[p ])> _next2_trans_keys[_mid + 1 ] )
								_lower = _mid + 2;
								
								else
								{
									_trans += uint32  ( ((_mid - _keys)>>1) );
									_have = 1;
									
								}
								
								
							}
							
							if ( _have == 0  )
							_trans += uint32  ( _klen );
							
							
						}
						
						
					}
					
					_ckeys = _next2_trans_offsets[_trans];
					_klen = int ( _next2_trans_lengths[_trans] );
					_cond = uint32  ( _next2_trans_offsets[_trans] );
					_have = 0;
					_cpc = 0;
					if ( 1 ) {
						int _lower = 0;
						int _mid = 0;
						int _upper = 0;
						_lower = _ckeys;
						_upper = _ckeys + _klen - 1;
						while ( _have == 0 && _lower <= _upper  )
						{
							_mid = _lower + ((_upper-_lower)>> 1);
							if ( _cpc < int ( _next2_cond_keys[_mid ] ) )
							_upper = _mid - 1;
							
							else if ( _cpc > int ( _next2_cond_keys[_mid ] ) )
							_lower = _mid + 1;
							
							else
							{
								_cond += uint32  ( (_mid - _ckeys) );
								_have = 1;
								
							}
							
							
						}
						
						if ( _have == 0  )
						{
							cs = 0;
							_cont = 0;
							
						}
						
						
					}
					
				}
				
				if ( _cont == 1  )
				{
					cs = int ( _next2_cond_targs[_cond] );
					if ( _next2_cond_actions[_cond]!= 0  )
					{
						_acts = _next2_cond_actions[_cond];
						_nacts = uint32  ( _next2_actions[_acts ] );
						_acts += 1;
						while ( _nacts > 0  )
						{
							if ( _next2_actions[_acts ] == 0  ) {
								if ( 1 ) {
									cout.format( "one\n" );
									target = 19;
									if ( 1 ) {
										cs = (target);
										
									}
									
								}
								
							}
							else if ( _next2_actions[_acts ] == 1  ) {
								if ( 1 ) {
									cout.format( "two\n" );
									target = 19;
									if ( 1 ) {
										cs = (target);
										
									}
									
								}
								
							}
							else if ( _next2_actions[_acts ] == 2  ) {
								if ( 1 ) {
									cout.format( "three\n" );
									target = 19;
									if ( 1 ) {
										cs = (target);
										
									}
									
								}
								
							}
							else if ( _next2_actions[_acts ] == 3  ) {
								if ( 1 ) {
									target = 8;
									if ( 1 ) {
										cs = (target);
										
									}
									last = 1;
									
								}
								
							}
							else if ( _next2_actions[_acts ] == 4  ) {
								if ( 1 ) {
									target = 11;
									if ( 1 ) {
										cs = (target);
										
									}
									last = 2;
									
								}
								
							}
							else if ( _next2_actions[_acts ] == 5  ) {
								if ( 1 ) {
									if ( last == 2 )
									{
										target = 14;
										if ( 1 ) {
											cs = (target);
											
										}
										
									} 
									last = 3;
									
								}
								
							}
							;
							_nacts -= 1;
							_acts += 1;
							
						}
						
						
					}
					
					if ( cs == 0  )
					_cont = 0;
					
					if ( _cont == 1  )
					p += 1;
					
					
				}
				
				
			}
			
			
		}
		
		
	}
	if ( cs >= next2_first_final ) {
		cout `ACCEPT\n`;
	}
	else {
		cout `FAIL\n`;
	}
}

void main()
{
	m( "1one3x2two3three\n" );
}

main();
