#
# @LANG: ruby
# @GENERATED: true
#






class << self
	attr_accessor :_next1_trans_keys 
	private :_next1_trans_keys, :_next1_trans_keys=
end
self._next1_trans_keys = [
1, 0, 0, 3, 10, 10, 6, 6, 10, 10, 8, 8, 5, 5, 4, 4, 7, 7, 6, 6, 5, 5, 9, 9, 11, 11, 7, 7, 1, 0, 1, 0, 1, 0, 1, 0, 0 , 
]

class << self
	attr_accessor :_next1_char_class 
	private :_next1_char_class, :_next1_char_class=
end
self._next1_char_class = [
0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 5, 1, 1, 1, 1, 1, 1, 1, 1, 6, 7, 1, 1, 1, 8, 9, 10, 1, 11, 0 , 
]

class << self
	attr_accessor :_next1_index_offsets 
	private :_next1_index_offsets, :_next1_index_offsets=
end
self._next1_index_offsets = [
0, 0, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 16, 16, 16, 0 , 
]

class << self
	attr_accessor :_next1_indicies 
	private :_next1_indicies, :_next1_indicies=
end
self._next1_indicies = [
0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0 , 
]

class << self
	attr_accessor :_next1_index_defaults 
	private :_next1_index_defaults, :_next1_index_defaults=
end
self._next1_index_defaults = [
0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0 , 
]

class << self
	attr_accessor :_next1_trans_cond_spaces 
	private :_next1_trans_cond_spaces, :_next1_trans_cond_spaces=
end
self._next1_trans_cond_spaces = [
-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0 , 
]

class << self
	attr_accessor :_next1_cond_targs 
	private :_next1_cond_targs, :_next1_cond_targs=
end
self._next1_cond_targs = [
14, 0, 14, 14, 3, 4, 5, 6, 7, 15, 9, 10, 16, 12, 13, 17, 0 , 
]

class << self
	attr_accessor :_next1_cond_actions 
	private :_next1_cond_actions, :_next1_cond_actions=
end
self._next1_cond_actions = [
0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 4, 0 , 
]

class << self
	attr_accessor :_next1_nfa_targs 
	private :_next1_nfa_targs, :_next1_nfa_targs=
end
self._next1_nfa_targs = [
0, 0 , 
]

class << self
	attr_accessor :_next1_nfa_offsets 
	private :_next1_nfa_offsets, :_next1_nfa_offsets=
end
self._next1_nfa_offsets = [
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 , 
]

class << self
	attr_accessor :_next1_nfa_push_actions 
	private :_next1_nfa_push_actions, :_next1_nfa_push_actions=
end
self._next1_nfa_push_actions = [
0, 0 , 
]

class << self
	attr_accessor :_next1_nfa_pop_trans 
	private :_next1_nfa_pop_trans, :_next1_nfa_pop_trans=
end
self._next1_nfa_pop_trans = [
0, 0 , 
]

class << self
	attr_accessor :next1_start 
end
self.next1_start  = 1;

class << self
	attr_accessor :next1_first_final 
end
self.next1_first_final  = 14;

class << self
	attr_accessor :next1_error 
end
self.next1_error  = 0;

class << self
	attr_accessor :next1_en_unused 
end
self.next1_en_unused  = 2;

class << self
	attr_accessor :next1_en_one 
end
self.next1_en_one  = 8;

class << self
	attr_accessor :next1_en_two 
end
self.next1_en_two  = 11;

class << self
	attr_accessor :next1_en_main 
end
self.next1_en_main  = 1;

def run_machine( data )
	p = 0
	pe = data.length
	eof = data.length
	cs = 0;
	_m = 
	_a = 
	buffer = Array.new
	blen = 0
	target = 1
	begin
		cs = next1_start;
		
	end
	begin
		_trans = 0;
		_have = 0;
		_cont = 1;
		_keys = 0;
		_inds = 0;
		while ( _cont == 1  )
			begin
				if ( cs == 0  )
					_cont = 0;
					
				end
				_have = 0;
				if ( p == pe  )
					begin
						if ( _have == 0  )
							_cont = 0;
							
						end
						
					end
					
				end
				if ( _cont == 1  )
					begin
						if ( _have == 0  )
							begin
								_keys = (cs<<1) ;
								_inds = _next1_index_offsets[cs] ;
								if ( ( data[p ].ord) <= 119 && ( data[p ].ord) >= 10  )
									begin
										_ic = _next1_char_class[( data[p ].ord) - 10];
										if ( _ic <= _next1_trans_keys[_keys+1 ]&& _ic >= _next1_trans_keys[_keys ] )
											_trans = _next1_indicies[_inds + ( _ic - _next1_trans_keys[_keys ])  ];
											
											else
											_trans = _next1_index_defaults[cs];
											
										end
										
									end
									
									else
									begin
										_trans = _next1_index_defaults[cs];
										
									end
									
								end
								
							end
							
						end
						if ( _cont == 1  )
							begin
								cs = _next1_cond_targs[_trans];
								case  _next1_cond_actions[_trans]  
								when -2 then
								begin
								end
								when 3  then
								begin
									begin
										print( "one\n" );
										target = 1;
										begin
											cs = (target);
											
										end
										
									end
									
								end
								when 4  then
								begin
									begin
										print( "two\n" );
										target = 1;
										begin
											cs = (target);
											
										end
										
									end
									
								end
								when 1  then
								begin
									begin
										target = 8;
										begin
											cs = (target);
											
										end
										
									end
									
								end
								when 2  then
								begin
									begin
										target = 11;
										begin
											cs = (target);
											
										end
										
									end
									
									
								end
							end
							if ( cs == 0  )
								_cont = 0;
								
							end
							if ( _cont == 1  )
								p += 1;
								
							end
							
						end
						
					end
					
				end
				
			end
			
		end
		
	end
	
end
if cs >= next1_first_final
	puts "ACCEPT"
	else
	puts "FAIL"
end
end
	
	inp = [
	"1one2two1one\n",
	]
	
	inplen = 1
	
	inp.each { |str| run_machine(str) }
	
