static mut comm : u8 = 0;
static mut top : i32 = 0;
static mut stack : [ i32 ; 32] = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ];
static mut ts : i32
= 0;
static mut te : i32
= 0;
static mut act : i32 = 0;
static mut value : i32 = 0;





static _patact_key_offsets: [i8 ; 31] = [ 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 25, 28, 32, 35, 41, 43, 45, 53, 56, 60, 63, 0 , 0 ];
static _patact_trans_keys: [u8 ; 66] = [ 102, 111, 105, 108, 102, 111, 105, 108, 102, 111, 105, 108, 102, 111, 105, 108, 10, 32, 33, 50, 59, 48, 57, 97, 122, 32, 48, 57, 32, 50, 48, 57, 32, 97, 122, 10, 32, 48, 57, 97, 122, 48, 57, 97, 122, 10, 32, 33, 50, 48, 57, 97, 122, 32, 48, 57, 32, 50, 48, 57, 32, 97, 122, 59, 0 , 0 ];
static _patact_single_lengths: [i8 ; 31] = [ 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 5, 1, 2, 1, 2, 0, 0, 4, 1, 2, 1, 1, 0 , 0 ];
static _patact_range_lengths: [i8 ; 31] = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 0, 0 , 0 ];
static _patact_index_offsets: [i8 ; 31] = [ 0, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 40, 43, 47, 50, 55, 57, 59, 66, 69, 73, 76, 0 , 0 ];
static _patact_trans_cond_spaces: [i8 ; 104] = [ -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0 , 0 ];
static _patact_trans_offsets: [i8 ; 104] = [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 0 , 0 ];
static _patact_trans_lengths: [i8 ; 104] = [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0 , 0 ];
static _patact_cond_keys: [i8 ; 104] = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 , 0 ];
static _patact_cond_targs: [i8 ; 104] = [ 2, 17, 3, 17, 4, 17, 17, 17, 6, 17, 7, 17, 8, 17, 17, 17, 10, 24, 11, 24, 12, 24, 24, 24, 14, 24, 15, 24, 16, 24, 24, 24, 17, 17, 17, 19, 17, 18, 20, 0, 1, 18, 17, 1, 18, 18, 17, 5, 20, 17, 21, 21, 22, 23, 0, 22, 21, 23, 21, 24, 24, 24, 26, 25, 27, 0, 9, 25, 24, 9, 25, 25, 24, 13, 27, 24, 28, 0, 17, 17, 17, 17, 17, 17, 17, 17, 24, 24, 24, 24, 24, 24, 24, 24, 17, 17, 17, 21, 21, 24, 24, 24, 0 , 0 ];
static _patact_cond_actions: [i8 ; 104] = [ 0, 1, 0, 1, 0, 1, 2, 1, 0, 3, 0, 3, 0, 3, 4, 3, 0, 5, 0, 5, 0, 5, 6, 5, 0, 7, 0, 7, 0, 7, 8, 7, 11, 11, 12, 13, 14, 13, 15, 0, 0, 13, 1, 0, 17, 13, 16, 0, 15, 18, 19, 19, 0, 0, 0, 0, 20, 0, 21, 22, 22, 23, 24, 24, 15, 0, 0, 24, 5, 0, 26, 24, 25, 0, 15, 27, 28, 0, 1, 1, 1, 1, 3, 3, 3, 3, 5, 5, 5, 5, 7, 7, 7, 7, 1, 16, 18, 20, 21, 5, 25, 27, 0 , 0 ];
static _patact_to_state_actions: [i8 ; 31] = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 9, 0, 0, 9, 0, 0, 0, 9, 0 , 0 ];
static _patact_from_state_actions: [i8 ; 31] = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 0, 0, 0, 10, 0, 0, 10, 0, 0, 0, 10, 0 , 0 ];
static _patact_eof_trans_indexed: [i8 ; 31] = [ 0, 18, 18, 18, 18, 20, 20, 20, 20, 36, 36, 36, 36, 38, 38, 38, 38, 0, 18, 25, 26, 0, 32, 33, 0, 36, 42, 43, 0, 0 , 0 ];
static _patact_eof_trans_direct: [i8 ; 31] = [ 0, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 0, 95, 96, 97, 0, 98, 99, 0, 100, 101, 102, 0, 0 , 0 ];
static _patact_nfa_targs: [i8 ; 3] = [ 0, 0 , 0 ];
static _patact_nfa_offsets: [i8 ; 31] = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 , 0 ];
static _patact_nfa_push_actions: [i8 ; 3] = [ 0, 0 , 0 ];
static _patact_nfa_pop_trans: [i8 ; 3] = [ 0, 0 , 0 ];
static patact_start : i32 = 17;
static patact_first_final : i32 = 17;
static patact_error : i32 = 0;
static patact_en_other : i32 = 21;
static patact_en_exec_test : i32 = 24;
static patact_en_semi : i32 = 28;
static patact_en_main : i32 = 17;
unsafe fn m( s: String )
{
	let data: &[u8] = s.as_bytes();
	let mut p:i32 = 0;
	let mut pe:i32 = s.len() as i32;
	let mut eof:i32 = s.len() as i32;
	let mut cs: i32 = 0;
	let mut buffer = String::new();
	
	
	{
		cs = ( patact_start ) as i32;
		ts = 0;
		te = 0;
		act = 0;
	}
	
	{
		let mut _klen = 0;
		let mut _keys :i32 = 0;
		let mut _ckeys :i32 = 0;
		let mut _cpc = 0;
		let mut _trans = 0;
		let mut _cond  = 0;
		let mut _have  = 0;
		let mut _cont  = 1;
		while ( _cont == 1  )
		{
		
			if ( cs == 0  ) {
				_cont = 0;
				
			}
			_have = 0;
			if ( p == pe  ) {
				{
					if ( p == eof  ) {
						{
							if ( _patact_eof_trans_direct[(cs) as usize]> 0  ) {
								{
									_trans = ( _patact_eof_trans_direct[(cs) as usize] ) as u32- 1;
									_cond = ( _patact_trans_offsets[(_trans) as usize] ) as u32;
									_have = 1;
								}
								
							}
							if ( _have == 0  ) {
								{
								}
								
							}
						}
						
						
					}
					if ( _have == 0  ) {
						_cont = 0;
						
					}
				}
				
			}
			if ( _cont == 1  ) {
				{
					if ( _have == 0  ) {
						{
							match ( _patact_from_state_actions[(cs) as usize] ) {
								10  => {
									{{ts = p;
										}}
									
								}
								
								_ => {}
							}
							_keys = ( _patact_key_offsets[(cs) as usize] ) as i32;
							_trans = ( _patact_index_offsets[(cs) as usize] ) as u32;
							_have = 0;
							_klen = ( _patact_single_lengths[(cs) as usize] ) as i32;
							if ( _klen > 0  ) {
								{
									let mut _lower :i32 = 0;
									let mut _mid :i32 = 0;
									let mut _upper :i32 = 0;
									_lower = _keys;
									_upper = _keys + _klen - 1;
									while ( _upper >= _lower && _have == 0  )
									{
										_mid = _lower + ((_upper-_lower) >> 1);
										if ( ( data[(p ) as usize]
										) < _patact_trans_keys[(_mid ) as usize]
										) {
											_upper = _mid - 1;
											
										}
										else if ( ( data[(p ) as usize]
										) > _patact_trans_keys[(_mid ) as usize]
										) {
											_lower = _mid + 1;
											
										}
										else {
											{
												_trans += ( (_mid - _keys) ) as u32;
												_have = 1;
											}
											
										}
									}
									
									if ( _have == 0  ) {
										{
											_keys += _klen;
											_trans += ( _klen ) as u32;
										}
										
									}
								}
								
								
							}
							if ( _have == 0  ) {
								{
									_klen = ( _patact_range_lengths[(cs) as usize] ) as i32;
									if ( _klen > 0  ) {
										{
											let mut _lower :i32 = 0;
											let mut _mid :i32 = 0;
											let mut _upper :i32 = 0;
											_lower = _keys;
											_upper = _keys + (_klen<<1) - 2;
											while ( _have == 0 && _lower <= _upper  )
											{
												_mid = _lower + (((_upper-_lower) >> 1) & !1
												);
												if ( ( data[(p ) as usize]
												) < _patact_trans_keys[(_mid ) as usize]
												) {
													_upper = _mid - 2;
													
												}
												else if ( ( data[(p ) as usize]
												) > _patact_trans_keys[(_mid + 1 ) as usize]
												) {
													_lower = _mid + 2;
													
												}
												else {
													{
														_trans += ( ((_mid - _keys)>>1) ) as u32;
														_have = 1;
													}
													
												}
											}
											
											if ( _have == 0  ) {
												_trans += ( _klen ) as u32;
												
											}
										}
										
									}
								}
								
								
							}
							_ckeys = ( _patact_trans_offsets[(_trans) as usize] ) as i32;
							_klen = ( _patact_trans_lengths[(_trans) as usize] ) as i32;
							_cond = ( _patact_trans_offsets[(_trans) as usize] ) as u32;
							_have = 0;
							_cpc = 0;
							{
								let mut _lower :i32 = 0;
								let mut _mid :i32 = 0;
								let mut _upper :i32 = 0;
								_lower = _ckeys;
								_upper = _ckeys + _klen - 1;
								while ( _have == 0 && _lower <= _upper  )
								{
									_mid = _lower + ((_upper-_lower) >> 1);
									if ( _cpc < ( _patact_cond_keys[(_mid ) as usize]
									) as i32 ) {
										_upper = _mid - 1;
										
									}
									else if ( _cpc > ( _patact_cond_keys[(_mid ) as usize]
									) as i32 ) {
										_lower = _mid + 1;
										
									}
									else {
										{
											_cond += ( (_mid - _ckeys) ) as u32;
											_have = 1;
										}
										
									}
								}
								
								if ( _have == 0  ) {
									{
										cs = 0;
										_cont = 0;
									}
									
								}
							}
						}
						
					}
					if ( _cont == 1  ) {
						{
							cs = ( _patact_cond_targs[(_cond) as usize] ) as i32;
							match ( _patact_cond_actions[(_cond) as usize] ) {
								15  => {
									{{te = p+1;
										}}
									
								}
								19  => {
									{{te = p+1;
											{print!( "{}", "space\n" );
											}
										}}
									
								}
								21  => {
									{{te = p;
											p = p - 1;
											{print!( "{}", "word\n" );
											}
										}}
									
								}
								20  => {
									{{te = p;
											p = p - 1;
											{print!( "{}", "num\n" );
											}
										}}
									
								}
								8  => {
									{{te = p+1;
											{print!( "{}", "word (c/lbh)\n" );
											}
										}}
									
								}
								22  => {
									{{te = p+1;
											{print!( "{}", "space\n" );
											}
										}}
									
								}
								6  => {
									{{te = p+1;
											{print!( "{}", "num (c/switch)\n" );
											}
										}}
									
								}
								23  => {
									{{te = p+1;
										}}
									
								}
								27  => {
									{{te = p;
											p = p - 1;
											{print!( "{}", "word (w/lbh)\n" );
												{p = (( te-1))-1;
												}
												{cs = 21;
												}}
										}}
									
								}
								25  => {
									{{te = p;
											p = p - 1;
											{print!( "{}", "num (w/switch)\n" );
												{p = (( te-1))-1;
												}
												{cs = 21;
												}}
										}}
									
								}
								7  => {
									{{p = ((te))-1;
											{print!( "{}", "word (w/lbh)\n" );
												{p = (( te-1))-1;
												}
												{cs = 21;
												}}
										}}
									
								}
								5  => {
									{{match ( act  ) {
												7  => {
													p = ((te))-1;
													{print!( "{}", "num (w/switch)\n" );
													}
													
												}
												8  => {
													p = ((te))-1;
													{print!( "{}", "num (w/switch)\n" );
														{p = (( te-1))-1;
														}
														{cs = 21;
														}}
													
												}
												
												_ => {}
											}
										}
									}
									
								}
								28  => {
									{{te = p+1;
											{print!( "{}", "in semi\n" );
												{cs = 17;
												}}
										}}
									
								}
								4  => {
									{{te = p+1;
											{print!( "{}", "word (c/lbh)\n" );
											}
										}}
									
								}
								11  => {
									{{te = p+1;
											{print!( "{}", "space\n" );
											}
										}}
									
								}
								2  => {
									{{te = p+1;
											{print!( "{}", "num (c/switch)\n" );
											}
										}}
									
								}
								14  => {
									{{te = p+1;
											{print!( "{}", "going to semi\n" );
												{p = p - 1;
												}{cs = 28;
												}}
										}}
									
								}
								12  => {
									{{te = p+1;
											{print!( "{}", "immdiate\n" );
												{cs = 24;
												}}
										}}
									
								}
								18  => {
									{{te = p;
											p = p - 1;
											{print!( "{}", "word (w/lbh)\n" );
												{p = p - 1;
												}{cs = 21;
												}}
										}}
									
								}
								16  => {
									{{te = p;
											p = p - 1;
											{print!( "{}", "num (w/switch)\n" );
												{p = p - 1;
												}{cs = 21;
												}}
										}}
									
								}
								3  => {
									{{p = ((te))-1;
											{print!( "{}", "word (w/lbh)\n" );
												{p = p - 1;
												}{cs = 21;
												}}
										}}
									
								}
								1  => {
									{{match ( act  ) {
												15  => {
													p = ((te))-1;
													{print!( "{}", "num (w/switch)\n" );
													}
													
												}
												16  => {
													p = ((te))-1;
													{print!( "{}", "num (w/switch)\n" );
														{p = p - 1;
														}{cs = 21;
														}}
													
												}
												
												_ => {}
											}
										}
									}
									
								}
								26  => {
									{{te = p+1;
										}}
									{{act = 7;
										}}
									
								}
								24  => {
									{{te = p+1;
										}}
									{{act = 8;
										}}
									
								}
								17  => {
									{{te = p+1;
										}}
									{{act = 15;
										}}
									
								}
								13  => {
									{{te = p+1;
										}}
									{{act = 16;
										}}
									
								}
								
								_ => {}
							}
							match ( _patact_to_state_actions[(cs) as usize] ) {
								9  => {
									{{ts = 0;
										}}
									
								}
								
								_ => {}
							}
							if ( cs == 0  ) {
								_cont = 0;
								
							}
							if ( _cont == 1  ) {
								p += 1;
								
							}
						}
					}
				}
				
			}
		}
		
	}
	if ( cs >= patact_first_final ) {
		println!( "ACCEPT" );
	}
	else {
		println!( "FAIL" );
	}
}

fn main()
{
	unsafe { m( "abcd foix\n".to_string() ); }
	unsafe { m( "abcd\nanother\n".to_string() ); }
	unsafe { m( "123 foix\n".to_string() ); }
	unsafe { m( "!abcd foix\n".to_string() ); }
	unsafe { m( "!abcd\nanother\n".to_string() ); }
	unsafe { m( "!123 foix\n".to_string() ); }
	unsafe { m( ";".to_string() ); }
}

