#include <string.h>
#include <stdio.h>







static const char  _rangei_trans_keys [] = { 1, 0, 1, 2, 1, 2, 0, 3, 1, 5, 1, 4, 0, 5, 1, 0, 0 ,  };
static const char  _rangei_char_class [] = { 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 3, 3, 3, 4, 4, 4, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 5, 5, 5, 0 ,  };
static const char  _rangei_index_offsets [] = { 0, 0, 2, 4, 8, 13, 17, 23, 0 ,  };
static const char  _rangei_indicies [] = { 0, 0, 2, 2, 3, 3, 3, 3, 4, 4, 1, 4, 4, 5, 1, 5, 5, 6, 6, 6, 6, 6, 6, 0 ,  };
static const char  _rangei_index_defaults [] = { 0, 1, 1, 1, 1, 1, 1, 1, 0 ,  };
static const char  _rangei_trans_cond_spaces [] = { -1, -1, -1, -1, -1, -1, -1, 0 ,  };
static const char  _rangei_cond_targs [] = { 2, 0, 3, 4, 5, 6, 7, 0 ,  };
static const char  _rangei_cond_actions [] = { 0, 0, 0, 0, 0, 0, 0, 0 ,  };
static const char  _rangei_nfa_targs [] = { 0, 0 ,  };
static const char  _rangei_nfa_offsets [] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  };
static const char  _rangei_nfa_push_actions [] = { 0, 0 ,  };
static const char  _rangei_nfa_pop_trans [] = { 0, 0 ,  };
static const int  rangei_start  = 1;
static const int  rangei_first_final  = 7;
static const int  rangei_error  = 0;
static const int  rangei_en_main  = 1;
int cs;
int blen;
char buffer[1024];

void init()
{

	{
		cs = ( int ) rangei_start;
	}
}

void exec( char *data, int len )
{
	char *p = data;
	char *pe = data + len;
	
	{
		unsigned int _trans = 0;
		unsigned int _have = 0;
		unsigned int _cont = 1;
		const char  *_keys;
		const char  *_inds;
		while ( _cont == 1  )
		{
		
			if ( cs == 0  )
			_cont = 0;
			
			_have = 0;
			if ( p == pe  )
			{
				if ( _have == 0  )
				_cont = 0;
				
			}
			
			if ( _cont == 1  )
			{
				if ( _have == 0  )
				{
					_keys = _rangei_trans_keys + (cs<<1);
					_inds = _rangei_indicies + _rangei_index_offsets[cs];
					if ( ((*( p  ))
					)<= 125 && ((*( p  ))
					)>= 60  )
					{
						int _ic = ( int ) _rangei_char_class[( int ) ((*( p  ))
						)- 60];
						if ( _ic <= ( int ) (*( _keys+1  ))
						&& _ic >= ( int ) (*( _keys  ))
						)
						_trans = ( unsigned int  ) (*( _inds + ( int ) (_ic - ( int ) (*( _keys  ))
						) ))
						;
						
						else
						_trans = ( unsigned int  ) _rangei_index_defaults[cs];
						
					}
					
					else
					{
						_trans = ( unsigned int  ) _rangei_index_defaults[cs];
					}
					
					
				}
				
				if ( _cont == 1  )
				{
					cs = ( int ) _rangei_cond_targs[_trans];
					if ( cs == 0  )
					_cont = 0;
					
					if ( _cont == 1  )
					p += 1;
					
				}
			}
			
		}
		
	}
}

void finish( )
{
	if ( cs >= rangei_first_final )
	printf( "ACCEPT\n" );
	else
	printf( "FAIL\n" );
}

char *inp[] = {
	"AaBbAa",
	"Aa`bAa",
	"AaB@Aa",
	"AaBbMa",
	"AaBbma",
};

int inplen = 5;

int main( )
{
	int i;
	for ( i = 0; i < inplen; i++ ) {
		init();
		exec( inp[i], strlen(inp[i]) );
		finish();
	}
	return 0;
}

