#include <stdio.h>
#include <string.h>

struct range
{
	int cs;
};



static const char  _range_trans_keys [] = { 1, 0, 2, 2, 0, 0, 1, 0, 0 ,  };
static const char  _range_char_class [] = { 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0 ,  };
static const char  _range_index_offsets [] = { 0, 0, 1, 2, 0 ,  };
static const char  _range_indicies [] = { 0, 2, 0 ,  };
static const char  _range_index_defaults [] = { 0, 1, 1, 1, 0 ,  };
static const char  _range_trans_cond_spaces [] = { -1, -1, -1, 0 ,  };
static const char  _range_cond_targs [] = { 2, 0, 3, 0 ,  };
static const char  _range_cond_actions [] = { 0, 0, 0, 0 ,  };
static const char  _range_nfa_targs [] = { 0, 0 ,  };
static const char  _range_nfa_offsets [] = { 0, 0, 0, 0, 0 ,  };
static const char  _range_nfa_push_actions [] = { 0, 0 ,  };
static const char  _range_nfa_pop_trans [] = { 0, 0 ,  };
static const int  range_start  = 1;
static const int  range_first_final  = 3;
static const int  range_error  = 0;
static const int  range_en_main  = 1;
void range_init( struct range *fsm )
{

	{
		(fsm->cs) = ( int ) range_start;
	}
}

void range_execute( struct range *fsm, const char *_data, int _len )
{
	const char *p = _data;
	const char *pe = _data+_len;
	
	
	{
		unsigned int _trans = 0;
		unsigned int _have = 0;
		unsigned int _cont = 1;
		const char  *_keys;
		const char  *_inds;
		while ( _cont == 1  )
		{
		
			if ( (fsm->cs) == 0  )
			_cont = 0;
			
			_have = 0;
			if ( p == pe  )
			{
				if ( _have == 0  )
				_cont = 0;
				
			}
			
			if ( _cont == 1  )
			{
				if ( _have == 0  )
				{
					_keys = _range_trans_keys + ((fsm->cs)<<1);
					_inds = _range_indicies + _range_index_offsets[(fsm->cs)];
					if ( ((*( p  ))
					)<= 122 && ((*( p  ))
					)>= 10  )
					{
						int _ic = ( int ) _range_char_class[( int ) ((*( p  ))
						)- 10];
						if ( _ic <= ( int ) (*( _keys+1  ))
						&& _ic >= ( int ) (*( _keys  ))
						)
						_trans = ( unsigned int  ) (*( _inds + ( int ) (_ic - ( int ) (*( _keys  ))
						) ))
						;
						
						else
						_trans = ( unsigned int  ) _range_index_defaults[(fsm->cs)];
						
					}
					
					else
					{
						_trans = ( unsigned int  ) _range_index_defaults[(fsm->cs)];
					}
					
					
				}
				
				if ( _cont == 1  )
				{
					(fsm->cs) = ( int ) _range_cond_targs[_trans];
					if ( (fsm->cs) == 0  )
					_cont = 0;
					
					if ( _cont == 1  )
					p += 1;
					
				}
			}
			
		}
		
	}
}

int range_finish( struct range *fsm )
{
	if ( fsm->cs == range_error )
	return -1;
	if ( fsm->cs >= range_first_final )
	return 1;
	return 0;
}

struct range fsm;

void test( char *buf )
{
	int len = strlen( buf );
	range_init( &fsm );
	range_execute( &fsm, buf, len );
	if ( range_finish( &fsm ) > 0 )
	printf("ACCEPT\n");
	else
	printf("FAIL\n");
}

int main()
{
	test( "a\n" );
	test( "z\n" );
	test( "g\n" );
	test( "no\n" );
	test( "1\n" );
	
	return 0;
}

