#include <string.h>
#include <stdio.h>







static const int  rangei_start  = 1;
static const int  rangei_first_final  = 7;
static const int  rangei_error  = 0;
static const int  rangei_en_main  = 1;
static const char  _rangei_nfa_targs [] = { 0, 0 ,  };
static const char  _rangei_nfa_offsets [] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  };
static const char  _rangei_nfa_push_actions [] = { 0, 0 ,  };
static const char  _rangei_nfa_pop_trans [] = { 0, 0 ,  };
int cs;
int blen;
char buffer[1024];

void init()
{

	{
		cs = ( int ) rangei_start;
	}
}

void exec( char *data, int len )
{
	char *p = data;
	char *pe = data + len;
	
	{
		if ( p == pe  )
		goto _test_eof;
		
		switch ( cs  ) {
			case 1:
			goto st_case_1;
			case 0:
			goto st_case_0;
			case 2:
			goto st_case_2;
			case 3:
			goto st_case_3;
			case 4:
			goto st_case_4;
			case 5:
			goto st_case_5;
			case 6:
			goto st_case_6;
			case 7:
			goto st_case_7;
			
		}
		goto st_out;
		st_case_1:
		if ( ((*( p  ))
		)> 90  )
		{
			if ( 97 <= ((*( p  ))
			)&& ((*( p  ))
			)<= 122  )
			{
				goto st2;
			}
			
		} 
		else if ( ((*( p  ))
		)>= 65  )
		{
			goto st2;
		}
		
		{
			goto st0;
		}
		st_case_0:
		st0:
		cs = 0;
		goto _out;
		st2:
		p+= 1;
		if ( p == pe  )
		goto _test_eof2;
		
		st_case_2:
		if ( ((*( p  ))
		)> 90  )
		{
			if ( 97 <= ((*( p  ))
			)&& ((*( p  ))
			)<= 122  )
			{
				goto st3;
			}
			
		} 
		else if ( ((*( p  ))
		)>= 65  )
		{
			goto st3;
		}
		
		{
			goto st0;
		}
		st3:
		p+= 1;
		if ( p == pe  )
		goto _test_eof3;
		
		st_case_3:
		if ( ((*( p  ))
		)> 93  )
		{
			if ( 97 <= ((*( p  ))
			)&& ((*( p  ))
			)<= 122  )
			{
				goto st4;
			}
			
		} 
		else if ( ((*( p  ))
		)>= 60  )
		{
			goto st4;
		}
		
		{
			goto st0;
		}
		st4:
		p+= 1;
		if ( p == pe  )
		goto _test_eof4;
		
		st_case_4:
		if ( ((*( p  ))
		)> 90  )
		{
			if ( 94 <= ((*( p  ))
			)&& ((*( p  ))
			)<= 125  )
			{
				goto st5;
			}
			
		} 
		else if ( ((*( p  ))
		)>= 65  )
		{
			goto st5;
		}
		
		{
			goto st0;
		}
		st5:
		p+= 1;
		if ( p == pe  )
		goto _test_eof5;
		
		st_case_5:
		if ( ((*( p  ))
		)< 86  )
		{
			if ( 65 <= ((*( p  ))
			)&& ((*( p  ))
			)<= 69  )
			{
				goto st6;
			}
			
		} 
		else if ( ((*( p  ))
		)> 101  )
		{
			if ( 118 <= ((*( p  ))
			)&& ((*( p  ))
			)<= 122  )
			{
				goto st6;
			}
			
		} 
		else
		{
			goto st6;
		}
		
		{
			goto st0;
		}
		st6:
		p+= 1;
		if ( p == pe  )
		goto _test_eof6;
		
		st_case_6:
		if ( 60 <= ((*( p  ))
		)&& ((*( p  ))
		)<= 125  )
		{
			goto st7;
		}
		
		{
			goto st0;
		}
		st7:
		p+= 1;
		if ( p == pe  )
		goto _test_eof7;
		
		st_case_7:
		{
			goto st0;
		}
		st_out:
		_test_eof2: cs = 2;
		goto _test_eof; 
		_test_eof3: cs = 3;
		goto _test_eof; 
		_test_eof4: cs = 4;
		goto _test_eof; 
		_test_eof5: cs = 5;
		goto _test_eof; 
		_test_eof6: cs = 6;
		goto _test_eof; 
		_test_eof7: cs = 7;
		goto _test_eof; 
		
		_test_eof: {}
		_out: {}
	}
}

void finish( )
{
	if ( cs >= rangei_first_final )
	printf( "ACCEPT\n" );
	else
	printf( "FAIL\n" );
}

char *inp[] = {
	"AaBbAa",
	"Aa`bAa",
	"AaB@Aa",
	"AaBbMa",
	"AaBbma",
};

int inplen = 5;

int main( )
{
	int i;
	for ( i = 0; i < inplen; i++ ) {
		init();
		exec( inp[i], strlen(inp[i]) );
		finish();
	}
	return 0;
}

