(*
* @LANG: ocaml
*)

let id x = x
let fail fmt = Printf.ksprintf failwith fmt
let pr fmt = Printf.ksprintf print_endline fmt

let failed fmt = Printf.ksprintf (fun s -> prerr_endline s; exit 1) fmt
let test' show f x y = if f x <> y then failed "FAILED: test %S" (show x)
let case = ref 0
let test f x y = incr case; if f x <> y then failed "FAILED: case %d" !case
let error f x = match try Some (f x) with _ -> None with Some _ -> failed "FAILED: fail %S" x | None -> ()

(*
// -*-go-*-
//
// Reverse Polish Notation Calculator
// Copyright (c) 2010 J.A. Roberts Tunney
// MIT License
//
// To compile:
//
//   ragel -Z -G2 -o rpn.go rpn.rl
//   6g -o rpn.6 rpn.go
//   6l -o rpn rpn.6
//   ./rpn
//
// To show a diagram of your state machine:
//
//   ragel -V -G2 -p -o rpn.dot rpn.rl
//   dot -Tpng -o rpn.png rpn.dot
//   chrome rpn.png
//
*)


let _rpn_actions : int array = [|
0; 1; 0; 1; 1; 1; 2; 1; 3; 1; 4; 1; 5; 1; 6; 1; 7; 0 ; 
|]
let _rpn_key_offsets : int array = [|
0; 0; 3; 8; 10; 12; 13; 16; 19; 20; 23; 0 ; 
|]
let _rpn_trans_keys : int array = [|
32; 9; 13; 32; 9; 13; 48; 57; 98; 100; 98; 115; 97; 32; 9; 13; 32; 9; 13; 100; 32; 9; 13; 32; 42; 43; 45; 47; 97; 9; 13; 48; 57; 0 ; 
|]
let _rpn_single_lengths : int array = [|
0; 1; 1; 2; 2; 1; 1; 1; 1; 1; 6; 0 ; 
|]
let _rpn_range_lengths : int array = [|
0; 1; 2; 0; 0; 0; 1; 1; 0; 1; 2; 0 ; 
|]
let _rpn_index_offsets : int array = [|
0; 0; 3; 7; 10; 13; 15; 18; 21; 23; 26; 0 ; 
|]
let _rpn_trans_cond_spaces : int array = [|
-1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; 0 ; 
|]
let _rpn_trans_offsets : int array = [|
0; 1; 2; 3; 4; 5; 6; 7; 8; 9; 10; 11; 12; 13; 14; 15; 16; 17; 18; 19; 20; 21; 22; 23; 24; 25; 26; 27; 28; 29; 30; 31; 32; 33; 34; 0 ; 
|]
let _rpn_trans_lengths : int array = [|
1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 0 ; 
|]
let _rpn_cond_keys : int array = [|
0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0 ; 
|]
let _rpn_cond_targs : int array = [|
10; 10; 0; 10; 10; 2; 0; 4; 8; 0; 5; 7; 0; 6; 0; 10; 10; 0; 10; 10; 0; 9; 0; 10; 10; 0; 10; 1; 1; 1; 1; 3; 10; 2; 0; 0 ; 
|]
let _rpn_cond_actions : int array = [|
0; 0; 0; 3; 3; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 15; 15; 0; 13; 13; 0; 0; 0; 5; 5; 0; 0; 9; 5; 7; 11; 0; 0; 1; 0; 0 ; 
|]
let _rpn_nfa_targs : int array = [|
0; 0 ; 
|]
let _rpn_nfa_offsets : int array = [|
0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0 ; 
|]
let _rpn_nfa_push_actions : int array = [|
0; 0 ; 
|]
let _rpn_nfa_pop_trans : int array = [|
0; 0 ; 
|]
let rpn_start  : int  = 10
let rpn_first_final  : int  = 10
let rpn_error  : int  = 0
let rpn_en_main  : int  = 10
let fail fmt = Printf.ksprintf failwith fmt

let rpn data =
let (cs, p, pe) = (ref 0, ref 0, ref (String.length data)) in
let mark = ref 0 in
let st = Stack.create () in

begin
	cs  := rpn_start;
	
end;
begin
	let _klen : int  ref = ref 0 in
	let _trans  : int  ref = ref 0 in
	let _cond  : int  ref = ref 0 in
	let _have  : int  ref = ref 0 in
	let _cont  : int  ref = ref 1 in
	let _acts : int ref = ref 0 in
	let _nacts : int  ref = ref 0 in
	let _keys : int ref = ref 0 in
	let _ckeys : int ref = ref 0 in
	let _cpc : int  ref = ref 0 in
	while _cont.contents= 1  do
	begin
		if cs.contents= 0  then
		begin
			_cont  := 0;
			
		end
		;_have  := 0;
		if p.contents= pe.contents then
		begin
			begin
				if _have.contents= 0  then
				begin
					_cont  := 0;
					
				end
				;
			end;
			
		end
		;if _cont.contents= 1  then
		begin
			begin
				if _have.contents= 0  then
				begin
					begin
						_keys  := _rpn_key_offsets.(cs.contents);
						_trans  := _rpn_index_offsets.(cs.contents);
						_have  := 0;
						_klen  := _rpn_single_lengths.(cs.contents);
						if _klen.contents> 0  then
						begin
							begin
								let _lower : int ref = ref 0 in
								let _mid : int ref = ref 0 in
								let _upper : int ref = ref 0 in
								_lower  := _keys.contents;
								_upper  := _keys.contents+ _klen.contents- 1;
								while _upper.contents>= _lower.contents&& _have.contents= 0  do
								begin
									_mid  := _lower.contents+ ( ( _upper.contents-_lower.contents ) asr 1 );
									if ( Char.code data.[p.contents] )< _rpn_trans_keys.( _mid.contents ) then
									begin
										_upper  := _mid.contents- 1;
										
									end
									else if ( Char.code data.[p.contents] )> _rpn_trans_keys.( _mid.contents ) then
									begin
										_lower  := _mid.contents+ 1;
										
									end
									else
									begin
										begin
											_trans  := _trans.contents + ( _mid.contents- _keys.contents );
											_have  := 1;
											
										end;
										
									end
									;
								end;
								
								done;
								if _have.contents= 0  then
								begin
									begin
										_keys  := _keys.contents + _klen.contents;
										_trans  := _trans.contents + _klen.contents;
										
									end;
									
								end
								;
							end;
							
						end
						;if _have.contents= 0  then
						begin
							begin
								_klen  := _rpn_range_lengths.(cs.contents);
								if _klen.contents> 0  then
								begin
									begin
										let _lower : int ref = ref 0 in
										let _mid : int ref = ref 0 in
										let _upper : int ref = ref 0 in
										_lower  := _keys.contents;
										_upper  := _keys.contents+ ( _klen.contents lsl 1 )- 2;
										while _have.contents= 0 && _lower.contents<= _upper.contents do
										begin
											_mid  := _lower.contents+ ( ( ( _upper.contents-_lower.contents ) asr 1 ) land  lnot 1 );
											if ( Char.code data.[p.contents] )< _rpn_trans_keys.( _mid.contents ) then
											begin
												_upper  := _mid.contents- 2;
												
											end
											else if ( Char.code data.[p.contents] )> _rpn_trans_keys.( _mid.contents+ 1  ) then
											begin
												_lower  := _mid.contents+ 2;
												
											end
											else
											begin
												begin
													_trans  := _trans.contents + ( ( _mid.contents- _keys.contents ) asr 1 );
													_have  := 1;
													
												end;
												
											end
											;
										end;
										
										done;
										if _have.contents= 0  then
										begin
											_trans  := _trans.contents + _klen.contents;
											
										end
										;
									end;
									
								end
								;
							end;
							
						end
						;_ckeys  := _rpn_trans_offsets.(_trans.contents);
						_klen  := _rpn_trans_lengths.(_trans.contents);
						_cond  := _rpn_trans_offsets.(_trans.contents);
						_have  := 0;
						_cpc  := 0;
						begin
							let _lower : int ref = ref 0 in
							let _mid : int ref = ref 0 in
							let _upper : int ref = ref 0 in
							_lower  := _ckeys.contents;
							_upper  := _ckeys.contents+ _klen.contents- 1;
							while _have.contents= 0 && _lower.contents<= _upper.contents do
							begin
								_mid  := _lower.contents+ ( ( _upper.contents-_lower.contents ) asr 1 );
								if _cpc.contents< _rpn_cond_keys.( _mid.contents ) then
								begin
									_upper  := _mid.contents- 1;
									
								end
								else if _cpc.contents> _rpn_cond_keys.( _mid.contents ) then
								begin
									_lower  := _mid.contents+ 1;
									
								end
								else
								begin
									begin
										_cond  := _cond.contents + ( _mid.contents- _ckeys.contents );
										_have  := 1;
										
									end;
									
								end
								;
							end;
							
							done;
							if _have.contents= 0  then
							begin
								begin
									cs  := 0;
									_cont  := 0;
									
								end;
								
							end
							;
						end;
						
					end;
					
				end
				;if _cont.contents= 1  then
				begin
					begin
						cs  := _rpn_cond_targs.(_cond.contents);
						if _rpn_cond_actions.(_cond.contents)!= 0  then
						begin
							begin
								_acts  := _rpn_cond_actions.(_cond.contents);
								_nacts  := _rpn_actions.( _acts.contents );
								_acts  := _acts.contents + 1;
								while _nacts.contents> 0  do
								begin
									if _rpn_actions.( _acts.contents ) = 0  then
									begin
										begin
											mark := !p 
										end;
										
									end
									else if _rpn_actions.( _acts.contents ) = 1  then
									begin
										begin
											Stack.push (int_of_string (String.sub data !mark (!p - !mark))) st 
										end;
										
									end
									else if _rpn_actions.( _acts.contents ) = 2  then
									begin
										begin
											let y = Stack.pop st in let x = Stack.pop st in Stack.push (x + y) st 
										end;
										
									end
									else if _rpn_actions.( _acts.contents ) = 3  then
									begin
										begin
											let y = Stack.pop st in let x = Stack.pop st in Stack.push (x - y) st 
										end;
										
									end
									else if _rpn_actions.( _acts.contents ) = 4  then
									begin
										begin
											let y = Stack.pop st in let x = Stack.pop st in Stack.push (x * y) st 
										end;
										
									end
									else if _rpn_actions.( _acts.contents ) = 5  then
									begin
										begin
											let y = Stack.pop st in let x = Stack.pop st in Stack.push (x / y) st 
										end;
										
									end
									else if _rpn_actions.( _acts.contents ) = 6  then
									begin
										begin
											Stack.push (abs (Stack.pop st)) st 
										end;
										
									end
									else if _rpn_actions.( _acts.contents ) = 7  then
									begin
										begin
											Stack.push 666 st 
										end;
										
									end
									;
									_nacts  := _nacts.contents - 1;
									_acts  := _acts.contents + 1;
									
								end;
								
								done;
								
							end;
							
						end
						;if cs.contents= 0  then
						begin
							_cont  := 0;
							
						end
						;if _cont.contents= 1  then
						begin
							p  := p.contents + 1;
							
						end
						;
					end;
					
				end
				;
			end;
			
		end
		;
	end;
	
	done;
	
end;
if !cs < rpn_first_final then
begin
	if !p = !pe then
	fail "unexpected eof"
	else
	fail "error at position %d" !p
end;

if Stack.is_empty st then
fail "rpn stack empty on result"
else
Stack.pop st

(* ////////////////////////////////////////////////////////////////////// *)

let rpnTests = [
("666\n", 666);
("666 111\n", 111);
("4 3 add\n", 7);
("4 3 +\n", 7);
("4 3 -\n", 1);
("4 3 *\n", 12);
("6 2 /\n", 3);
("0 3 -\n", -3);
("0 3 - abs\n", 3);
(" 2  2 + 3 - \n", 1);
("10 7 3 2 * - +\n", 11);
("abba abba add\n", 1332);
]

let rpnFailTests = [
("\n")
]

let () =
List.iter (fun (s,x) -> test rpn s x) rpnTests;
List.iter (fun s -> error rpn s) rpnFailTests

