#
# @LANG: ruby
#
# Test the host language scanning for ruby.
#

# %%{
a = 1
b = /%%\{\}/;



# %%{
e = 1
f = /%%\{\}/;

class << self
	attr_accessor :_ruby1_actions 
	private :_ruby1_actions, :_ruby1_actions=
end
self._ruby1_actions = [
0, 1, 0, 0 , 
]

class << self
	attr_accessor :_ruby1_key_offsets 
	private :_ruby1_key_offsets, :_ruby1_key_offsets=
end
self._ruby1_key_offsets = [
0, 0, 2, 6, 9, 0 , 
]

class << self
	attr_accessor :_ruby1_trans_keys 
	private :_ruby1_trans_keys, :_ruby1_trans_keys=
end
self._ruby1_trans_keys = [
97, 122, 48, 57, 97, 122, 10, 48, 57, 0 , 
]

class << self
	attr_accessor :_ruby1_single_lengths 
	private :_ruby1_single_lengths, :_ruby1_single_lengths=
end
self._ruby1_single_lengths = [
0, 0, 0, 1, 0, 0 , 
]

class << self
	attr_accessor :_ruby1_range_lengths 
	private :_ruby1_range_lengths, :_ruby1_range_lengths=
end
self._ruby1_range_lengths = [
0, 1, 2, 1, 0, 0 , 
]

class << self
	attr_accessor :_ruby1_index_offsets 
	private :_ruby1_index_offsets, :_ruby1_index_offsets=
end
self._ruby1_index_offsets = [
0, 0, 2, 5, 8, 0 , 
]

class << self
	attr_accessor :_ruby1_trans_cond_spaces 
	private :_ruby1_trans_cond_spaces, :_ruby1_trans_cond_spaces=
end
self._ruby1_trans_cond_spaces = [
-1, -1, -1, -1, -1, -1, -1, -1, -1, 0 , 
]

class << self
	attr_accessor :_ruby1_trans_offsets 
	private :_ruby1_trans_offsets, :_ruby1_trans_offsets=
end
self._ruby1_trans_offsets = [
0, 1, 2, 3, 4, 5, 6, 7, 8, 0 , 
]

class << self
	attr_accessor :_ruby1_trans_lengths 
	private :_ruby1_trans_lengths, :_ruby1_trans_lengths=
end
self._ruby1_trans_lengths = [
1, 1, 1, 1, 1, 1, 1, 1, 1, 0 , 
]

class << self
	attr_accessor :_ruby1_cond_keys 
	private :_ruby1_cond_keys, :_ruby1_cond_keys=
end
self._ruby1_cond_keys = [
0, 0, 0, 0, 0, 0, 0, 0, 0, 0 , 
]

class << self
	attr_accessor :_ruby1_cond_targs 
	private :_ruby1_cond_targs, :_ruby1_cond_targs=
end
self._ruby1_cond_targs = [
2, 0, 3, 2, 0, 4, 3, 0, 0, 0 , 
]

class << self
	attr_accessor :_ruby1_cond_actions 
	private :_ruby1_cond_actions, :_ruby1_cond_actions=
end
self._ruby1_cond_actions = [
0, 0, 0, 0, 0, 1, 0, 0, 0, 0 , 
]

class << self
	attr_accessor :_ruby1_nfa_targs 
	private :_ruby1_nfa_targs, :_ruby1_nfa_targs=
end
self._ruby1_nfa_targs = [
0, 0 , 
]

class << self
	attr_accessor :_ruby1_nfa_offsets 
	private :_ruby1_nfa_offsets, :_ruby1_nfa_offsets=
end
self._ruby1_nfa_offsets = [
0, 0, 0, 0, 0, 0 , 
]

class << self
	attr_accessor :_ruby1_nfa_push_actions 
	private :_ruby1_nfa_push_actions, :_ruby1_nfa_push_actions=
end
self._ruby1_nfa_push_actions = [
0, 0 , 
]

class << self
	attr_accessor :_ruby1_nfa_pop_trans 
	private :_ruby1_nfa_pop_trans, :_ruby1_nfa_pop_trans=
end
self._ruby1_nfa_pop_trans = [
0, 0 , 
]

class << self
	attr_accessor :ruby1_start 
end
self.ruby1_start  = 1;

class << self
	attr_accessor :ruby1_first_final 
end
self.ruby1_first_final  = 4;

class << self
	attr_accessor :ruby1_error 
end
self.ruby1_error  = 0;

class << self
	attr_accessor :ruby1_en_main 
end
self.ruby1_en_main  = 1;

# %%{
g = 1
h = /%%\{\}/;

def run_machine( data )
	p = 0;
	pe = data.length
	cs = 0
	
	begin
		cs = ruby1_start;
		
	end
	begin
		_klen= 0
		;
		_trans = 0;
		_cond = 0;
		_have = 0;
		_cont = 1;
		_acts = 0;
		_nacts= 0
		;
		_keys = 0;
		_ckeys = 0;
		_cpc= 0
		;
		while ( _cont == 1  )
			begin
				if ( cs == 0  )
					_cont = 0;
					
				end
				_have = 0;
				if ( p == pe  )
					begin
						if ( _have == 0  )
							_cont = 0;
							
						end
						
					end
					
				end
				if ( _cont == 1  )
					begin
						if ( _have == 0  )
							begin
								_keys = _ruby1_key_offsets[cs] ;
								_trans = _ruby1_index_offsets[cs];
								_have = 0;
								_klen = _ruby1_single_lengths[cs];
								if ( _klen > 0  )
									begin
										_lower = 0;
										_mid = 0;
										_upper = 0;
										_lower = _keys;
										_upper = _keys + _klen - 1;
										while ( _upper >= _lower && _have == 0  )
											begin
												_mid = _lower + ((_upper-_lower) >> 1);
												if ( ( data[p ].ord) < _ruby1_trans_keys[_mid ] )
													_upper = _mid - 1;
													
													elsif ( ( data[p ].ord) > _ruby1_trans_keys[_mid ] )
													_lower = _mid + 1;
													
													else
													begin
														_trans += (_mid - _keys);
														_have = 1;
														
													end
													
												end
												
											end
											
										end
										if ( _have == 0  )
											begin
												_keys += _klen;
												_trans += _klen;
												
											end
											
										end
										
									end
									
								end
								if ( _have == 0  )
									begin
										_klen = _ruby1_range_lengths[cs];
										if ( _klen > 0  )
											begin
												_lower = 0;
												_mid = 0;
												_upper = 0;
												_lower = _keys;
												_upper = _keys + (_klen<<1) - 2;
												while ( _have == 0 && _lower <= _upper  )
													begin
														_mid = _lower + (((_upper-_lower) >> 1) & ~1);
														if ( ( data[p ].ord) < _ruby1_trans_keys[_mid ] )
															_upper = _mid - 2;
															
															elsif ( ( data[p ].ord) > _ruby1_trans_keys[_mid + 1 ] )
															_lower = _mid + 2;
															
															else
															begin
																_trans += ((_mid - _keys)>>1);
																_have = 1;
																
															end
															
														end
														
													end
													
												end
												if ( _have == 0  )
													_trans += _klen;
													
												end
												
											end
											
										end
										
									end
									
								end
								_ckeys = _ruby1_trans_offsets[_trans] ;
								_klen = _ruby1_trans_lengths[_trans];
								_cond = _ruby1_trans_offsets[_trans];
								_have = 0;
								_cpc = 0;
								begin
									_lower = 0;
									_mid = 0;
									_upper = 0;
									_lower = _ckeys;
									_upper = _ckeys + _klen - 1;
									while ( _have == 0 && _lower <= _upper  )
										begin
											_mid = _lower + ((_upper-_lower) >> 1);
											if ( _cpc < _ruby1_cond_keys[_mid ] )
												_upper = _mid - 1;
												
												elsif ( _cpc > _ruby1_cond_keys[_mid ] )
												_lower = _mid + 1;
												
												else
												begin
													_cond += (_mid - _ckeys);
													_have = 1;
													
												end
												
											end
											
										end
										
									end
									if ( _have == 0  )
										begin
											cs = 0;
											_cont = 0;
											
										end
										
									end
									
								end
								
							end
							
						end
						if ( _cont == 1  )
							begin
								cs = _ruby1_cond_targs[_cond];
								if ( _ruby1_cond_actions[_cond] != 0  )
									begin
										_acts = _ruby1_cond_actions[_cond] ;
										_nacts = _ruby1_actions[_acts ];
										_acts += 1;
										while ( _nacts > 0  )
											begin
												case  _ruby1_actions[_acts ] 
												when -2 then
												begin
												end
												when 0  then
												begin
													begin
														# }
														c = 1
														d = /\}/
														puts "NL"
														
													end
													
													
												end
											end
											_nacts -= 1;
											_acts += 1;
											
										end
										
									end
									
								end
								
							end
							if ( cs == 0  )
								_cont = 0;
								
							end
							if ( _cont == 1  )
								p += 1;
								
							end
							
						end
						
					end
					
				end
				
			end
			
		end
		
	end
	
end
if  cs >= ruby1_first_final
	puts "ACCEPT"
	else
	puts "FAIL"
end
end
		
		inp = [
		"abc1231\n",
		]
		
		inp.each { |str| run_machine(str) }
		
	