class scan2_java
{
	int
	ts ;
	int
	te ;
	int act ;
	int token ;
	
	
	
	
	
	private static byte  _scanner_actions [] = { 0, 1, 0, 1, 1, 1, 5, 1, 6, 1, 7, 2, 2, 3, 2, 2, 4, 0 ,  };
	private static byte  _scanner_key_offsets [] = { 0, 3, 5, 0 ,  };
	private static char  _scanner_trans_keys [] = { 99, 97, 98, 97, 98, 99, 97, 98, 0,  };
	private static byte  _scanner_single_lengths [] = { 1, 2, 1, 0 ,  };
	private static byte  _scanner_range_lengths [] = { 1, 0, 1, 0 ,  };
	private static byte  _scanner_index_offsets [] = { 0, 3, 6, 0 ,  };
	private static byte  _scanner_trans_cond_spaces [] = { -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0 ,  };
	private static byte  _scanner_trans_offsets [] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0 ,  };
	private static byte  _scanner_trans_lengths [] = { 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0 ,  };
	private static byte  _scanner_cond_keys [] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  };
	private static byte  _scanner_cond_targs [] = { 1, 0, 1, 2, 2, 1, 1, 0, 1, 1, 1, 0 ,  };
	private static byte  _scanner_cond_actions [] = { 5, 0, 9, 11, 14, 7, 5, 0, 9, 9, 9, 0 ,  };
	private static byte  _scanner_to_state_actions [] = { 0, 1, 0, 0 ,  };
	private static byte  _scanner_from_state_actions [] = { 0, 3, 0, 0 ,  };
	private static byte  _scanner_eof_trans_indexed [] = { 2, 0, 2, 0 ,  };
	private static byte  _scanner_eof_trans_direct [] = { 10, 0, 11, 0 ,  };
	private static byte  _scanner_nfa_targs [] = { 0, 0 ,  };
	private static byte  _scanner_nfa_offsets [] = { 0, 0, 0, 0 ,  };
	private static byte  _scanner_nfa_push_actions [] = { 0, 0 ,  };
	private static byte  _scanner_nfa_pop_trans [] = { 0, 0 ,  };
	private static int  scanner_start  = 1;
	private static int  scanner_first_final  = 1;
	private static int  scanner_error  = -1;
	private static int  scanner_en_main  = 1;
	int cs;
	
	void init()
	{
		{
			cs = (int)scanner_start;
			ts = 0;
			te = 0;
			act = 0;
			
		}
	}
	
	void exec( char data[], int len )
	{
		char buffer [] = new char[1024];
		int blen = 0;
		int p = 0;
		int pe = len;
		
		int eof = len;
		String _s;
		{
			int _klen;
			int _trans = 0;
			int _cond = 0;
			int _acts;
			int _nacts;
			int _keys;
			int _ckeys;
			int _cpc;
			int _goto_targ = 0;
			_goto: while ( true ) {
				switch ( _goto_targ ) {
					case 0:
					if ( p == pe  )
					{
						_goto_targ = 5;
						if (true)
						continue _goto;
					}
					
					case 1:
					_acts = _scanner_from_state_actions[cs] ;
					_nacts = (int )_scanner_actions[_acts ];
					_acts += 1;
					while ( _nacts > 0  )
					{
						switch ( _scanner_actions[_acts ] ) {
							case 1 :
							{
								{
									ts = p;
									
								}
								
							}
							
							break;
							
						}
						_nacts -= 1;
						_acts += 1;
						
					}
					
					_keys = _scanner_key_offsets[cs] ;
					_trans = (int )_scanner_index_offsets[cs];
					_klen = (int)_scanner_single_lengths[cs];
					if ( _klen > 0  )
					{
						int _lower;
						int _mid;
						int _upper;
						_lower = _keys;
						_upper = _keys + _klen - 1;
						while ( true  )
						{
							if ( _upper < _lower  )
							break;
							
							
							_mid = _lower + ((_upper-_lower) >> 1);
							if ( ( data[p ]) < _scanner_trans_keys[_mid ] )
							_upper = _mid - 1;
							
							else if ( ( data[p ]) > _scanner_trans_keys[_mid ] )
							_lower = _mid + 1;
							
							else
							{
								_trans += (int )(_mid - _keys);
								{
									_goto_targ = 2;
									if (true)
									continue _goto;
								}
								
							}
							
							
						}
						
						_keys += _klen;
						_trans += (int )_klen;
						
					}
					
					_klen = (int)_scanner_range_lengths[cs];
					if ( _klen > 0  )
					{
						int _lower;
						int _mid;
						int _upper;
						_lower = _keys;
						_upper = _keys + (_klen<<1) - 2;
						while ( true  )
						{
							if ( _upper < _lower  )
							break;
							
							
							_mid = _lower + (((_upper-_lower) >> 1) & ~1);
							if ( ( data[p ]) < _scanner_trans_keys[_mid ] )
							_upper = _mid - 2;
							
							else if ( ( data[p ]) > _scanner_trans_keys[_mid + 1 ] )
							_lower = _mid + 2;
							
							else
							{
								_trans += (int )((_mid - _keys)>>1);
								{
									_goto_targ = 2;
									if (true)
									continue _goto;
								}
								
							}
							
							
						}
						
						_trans += (int )_klen;
						
					}
					
					
					case 2:
					_ckeys = _scanner_trans_offsets[_trans] ;
					_klen = (int)_scanner_trans_lengths[_trans];
					_cond = (int )_scanner_trans_offsets[_trans];
					_cpc = 0;
					{
						int _lower;
						int _mid;
						int _upper;
						_lower = _ckeys;
						_upper = _ckeys + _klen - 1;
						while ( true  )
						{
							if ( _upper < _lower  )
							break;
							
							
							_mid = _lower + ((_upper-_lower) >> 1);
							if ( _cpc < (int)_scanner_cond_keys[_mid ] )
							_upper = _mid - 1;
							
							else if ( _cpc > (int)_scanner_cond_keys[_mid ] )
							_lower = _mid + 1;
							
							else
							{
								_cond += (int )(_mid - _ckeys);
								{
									_goto_targ = 3;
									if (true)
									continue _goto;
								}
								
							}
							
							
						}
						
						cs = -1;
						{
							_goto_targ = 4;
							if (true)
							continue _goto;
						}
						
					}
					
					case 3:
					cs = (int)_scanner_cond_targs[_cond];
					if ( _scanner_cond_actions[_cond] == 0  )
					{
						_goto_targ = 4;
						if (true)
						continue _goto;
					}
					
					_acts = _scanner_cond_actions[_cond] ;
					_nacts = (int )_scanner_actions[_acts ];
					_acts += 1;
					while ( _nacts > 0  )
					{
						switch ( _scanner_actions[_acts ] ) {
							case 2 :
							{
								{
									te = p+1;
									
								}
								
							}
							
							break;
							case 3 :
							{
								{
									act = 1;
									
								}
								
							}
							
							break;
							case 4 :
							{
								{
									act = 3;
									
								}
								
							}
							
							break;
							case 5 :
							{
								{
									te = p+1;
									{
										System.out.print( "pat2\n" );
										
									}
									
								}
								
							}
							
							break;
							case 6 :
							{
								{
									te = p+1;
									{
										System.out.print( "any\n" );
										
									}
									
								}
								
							}
							
							break;
							case 7 :
							{
								{
									switch ( act  ) {
										case 1 :
										p = ((te))-1;
										{
											System.out.print( "pat1\n" );
											
										}
										
										break;
										case 3 :
										p = ((te))-1;
										{
											System.out.print( "any\n" );
											
										}
										
										break;
										
									}
									
								}
								
								
							}
							
							break;
							
						}
						_nacts -= 1;
						_acts += 1;
						
					}
					
					
					case 4:
					_acts = _scanner_to_state_actions[cs] ;
					_nacts = (int )_scanner_actions[_acts ];
					_acts += 1;
					while ( _nacts > 0  )
					{
						switch ( _scanner_actions[_acts ] ) {
							case 0 :
							{
								{
									ts = 0;
									
								}
								
							}
							
							break;
							
						}
						_nacts -= 1;
						_acts += 1;
						
					}
					
					p += 1;
					if ( p != pe  )
					{
						_goto_targ = 1;
						if (true)
						continue _goto;
					}
					
					
					case 5:
					{
					
					}
					if ( p == eof  )
					{
						if ( _scanner_eof_trans_direct[cs] > 0  )
						{
							_trans = (int )_scanner_eof_trans_direct[cs] - 1;
							_cond = (int )_scanner_trans_offsets[_trans];
							{
								_goto_targ = 3;
								if (true)
								continue _goto;
							}
							
						}
						
						
					}
					
					
					
				}
				break;
			}
			
		}
	}
	
	void finish( )
	{
		if ( cs >= scanner_first_final )
		System.out.println( "ACCEPT" );
		else
		System.out.println( "FAIL" );
	}
	
	static final String inp[] = {
		"a",
	};
	
	static final int inplen = 1;
	
	public static void main (String[] args)
	{
		scan2_java machine = new scan2_java();
		for ( int i = 0; i < inplen; i++ ) {
			machine.init();
			machine.exec( inp[i].toCharArray(), inp[i].length() );
			machine.finish();
		}
	}
}
