#include <string.h>
#include <stdio.h>








static const int  state_act_start  = 4;
static const int  state_act_first_final  = 4;
static const int  state_act_error  = 0;
static const int  state_act_en_main  = 4;
static const int  state_act_en_main_line_again  = 3;
static const char  _state_act_nfa_targs [] = { 0, 0 ,  };
static const char  _state_act_nfa_offsets [] = { 0, 0, 0, 0, 0, 0, 0 ,  };
static const char  _state_act_nfa_push_actions [] = { 0, 0 ,  };
static const char  _state_act_nfa_pop_trans [] = { 0, 0 ,  };
int cs;
int blen;
char buffer[1024];

void init()
{

	{
		cs = ( int ) state_act_start;
	}
}

void exec( char *data, int len )
{
	char *p = data;
	char *pe = data + len;
	
	{
		if ( p == pe  )
		goto _test_eof;
		
		goto _resume;
		
		_again:
		switch ( cs  ) {
			case 4:
			goto st4;
			case 0:
			goto st0;
			case 1:
			goto st1;
			case 2:
			goto st2;
			case 5:
			goto st5;
			case 3:
			goto st3;
			
		}
		_resume:
		switch ( cs  ) {
			case 4:
			goto st_case_4;
			case 0:
			goto st_case_0;
			case 1:
			goto st_case_1;
			case 2:
			goto st_case_2;
			case 5:
			goto st_case_5;
			case 3:
			goto st_case_3;
			
		}
		goto st_out;
		st4:
		{
			printf( "%s", "a1\n" );
			
		}
		{
			printf( "%s", "b1\n" );
			
		}
		
		p+= 1;
		if ( p == pe  )
		goto _test_eof4;
		
		st_case_4:
		{
			printf( "%s", "a2\n" );
			
		}
		{
			printf( "%s", "b2\n" );
			
		}
		if ( ((*( p  ))
		)== 104  )
		{
			goto st1;
		}
		
		{
			goto st0;
		}
		st_case_0:
		st0:
		cs = 0;
		goto _out;
		st1:
		p+= 1;
		if ( p == pe  )
		goto _test_eof1;
		
		st_case_1:
		if ( ((*( p  ))
		)== 105  )
		{
			goto st2;
		}
		
		{
			goto st0;
		}
		st2:
		{
			printf( "%s", "c1\n" );
			
		}
		
		p+= 1;
		if ( p == pe  )
		goto _test_eof2;
		
		st_case_2:
		{
			printf( "%s", "c2\n" );
			
		}
		if ( ((*( p  ))
		)== 10  )
		{
			goto ctr2;
		}
		
		{
			goto st0;
		}
		ctr2:
		cs = 5;
		{
			cs = 3;
		}
		
		
		goto _again;
		st5:
		{
			printf( "%s", "b1\n" );
			
		}
		
		p+= 1;
		if ( p == pe  )
		goto _test_eof5;
		
		st_case_5:
		{
			printf( "%s", "b2\n" );
			
		}
		if ( ((*( p  ))
		)== 104  )
		{
			goto st1;
		}
		
		{
			goto st0;
		}
		st3:
		{
			printf( "%s", "b1\n" );
			
		}
		
		p+= 1;
		if ( p == pe  )
		goto _test_eof3;
		
		st_case_3:
		{
			printf( "%s", "b2\n" );
			
		}
		if ( ((*( p  ))
		)== 104  )
		{
			goto st1;
		}
		
		{
			goto st0;
		}
		st_out:
		_test_eof4: cs = 4;
		goto _test_eof; 
		_test_eof1: cs = 1;
		goto _test_eof; 
		_test_eof2: cs = 2;
		goto _test_eof; 
		_test_eof5: cs = 5;
		goto _test_eof; 
		_test_eof3: cs = 3;
		goto _test_eof; 
		
		_test_eof: {}
		_out: {}
	}
}

void finish( )
{
	if ( cs >= state_act_first_final )
	printf( "ACCEPT\n" );
	else
	printf( "FAIL\n" );
}

char *inp[] = {
	"hi\nhi\n",
};

int inplen = 1;

int main( )
{
	int i;
	for ( i = 0; i < inplen; i++ ) {
		init();
		exec( inp[i], strlen(inp[i]) );
		finish();
	}
	return 0;
}

