const _state_act_key_offsets = Int8[0, 0, 1, 2, 3, 4, 0 , ]
const _state_act_trans_keys = UInt8[105, 10, 104, 104, 104, 0 , ]
const _state_act_single_lengths = Int8[0, 1, 1, 1, 1, 1, 0 , ]
const _state_act_range_lengths = Int8[0, 0, 0, 0, 0, 0, 0 , ]
const _state_act_index_offsets = Int8[0, 0, 2, 4, 6, 8, 0 , ]
const _state_act_trans_cond_spaces = Int8[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0 , ]
const _state_act_trans_offsets = Int8[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0 , ]
const _state_act_trans_lengths = Int8[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0 , ]
const _state_act_cond_keys = Int8[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 , ]
const _state_act_cond_targs = Int8[2, 0, 5, 0, 1, 0, 1, 0, 1, 0, 0 , ]
const _state_act_cond_actions = Int8[0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0 , ]
const _state_act_to_state_actions = Int8[0, 0, 1, 4, 6, 4, 0 , ]
const _state_act_from_state_actions = Int8[0, 0, 2, 5, 7, 5, 0 , ]
const _state_act_nfa_targs = Int8[0, 0 , ]
const _state_act_nfa_offsets = Int8[0, 0, 0, 0, 0, 0, 0 , ]
const _state_act_nfa_push_actions = Int8[0, 0 , ]
const _state_act_nfa_pop_trans = Int8[0, 0 , ]
const state_act_start  = 4
const state_act_first_final  = 4
const state_act_error  = 0
const state_act_en_main  = 4
const state_act_en_main_line_again  = 3
function m( data::AbstractString )
	p = 0
	pe = length(data)
	eof = length(data)
	cs = 0
	buffer = ""
	
	cs = convert(Int, state_act_start )
	_klen= 0
	;
	_keys = 0;
	_ckeys = 0;
	_cpc= 0
	;
	_trans= 0
	;
	_cond = 0;
	_have = 0;
	_cont = 1;
	while _cont == 1 
		if cs == 0 
			_cont = 0
			
		end
		_have = 0
		if p == pe 
			if _have == 0 
				_cont = 0
				
			end
			
		end
		if _cont == 1 
			if _have == 0 
				if _state_act_from_state_actions[1+(cs)] == 5 
					print( "b2\n" );
					
				elseif _state_act_from_state_actions[1+(cs)] == 2 
					print( "c2\n" );
					
				elseif _state_act_from_state_actions[1+(cs)] == 7 
					print( "a2\n" );
					print( "b2\n" );
					
				end
				_keys = _state_act_key_offsets[1+(cs)]
				_trans = convert(UInt, _state_act_index_offsets[1+(cs)] )
				_have = 0
				_klen = convert(Int, _state_act_single_lengths[1+(cs)] )
				if _klen > 0 
					_lower = 0;
					_mid = 0;
					_upper = 0;
					_lower = _keys
					_upper = _keys + _klen - 1
					while _upper >= _lower && _have == 0 
						_mid = _lower + ((_upper-_lower)>> 1)
						if (data[1+(p )])< _state_act_trans_keys[1+(_mid )]
							_upper = _mid - 1
							
						elseif (data[1+(p )])> _state_act_trans_keys[1+(_mid )]
							_lower = _mid + 1
							
						else
							_trans += convert(UInt, (_mid - _keys) )
							_have = 1
							
						end
						
					end
					if _have == 0 
						_keys += _klen
						_trans += convert(UInt, _klen )
						
					end
					
				end
				if _have == 0 
					_klen = convert(Int, _state_act_range_lengths[1+(cs)] )
					if _klen > 0 
						_lower = 0;
						_mid = 0;
						_upper = 0;
						_lower = _keys
						_upper = _keys + (_klen<<1)- 2
						while _have == 0 && _lower <= _upper 
							_mid = _lower + (((_upper-_lower)>> 1)& ~1)
							if (data[1+(p )])< _state_act_trans_keys[1+(_mid )]
								_upper = _mid - 2
								
							elseif (data[1+(p )])> _state_act_trans_keys[1+(_mid + 1 )]
								_lower = _mid + 2
								
							else
								_trans += convert(UInt, ((_mid - _keys)>>1) )
								_have = 1
								
							end
							
						end
						if _have == 0 
							_trans += convert(UInt, _klen )
							
						end
						
					end
					
				end
				_ckeys = _state_act_trans_offsets[1+(_trans)]
				_klen = convert(Int, _state_act_trans_lengths[1+(_trans)] )
				_cond = convert(UInt, _state_act_trans_offsets[1+(_trans)] )
				_have = 0
				_cpc = 0
				_lower = 0;
				_mid = 0;
				_upper = 0;
				_lower = _ckeys
				_upper = _ckeys + _klen - 1
				while _have == 0 && _lower <= _upper 
					_mid = _lower + ((_upper-_lower)>> 1)
					if _cpc < convert(Int, _state_act_cond_keys[1+(_mid )] )
						_upper = _mid - 1
						
					elseif _cpc > convert(Int, _state_act_cond_keys[1+(_mid )] )
						_lower = _mid + 1
						
					else
						_cond += convert(UInt, (_mid - _ckeys) )
						_have = 1
						
					end
					
				end
				if _have == 0 
					cs = 0
					_cont = 0
					
				end
				
			end
			if _cont == 1 
				cs = convert(Int, _state_act_cond_targs[1+(_cond)] )
				if _state_act_cond_actions[1+(_cond)] == 3 
					{
						cs = 3
						
					}
					
				end
				if _state_act_to_state_actions[1+(cs)] == 4 
					print( "b1\n" );
					
				elseif _state_act_to_state_actions[1+(cs)] == 1 
					print( "c1\n" );
					
				elseif _state_act_to_state_actions[1+(cs)] == 6 
					print( "a1\n" );
					print( "b1\n" );
					
				end
				if cs == 0 
					_cont = 0
					
				end
				if _cont == 1 
					p += 1
					
				end
				
			end
			
		end
		
	end
	if ( cs >= state_act_first_final )
		println( "ACCEPT" );
	else
		println( "FAIL" );
	end
end

m( "hi\nhi\n" );
