(*
* @LANG: ocaml
* @GENERATED: true
*)

let return_to = ref 0






let _targs1_actions : int array = [|
0; 1; 0; 1; 1; 1; 2; 1; 3; 0 ; 
|]
let _targs1_key_offsets : int array = [|
0; 0; 1; 2; 3; 4; 5; 6; 7; 8; 9; 10; 11; 12; 15; 15; 15; 0 ; 
|]
let _targs1_trans_keys : int array = [|
117; 110; 117; 115; 101; 100; 111; 110; 101; 116; 119; 111; 10; 49; 50; 0 ; 
|]
let _targs1_single_lengths : int array = [|
0; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 3; 0; 0; 0; 0 ; 
|]
let _targs1_range_lengths : int array = [|
0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0 ; 
|]
let _targs1_index_offsets : int array = [|
0; 0; 2; 4; 6; 8; 10; 12; 14; 16; 18; 20; 22; 24; 28; 29; 30; 0 ; 
|]
let _targs1_trans_cond_spaces : int array = [|
-1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; -1; 0 ; 
|]
let _targs1_trans_offsets : int array = [|
0; 1; 2; 3; 4; 5; 6; 7; 8; 9; 10; 11; 12; 13; 14; 15; 16; 17; 18; 19; 20; 21; 22; 23; 24; 25; 26; 27; 28; 29; 30; 0 ; 
|]
let _targs1_trans_lengths : int array = [|
1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 0 ; 
|]
let _targs1_cond_keys : int array = [|
0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0 ; 
|]
let _targs1_cond_targs : int array = [|
2; 0; 3; 0; 4; 0; 5; 0; 6; 0; 14; 0; 8; 0; 9; 0; 15; 0; 11; 0; 12; 0; 16; 0; 13; 13; 13; 0; 0; 0; 0; 0 ; 
|]
let _targs1_cond_actions : int array = [|
0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 1; 0; 0; 0; 0; 0; 3; 0; 0; 5; 7; 0; 0; 0; 0; 0 ; 
|]
let _targs1_nfa_targs : int array = [|
0; 0 ; 
|]
let _targs1_nfa_offsets : int array = [|
0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0 ; 
|]
let _targs1_nfa_push_actions : int array = [|
0; 0 ; 
|]
let _targs1_nfa_pop_trans : int array = [|
0; 0 ; 
|]
let targs1_start  : int  = 13
let targs1_first_final  : int  = 13
let targs1_error  : int  = 0
let targs1_en_unused  : int  = 1
let targs1_en_one  : int  = 7
let targs1_en_two  : int  = 10
let targs1_en_main  : int  = 13
let exec data = 
let buffer = String.create(1024) in 
let blen :int ref = ref 0 in
let cs = ref 0 in
let p = ref 0 in
let pe = ref (String.length data) in
begin
	cs  := targs1_start;
	
end;
begin
	let _klen : int  ref = ref 0 in
	let _trans  : int  ref = ref 0 in
	let _cond  : int  ref = ref 0 in
	let _have  : int  ref = ref 0 in
	let _cont  : int  ref = ref 1 in
	let _acts : int ref = ref 0 in
	let _nacts : int  ref = ref 0 in
	let _keys : int ref = ref 0 in
	let _ckeys : int ref = ref 0 in
	let _cpc : int  ref = ref 0 in
	while _cont.contents= 1  do
	begin
		if cs.contents= 0  then
		begin
			_cont  := 0;
			
		end
		;_have  := 0;
		if p.contents= pe.contents then
		begin
			begin
				if _have.contents= 0  then
				begin
					_cont  := 0;
					
				end
				;
			end;
			
		end
		;if _cont.contents= 1  then
		begin
			begin
				if _have.contents= 0  then
				begin
					begin
						_keys  := _targs1_key_offsets.(cs.contents);
						_trans  := _targs1_index_offsets.(cs.contents);
						_have  := 0;
						_klen  := _targs1_single_lengths.(cs.contents);
						if _klen.contents> 0  then
						begin
							begin
								let _lower : int ref = ref 0 in
								let _mid : int ref = ref 0 in
								let _upper : int ref = ref 0 in
								_lower  := _keys.contents;
								_upper  := _keys.contents+ _klen.contents- 1;
								while _upper.contents>= _lower.contents&& _have.contents= 0  do
								begin
									_mid  := _lower.contents+ ( ( _upper.contents-_lower.contents ) asr 1 );
									if ( Char.code data.[p.contents] )< _targs1_trans_keys.( _mid.contents ) then
									begin
										_upper  := _mid.contents- 1;
										
									end
									else if ( Char.code data.[p.contents] )> _targs1_trans_keys.( _mid.contents ) then
									begin
										_lower  := _mid.contents+ 1;
										
									end
									else
									begin
										begin
											_trans  := _trans.contents + ( _mid.contents- _keys.contents );
											_have  := 1;
											
										end;
										
									end
									;
								end;
								
								done;
								if _have.contents= 0  then
								begin
									begin
										_keys  := _keys.contents + _klen.contents;
										_trans  := _trans.contents + _klen.contents;
										
									end;
									
								end
								;
							end;
							
						end
						;if _have.contents= 0  then
						begin
							begin
								_klen  := _targs1_range_lengths.(cs.contents);
								if _klen.contents> 0  then
								begin
									begin
										let _lower : int ref = ref 0 in
										let _mid : int ref = ref 0 in
										let _upper : int ref = ref 0 in
										_lower  := _keys.contents;
										_upper  := _keys.contents+ ( _klen.contents lsl 1 )- 2;
										while _have.contents= 0 && _lower.contents<= _upper.contents do
										begin
											_mid  := _lower.contents+ ( ( ( _upper.contents-_lower.contents ) asr 1 ) land  lnot 1 );
											if ( Char.code data.[p.contents] )< _targs1_trans_keys.( _mid.contents ) then
											begin
												_upper  := _mid.contents- 2;
												
											end
											else if ( Char.code data.[p.contents] )> _targs1_trans_keys.( _mid.contents+ 1  ) then
											begin
												_lower  := _mid.contents+ 2;
												
											end
											else
											begin
												begin
													_trans  := _trans.contents + ( ( _mid.contents- _keys.contents ) asr 1 );
													_have  := 1;
													
												end;
												
											end
											;
										end;
										
										done;
										if _have.contents= 0  then
										begin
											_trans  := _trans.contents + _klen.contents;
											
										end
										;
									end;
									
								end
								;
							end;
							
						end
						;_ckeys  := _targs1_trans_offsets.(_trans.contents);
						_klen  := _targs1_trans_lengths.(_trans.contents);
						_cond  := _targs1_trans_offsets.(_trans.contents);
						_have  := 0;
						_cpc  := 0;
						begin
							let _lower : int ref = ref 0 in
							let _mid : int ref = ref 0 in
							let _upper : int ref = ref 0 in
							_lower  := _ckeys.contents;
							_upper  := _ckeys.contents+ _klen.contents- 1;
							while _have.contents= 0 && _lower.contents<= _upper.contents do
							begin
								_mid  := _lower.contents+ ( ( _upper.contents-_lower.contents ) asr 1 );
								if _cpc.contents< _targs1_cond_keys.( _mid.contents ) then
								begin
									_upper  := _mid.contents- 1;
									
								end
								else if _cpc.contents> _targs1_cond_keys.( _mid.contents ) then
								begin
									_lower  := _mid.contents+ 1;
									
								end
								else
								begin
									begin
										_cond  := _cond.contents + ( _mid.contents- _ckeys.contents );
										_have  := 1;
										
									end;
									
								end
								;
							end;
							
							done;
							if _have.contents= 0  then
							begin
								begin
									cs  := 0;
									_cont  := 0;
									
								end;
								
							end
							;
						end;
						
					end;
					
				end
				;if _cont.contents= 1  then
				begin
					begin
						cs  := _targs1_cond_targs.(_cond.contents);
						if _targs1_cond_actions.(_cond.contents)!= 0  then
						begin
							begin
								_acts  := _targs1_cond_actions.(_cond.contents);
								_nacts  := _targs1_actions.( _acts.contents );
								_acts  := _acts.contents + 1;
								while _nacts.contents> 0  do
								begin
									if _targs1_actions.( _acts.contents ) = 0  then
									begin
										begin
											print_string( "one\n" );
											begin
												cs  := (return_to.contents);
												
											end;
											
											
										end;
										
									end
									else if _targs1_actions.( _acts.contents ) = 1  then
									begin
										begin
											print_string( "two\n" );
											begin
												cs  := (return_to.contents);
												
											end;
											
											
										end;
										
									end
									else if _targs1_actions.( _acts.contents ) = 2  then
									begin
										begin
											return_to := (cs.contents);
											begin
												cs  := 7;
												
											end;
											
										end;
										
									end
									else if _targs1_actions.( _acts.contents ) = 3  then
									begin
										begin
											return_to := (cs.contents);
											begin
												cs  := 10;
												
											end;
											
										end;
										
									end
									;
									_nacts  := _nacts.contents - 1;
									_acts  := _acts.contents + 1;
									
								end;
								
								done;
								
							end;
							
						end
						;if cs.contents= 0  then
						begin
							_cont  := 0;
							
						end
						;if _cont.contents= 1  then
						begin
							p  := p.contents + 1;
							
						end
						;
					end;
					
				end
				;
			end;
			
		end
		;
	end;
	
	done;
	
end;
if !cs >= targs1_first_final then
print_string "ACCEPT\n"
else
print_string "FAIL\n"
;;

let () =
exec "1one2two1one\n";
()
;;

