#
# @LANG: ruby
# @GENERATED: true
#






class << self
	attr_accessor :_targs1_key_offsets 
	private :_targs1_key_offsets, :_targs1_key_offsets=
end
self._targs1_key_offsets = [
0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 15, 15, 15, 0 , 
]

class << self
	attr_accessor :_targs1_trans_keys 
	private :_targs1_trans_keys, :_targs1_trans_keys=
end
self._targs1_trans_keys = [
117, 110, 117, 115, 101, 100, 111, 110, 101, 116, 119, 111, 10, 49, 50, 0 , 
]

class << self
	attr_accessor :_targs1_single_lengths 
	private :_targs1_single_lengths, :_targs1_single_lengths=
end
self._targs1_single_lengths = [
0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 0, 0, 0, 0 , 
]

class << self
	attr_accessor :_targs1_range_lengths 
	private :_targs1_range_lengths, :_targs1_range_lengths=
end
self._targs1_range_lengths = [
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 , 
]

class << self
	attr_accessor :_targs1_index_offsets 
	private :_targs1_index_offsets, :_targs1_index_offsets=
end
self._targs1_index_offsets = [
0, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 28, 29, 30, 0 , 
]

class << self
	attr_accessor :_targs1_trans_cond_spaces 
	private :_targs1_trans_cond_spaces, :_targs1_trans_cond_spaces=
end
self._targs1_trans_cond_spaces = [
-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0 , 
]

class << self
	attr_accessor :_targs1_trans_offsets 
	private :_targs1_trans_offsets, :_targs1_trans_offsets=
end
self._targs1_trans_offsets = [
0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 0 , 
]

class << self
	attr_accessor :_targs1_trans_lengths 
	private :_targs1_trans_lengths, :_targs1_trans_lengths=
end
self._targs1_trans_lengths = [
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0 , 
]

class << self
	attr_accessor :_targs1_cond_keys 
	private :_targs1_cond_keys, :_targs1_cond_keys=
end
self._targs1_cond_keys = [
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 , 
]

class << self
	attr_accessor :_targs1_cond_targs 
	private :_targs1_cond_targs, :_targs1_cond_targs=
end
self._targs1_cond_targs = [
2, 0, 3, 0, 4, 0, 5, 0, 6, 0, 14, 0, 8, 0, 9, 0, 15, 0, 11, 0, 12, 0, 16, 0, 13, 13, 13, 0, 0, 0, 0, 0 , 
]

class << self
	attr_accessor :_targs1_cond_actions 
	private :_targs1_cond_actions, :_targs1_cond_actions=
end
self._targs1_cond_actions = [
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 3, 4, 0, 0, 0, 0, 0 , 
]

class << self
	attr_accessor :_targs1_nfa_targs 
	private :_targs1_nfa_targs, :_targs1_nfa_targs=
end
self._targs1_nfa_targs = [
0, 0 , 
]

class << self
	attr_accessor :_targs1_nfa_offsets 
	private :_targs1_nfa_offsets, :_targs1_nfa_offsets=
end
self._targs1_nfa_offsets = [
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 , 
]

class << self
	attr_accessor :_targs1_nfa_push_actions 
	private :_targs1_nfa_push_actions, :_targs1_nfa_push_actions=
end
self._targs1_nfa_push_actions = [
0, 0 , 
]

class << self
	attr_accessor :_targs1_nfa_pop_trans 
	private :_targs1_nfa_pop_trans, :_targs1_nfa_pop_trans=
end
self._targs1_nfa_pop_trans = [
0, 0 , 
]

class << self
	attr_accessor :targs1_start 
end
self.targs1_start  = 13;

class << self
	attr_accessor :targs1_first_final 
end
self.targs1_first_final  = 13;

class << self
	attr_accessor :targs1_error 
end
self.targs1_error  = 0;

class << self
	attr_accessor :targs1_en_unused 
end
self.targs1_en_unused  = 1;

class << self
	attr_accessor :targs1_en_one 
end
self.targs1_en_one  = 7;

class << self
	attr_accessor :targs1_en_two 
end
self.targs1_en_two  = 10;

class << self
	attr_accessor :targs1_en_main 
end
self.targs1_en_main  = 13;

def run_machine( data )
	p = 0
	pe = data.length
	eof = data.length
	cs = 0;
	_m = 
	_a = 
	buffer = Array.new
	blen = 0
	return_to = 1
	begin
		cs = targs1_start;
		
	end
	begin
		_klen= 0
		;
		_keys = 0;
		_ckeys = 0;
		_cpc= 0
		;
		_trans= 0
		;
		_cond = 0;
		_have = 0;
		_cont = 1;
		while ( _cont == 1  )
			begin
				if ( cs == 0  )
					_cont = 0;
					
				end
				_have = 0;
				if ( p == pe  )
					begin
						if ( _have == 0  )
							_cont = 0;
							
						end
						
					end
					
				end
				if ( _cont == 1  )
					begin
						if ( _have == 0  )
							begin
								_keys = _targs1_key_offsets[cs] ;
								_trans = _targs1_index_offsets[cs];
								_have = 0;
								_klen = _targs1_single_lengths[cs];
								if ( _klen > 0  )
									begin
										_lower = 0;
										_mid = 0;
										_upper = 0;
										_lower = _keys;
										_upper = _keys + _klen - 1;
										while ( _upper >= _lower && _have == 0  )
											begin
												_mid = _lower + ((_upper-_lower) >> 1);
												if ( ( data[p ].ord) < _targs1_trans_keys[_mid ] )
													_upper = _mid - 1;
													
													elsif ( ( data[p ].ord) > _targs1_trans_keys[_mid ] )
													_lower = _mid + 1;
													
													else
													begin
														_trans += (_mid - _keys);
														_have = 1;
														
													end
													
												end
												
											end
											
										end
										if ( _have == 0  )
											begin
												_keys += _klen;
												_trans += _klen;
												
											end
											
										end
										
									end
									
								end
								if ( _have == 0  )
									begin
										_klen = _targs1_range_lengths[cs];
										if ( _klen > 0  )
											begin
												_lower = 0;
												_mid = 0;
												_upper = 0;
												_lower = _keys;
												_upper = _keys + (_klen<<1) - 2;
												while ( _have == 0 && _lower <= _upper  )
													begin
														_mid = _lower + (((_upper-_lower) >> 1) & ~1);
														if ( ( data[p ].ord) < _targs1_trans_keys[_mid ] )
															_upper = _mid - 2;
															
															elsif ( ( data[p ].ord) > _targs1_trans_keys[_mid + 1 ] )
															_lower = _mid + 2;
															
															else
															begin
																_trans += ((_mid - _keys)>>1);
																_have = 1;
																
															end
															
														end
														
													end
													
												end
												if ( _have == 0  )
													_trans += _klen;
													
												end
												
											end
											
										end
										
									end
									
								end
								_ckeys = _targs1_trans_offsets[_trans] ;
								_klen = _targs1_trans_lengths[_trans];
								_cond = _targs1_trans_offsets[_trans];
								_have = 0;
								_cpc = 0;
								begin
									_lower = 0;
									_mid = 0;
									_upper = 0;
									_lower = _ckeys;
									_upper = _ckeys + _klen - 1;
									while ( _have == 0 && _lower <= _upper  )
										begin
											_mid = _lower + ((_upper-_lower) >> 1);
											if ( _cpc < _targs1_cond_keys[_mid ] )
												_upper = _mid - 1;
												
												elsif ( _cpc > _targs1_cond_keys[_mid ] )
												_lower = _mid + 1;
												
												else
												begin
													_cond += (_mid - _ckeys);
													_have = 1;
													
												end
												
											end
											
										end
										
									end
									if ( _have == 0  )
										begin
											cs = 0;
											_cont = 0;
											
										end
										
									end
									
								end
								
							end
							
						end
						if ( _cont == 1  )
							begin
								cs = _targs1_cond_targs[_cond];
								case  _targs1_cond_actions[_cond]  
								when -2 then
								begin
								end
								when 1  then
								begin
									begin
										print( "one\n" );
										begin
											cs = (return_to);
											
										end
										
									end
									
								end
								when 2  then
								begin
									begin
										print( "two\n" );
										begin
											cs = (return_to);
											
										end
										
									end
									
								end
								when 3  then
								begin
									begin
										return_to = cs;
										begin
											cs = 7;
											
										end
										
									end
									
								end
								when 4  then
								begin
									begin
										return_to = cs;
										begin
											cs = 10;
											
										end
										
									end
									
									
								end
							end
							if ( cs == 0  )
								_cont = 0;
								
							end
							if ( _cont == 1  )
								p += 1;
								
							end
							
						end
						
					end
					
				end
				
			end
			
		end
		
	end
	
end
if cs >= targs1_first_final
	puts "ACCEPT"
	else
	puts "FAIL"
end
end
	
	inp = [
	"1one2two1one\n",
	]
	
	inplen = 1
	
	inp.each { |str| run_machine(str) }
	
