#include <string.h>
#include <stdio.h>








static const char  _zlen1_key_offsets [] = { 0, 0, 0 ,  };
static const char  _zlen1_trans_keys [] = { 0 ,  };
static const char  _zlen1_single_lengths [] = { 0, 0, 0 ,  };
static const char  _zlen1_range_lengths [] = { 0, 0, 0 ,  };
static const char  _zlen1_index_offsets [] = { 0, 0, 0 ,  };
static const char  _zlen1_trans_cond_spaces [] = { -1, 0 ,  };
static const char  _zlen1_trans_offsets [] = { 0, 0 ,  };
static const char  _zlen1_trans_lengths [] = { 1, 0 ,  };
static const char  _zlen1_cond_keys [] = { 0, 0 ,  };
static const char  _zlen1_cond_targs [] = { 0, 0 ,  };
static const char  _zlen1_cond_actions [] = { 0, 0 ,  };
static const char  _zlen1_nfa_targs [] = { 0, 0 ,  };
static const char  _zlen1_nfa_offsets [] = { 0, 0, 0 ,  };
static const char  _zlen1_nfa_push_actions [] = { 0, 0 ,  };
static const char  _zlen1_nfa_pop_trans [] = { 0, 0 ,  };
static const int  zlen1_start  = 1;
static const int  zlen1_first_final  = 1;
static const int  zlen1_error  = 0;
static const int  zlen1_en_main  = 1;
int cs;
int blen;
char buffer[1024];

void init()
{

	{
		cs = ( int ) zlen1_start;
	}
}

void exec( char *data, int len )
{
	char *p = data;
	char *pe = data + len;
	
	{
		int _klen;
		const char  *_keys;
		const char  *_ckeys;
		int _cpc;
		unsigned int _trans;
		unsigned int _cond = 0;
		unsigned int _have = 0;
		unsigned int _cont = 1;
		while ( _cont == 1  )
		{
		
			if ( cs == 0  )
			_cont = 0;
			
			_have = 0;
			if ( p == pe  )
			{
				if ( _have == 0  )
				_cont = 0;
				
			}
			
			if ( _cont == 1  )
			{
				if ( _have == 0  )
				{
					_keys = _zlen1_trans_keys + _zlen1_key_offsets[cs];
					_trans = ( unsigned int  ) _zlen1_index_offsets[cs];
					_have = 0;
					_klen = ( int ) _zlen1_single_lengths[cs];
					if ( _klen > 0  )
					{
						const char  *_lower;
						const char  *_mid;
						const char  *_upper;
						_lower = _keys;
						_upper = _keys + _klen - 1;
						while ( _upper >= _lower && _have == 0  )
						{
							_mid = _lower + ((_upper-_lower)>> 1);
							if ( ((*( p  ))
							)< (*( _mid  ))
							)
							_upper = _mid - 1;
							
							else if ( ((*( p  ))
							)> (*( _mid  ))
							)
							_lower = _mid + 1;
							
							else
							{
								_trans += ( unsigned int  ) (_mid - _keys);
								_have = 1;
							}
							
						}
						
						if ( _have == 0  )
						{
							_keys += _klen;
							_trans += ( unsigned int  ) _klen;
						}
						
					}
					
					
					if ( _have == 0  )
					{
						_klen = ( int ) _zlen1_range_lengths[cs];
						if ( _klen > 0  )
						{
							const char  *_lower;
							const char  *_mid;
							const char  *_upper;
							_lower = _keys;
							_upper = _keys + (_klen<<1)- 2;
							while ( _have == 0 && _lower <= _upper  )
							{
								_mid = _lower + (((_upper-_lower)>> 1)& ~1);
								if ( ((*( p  ))
								)< (*( _mid  ))
								)
								_upper = _mid - 2;
								
								else if ( ((*( p  ))
								)> (*( _mid + 1  ))
								)
								_lower = _mid + 2;
								
								else
								{
									_trans += ( unsigned int  ) ((_mid - _keys)>>1);
									_have = 1;
								}
								
							}
							
							if ( _have == 0  )
							_trans += ( unsigned int  ) _klen;
							
						}
						
					}
					
					
					_ckeys = _zlen1_cond_keys + _zlen1_trans_offsets[_trans];
					_klen = ( int ) _zlen1_trans_lengths[_trans];
					_cond = ( unsigned int  ) _zlen1_trans_offsets[_trans];
					_have = 0;
					_cpc = 0;
					{
						const char  *_lower;
						const char  *_mid;
						const char  *_upper;
						_lower = _ckeys;
						_upper = _ckeys + _klen - 1;
						while ( _have == 0 && _lower <= _upper  )
						{
							_mid = _lower + ((_upper-_lower)>> 1);
							if ( _cpc < ( int ) (*( _mid  ))
							)
							_upper = _mid - 1;
							
							else if ( _cpc > ( int ) (*( _mid  ))
							)
							_lower = _mid + 1;
							
							else
							{
								_cond += ( unsigned int  ) (_mid - _ckeys);
								_have = 1;
							}
							
						}
						
						if ( _have == 0  )
						{
							cs = 0;
							_cont = 0;
						}
						
					}
				}
				
				if ( _cont == 1  )
				{
					cs = ( int ) _zlen1_cond_targs[_cond];
					if ( cs == 0  )
					_cont = 0;
					
					if ( _cont == 1  )
					p += 1;
					
				}
			}
			
		}
		
	}
}

void finish( )
{
	if ( cs >= zlen1_first_final )
	printf( "ACCEPT\n" );
	else
	printf( "FAIL\n" );
}

char *inp[] = {
	"",
	"x",
};

int inplen = 2;

int main( )
{
	int i;
	for ( i = 0; i < inplen; i++ ) {
		init();
		exec( inp[i], strlen(inp[i]) );
		finish();
	}
	return 0;
}

