class atoi2_java
{
	int neg ;
	int value ;
	
	
	
	
	
	private static byte  _state_chart_actions [] = { 0, 1, 0, 1, 2, 2, 0, 1, 2, 0, 2, 2, 3, 4, 0 ,  };
	private static char  _state_chart_trans_keys [] = { 1, 0, 4, 4, 0, 4, 2, 4, 0,  };
	private static byte  _state_chart_char_class [] = { 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 3, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0 ,  };
	private static byte  _state_chart_index_offsets [] = { 0, 0, 1, 6, 0 ,  };
	private static byte  _state_chart_indicies [] = { 0, 2, 1, 1, 1, 0, 3, 4, 5, 0 ,  };
	private static byte  _state_chart_index_defaults [] = { 0, 1, 1, 1, 0 ,  };
	private static byte  _state_chart_trans_cond_spaces [] = { -1, -1, -1, -1, -1, -1, 0 ,  };
	private static byte  _state_chart_cond_targs [] = { 2, 0, 3, 1, 1, 2, 0 ,  };
	private static byte  _state_chart_cond_actions [] = { 3, 0, 11, 1, 5, 8, 0 ,  };
	private static byte  _state_chart_nfa_targs [] = { 0, 0 ,  };
	private static byte  _state_chart_nfa_offsets [] = { 0, 0, 0, 0, 0 ,  };
	private static byte  _state_chart_nfa_push_actions [] = { 0, 0 ,  };
	private static byte  _state_chart_nfa_pop_trans [] = { 0, 0 ,  };
	private static int  state_chart_start  = 3;
	private static int  state_chart_first_final  = 3;
	private static int  state_chart_error  = 0;
	private static int  state_chart_en_main  = 3;
	int cs;
	
	void init()
	{
		value = 0;
		neg = 0;
		{
			cs = (int)state_chart_start;
			
		}
	}
	
	void exec( char data[], int len )
	{
		char buffer [] = new char[1024];
		int blen = 0;
		int p = 0;
		int pe = len;
		
		String _s;
		{
			int _trans = 0;
			int _have = 0;
			int _cont = 1;
			int _acts;
			int _nacts;
			int _keys;
			int _inds;
			while ( _cont == 1  )
			{
				if ( cs == 0  )
				_cont = 0;
				
				_have = 0;
				if ( p == pe  )
				{
					if ( _have == 0  )
					_cont = 0;
					
					
				}
				
				if ( _cont == 1  )
				{
					if ( _have == 0  )
					{
						_keys = (cs<<1) ;
						_inds = _state_chart_index_offsets[cs] ;
						if ( ( data[p ]) <= 57 && ( data[p ]) >= 10  )
						{
							int _ic = (int)_state_chart_char_class[(int)( data[p ]) - 10];
							if ( _ic <= (int)_state_chart_trans_keys[_keys+1 ]&& _ic >= (int)_state_chart_trans_keys[_keys ] )
							_trans = (int )_state_chart_indicies[_inds + (int)( _ic - (int)_state_chart_trans_keys[_keys ])  ];
							
							else
							_trans = (int )_state_chart_index_defaults[cs];
							
							
						}
						
						else
						{
							_trans = (int )_state_chart_index_defaults[cs];
							
						}
						
						
					}
					
					if ( _cont == 1  )
					{
						cs = (int)_state_chart_cond_targs[_trans];
						if ( _state_chart_cond_actions[_trans] != 0  )
						{
							_acts = _state_chart_cond_actions[_trans] ;
							_nacts = (int )_state_chart_actions[_acts ];
							_acts += 1;
							while ( _nacts > 0  )
							{
								switch ( _state_chart_actions[_acts ] ) {
									case 0 :
									{
										neg = 0;
										value = 0;
										
									}
									
									break;
									case 1 :
									{
										neg = 1;
										
									}
									
									break;
									case 2 :
									{
										value = value * 10 + ( int ) ( (( data[p ])) - 48 )
										;
										
									}
									
									break;
									case 3 :
									{
										if ( neg != 0 )
										{
											value = -1 * value;
											
										} 
										
									}
									
									break;
									case 4 :
									{
										System.out.print( value );
										System.out.print( "\n" );
										
									}
									
									break;
									
								}
								_nacts -= 1;
								_acts += 1;
								
							}
							
							
						}
						
						if ( cs == 0  )
						_cont = 0;
						
						if ( _cont == 1  )
						p += 1;
						
						
					}
					
					
				}
				
				
			}
			
			
		}
	}
	
	void finish( )
	{
		if ( cs >= state_chart_first_final )
		System.out.println( "ACCEPT" );
		else
		System.out.println( "FAIL" );
	}
	
	static final String inp[] = {
		"1\n",
		"12\n",
		"222222\n",
		"+2123\n",
		"213 3213\n",
		"-12321\n",
		"--123\n",
		"-99\n",
		" -3000\n",
	};
	
	static final int inplen = 9;
	
	public static void main (String[] args)
	{
		atoi2_java machine = new atoi2_java();
		for ( int i = 0; i < inplen; i++ ) {
			machine.init();
			machine.exec( inp[i].toCharArray(), inp[i].length() );
			machine.finish();
		}
	}
}
