class atoi1_java
{
	int neg ;
	int value ;
	
	
	
	
	
	private static char  _atoi_trans_keys [] = { 1, 0, 2, 4, 4, 4, 0, 4, 1, 0, 0,  };
	private static byte  _atoi_char_class [] = { 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 3, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0 ,  };
	private static byte  _atoi_index_offsets [] = { 0, 0, 3, 4, 9, 0 ,  };
	private static byte  _atoi_indicies [] = { 0, 2, 3, 4, 5, 1, 1, 1, 4, 0 ,  };
	private static byte  _atoi_index_defaults [] = { 0, 1, 1, 1, 1, 0 ,  };
	private static byte  _atoi_trans_cond_spaces [] = { -1, -1, -1, -1, -1, -1, 0 ,  };
	private static byte  _atoi_cond_targs [] = { 2, 0, 2, 3, 3, 4, 0 ,  };
	private static byte  _atoi_cond_actions [] = { 1, 0, 2, 3, 4, 5, 0 ,  };
	private static byte  _atoi_nfa_targs [] = { 0, 0 ,  };
	private static byte  _atoi_nfa_offsets [] = { 0, 0, 0, 0, 0, 0 ,  };
	private static byte  _atoi_nfa_push_actions [] = { 0, 0 ,  };
	private static byte  _atoi_nfa_pop_trans [] = { 0, 0 ,  };
	private static int  atoi_start  = 1;
	private static int  atoi_first_final  = 4;
	private static int  atoi_error  = 0;
	private static int  atoi_en_main  = 1;
	int cs;
	
	void init()
	{
		value = 0;
		neg = 0;
		{
			cs = (int)atoi_start;
			
		}
	}
	
	void exec( char data[], int len )
	{
		char buffer [] = new char[1024];
		int blen = 0;
		int p = 0;
		int pe = len;
		
		String _s;
		{
			int _trans = 0;
			int _have = 0;
			int _cont = 1;
			int _keys;
			int _inds;
			while ( _cont == 1  )
			{
				if ( cs == 0  )
				_cont = 0;
				
				_have = 0;
				if ( p == pe  )
				{
					if ( _have == 0  )
					_cont = 0;
					
					
				}
				
				if ( _cont == 1  )
				{
					if ( _have == 0  )
					{
						_keys = (cs<<1) ;
						_inds = _atoi_index_offsets[cs] ;
						if ( ( data[p ]) <= 57 && ( data[p ]) >= 10  )
						{
							int _ic = (int)_atoi_char_class[(int)( data[p ]) - 10];
							if ( _ic <= (int)_atoi_trans_keys[_keys+1 ]&& _ic >= (int)_atoi_trans_keys[_keys ] )
							_trans = (int )_atoi_indicies[_inds + (int)( _ic - (int)_atoi_trans_keys[_keys ])  ];
							
							else
							_trans = (int )_atoi_index_defaults[cs];
							
							
						}
						
						else
						{
							_trans = (int )_atoi_index_defaults[cs];
							
						}
						
						
					}
					
					if ( _cont == 1  )
					{
						cs = (int)_atoi_cond_targs[_trans];
						switch ( _atoi_cond_actions[_trans]  ) {
							case 1 :
							{
								neg = 0;
								value = 0;
								
							}
							
							break;
							case 4 :
							{
								value = value * 10 + ( int ) ( (( data[p ])) - 48 )
								;
								
							}
							
							break;
							case 2 :
							{
								neg = 0;
								value = 0;
								
							}
							{
								neg = 1;
								
							}
							
							break;
							case 3 :
							{
								neg = 0;
								value = 0;
								
							}
							{
								value = value * 10 + ( int ) ( (( data[p ])) - 48 )
								;
								
							}
							
							break;
							case 5 :
							{
								if ( neg != 0 )
								{
									value = -1 * value;
									
								} 
								
							}
							{
								System.out.print( value );
								System.out.print( "\n" );
								
							}
							
							break;
							
						}
						if ( cs == 0  )
						_cont = 0;
						
						if ( _cont == 1  )
						p += 1;
						
						
					}
					
					
				}
				
				
			}
			
			
		}
	}
	
	void finish( )
	{
		if ( cs >= atoi_first_final )
		System.out.println( "ACCEPT" );
		else
		System.out.println( "FAIL" );
	}
	
	static final String inp[] = {
		"1\n",
		"12\n",
		"222222\n",
		"+2123\n",
		"213 3213\n",
		"-12321\n",
		"--123\n",
		"-99\n",
		" -3000\n",
	};
	
	static final int inplen = 9;
	
	public static void main (String[] args)
	{
		atoi1_java machine = new atoi1_java();
		for ( int i = 0; i < inplen; i++ ) {
			machine.init();
			machine.exec( inp[i].toCharArray(), inp[i].length() );
			machine.finish();
		}
	}
}
