import crack.io cout;
import crack.lang Buffer;







const array[byte ] _indep_trans_keys = [ 1, 0, 2, 3, 9, 9, 8, 8, 10, 10, 10, 10, 11, 11, 0, 0, 5, 9, 4, 8, 6, 10, 6, 10, 7, 11, 1, 0, 0,  ];
const array[int16 ] _indep_char_class = [ 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 5, 1, 1, 1, 6, 1, 1, 7, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 8, 1, 1, 9, 1, 1, 1, 10, 1, 1, 11, 0 ,  ];
const array[int16 ] _indep_index_offsets = [ 0, 0, 2, 3, 4, 5, 6, 7, 8, 13, 18, 23, 28, 33, 0 ,  ];
const array[int16 ] _indep_indicies = [ 0, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 9, 10, 1, 1, 1, 10, 11, 1, 1, 1, 11, 12, 1, 1, 1, 12, 7, 1, 1, 1, 7, 0 ,  ];
const array[int16 ] _indep_index_defaults = [ 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0 ,  ];
const array[int16 ] _indep_trans_cond_spaces = [ -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0 ,  ];
const array[int16 ] _indep_cond_targs = [ 2, 0, 8, 3, 4, 5, 6, 7, 13, 9, 10, 11, 12, 0 ,  ];
const array[int16 ] _indep_cond_actions = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  ];
const array[int16 ] _indep_nfa_targs = [ 0, 0 ,  ];
const array[int16 ] _indep_nfa_offsets = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  ];
const array[int16 ] _indep_nfa_push_actions = [ 0, 0 ,  ];
const array[int16 ] _indep_nfa_pop_trans = [ 0, 0 ,  ];
const int  indep_start  = 1;
const int  indep_first_final  = 13;
const int  indep_error  = 0;
const int  indep_en_main  = 1;
void m( String s )
{
	byteptr data = s.buffer;
	int p = 0;
	int pe = s.size;
	int cs;
	String buffer;
	
	if ( 1 ) {
		cs = int ( indep_start );
		
	}
	if ( 1 ) {
		uint32 _trans = 0;
		uint32 _have = 0;
		uint32 _cont = 1;
		int _keys = 0;
		int _inds = 0;
		while ( _cont == 1  )
		{
			if ( cs == 0  )
			_cont = 0;
			
			_have = 0;
			if ( p == pe  )
			{
				if ( _have == 0  )
				_cont = 0;
				
				
			}
			
			if ( _cont == 1  )
			{
				if ( _have == 0  )
				{
					_keys = (cs<<1);
					_inds = _indep_index_offsets[cs];
					if ( (data[p ])<= 111 && (data[p ])>= 10  )
					{
						int _ic = int ( _indep_char_class[int ( (data[p ]) )- 10] );
						if ( _ic <= int ( _indep_trans_keys[_keys+1 ] )&& _ic >= int ( _indep_trans_keys[_keys ] ) )
						_trans = uint32  ( _indep_indicies[_inds + int ( (_ic - int ( _indep_trans_keys[_keys ] )) )] );
						
						else
						_trans = uint32  ( _indep_index_defaults[cs] );
						
						
					}
					
					else
					{
						_trans = uint32  ( _indep_index_defaults[cs] );
						
					}
					
					
				}
				
				if ( _cont == 1  )
				{
					cs = int ( _indep_cond_targs[_trans] );
					if ( cs == 0  )
					_cont = 0;
					
					if ( _cont == 1  )
					p += 1;
					
					
				}
				
				
			}
			
			
		}
		
		
	}
	if ( cs >= indep_first_final ) {
		cout `ACCEPT\n`;
	}
	else {
		cout `FAIL\n`;
	}
}

void main()
{
	m( "1hello\n" );
	m( "1HELLO\n" );
	m( "1HeLLo\n" );
	m( "2hello\n" );
	m( "2HELLO\n" );
	m( "2HeLLo\n" );
	m( "3hello\n" );
	m( "3HELLO\n" );
	m( "3HeLLo\n" );
	m( "4hello\n" );
	m( "4HELLO\n" );
	m( "4HeLLo\n" );
	m( "5hello\n" );
	m( "5HELLO\n" );
	m( "5HeLLo\n" );
	m( "6hello\n" );
	m( "6HELLO\n" );
	m( "6HeLLo\n" );
}

main();
