#include <string.h>
#include <stdio.h>

int i ;
int j ;
int k ;





static const char  _foo_actions [] = { 0, 1, 0, 1, 1, 1, 2, 1, 3, 1, 4, 1, 5, 1, 6, 2, 0, 1, 2, 0, 2, 2, 1, 2, 3, 0, 1, 2, 0 ,  };
static const char  _foo_trans_keys [] = { 1, 0, 2, 2, 2, 2, 2, 2, 3, 4, 3, 4, 3, 4, 5, 5, 0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 0, 0 ,  };
static const char  _foo_char_class [] = { 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 4, 5, 0 ,  };
static const char  _foo_index_offsets [] = { 0, 0, 1, 2, 3, 5, 7, 9, 10, 11, 12, 13, 14, 15, 16, 17, 0 ,  };
static const char  _foo_indicies [] = { 0, 2, 3, 4, 5, 6, 7, 6, 8, 9, 10, 11, 12, 13, 14, 15, 16, 0 ,  };
static const char  _foo_index_defaults [] = { 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0 ,  };
static const char  _foo_trans_cond_spaces [] = { -1, -1, -1, -1, -1, 1, -1, 5, 4, -1, -1, -1, -1, -1, -1, -1, -1, 0 ,  };
static const char  _foo_trans_offsets [] = { 0, 1, 2, 3, 4, 5, 7, 8, 16, 20, 21, 22, 23, 24, 25, 26, 27, 0 ,  };
static const char  _foo_cond_targs [] = { 2, 0, 3, 4, 5, 0, 7, 6, 0, 11, 7, 12, 9, 13, 10, 14, 0, 7, 9, 10, 8, 15, 8, 8, 8, 8, 8, 8, 0 ,  };
static const char  _foo_cond_actions [] = { 7, 0, 9, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 13, 5, 21, 1, 15, 18, 24, 0 ,  };
static const char  _foo_nfa_targs [] = { 0, 0 ,  };
static const char  _foo_nfa_offsets [] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  };
static const char  _foo_nfa_push_actions [] = { 0, 0 ,  };
static const char  _foo_nfa_pop_trans [] = { 0, 0 ,  };
static const int  foo_start  = 1;
static const int  foo_first_final  = 15;
static const int  foo_error  = 0;
static const int  foo_en_main  = 1;
int cs;
int blen;
char buffer[1024];

void init()
{

	{
		cs = ( int ) foo_start;
	}
}

void exec( char *data, int len )
{
	char *p = data;
	char *pe = data + len;
	
	{
		unsigned int _trans = 0;
		unsigned int _have = 0;
		unsigned int _cont = 1;
		unsigned int _cond = 0;
		const char  *_acts;
		unsigned int _nacts;
		const char  *_keys;
		const char  *_inds;
		int _cpc;
		while ( _cont == 1  )
		{
		
			if ( cs == 0  )
			_cont = 0;
			
			_have = 0;
			if ( p == pe  )
			{
				if ( _have == 0  )
				_cont = 0;
				
			}
			
			if ( _cont == 1  )
			{
				if ( _have == 0  )
				{
					_keys = _foo_trans_keys + (cs<<1);
					_inds = _foo_indicies + _foo_index_offsets[cs];
					if ( ((*( p  ))
					)<= 99 && ((*( p  ))
					)>= 10  )
					{
						int _ic = ( int ) _foo_char_class[( int ) ((*( p  ))
						)- 10];
						if ( _ic <= ( int ) (*( _keys+1  ))
						&& _ic >= ( int ) (*( _keys  ))
						)
						_trans = ( unsigned int  ) (*( _inds + ( int ) (_ic - ( int ) (*( _keys  ))
						) ))
						;
						
						else
						_trans = ( unsigned int  ) _foo_index_defaults[cs];
						
					}
					
					else
					{
						_trans = ( unsigned int  ) _foo_index_defaults[cs];
					}
					
					
					_cond = ( unsigned int  ) _foo_trans_offsets[_trans];
					_cpc = 0;
					switch ( _foo_trans_cond_spaces[_trans] ) {
						case 0 :
						if ( (i != 0) )
						_cpc += 1;
						
						
						break;
						case 1 :
						if ( (j != 0) )
						_cpc += 1;
						
						
						break;
						case 2 :
						if ( (k != 0) )
						_cpc += 1;
						
						
						break;
						case 3 :
						if ( (i != 0) )
						_cpc += 1;
						
						if ( (j != 0) )
						_cpc += 2;
						
						
						break;
						case 4 :
						if ( (j != 0) )
						_cpc += 1;
						
						if ( (k != 0) )
						_cpc += 2;
						
						
						break;
						case 5 :
						if ( (i != 0) )
						_cpc += 1;
						
						if ( (j != 0) )
						_cpc += 2;
						
						if ( (k != 0) )
						_cpc += 4;
						
						
						break;
						
					}
					_cond += ( unsigned int  ) _cpc;
				}
				
				if ( _cont == 1  )
				{
					cs = ( int ) _foo_cond_targs[_cond];
					if ( _foo_cond_actions[_cond]!= 0  )
					{
						_acts = _foo_actions + _foo_cond_actions[_cond];
						_nacts = ( unsigned int  ) (*( _acts  ))
						;
						_acts += 1;
						while ( _nacts > 0  )
						{
							switch ( (*( _acts  ))
							) {
								case 0 :
								{
									printf( "%s", "  one\n" );
									
								}
								
								break;
								case 1 :
								{
									printf( "%s", "  two\n" );
									
								}
								
								break;
								case 2 :
								{
									printf( "%s", "  three\n" );
									
								}
								
								break;
								case 3 :
								{
									if ( (((*( p  ))
									)) == 48 )
									{
										i = 0;
										
									} 
									else {
										i = 1;
										
									}
									
								}
								
								break;
								case 4 :
								{
									if ( (((*( p  ))
									)) == 48 )
									{
										j = 0;
										
									} 
									else {
										j = 1;
										
									}
									
								}
								
								break;
								case 5 :
								{
									if ( (((*( p  ))
									)) == 48 )
									{
										k = 0;
										
									} 
									else {
										k = 1;
										
									}
									
								}
								
								break;
								case 6 :
								{
									{
										p+= 1;
										_cont = 0;
										
									}
									
								}
								
								break;
								
							}
							_nacts -= 1;
							_acts += 1;
						}
						
					}
					
					
					if ( cs == 0  )
					_cont = 0;
					
					if ( _cont == 1  )
					p += 1;
					
				}
			}
			
		}
		
	}
}

void finish( )
{
	if ( cs >= foo_first_final )
	printf( "ACCEPT\n" );
	else
	printf( "FAIL\n" );
}

char *inp[] = {
	"000abc\n",
	"100abc\n",
	"010abc\n",
	"110abc\n",
	"001abc\n",
	"101abc\n",
	"011abc\n",
	"111abc\n",
};

int inplen = 8;

int main( )
{
	int i;
	for ( i = 0; i < inplen; i++ ) {
		init();
		exec( inp[i], strlen(inp[i]) );
		finish();
	}
	return 0;
}

