(*
* @LANG: ocaml
* @GENERATED: true
*)

let i = ref 0
let c = ref 0






let _foo_key_offsets : int array = [|
0; 0; 2; 4; 7; 0 ; 
|]
let _foo_trans_keys : int array = [|
48; 57; 48; 57; 10; 48; 57; 0 ; 
|]
let _foo_single_lengths : int array = [|
0; 0; 0; 1; 0; 0 ; 
|]
let _foo_range_lengths : int array = [|
0; 1; 1; 1; 0; 0 ; 
|]
let _foo_index_offsets : int array = [|
0; 0; 2; 4; 7; 0 ; 
|]
let _foo_trans_cond_spaces : int array = [|
-1; -1; 0; -1; 0; 0; -1; -1; 0 ; 
|]
let _foo_trans_offsets : int array = [|
0; 1; 2; 4; 5; 6; 7; 8; 0 ; 
|]
let _foo_trans_lengths : int array = [|
1; 1; 2; 1; 1; 1; 1; 1; 0 ; 
|]
let _foo_cond_keys : int array = [|
0; 0; 0; 1; 0; 0; 1; 0; 0; 0 ; 
|]
let _foo_cond_targs : int array = [|
2; 0; 3; 2; 0; 4; 3; 0; 0; 0 ; 
|]
let _foo_cond_actions : int array = [|
1; 0; 1; 2; 0; 0; 2; 0; 0; 0 ; 
|]
let _foo_nfa_targs : int array = [|
0; 0 ; 
|]
let _foo_nfa_offsets : int array = [|
0; 0; 0; 0; 0; 0 ; 
|]
let _foo_nfa_push_actions : int array = [|
0; 0 ; 
|]
let _foo_nfa_pop_trans : int array = [|
0; 0 ; 
|]
let foo_start  : int  = 1
let foo_first_final  : int  = 4
let foo_error  : int  = 0
let foo_en_main  : int  = 1
let exec data = 
let buffer = String.create(1024) in 
let blen :int ref = ref 0 in
let cs = ref 0 in
let p = ref 0 in
let pe = ref (String.length data) in
begin
	cs  := foo_start;
	
end;
begin
	let _klen : int  ref = ref 0 in
	let _keys : int ref = ref 0 in
	let _ckeys : int ref = ref 0 in
	let _cpc : int  ref = ref 0 in
	let _trans : int  ref = ref 0 in
	let _cond  : int  ref = ref 0 in
	let _have  : int  ref = ref 0 in
	let _cont  : int  ref = ref 1 in
	while _cont.contents= 1  do
	begin
		if cs.contents= 0  then
		begin
			_cont  := 0;
			
		end
		;_have  := 0;
		if p.contents= pe.contents then
		begin
			begin
				if _have.contents= 0  then
				begin
					_cont  := 0;
					
				end
				;
			end;
			
		end
		;if _cont.contents= 1  then
		begin
			begin
				if _have.contents= 0  then
				begin
					begin
						_keys  := _foo_key_offsets.(cs.contents);
						_trans  := _foo_index_offsets.(cs.contents);
						_have  := 0;
						_klen  := _foo_single_lengths.(cs.contents);
						if _klen.contents> 0  then
						begin
							begin
								let _lower : int ref = ref 0 in
								let _mid : int ref = ref 0 in
								let _upper : int ref = ref 0 in
								_lower  := _keys.contents;
								_upper  := _keys.contents+ _klen.contents- 1;
								while _upper.contents>= _lower.contents&& _have.contents= 0  do
								begin
									_mid  := _lower.contents+ ( ( _upper.contents-_lower.contents ) asr 1 );
									if ( Char.code data.[p.contents] )< _foo_trans_keys.( _mid.contents ) then
									begin
										_upper  := _mid.contents- 1;
										
									end
									else if ( Char.code data.[p.contents] )> _foo_trans_keys.( _mid.contents ) then
									begin
										_lower  := _mid.contents+ 1;
										
									end
									else
									begin
										begin
											_trans  := _trans.contents + ( _mid.contents- _keys.contents );
											_have  := 1;
											
										end;
										
									end
									;
								end;
								
								done;
								if _have.contents= 0  then
								begin
									begin
										_keys  := _keys.contents + _klen.contents;
										_trans  := _trans.contents + _klen.contents;
										
									end;
									
								end
								;
							end;
							
						end
						;if _have.contents= 0  then
						begin
							begin
								_klen  := _foo_range_lengths.(cs.contents);
								if _klen.contents> 0  then
								begin
									begin
										let _lower : int ref = ref 0 in
										let _mid : int ref = ref 0 in
										let _upper : int ref = ref 0 in
										_lower  := _keys.contents;
										_upper  := _keys.contents+ ( _klen.contents lsl 1 )- 2;
										while _have.contents= 0 && _lower.contents<= _upper.contents do
										begin
											_mid  := _lower.contents+ ( ( ( _upper.contents-_lower.contents ) asr 1 ) land  lnot 1 );
											if ( Char.code data.[p.contents] )< _foo_trans_keys.( _mid.contents ) then
											begin
												_upper  := _mid.contents- 2;
												
											end
											else if ( Char.code data.[p.contents] )> _foo_trans_keys.( _mid.contents+ 1  ) then
											begin
												_lower  := _mid.contents+ 2;
												
											end
											else
											begin
												begin
													_trans  := _trans.contents + ( ( _mid.contents- _keys.contents ) asr 1 );
													_have  := 1;
													
												end;
												
											end
											;
										end;
										
										done;
										if _have.contents= 0  then
										begin
											_trans  := _trans.contents + _klen.contents;
											
										end
										;
									end;
									
								end
								;
							end;
							
						end
						;_ckeys  := _foo_trans_offsets.(_trans.contents);
						_klen  := _foo_trans_lengths.(_trans.contents);
						_cond  := _foo_trans_offsets.(_trans.contents);
						_have  := 0;
						_cpc  := 0;
						if _foo_trans_cond_spaces.(_trans.contents) = 0  then
						begin
							if (i .contents > 0) then
							begin
								_cpc  := _cpc.contents + 1;
								
							end
							;
						end
						;
						begin
							let _lower : int ref = ref 0 in
							let _mid : int ref = ref 0 in
							let _upper : int ref = ref 0 in
							_lower  := _ckeys.contents;
							_upper  := _ckeys.contents+ _klen.contents- 1;
							while _have.contents= 0 && _lower.contents<= _upper.contents do
							begin
								_mid  := _lower.contents+ ( ( _upper.contents-_lower.contents ) asr 1 );
								if _cpc.contents< _foo_cond_keys.( _mid.contents ) then
								begin
									_upper  := _mid.contents- 1;
									
								end
								else if _cpc.contents> _foo_cond_keys.( _mid.contents ) then
								begin
									_lower  := _mid.contents+ 1;
									
								end
								else
								begin
									begin
										_cond  := _cond.contents + ( _mid.contents- _ckeys.contents );
										_have  := 1;
										
									end;
									
								end
								;
							end;
							
							done;
							if _have.contents= 0  then
							begin
								begin
									cs  := 0;
									_cont  := 0;
									
								end;
								
							end
							;
						end;
						
					end;
					
				end
				;if _cont.contents= 1  then
				begin
					begin
						cs  := _foo_cond_targs.(_cond.contents);
						if _foo_cond_actions.(_cond.contents) = 2  then
						begin
							begin
								i := i .contents - 1;
								c := ( (( Char.code data.[p.contents] )) )
								;
								print_string( "item: " );
								print_int( c.contents );
								print_string( "\n" );
								
							end;
							
						end
						else if _foo_cond_actions.(_cond.contents) = 1  then
						begin
							begin
								i := ( (( Char.code data.[p.contents] )) - 48 )
								;
								print_string( "count: " );
								print_int( i.contents );
								print_string( "\n" );
								
							end;
							
						end
						;
						if cs.contents= 0  then
						begin
							_cont  := 0;
							
						end
						;if _cont.contents= 1  then
						begin
							p  := p.contents + 1;
							
						end
						;
					end;
					
				end
				;
			end;
			
		end
		;
	end;
	
	done;
	
end;
if !cs >= foo_first_final then
print_string "ACCEPT\n"
else
print_string "FAIL\n"
;;

let () =
exec "00\n";
exec "019\n";
exec "190\n";
exec "1719\n";
exec "1040000\n";
exec "104000a\n";
exec "104000\n";
()
;;

