#
# @LANG: ruby
# @GENERATED: true
#







class << self
	attr_accessor :_indep_key_offsets 
	private :_indep_key_offsets, :_indep_key_offsets=
end
self._indep_key_offsets = [
0, 0, 4, 5, 6, 7, 8, 9, 10, 12, 14, 16, 18, 20, 0 , 
]

class << self
	attr_accessor :_indep_trans_keys 
	private :_indep_trans_keys, :_indep_trans_keys=
end
self._indep_trans_keys = [
49, 51, 52, 54, 104, 101, 108, 108, 111, 10, 72, 104, 69, 101, 76, 108, 76, 108, 79, 111, 0 , 
]

class << self
	attr_accessor :_indep_single_lengths 
	private :_indep_single_lengths, :_indep_single_lengths=
end
self._indep_single_lengths = [
0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 0, 0 , 
]

class << self
	attr_accessor :_indep_range_lengths 
	private :_indep_range_lengths, :_indep_range_lengths=
end
self._indep_range_lengths = [
0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 , 
]

class << self
	attr_accessor :_indep_index_offsets 
	private :_indep_index_offsets, :_indep_index_offsets=
end
self._indep_index_offsets = [
0, 0, 3, 5, 7, 9, 11, 13, 15, 18, 21, 24, 27, 30, 0 , 
]

class << self
	attr_accessor :_indep_trans_cond_spaces 
	private :_indep_trans_cond_spaces, :_indep_trans_cond_spaces=
end
self._indep_trans_cond_spaces = [
-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0 , 
]

class << self
	attr_accessor :_indep_trans_offsets 
	private :_indep_trans_offsets, :_indep_trans_offsets=
end
self._indep_trans_offsets = [
0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 0 , 
]

class << self
	attr_accessor :_indep_trans_lengths 
	private :_indep_trans_lengths, :_indep_trans_lengths=
end
self._indep_trans_lengths = [
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0 , 
]

class << self
	attr_accessor :_indep_cond_keys 
	private :_indep_cond_keys, :_indep_cond_keys=
end
self._indep_cond_keys = [
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 , 
]

class << self
	attr_accessor :_indep_cond_targs 
	private :_indep_cond_targs, :_indep_cond_targs=
end
self._indep_cond_targs = [
2, 8, 0, 3, 0, 4, 0, 5, 0, 6, 0, 7, 0, 13, 0, 9, 9, 0, 10, 10, 0, 11, 11, 0, 12, 12, 0, 7, 7, 0, 0, 0 , 
]

class << self
	attr_accessor :_indep_cond_actions 
	private :_indep_cond_actions, :_indep_cond_actions=
end
self._indep_cond_actions = [
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 , 
]

class << self
	attr_accessor :_indep_nfa_targs 
	private :_indep_nfa_targs, :_indep_nfa_targs=
end
self._indep_nfa_targs = [
0, 0 , 
]

class << self
	attr_accessor :_indep_nfa_offsets 
	private :_indep_nfa_offsets, :_indep_nfa_offsets=
end
self._indep_nfa_offsets = [
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 , 
]

class << self
	attr_accessor :_indep_nfa_push_actions 
	private :_indep_nfa_push_actions, :_indep_nfa_push_actions=
end
self._indep_nfa_push_actions = [
0, 0 , 
]

class << self
	attr_accessor :_indep_nfa_pop_trans 
	private :_indep_nfa_pop_trans, :_indep_nfa_pop_trans=
end
self._indep_nfa_pop_trans = [
0, 0 , 
]

class << self
	attr_accessor :indep_start 
end
self.indep_start  = 1;

class << self
	attr_accessor :indep_first_final 
end
self.indep_first_final  = 13;

class << self
	attr_accessor :indep_error 
end
self.indep_error  = 0;

class << self
	attr_accessor :indep_en_main 
end
self.indep_en_main  = 1;

def run_machine( data )
	p = 0
	pe = data.length
	eof = data.length
	cs = 0;
	_m = 
	_a = 
	buffer = Array.new
	blen = 0
	begin
		cs = indep_start;
		
	end
	begin
		_klen= 0
		;
		_trans = 0;
		_cond = 0;
		_have = 0;
		_cont = 1;
		_keys = 0;
		_ckeys = 0;
		_cpc= 0
		;
		while ( _cont == 1  )
			begin
				if ( cs == 0  )
					_cont = 0;
					
				end
				_have = 0;
				if ( p == pe  )
					begin
						if ( _have == 0  )
							_cont = 0;
							
						end
						
					end
					
				end
				if ( _cont == 1  )
					begin
						if ( _have == 0  )
							begin
								_keys = _indep_key_offsets[cs] ;
								_trans = _indep_index_offsets[cs];
								_have = 0;
								_klen = _indep_single_lengths[cs];
								if ( _klen > 0  )
									begin
										_lower = 0;
										_mid = 0;
										_upper = 0;
										_lower = _keys;
										_upper = _keys + _klen - 1;
										while ( _upper >= _lower && _have == 0  )
											begin
												_mid = _lower + ((_upper-_lower) >> 1);
												if ( ( data[p ].ord) < _indep_trans_keys[_mid ] )
													_upper = _mid - 1;
													
													elsif ( ( data[p ].ord) > _indep_trans_keys[_mid ] )
													_lower = _mid + 1;
													
													else
													begin
														_trans += (_mid - _keys);
														_have = 1;
														
													end
													
												end
												
											end
											
										end
										if ( _have == 0  )
											begin
												_keys += _klen;
												_trans += _klen;
												
											end
											
										end
										
									end
									
								end
								if ( _have == 0  )
									begin
										_klen = _indep_range_lengths[cs];
										if ( _klen > 0  )
											begin
												_lower = 0;
												_mid = 0;
												_upper = 0;
												_lower = _keys;
												_upper = _keys + (_klen<<1) - 2;
												while ( _have == 0 && _lower <= _upper  )
													begin
														_mid = _lower + (((_upper-_lower) >> 1) & ~1);
														if ( ( data[p ].ord) < _indep_trans_keys[_mid ] )
															_upper = _mid - 2;
															
															elsif ( ( data[p ].ord) > _indep_trans_keys[_mid + 1 ] )
															_lower = _mid + 2;
															
															else
															begin
																_trans += ((_mid - _keys)>>1);
																_have = 1;
																
															end
															
														end
														
													end
													
												end
												if ( _have == 0  )
													_trans += _klen;
													
												end
												
											end
											
										end
										
									end
									
								end
								_ckeys = _indep_trans_offsets[_trans] ;
								_klen = _indep_trans_lengths[_trans];
								_cond = _indep_trans_offsets[_trans];
								_have = 0;
								_cpc = 0;
								begin
									_lower = 0;
									_mid = 0;
									_upper = 0;
									_lower = _ckeys;
									_upper = _ckeys + _klen - 1;
									while ( _have == 0 && _lower <= _upper  )
										begin
											_mid = _lower + ((_upper-_lower) >> 1);
											if ( _cpc < _indep_cond_keys[_mid ] )
												_upper = _mid - 1;
												
												elsif ( _cpc > _indep_cond_keys[_mid ] )
												_lower = _mid + 1;
												
												else
												begin
													_cond += (_mid - _ckeys);
													_have = 1;
													
												end
												
											end
											
										end
										
									end
									if ( _have == 0  )
										begin
											cs = 0;
											_cont = 0;
											
										end
										
									end
									
								end
								
							end
							
						end
						if ( _cont == 1  )
							begin
								cs = _indep_cond_targs[_cond];
								if ( cs == 0  )
									_cont = 0;
									
								end
								if ( _cont == 1  )
									p += 1;
									
								end
								
							end
							
						end
						
					end
					
				end
				
			end
			
		end
		
	end
	if cs >= indep_first_final
		puts "ACCEPT"
		else
		puts "FAIL"
	end
end

inp = [
"1hello\n",
"1HELLO\n",
"1HeLLo\n",
"2hello\n",
"2HELLO\n",
"2HeLLo\n",
"3hello\n",
"3HELLO\n",
"3HeLLo\n",
"4hello\n",
"4HELLO\n",
"4HeLLo\n",
"5hello\n",
"5HELLO\n",
"5HeLLo\n",
"6hello\n",
"6HELLO\n",
"6HeLLo\n",
]

inplen = 18

inp.each { |str| run_machine(str) }

