(*
* @LANG: ocaml
*)

let id x = x
let fail fmt = Printf.ksprintf failwith fmt
let pr fmt = Printf.ksprintf print_endline fmt

let failed fmt = Printf.ksprintf (fun s -> prerr_endline s; exit 1) fmt
let test' show f x y = if f x <> y then failed "FAILED: test %S" (show x)
let case = ref 0
let test f x y = incr case; if f x <> y then failed "FAILED: case %d" !case
let error f x = match try Some (f x) with _ -> None with Some _ -> failed "FAILED: fail %S" x | None -> ()


let _cond_actions : int array = [|
0; 1; 0; 0 ; 
|]
let _cond_key_offsets : int array = [|
0; 0; 2; 5; 6; 0 ; 
|]
let _cond_trans_keys : int array = [|
48; 57; 58; 48; 57; 100; 100; 97; 122; 0 ; 
|]
let _cond_single_lengths : int array = [|
0; 0; 1; 1; 1; 0 ; 
|]
let _cond_range_lengths : int array = [|
0; 1; 1; 0; 1; 0 ; 
|]
let _cond_index_offsets : int array = [|
0; 0; 2; 5; 7; 0 ; 
|]
let _cond_trans_cond_spaces : int array = [|
-1; -1; -1; -1; -1; -1; -1; 0; 0; -1; 0 ; 
|]
let _cond_trans_offsets : int array = [|
0; 1; 2; 3; 4; 5; 6; 7; 9; 10; 0 ; 
|]
let _cond_trans_lengths : int array = [|
1; 1; 1; 1; 1; 1; 1; 2; 1; 1; 0 ; 
|]
let _cond_cond_keys : int array = [|
0; 0; 0; 0; 0; 0; 0; 0; 1; 1; 0; 0 ; 
|]
let _cond_cond_targs : int array = [|
2; 0; 4; 2; 0; 1; 0; 1; 4; 4; 0; 0 ; 
|]
let _cond_cond_actions : int array = [|
0; 0; 0; 0; 0; 0; 0; 0; 1; 1; 0; 0 ; 
|]
let _cond_nfa_targs : int array = [|
0; 0 ; 
|]
let _cond_nfa_offsets : int array = [|
0; 0; 0; 0; 0; 0 ; 
|]
let _cond_nfa_push_actions : int array = [|
0; 0 ; 
|]
let _cond_nfa_pop_trans : int array = [|
0; 0 ; 
|]
let cond_start  : int  = 3
let cond_first_final  : int  = 3
let cond_error  : int  = 0
let cond_en_main  : int  = 3
let fail fmt = Printf.ksprintf failwith fmt

let run data n =
let cs = ref 0 in
let p = ref 0 in
let pe = ref (String.length data) in
let i = ref 0 in

begin
	cs  := cond_start;
	
end;
begin
	let _klen : int  ref = ref 0 in
	let _trans  : int  ref = ref 0 in
	let _cond  : int  ref = ref 0 in
	let _have  : int  ref = ref 0 in
	let _cont  : int  ref = ref 1 in
	let _acts : int ref = ref 0 in
	let _nacts : int  ref = ref 0 in
	let _keys : int ref = ref 0 in
	let _ckeys : int ref = ref 0 in
	let _cpc : int  ref = ref 0 in
	while _cont.contents= 1  do
	begin
		if cs.contents= 0  then
		begin
			_cont  := 0;
			
		end
		;_have  := 0;
		if p.contents= pe.contents then
		begin
			begin
				if _have.contents= 0  then
				begin
					_cont  := 0;
					
				end
				;
			end;
			
		end
		;if _cont.contents= 1  then
		begin
			begin
				if _have.contents= 0  then
				begin
					begin
						_keys  := _cond_key_offsets.(cs.contents);
						_trans  := _cond_index_offsets.(cs.contents);
						_have  := 0;
						_klen  := _cond_single_lengths.(cs.contents);
						if _klen.contents> 0  then
						begin
							begin
								let _lower : int ref = ref 0 in
								let _mid : int ref = ref 0 in
								let _upper : int ref = ref 0 in
								_lower  := _keys.contents;
								_upper  := _keys.contents+ _klen.contents- 1;
								while _upper.contents>= _lower.contents&& _have.contents= 0  do
								begin
									_mid  := _lower.contents+ ( ( _upper.contents-_lower.contents ) asr 1 );
									if ( Char.code data.[p.contents] )< _cond_trans_keys.( _mid.contents ) then
									begin
										_upper  := _mid.contents- 1;
										
									end
									else if ( Char.code data.[p.contents] )> _cond_trans_keys.( _mid.contents ) then
									begin
										_lower  := _mid.contents+ 1;
										
									end
									else
									begin
										begin
											_trans  := _trans.contents + ( _mid.contents- _keys.contents );
											_have  := 1;
											
										end;
										
									end
									;
								end;
								
								done;
								if _have.contents= 0  then
								begin
									begin
										_keys  := _keys.contents + _klen.contents;
										_trans  := _trans.contents + _klen.contents;
										
									end;
									
								end
								;
							end;
							
						end
						;if _have.contents= 0  then
						begin
							begin
								_klen  := _cond_range_lengths.(cs.contents);
								if _klen.contents> 0  then
								begin
									begin
										let _lower : int ref = ref 0 in
										let _mid : int ref = ref 0 in
										let _upper : int ref = ref 0 in
										_lower  := _keys.contents;
										_upper  := _keys.contents+ ( _klen.contents lsl 1 )- 2;
										while _have.contents= 0 && _lower.contents<= _upper.contents do
										begin
											_mid  := _lower.contents+ ( ( ( _upper.contents-_lower.contents ) asr 1 ) land  lnot 1 );
											if ( Char.code data.[p.contents] )< _cond_trans_keys.( _mid.contents ) then
											begin
												_upper  := _mid.contents- 2;
												
											end
											else if ( Char.code data.[p.contents] )> _cond_trans_keys.( _mid.contents+ 1  ) then
											begin
												_lower  := _mid.contents+ 2;
												
											end
											else
											begin
												begin
													_trans  := _trans.contents + ( ( _mid.contents- _keys.contents ) asr 1 );
													_have  := 1;
													
												end;
												
											end
											;
										end;
										
										done;
										if _have.contents= 0  then
										begin
											_trans  := _trans.contents + _klen.contents;
											
										end
										;
									end;
									
								end
								;
							end;
							
						end
						;_ckeys  := _cond_trans_offsets.(_trans.contents);
						_klen  := _cond_trans_lengths.(_trans.contents);
						_cond  := _cond_trans_offsets.(_trans.contents);
						_have  := 0;
						_cpc  := 0;
						if _cond_trans_cond_spaces.(_trans.contents) = 0  then
						begin
							if (i < n ) then
							begin
								_cpc  := _cpc.contents + 1;
								
							end
							;
						end
						;
						begin
							let _lower : int ref = ref 0 in
							let _mid : int ref = ref 0 in
							let _upper : int ref = ref 0 in
							_lower  := _ckeys.contents;
							_upper  := _ckeys.contents+ _klen.contents- 1;
							while _have.contents= 0 && _lower.contents<= _upper.contents do
							begin
								_mid  := _lower.contents+ ( ( _upper.contents-_lower.contents ) asr 1 );
								if _cpc.contents< _cond_cond_keys.( _mid.contents ) then
								begin
									_upper  := _mid.contents- 1;
									
								end
								else if _cpc.contents> _cond_cond_keys.( _mid.contents ) then
								begin
									_lower  := _mid.contents+ 1;
									
								end
								else
								begin
									begin
										_cond  := _cond.contents + ( _mid.contents- _ckeys.contents );
										_have  := 1;
										
									end;
									
								end
								;
							end;
							
							done;
							if _have.contents= 0  then
							begin
								begin
									cs  := 0;
									_cont  := 0;
									
								end;
								
							end
							;
						end;
						
					end;
					
				end
				;if _cont.contents= 1  then
				begin
					begin
						cs  := _cond_cond_targs.(_cond.contents);
						if _cond_cond_actions.(_cond.contents)!= 0  then
						begin
							begin
								_acts  := _cond_cond_actions.(_cond.contents);
								_nacts  := _cond_actions.( _acts.contents );
								_acts  := _acts.contents + 1;
								while _nacts.contents> 0  do
								begin
									if _cond_actions.( _acts.contents ) = 0  then
									begin
										begin
											i := i.contents + 1 
										end;
										
									end
									;
									_nacts  := _nacts.contents - 1;
									_acts  := _acts.contents + 1;
									
								end;
								
								done;
								
							end;
							
						end
						;if cs.contents= 0  then
						begin
							_cont  := 0;
							
						end
						;if _cont.contents= 1  then
						begin
							p  := p.contents + 1;
							
						end
						;
					end;
					
				end
				;
			end;
			
		end
		;
	end;
	
	done;
	
end;
if !cs < cond_first_final then
print_string "fail\n"
else
print_string "ok\n"

let () =
run "d2:abc" ( ref 1 );
run "d2:abc" ( ref 2 );
run "d2:abc" ( ref 3 );
run "d2:abc" ( ref 4 );

