using System;
// Disables lots of warnings that appear in the test suite
#pragma warning disable 0168, 0169, 0219, 0162, 0414
namespace Test {
	class Test
	{
		int i;
		int j;
		int k;
		
		
		
		
		static readonly sbyte  []_foo_key_offsets = { 0, 0, 2, 4, 6, 8, 10, 12, 13, 14, 15, 16, 17, 18, 19, 20, 0,  };
		static readonly char  []_foo_trans_keys = { '\u0030', '\u0031', '\u0030', '\u0031', '\u0030', '\u0031', '\u0061', '\u0062', '\u0061', '\u0062', '\u0061', '\u0062', '\u0063', '\u000a', '\u0063', '\u0063', '\u0063', '\u0063', '\u0063', '\u0063', '\u0000',  };
		static readonly sbyte  []_foo_single_lengths = { 0, 0, 0, 0, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,  };
		static readonly sbyte  []_foo_range_lengths = { 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  };
		static readonly sbyte  []_foo_index_offsets = { 0, 0, 2, 4, 6, 9, 12, 15, 17, 19, 21, 23, 25, 27, 29, 31, 0,  };
		static readonly sbyte  []_foo_trans_cond_spaces = { -1, -1, -1, -1, -1, -1, -1, 1, -1, -1, 5, -1, -1, 4, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0,  };
		static readonly sbyte  []_foo_trans_offsets = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 17, 18, 19, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 0,  };
		static readonly sbyte  []_foo_trans_lengths = { 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 7, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,  };
		static readonly sbyte  []_foo_cond_keys = { 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 2, 3, 4, 5, 6, 7, 0, 0, 1, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  };
		static readonly sbyte  []_foo_cond_targs = { 2, 0, 3, 0, 4, 0, 5, 7, 0, 6, 11, 7, 12, 9, 13, 10, 14, 0, 6, 7, 9, 10, 0, 8, 0, 15, 0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0, 0, 0,  };
		static readonly sbyte  []_foo_cond_actions = { 1, 0, 2, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 5, 0, 6, 0, 7, 0, 8, 0, 9, 0, 10, 0, 11, 0, 0, 0,  };
		static readonly sbyte  []_foo_nfa_targs = { 0, 0,  };
		static readonly sbyte  []_foo_nfa_offsets = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  };
		static readonly sbyte  []_foo_nfa_push_actions = { 0, 0,  };
		static readonly sbyte  []_foo_nfa_pop_trans = { 0, 0,  };
		static readonly int  foo_start  = 1;
		static readonly int  foo_first_final  = 15;
		static readonly int  foo_error  = 0;
		static readonly int  foo_en_main  = 1;
		int cs;
		
		void init()
		{
		
			{
				cs = (int)foo_start;
			}
		}
		
		void exec( char[] data, int len )
		{
			int p = 0;
			int pe = len;
			int eof = len;
			string _s;
			char [] buffer = new char [1024];
			int blen = 0;
			
			{
				int _klen;
				int _keys;
				int _ckeys;
				int _cpc;
				uint _trans = 0;
				uint _cond = 0;
				int _nbreak;
				if ( p == pe  )
				goto _test_eof;
				
				if ( cs == 0 )
				goto _out;
				
				_resume :
				_keys = _foo_key_offsets[cs] ;
				_trans = (uint )_foo_index_offsets[cs];
				_klen = (int)_foo_single_lengths[cs];
				if ( _klen > 0 )
				{
					int _lower;
					int _mid;
					int _upper;
					_lower = _keys;
					_upper = _keys + _klen - 1;
					while ( true  )
					{
						if ( _upper < _lower  )
						break;
						
						
						_mid = _lower + ((_upper-_lower) >> 1);
						if ( ( data[p ]) < _foo_trans_keys[_mid ] )
						_upper = _mid - 1;
						
						else if ( ( data[p ]) > _foo_trans_keys[_mid ] )
						_lower = _mid + 1;
						
						else
						{
							_trans += (uint )(_mid - _keys);
							goto _match;
						}
						
					}
					
					_keys += _klen;
					_trans += (uint )_klen;
				}
				
				
				_klen = (int)_foo_range_lengths[cs];
				if ( _klen > 0 )
				{
					int _lower;
					int _mid;
					int _upper;
					_lower = _keys;
					_upper = _keys + (_klen<<1) - 2;
					while ( true  )
					{
						if ( _upper < _lower  )
						break;
						
						
						_mid = _lower + (((_upper-_lower) >> 1) & ~1);
						if ( ( data[p ]) < _foo_trans_keys[_mid ] )
						_upper = _mid - 2;
						
						else if ( ( data[p ]) > _foo_trans_keys[_mid + 1] )
						_lower = _mid + 2;
						
						else
						{
							_trans += (uint )((_mid - _keys)>>1);
							goto _match;
						}
						
					}
					
					_trans += (uint )_klen;
				}
				
				
				
				_match :
				_ckeys = _foo_trans_offsets[_trans] ;
				_klen = (int)_foo_trans_lengths[_trans];
				_cond = (uint )_foo_trans_offsets[_trans];
				_cpc = 0;
				switch ( _foo_trans_cond_spaces[_trans]  ) {
					case 0:
					if ( (i != 0) )
					_cpc += 1;
					
					
					break;
					case 1:
					if ( (j != 0) )
					_cpc += 1;
					
					
					break;
					case 2:
					if ( (k != 0) )
					_cpc += 1;
					
					
					break;
					case 3:
					if ( (i != 0) )
					_cpc += 1;
					
					if ( (j != 0) )
					_cpc += 2;
					
					
					break;
					case 4:
					if ( (j != 0) )
					_cpc += 1;
					
					if ( (k != 0) )
					_cpc += 2;
					
					
					break;
					case 5:
					if ( (i != 0) )
					_cpc += 1;
					
					if ( (j != 0) )
					_cpc += 2;
					
					if ( (k != 0) )
					_cpc += 4;
					
					
					break;
					
				}
				{
					int _lower;
					int _mid;
					int _upper;
					_lower = _ckeys;
					_upper = _ckeys + _klen - 1;
					while ( true  )
					{
						if ( _upper < _lower  )
						break;
						
						
						_mid = _lower + ((_upper-_lower) >> 1);
						if ( _cpc < (int)_foo_cond_keys[_mid ] )
						_upper = _mid - 1;
						
						else if ( _cpc > (int)_foo_cond_keys[_mid ] )
						_lower = _mid + 1;
						
						else
						{
							_cond += (uint )(_mid - _ckeys);
							goto _match_cond;
						}
						
					}
					
					cs = 0;
					goto _again;
				}
				
				_match_cond :
				cs = (int)_foo_cond_targs[_cond];
				if ( _foo_cond_actions[_cond] == 0 )
				goto _again;
				
				
				_nbreak = 0;
				switch ( _foo_cond_actions[_cond]  ) {
					case 8:
					{Console.Write( "  one\n" );}
					
					break;
					case 4:
					{Console.Write( "  two\n" );}
					
					break;
					case 6:
					{Console.Write( "  three\n" );}
					
					break;
					case 1:
					{if ( (( data[p ])) == 48 )
						{
							i = 0;
							
						} 
						else {
							i = 1;
							
						}
					}
					
					break;
					case 2:
					{if ( (( data[p ])) == 48 )
						{
							j = 0;
							
						} 
						else {
							j = 1;
							
						}
					}
					
					break;
					case 3:
					{if ( (( data[p ])) == 48 )
						{
							k = 0;
							
						} 
						else {
							k = 1;
							
						}
					}
					
					break;
					case 5:
					{{p+= 1;
							_nbreak = 1;
						}}
					
					break;
					case 9:
					{Console.Write( "  one\n" );}
					{Console.Write( "  two\n" );}
					
					break;
					case 10:
					{Console.Write( "  one\n" );}
					{Console.Write( "  three\n" );}
					
					break;
					case 7:
					{Console.Write( "  two\n" );}
					{Console.Write( "  three\n" );}
					
					break;
					case 11:
					{Console.Write( "  one\n" );}
					{Console.Write( "  two\n" );}
					{Console.Write( "  three\n" );}
					
					break;
					
				}
				if ( _nbreak == 1 )
				goto _out;
				
				
				
				_again :
				if ( cs == 0 )
				goto _out;
				
				p += 1;
				if ( p != pe  )
				goto _resume;
				
				
				_test_eof :
				{}
				
				_out :
				{}
				
			}
		}
		
		void finish( )
		{
			if ( cs >= foo_first_final )
			Console.WriteLine( "ACCEPT" );
			else
			Console.WriteLine( "FAIL" );
		}
		
		static readonly string[] inp = {
			"000abc\n",
			"100abc\n",
			"010abc\n",
			"110abc\n",
			"001abc\n",
			"101abc\n",
			"011abc\n",
			"111abc\n",
		};
		
		
		static readonly int inplen = 8;
		
		public static void Main (string[] args)
		{
			Test machine = new Test();
			for ( int i = 0; i < inplen; i++ ) {
				machine.init();
				machine.exec( inp[i].ToCharArray(), inp[i].Length );
				machine.finish();
			}
		}
	}
}
