#include <iostream>
#include <string.h>
using std::cout;
using std::endl;



static const char  _foo_actions [] = { 0, 1, 0, 0 ,  };
static const char  _foo_nfa_targs [] = { 0, 0 ,  };
static const char  _foo_nfa_offsets [] = { 0, 0, 0 ,  };
static const char  _foo_nfa_push_actions [] = { 0, 0 ,  };
static const char  _foo_nfa_pop_trans [] = { 0, 0 ,  };
static const int  foo_start  = 1;
static const int  foo_en_main  = 1;
void test( char *str )
{
	int len = strlen( str );
	int cs = foo_start;
	char *p = str, *pe = str+len;
	
	{
		const char  *_acts;
		unsigned int _nacts;
		
		if ( p == pe  )
		goto _test_eof;
		
		if ( cs == 0  )
		goto _out;
		
		_resume:
		switch ( cs  ) {
			case 1:
			if ( ((*( p  ))
			)< 32  )
			{
				if ( ((*( p  ))
				)< 10  )
				{
					if ( 0 <= ((*( p  ))
					) )
					{
						goto ctr0;
					}
					
				} 
				else if ( ((*( p  ))
				)> 19  )
				{
					if ( ((*( p  ))
					)> 29  )
					{
						{
							int ck = 0;
							if ( ((cout << "c1 ", true)) )
							ck += 1;
							
							if ( ((cout << "c2 ", true)) )
							ck += 2;
							
							if ( ((cout << "c3 ", true)) )
							ck += 4;
							
							if ( ck < 3  )
							{
								if ( ck < 1  )
								{
									goto ctr2;
								} 
								else if ( ck > 1  )
								{
									goto ctr2;
								} 
								else
								{
									goto ctr2;
								}
								
							} 
							else if ( ck > 3  )
							{
								if ( ck < 5  )
								{
									goto ctr2;
								} 
								else if ( ck > 5  )
								{
									if ( ck > 6  )
									{
										goto ctr2;
									} 
									else
									{
										goto ctr2;
									}
									
								} 
								else
								{
									goto ctr2;
								}
								
							} 
							else
							{
								goto ctr2;
							}
							
							
						}
					} 
					else
					{
						int ck = 0;
						if ( ((cout << "c1 ", true)) )
						ck += 1;
						
						if ( ((cout << "c2 ", true)) )
						ck += 2;
						
						if ( ck < 1  )
						{
							goto ctr2;
						} 
						else if ( ck > 1  )
						{
							if ( ck > 2  )
							{
								goto ctr2;
							} 
							else
							{
								goto ctr2;
							}
							
						} 
						else
						{
							goto ctr2;
						}
						
						
					}
					
				} 
				else
				{
					int ck = 0;
					if ( ((cout << "c1 ", true)) )
					ck += 1;
					
					if ( ck > 0  )
					{
						goto ctr2;
					} 
					else
					{
						goto ctr2;
					}
					
					
				}
				
			} 
			else if ( ((*( p  ))
			)> 38  )
			{
				if ( ((*( p  ))
				)< 41  )
				{
					{
						int ck = 0;
						if ( ((cout << "c1 ", true)) )
						ck += 1;
						
						if ( ((cout << "c2 ", true)) )
						ck += 2;
						
						if ( ((cout << "c3 ", true)) )
						ck += 4;
						
						if ( ck < 3  )
						{
							if ( ck < 1  )
							{
								goto ctr2;
							} 
							else if ( ck > 1  )
							{
								goto ctr2;
							} 
							else
							{
								goto ctr2;
							}
							
						} 
						else if ( ck > 3  )
						{
							if ( ck < 5  )
							{
								goto ctr2;
							} 
							else if ( ck > 5  )
							{
								if ( ck > 6  )
								{
									goto ctr2;
								} 
								else
								{
									goto ctr2;
								}
								
							} 
							else
							{
								goto ctr2;
							}
							
						} 
						else
						{
							goto ctr2;
						}
						
						
					}
				} 
				else if ( ((*( p  ))
				)> 50  )
				{
					if ( ((*( p  ))
					)> 60  )
					{
						if ( ((*( p  ))
						)<= 70  )
						{
							goto ctr0;
						}
						
					} 
					else
					{
						int ck = 0;
						if ( ((cout << "c1 ", true)) )
						ck += 1;
						
						if ( ck > 0  )
						{
							goto ctr2;
						} 
						else
						{
							goto ctr2;
						}
						
						
					}
					
				} 
				else
				{
					int ck = 0;
					if ( ((cout << "c1 ", true)) )
					ck += 1;
					
					if ( ((cout << "c3 ", true)) )
					ck += 2;
					
					if ( ck < 1  )
					{
						goto ctr2;
					} 
					else if ( ck > 1  )
					{
						if ( ck > 2  )
						{
							goto ctr2;
						} 
						else
						{
							goto ctr2;
						}
						
					} 
					else
					{
						goto ctr2;
					}
					
					
				}
				
			} 
			else
			{
				int ck = 0;
				if ( ((cout << "c1 ", true)) )
				ck += 1;
				
				if ( ((cout << "c2 ", true)) )
				ck += 2;
				
				if ( ((cout << "c3 ", true)) )
				ck += 4;
				
				if ( ((cout << "c4 ", true)) )
				ck += 8;
				
				if ( ck < 7  )
				{
					if ( ck < 3  )
					{
						if ( ck < 1  )
						{
							goto ctr2;
						} 
						else if ( ck > 1  )
						{
							goto ctr2;
						} 
						else
						{
							goto ctr2;
						}
						
					} 
					else if ( ck > 3  )
					{
						if ( ck < 5  )
						{
							goto ctr2;
						} 
						else if ( ck > 5  )
						{
							goto ctr2;
						} 
						else
						{
							goto ctr2;
						}
						
					} 
					else
					{
						goto ctr2;
					}
					
				} 
				else if ( ck > 7  )
				{
					if ( ck < 11  )
					{
						if ( ck < 9  )
						{
							goto ctr2;
						} 
						else if ( ck > 9  )
						{
							goto ctr2;
						} 
						else
						{
							goto ctr2;
						}
						
					} 
					else if ( ck > 11  )
					{
						if ( ck < 13  )
						{
							goto ctr2;
						} 
						else if ( ck > 13  )
						{
							if ( ck > 14  )
							{
								goto ctr2;
							} 
							else
							{
								goto ctr2;
							}
							
						} 
						else
						{
							goto ctr2;
						}
						
					} 
					else
					{
						goto ctr2;
					}
					
				} 
				else
				{
					goto ctr2;
				}
				
				
			}
			
			{
				goto ctr1;
			}
			case 0:
			goto _out;
			
		}
		ctr1: cs = 0;
		goto _again;
		ctr0: cs = 1;
		goto f0;
		ctr2: cs = 1;
		goto f0;
		
		f0: _acts = _foo_actions + 1 ;
		goto execFuncs;
		
		execFuncs:
		_nacts = ( unsigned int  ) (*( _acts  ))
		;
		_acts += 1;
		while ( _nacts > 0  )
		{
			switch ( (*( _acts  ))
			) {
				case 0:
				{
					cout << "char: " << (int)*p << endl;
				}
				
				break;
				
			}
			_acts += 1;
			_nacts -= 1;
		}
		
		
		goto _again;
		
		_again:
		if ( cs == 0  )
		goto _out;
		
		p += 1;
		if ( p != pe  )
		goto _resume;
		
		_test_eof: {}
		_out: {}
	}
}

char data[] = { 5, 15, 25, 31, 35, 39, 45, 55, 65, 0 };

int main()
{
	test( data );
	return 0;
}

