const _foo_actions = Int8[0, 1, 0, 1, 1, 0 , ]
const _foo_key_offsets = Int8[0, 0, 2, 4, 7, 0 , ]
const _foo_trans_keys = UInt8[48, 57, 48, 57, 10, 48, 57, 0 , ]
const _foo_single_lengths = Int8[0, 0, 0, 1, 0, 0 , ]
const _foo_range_lengths = Int8[0, 1, 1, 1, 0, 0 , ]
const _foo_index_offsets = Int8[0, 0, 2, 4, 7, 0 , ]
const _foo_trans_cond_spaces = Int8[-1, -1, 0, -1, 0, 0, -1, -1, 0 , ]
const _foo_trans_offsets = Int8[0, 1, 2, 4, 5, 6, 7, 8, 0 , ]
const _foo_trans_lengths = Int8[1, 1, 2, 1, 1, 1, 1, 1, 0 , ]
const _foo_cond_keys = Int8[0, 0, 0, 1, 0, 0, 1, 0, 0, 0 , ]
const _foo_cond_targs = Int8[2, 0, 3, 2, 0, 4, 3, 0, 0, 0 , ]
const _foo_cond_actions = Int8[3, 0, 3, 1, 0, 0, 1, 0, 0, 0 , ]
const _foo_nfa_targs = Int8[0, 0 , ]
const _foo_nfa_offsets = Int8[0, 0, 0, 0, 0, 0 , ]
const _foo_nfa_push_actions = Int8[0, 0 , ]
const _foo_nfa_pop_trans = Int8[0, 0 , ]
const foo_start  = 1
const foo_first_final  = 4
const foo_error  = 0
const foo_en_main  = 1
function m( data::AbstractString )
	p = 0
	pe = length(data)
	eof = length(data)
	cs = 0
	buffer = ""
	i = 0;
	c = 0;
	
	cs = convert(Int, foo_start )
	_klen= 0
	;
	_trans = 0;
	_cond = 0;
	_have = 0;
	_cont = 1;
	_acts = 0;
	_nacts= 0
	;
	_keys = 0;
	_ckeys = 0;
	_cpc= 0
	;
	while _cont == 1 
		if cs == 0 
			_cont = 0
			
		end
		_have = 0
		if p == pe 
			if _have == 0 
				_cont = 0
				
			end
			
		end
		if _cont == 1 
			if _have == 0 
				_keys = _foo_key_offsets[1+(cs)]
				_trans = convert(UInt, _foo_index_offsets[1+(cs)] )
				_have = 0
				_klen = convert(Int, _foo_single_lengths[1+(cs)] )
				if _klen > 0 
					_lower = 0;
					_mid = 0;
					_upper = 0;
					_lower = _keys
					_upper = _keys + _klen - 1
					while _upper >= _lower && _have == 0 
						_mid = _lower + ((_upper-_lower)>> 1)
						if (data[1+(p )])< _foo_trans_keys[1+(_mid )]
							_upper = _mid - 1
							
						elseif (data[1+(p )])> _foo_trans_keys[1+(_mid )]
							_lower = _mid + 1
							
						else
							_trans += convert(UInt, (_mid - _keys) )
							_have = 1
							
						end
						
					end
					if _have == 0 
						_keys += _klen
						_trans += convert(UInt, _klen )
						
					end
					
				end
				if _have == 0 
					_klen = convert(Int, _foo_range_lengths[1+(cs)] )
					if _klen > 0 
						_lower = 0;
						_mid = 0;
						_upper = 0;
						_lower = _keys
						_upper = _keys + (_klen<<1)- 2
						while _have == 0 && _lower <= _upper 
							_mid = _lower + (((_upper-_lower)>> 1)& ~1)
							if (data[1+(p )])< _foo_trans_keys[1+(_mid )]
								_upper = _mid - 2
								
							elseif (data[1+(p )])> _foo_trans_keys[1+(_mid + 1 )]
								_lower = _mid + 2
								
							else
								_trans += convert(UInt, ((_mid - _keys)>>1) )
								_have = 1
								
							end
							
						end
						if _have == 0 
							_trans += convert(UInt, _klen )
							
						end
						
					end
					
				end
				_ckeys = _foo_trans_offsets[1+(_trans)]
				_klen = convert(Int, _foo_trans_lengths[1+(_trans)] )
				_cond = convert(UInt, _foo_trans_offsets[1+(_trans)] )
				_have = 0
				_cpc = 0
				if _foo_trans_cond_spaces[1+(_trans)] == 0 
					if (i > 0)
						_cpc += 1
						
					end
					
				end
				_lower = 0;
				_mid = 0;
				_upper = 0;
				_lower = _ckeys
				_upper = _ckeys + _klen - 1
				while _have == 0 && _lower <= _upper 
					_mid = _lower + ((_upper-_lower)>> 1)
					if _cpc < convert(Int, _foo_cond_keys[1+(_mid )] )
						_upper = _mid - 1
						
					elseif _cpc > convert(Int, _foo_cond_keys[1+(_mid )] )
						_lower = _mid + 1
						
					else
						_cond += convert(UInt, (_mid - _ckeys) )
						_have = 1
						
					end
					
				end
				if _have == 0 
					cs = 0
					_cont = 0
					
				end
				
			end
			if _cont == 1 
				cs = convert(Int, _foo_cond_targs[1+(_cond)] )
				if _foo_cond_actions[1+(_cond)]!= 0 
					_acts = _foo_cond_actions[1+(_cond)]
					_nacts = convert(UInt, _foo_actions[1+(_acts )] )
					_acts += 1
					while _nacts > 0 
						if _foo_actions[1+(_acts )] == 0 
							i = i - 1;
							c = convert( Int, ( ((data[1+(p )])) ) ) 
							;
							print( "item: " );
							print( c );
							print( "\n" );
							
						elseif _foo_actions[1+(_acts )] == 1 
							i = convert( Int, ( ((data[1+(p )])) - 48 ) ) 
							;
							print( "count: " );
							print( i );
							print( "\n" );
							
						end
						_nacts -= 1
						_acts += 1
						
					end
					
				end
				if cs == 0 
					_cont = 0
					
				end
				if _cont == 1 
					p += 1
					
				end
				
			end
			
		end
		
	end
	if ( cs >= foo_first_final )
		println( "ACCEPT" );
	else
		println( "FAIL" );
	end
end

m( "00\n" );
m( "019\n" );
m( "190\n" );
m( "1719\n" );
m( "1040000\n" );
m( "104000a\n" );
m( "104000\n" );
