#include <iostream>
#include <string.h>
using std::cout;
using std::endl;

static const int  cond_start  = 1;
static const int  cond_first_final  = 4;
static const int  cond_en_main  = 1;
static const char  _cond_nfa_targs [] = { 0, 0 ,  };
static const char  _cond_nfa_offsets [] = { 0, 0, 0, 0, 0, 0 ,  };
static const char  _cond_nfa_push_actions [] = { 0, 0 ,  };
static const char  _cond_nfa_pop_trans [] = { 0, 0 ,  };
void test( const char *str )
{
	int cs = cond_start, n = 0;
	const char *p = str;
	const char *pe = str + strlen( str );
	
	
	{
		if ( p == pe  )
		goto _test_eof;
		
		switch ( cs  ) {
			case 1:
			goto st_case_1;
			case 0:
			goto st_case_0;
			case 2:
			goto st_case_2;
			case 3:
			goto st_case_3;
			case 4:
			goto st_case_4;
			
		}
		goto st_out;
		st1:
		p+= 1;
		if ( p == pe  )
		goto _test_eof1;
		
		st_case_1:
		switch ( ((*( p  ))
		) ) {
			case 32:
			{
				goto st1;
			}
			case 40:
			{
				goto ctr2;
			}
			
		}
		{
			goto st0;
		}
		st_case_0:
		st0:
		cs = 0;
		goto _out;
		ctr5:
		{
			n--;
		}
		
		
		goto st2;
		ctr2:
		{
			n=0;
		}
		
		
		goto st2;
		ctr4:
		{
			n++;
		}
		
		
		goto st2;
		st2:
		p+= 1;
		if ( p == pe  )
		goto _test_eof2;
		
		st_case_2:
		switch ( ((*( p  ))
		) ) {
			case 40:
			{
				goto ctr4;
			}
			case 41:
			{
				int ck = 0;
				if ( (!n) )
				ck += 1;
				
				if ( ck > 0  )
				{
					goto st3;
				} 
				else
				{
					goto ctr5;
				}
				
				
			}
			
		}
		{
			goto st2;
		}
		st3:
		p+= 1;
		if ( p == pe  )
		goto _test_eof3;
		
		st_case_3:
		switch ( ((*( p  ))
		) ) {
			case 10:
			{
				goto ctr7;
			}
			case 32:
			{
				goto st3;
			}
			
		}
		{
			goto st0;
		}
		ctr7:
		{
			cout << "success";
		}
		
		
		goto st4;
		st4:
		p+= 1;
		if ( p == pe  )
		goto _test_eof4;
		
		st_case_4:
		{
			goto st0;
		}
		st_out:
		_test_eof1: cs = 1;
		goto _test_eof; 
		_test_eof2: cs = 2;
		goto _test_eof; 
		_test_eof3: cs = 3;
		goto _test_eof; 
		_test_eof4: cs = 4;
		goto _test_eof; 
		
		_test_eof: {}
		_out: {}
	}
	if ( cs < cond_first_final )
	cout << "failure";
	cout << endl;
}

int main()
{
	test( "( ( )\n" );
	test( "()()\n" );
	test( "(((\n" );
	test( "((()\n" );
	test( "((())\n" );
	test( "()\n" );
	test( "((()))\n" );
	test( "(()())\n" );
	test( "((())()(((()))))\n" );
	return 0;
}

