package main
import "fmt"

var i  int ;
var j  int ;
var k  int ;




var cs int;
var blen int;
var buffer [1024] byte;

var _foo_actions [] int8  = [] int8  { 0, 1, 0, 1, 1, 1, 2, 1, 3, 1, 4, 1, 5, 1, 6, 2, 0, 1, 2, 0, 2, 2, 1, 2, 3, 0, 1, 2, 0  }
var _foo_trans_keys [] byte  = [] byte  { 1, 0, 2, 2, 2, 2, 2, 2, 3, 4, 3, 4, 3, 4, 5, 5, 0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 0, 0 }
var _foo_char_class [] int8  = [] int8  { 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 4, 5, 0  }
var _foo_index_offsets [] int8  = [] int8  { 0, 0, 1, 2, 3, 5, 7, 9, 10, 11, 12, 13, 14, 15, 16, 17, 0  }
var _foo_indicies [] int8  = [] int8  { 0, 2, 3, 4, 5, 6, 7, 6, 8, 9, 10, 11, 12, 13, 14, 15, 16, 0  }
var _foo_index_defaults [] int8  = [] int8  { 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0  }
var _foo_trans_cond_spaces [] int8  = [] int8  { -1, -1, -1, -1, -1, 1, -1, 5, 4, -1, -1, -1, -1, -1, -1, -1, -1, 0  }
var _foo_trans_offsets [] int8  = [] int8  { 0, 1, 2, 3, 4, 5, 7, 8, 16, 20, 21, 22, 23, 24, 25, 26, 27, 0  }
var _foo_cond_targs [] int8  = [] int8  { 2, 0, 3, 4, 5, 0, 7, 6, 0, 11, 7, 12, 9, 13, 10, 14, 0, 7, 9, 10, 8, 15, 8, 8, 8, 8, 8, 8, 0  }
var _foo_cond_actions [] int8  = [] int8  { 7, 0, 9, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 13, 5, 21, 1, 15, 18, 24, 0  }
var _foo_nfa_targs [] int8  = [] int8  { 0, 0  }
var _foo_nfa_offsets [] int8  = [] int8  { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0  }
var _foo_nfa_push_actions [] int8  = [] int8  { 0, 0  }
var _foo_nfa_pop_trans [] int8  = [] int8  { 0, 0  }
var foo_start  int  = 1
var foo_first_final  int  = 15
var foo_error  int  = 0
var foo_en_main  int  = 1
func prepare() {

	{
		cs = int(foo_start);
	}
}

func exec(data string) {
	var p int = 0
	var pe int = len(data)
	
	{
		var  _trans  int   = 0
		var  _cond  uint   = 0
		var  _acts int
		var  _nacts uint 
		var  _keys int
		var  _inds int
		var  _cpc int 
		var  _nbreak int 
		if p == pe  {
			goto _test_eof;
			
		}
		if cs == 0  {
			goto _out;
			
		}
		_resume :
		_keys = int((cs<<1) );
		_inds = int(_foo_index_offsets[cs] );
		switch {
			case ( data[p ]) <= 99 && ( data[p ]) >= 10 :
			{
				var  _ic  int   = int(_foo_char_class[int(( data[p ]) )- 10])
				switch {
					case _ic <= int(_foo_trans_keys[_keys+1 ])&& _ic >= int(_foo_trans_keys[_keys ]):
					_trans = int(_foo_indicies[_inds + int(( _ic - int(_foo_trans_keys[_keys ]))  )]);
					
					default:
					_trans = int(_foo_index_defaults[cs]);
					
				}
			}
			
			default:
			{
				_trans = int(_foo_index_defaults[cs]);
			}
			
			
		}
		_cond = uint(_foo_trans_offsets[_trans]);
		_cpc = 0;
		switch _foo_trans_cond_spaces[_trans]  {
			case 1 :
			if (j != 0) {
				_cpc += 1;
				
			}
			
			break;
			case 4 :
			if (j != 0) {
				_cpc += 1;
				
			}
			if (k != 0) {
				_cpc += 2;
				
			}
			
			break;
			case 5 :
			if (i != 0) {
				_cpc += 1;
				
			}
			if (j != 0) {
				_cpc += 2;
				
			}
			if (k != 0) {
				_cpc += 4;
				
			}
			
			break;
			
		}
		_cond += uint(_cpc);
		goto _match_cond;
		
		_match_cond :
		cs = int(_foo_cond_targs[_cond]);
		if _foo_cond_actions[_cond] == 0  {
			goto _again;
			
			
		}
		_nbreak = 0;
		_acts = int(_foo_cond_actions[_cond] );
		_nacts = uint(_foo_actions[_acts ]);
		_acts += 1;
		for _nacts > 0  {
			{
				switch _foo_actions[_acts ] {
					case 0 :
					{fmt.Print( "  one\n" );}
					
					break;
					case 1 :
					{fmt.Print( "  two\n" );}
					
					break;
					case 2 :
					{fmt.Print( "  three\n" );}
					
					break;
					case 3 :
					{if ( (( data[p ])) == 48 ) {
							i = 0;
							
						} else {
							i = 1;
							
						}
					}
					
					break;
					case 4 :
					{if ( (( data[p ])) == 48 ) {
							j = 0;
							
						} else {
							j = 1;
							
						}
					}
					
					break;
					case 5 :
					{if ( (( data[p ])) == 48 ) {
							k = 0;
							
						} else {
							k = 1;
							
						}
					}
					
					break;
					case 6 :
					{{p += 1;
							_nbreak = 1;
						}
					}
					
					break;
					
				}
				_nacts -= 1;
				_acts += 1;
			}
			
			
		}
		if _nbreak == 1  {
			goto _out;
			
			
		}
		
		_again :
		if cs == 0  {
			goto _out;
			
		}
		p += 1;
		if p != pe  {
			goto _resume;
			
		}
		
		_test_eof :
		{}
		
		_out :
		{}
		
	}
}
func finish() {
	if cs >= foo_first_final {
		fmt.Println("ACCEPT")
	} else {
		fmt.Println("FAIL")
	}
}
var inp []string = []string {
	"000abc\n",
	"100abc\n",
	"010abc\n",
	"110abc\n",
	"001abc\n",
	"101abc\n",
	"011abc\n",
	"111abc\n",
};

func main() {
	for _, data := range inp {
		prepare()
		exec(data)
		finish()
	}
}
