#include <iostream>
#include <string.h>

using std::cout;
using std::endl;



static const char  _foo_key_offsets [] = { 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 25, 33, 0 ,  };
static const char  _foo_trans_keys [] = { 60, 47, 115, 116, 121, 108, 101, 62, 60, 32, 95, 48, 57, 65, 90, 97, 122, 32, 95, 48, 57, 65, 90, 97, 122, 32, 95, 48, 57, 65, 90, 97, 122, 0 ,  };
static const char  _foo_single_lengths [] = { 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 0, 0 ,  };
static const char  _foo_range_lengths [] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 0, 0 ,  };
static const char  _foo_index_offsets [] = { 0, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 24, 30, 36, 0 ,  };
static const char  _foo_trans_cond_spaces [] = { -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 14, 13, 13, 13, 13, 8, 14, 13, 13, 13, 13, 8, 14, 13, 13, 13, 13, 8, -1, 0 ,  };
static const short  _foo_trans_offsets [] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 25, 36, 47, 58, 69, 70, 88, 95, 102, 109, 116, 117, 127, 145, 163, 181, 199, 200, 0 ,  };
static const char  _foo_trans_lengths [] = { 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 7, 11, 11, 11, 11, 1, 18, 7, 7, 7, 7, 1, 10, 18, 18, 18, 18, 1, 1, 0 ,  };
static const char  _foo_cond_keys [] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 15, 21, 23, 27, 29, 31, 13, 15, 18, 19, 22, 23, 26, 27, 29, 30, 31, 13, 15, 18, 19, 22, 23, 26, 27, 29, 30, 31, 13, 15, 18, 19, 22, 23, 26, 27, 29, 30, 31, 13, 15, 18, 19, 22, 23, 26, 27, 29, 30, 31, 7, 4, 5, 6, 7, 11, 12, 13, 14, 15, 20, 21, 22, 23, 27, 28, 29, 30, 31, 13, 15, 22, 23, 29, 30, 31, 13, 15, 22, 23, 29, 30, 31, 13, 15, 22, 23, 29, 30, 31, 13, 15, 22, 23, 29, 30, 31, 7, 5, 7, 11, 13, 15, 21, 23, 27, 29, 31, 2, 3, 6, 7, 10, 11, 13, 14, 15, 18, 19, 22, 23, 26, 27, 29, 30, 31, 2, 3, 6, 7, 10, 11, 13, 14, 15, 18, 19, 22, 23, 26, 27, 29, 30, 31, 2, 3, 6, 7, 10, 11, 13, 14, 15, 18, 19, 22, 23, 26, 27, 29, 30, 31, 2, 3, 6, 7, 10, 11, 13, 14, 15, 18, 19, 22, 23, 26, 27, 29, 30, 31, 7, 0, 0 ,  };
static const char  _foo_cond_targs [] = { 2, 0, 3, 0, 4, 0, 5, 0, 6, 0, 7, 0, 8, 0, 9, 0, 10, 0, 13, 13, 11, 11, 13, 11, 11, 13, 13, 12, 12, 12, 12, 12, 12, 13, 12, 12, 13, 13, 12, 12, 12, 12, 12, 12, 13, 12, 12, 13, 13, 12, 12, 12, 12, 12, 12, 13, 12, 12, 13, 13, 12, 12, 12, 12, 12, 12, 13, 12, 12, 13, 11, 11, 11, 11, 13, 11, 11, 11, 11, 11, 11, 11, 11, 13, 11, 11, 11, 11, 13, 13, 12, 12, 13, 12, 13, 13, 13, 12, 12, 13, 12, 13, 13, 13, 12, 12, 13, 12, 13, 13, 13, 12, 12, 13, 12, 13, 13, 11, 11, 13, 11, 11, 11, 11, 13, 11, 11, 12, 12, 12, 12, 12, 12, 13, 12, 12, 12, 12, 12, 12, 12, 12, 13, 12, 12, 12, 12, 12, 12, 12, 12, 13, 12, 12, 12, 12, 12, 12, 12, 12, 13, 12, 12, 12, 12, 12, 12, 12, 12, 13, 12, 12, 12, 12, 12, 12, 12, 12, 13, 12, 12, 12, 12, 12, 12, 12, 12, 13, 12, 12, 12, 12, 12, 12, 12, 12, 13, 12, 12, 13, 0, 0 ,  };
static const char  _foo_cond_actions [] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 3, 3, 2, 3, 3, 2, 2, 4, 4, 4, 4, 4, 4, 2, 4, 4, 2, 2, 4, 4, 4, 4, 4, 4, 2, 4, 4, 2, 2, 4, 4, 4, 4, 4, 4, 2, 4, 4, 2, 2, 4, 4, 4, 4, 4, 4, 2, 4, 4, 2, 6, 6, 6, 6, 2, 6, 6, 6, 6, 6, 6, 6, 6, 2, 6, 6, 6, 6, 2, 2, 4, 4, 2, 4, 2, 2, 2, 4, 4, 2, 4, 2, 2, 2, 4, 4, 2, 4, 2, 2, 2, 4, 4, 2, 4, 2, 2, 6, 6, 2, 6, 6, 6, 6, 2, 6, 6, 7, 7, 7, 7, 7, 7, 2, 7, 7, 7, 7, 7, 7, 7, 7, 2, 7, 7, 7, 7, 7, 7, 7, 7, 2, 7, 7, 7, 7, 7, 7, 7, 7, 2, 7, 7, 7, 7, 7, 7, 7, 7, 2, 7, 7, 7, 7, 7, 7, 7, 7, 2, 7, 7, 7, 7, 7, 7, 7, 7, 2, 7, 7, 7, 7, 7, 7, 7, 7, 2, 7, 7, 2, 0, 0 ,  };
static const char  _foo_from_state_actions [] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 5, 5, 0, 0 ,  };
static const char  _foo_nfa_targs [] = { 0, 0 ,  };
static const char  _foo_nfa_offsets [] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  };
static const char  _foo_nfa_push_actions [] = { 0, 0 ,  };
static const char  _foo_nfa_pop_trans [] = { 0, 0 ,  };
static const int  foo_start  = 1;
static const int  foo_first_final  = 13;
static const int  foo_error  = 0;
static const int  foo_en_main  = 1;
void test( const char *str )
{
	int cs = foo_start;
	const char *p = str;
	const char *pe = str + strlen( str );
	int match = 0;
	
	long q_4 = 0, q_5 = 0, q_6 = 0;
	
	cout << "run:" << endl;
	
	{
		int _klen;
		const char  *_keys;
		const char  *_ckeys;
		int _cpc;
		unsigned int _trans;
		unsigned int _cond = 0;
		unsigned int _have = 0;
		unsigned int _cont = 1;
		while ( _cont == 1  )
		{
		
			if ( cs == 0  )
			_cont = 0;
			
			_have = 0;
			if ( p == pe  )
			{
				if ( _have == 0  )
				_cont = 0;
				
			}
			
			if ( _cont == 1  )
			{
				if ( _have == 0  )
				{
					switch ( _foo_from_state_actions[cs] ) {
						case 5 :
						{
							q_4 = 0; 
						}
						{
							q_5 = 0; 
						}
						
						break;
						case 1 :
						{
							q_4 = 0; 
						}
						{
							q_5 = 0; 
						}
						{
							q_6 = 0; 
						}
						
						break;
						
					}
					_keys = _foo_trans_keys + _foo_key_offsets[cs];
					_trans = ( unsigned int  ) _foo_index_offsets[cs];
					_have = 0;
					_klen = ( int ) _foo_single_lengths[cs];
					if ( _klen > 0  )
					{
						const char  *_lower;
						const char  *_mid;
						const char  *_upper;
						_lower = _keys;
						_upper = _keys + _klen - 1;
						while ( _upper >= _lower && _have == 0  )
						{
							_mid = _lower + ((_upper-_lower)>> 1);
							if ( ((*( p  ))
							)< (*( _mid  ))
							)
							_upper = _mid - 1;
							
							else if ( ((*( p  ))
							)> (*( _mid  ))
							)
							_lower = _mid + 1;
							
							else
							{
								_trans += ( unsigned int  ) (_mid - _keys);
								_have = 1;
							}
							
						}
						
						if ( _have == 0  )
						{
							_keys += _klen;
							_trans += ( unsigned int  ) _klen;
						}
						
					}
					
					
					if ( _have == 0  )
					{
						_klen = ( int ) _foo_range_lengths[cs];
						if ( _klen > 0  )
						{
							const char  *_lower;
							const char  *_mid;
							const char  *_upper;
							_lower = _keys;
							_upper = _keys + (_klen<<1)- 2;
							while ( _have == 0 && _lower <= _upper  )
							{
								_mid = _lower + (((_upper-_lower)>> 1)& ~1);
								if ( ((*( p  ))
								)< (*( _mid  ))
								)
								_upper = _mid - 2;
								
								else if ( ((*( p  ))
								)> (*( _mid + 1  ))
								)
								_lower = _mid + 2;
								
								else
								{
									_trans += ( unsigned int  ) ((_mid - _keys)>>1);
									_have = 1;
								}
								
							}
							
							if ( _have == 0  )
							_trans += ( unsigned int  ) _klen;
							
						}
						
					}
					
					
					_ckeys = _foo_cond_keys + _foo_trans_offsets[_trans];
					_klen = ( int ) _foo_trans_lengths[_trans];
					_cond = ( unsigned int  ) _foo_trans_offsets[_trans];
					_have = 0;
					_cpc = 0;
					switch ( _foo_trans_cond_spaces[_trans] ) {
						case 0 :
						if ( (q_4 >= 1 ) )
						_cpc += 1;
						
						
						break;
						case 1 :
						if ( (q_4 < 25 ) )
						_cpc += 1;
						
						
						break;
						case 2 :
						if ( (q_5 >= 1 ) )
						_cpc += 1;
						
						
						break;
						case 3 :
						if ( (q_5 < 5 ) )
						_cpc += 1;
						
						
						break;
						case 4 :
						if ( (q_6 < 100 ) )
						_cpc += 1;
						
						
						break;
						case 5 :
						if ( (q_4 >= 1 ) )
						_cpc += 1;
						
						if ( (q_5 >= 1 ) )
						_cpc += 2;
						
						
						break;
						case 6 :
						if ( (q_4 >= 1 ) )
						_cpc += 1;
						
						if ( (q_5 < 5 ) )
						_cpc += 2;
						
						
						break;
						case 7 :
						if ( (q_4 < 25 ) )
						_cpc += 1;
						
						if ( (q_6 < 100 ) )
						_cpc += 2;
						
						
						break;
						case 8 :
						if ( (q_4 >= 1 ) )
						_cpc += 1;
						
						if ( (q_5 >= 1 ) )
						_cpc += 2;
						
						if ( (q_6 >= 100 ) )
						_cpc += 4;
						
						
						break;
						case 9 :
						if ( (q_4 >= 1 ) )
						_cpc += 1;
						
						if ( (q_5 < 5 ) )
						_cpc += 2;
						
						if ( (q_6 < 100 ) )
						_cpc += 4;
						
						
						break;
						case 10 :
						if ( (q_4 < 25 ) )
						_cpc += 1;
						
						if ( (q_5 >= 1 ) )
						_cpc += 2;
						
						if ( (q_6 < 100 ) )
						_cpc += 4;
						
						
						break;
						case 11 :
						if ( (q_4 >= 1 ) )
						_cpc += 1;
						
						if ( (q_4 < 25 ) )
						_cpc += 2;
						
						if ( (q_5 >= 1 ) )
						_cpc += 4;
						
						if ( (q_6 < 100 ) )
						_cpc += 8;
						
						
						break;
						case 12 :
						if ( (q_4 >= 1 ) )
						_cpc += 1;
						
						if ( (q_5 >= 1 ) )
						_cpc += 2;
						
						if ( (q_5 < 5 ) )
						_cpc += 4;
						
						if ( (q_6 < 100 ) )
						_cpc += 8;
						
						
						break;
						case 13 :
						if ( (q_4 >= 1 ) )
						_cpc += 1;
						
						if ( (q_4 < 25 ) )
						_cpc += 2;
						
						if ( (q_5 >= 1 ) )
						_cpc += 4;
						
						if ( (q_6 >= 100 ) )
						_cpc += 8;
						
						if ( (q_6 < 100 ) )
						_cpc += 16;
						
						
						break;
						case 14 :
						if ( (q_4 >= 1 ) )
						_cpc += 1;
						
						if ( (q_5 >= 1 ) )
						_cpc += 2;
						
						if ( (q_5 < 5 ) )
						_cpc += 4;
						
						if ( (q_6 >= 100 ) )
						_cpc += 8;
						
						if ( (q_6 < 100 ) )
						_cpc += 16;
						
						
						break;
						
					}
					{
						const char  *_lower;
						const char  *_mid;
						const char  *_upper;
						_lower = _ckeys;
						_upper = _ckeys + _klen - 1;
						while ( _have == 0 && _lower <= _upper  )
						{
							_mid = _lower + ((_upper-_lower)>> 1);
							if ( _cpc < ( int ) (*( _mid  ))
							)
							_upper = _mid - 1;
							
							else if ( _cpc > ( int ) (*( _mid  ))
							)
							_lower = _mid + 1;
							
							else
							{
								_cond += ( unsigned int  ) (_mid - _ckeys);
								_have = 1;
							}
							
						}
						
						if ( _have == 0  )
						{
							cs = 0;
							_cont = 0;
						}
						
					}
				}
				
				if ( _cont == 1  )
				{
					cs = ( int ) _foo_cond_targs[_cond];
					switch ( _foo_cond_actions[_cond] ) {
						case 7 :
						{
							q_4++; 
						}
						
						break;
						case 6 :
						{
							q_5++; 
						}
						
						break;
						case 4 :
						{
							q_4++; 
						}
						{
							q_6++; 
						}
						
						break;
						case 3 :
						{
							q_6++; 
						}
						{
							q_5++; 
						}
						
						break;
						case 2 :
						{
							q_6++; 
						}
						{
							match = 1; 
						}
						
						break;
						
					}
					if ( cs == 0  )
					_cont = 0;
					
					if ( _cont == 1  )
					p += 1;
					
				}
			}
			
		}
		
	}
	if ( match )
	cout << "  success" << endl;
	else
	cout << "  failure" << endl;
	cout << endl;
}

int main()
{
	return 0;
}

