#include <iostream>
using namespace std;

struct LangEl
{
	int key;
	const char *name;
};

struct Fsm
{
	int cs;
	
	// Initialize the machine. Invokes any init statement blocks. Returns 0
	// if the machine begins in a non-accepting state and 1 if the machine
	// begins in an accepting state.
	int init( );
	
	// Execute the machine on a block of data. Returns -1 if after processing
	// the data, the machine is in the error state and can never accept, 0 if
	// the machine is in a non-accepting state and 1 if the machine is in an
	// accepting state.
	int execute(  LangEl *data, int len );
	
	// Indicate that there is no more data. Returns -1 if the machine finishes
	// in the error state and does not accept, 0 if the machine finishes
	// in any other non-accepting state and 1 if the machine finishes in an
	// accepting state.
	int finish( );
	
};



static const char  _Fsm_key_offsets [] = { 0, 0, 1, 3, 0 ,  };
static const int  _Fsm_trans_keys [] = { 1, 2, 3, 0 ,  };
static const char  _Fsm_single_lengths [] = { 0, 1, 2, 0, 0 ,  };
static const char  _Fsm_range_lengths [] = { 0, 0, 0, 0, 0 ,  };
static const char  _Fsm_index_offsets [] = { 0, 0, 2, 5, 0 ,  };
static const char  _Fsm_trans_cond_spaces [] = { -1, -1, -1, -1, -1, -1, 0 ,  };
static const char  _Fsm_trans_offsets [] = { 0, 1, 2, 3, 4, 5, 0 ,  };
static const char  _Fsm_trans_lengths [] = { 1, 1, 1, 1, 1, 1, 0 ,  };
static const char  _Fsm_cond_keys [] = { 0, 0, 0, 0, 0, 0, 0 ,  };
static const char  _Fsm_cond_targs [] = { 2, 0, 2, 3, 0, 0, 0 ,  };
static const char  _Fsm_cond_actions [] = { 1, 0, 1, 1, 0, 0, 0 ,  };
static const char  _Fsm_eof_actions [] = { 0, 0, 0, 2, 0 ,  };
static const char  _Fsm_nfa_targs [] = { 0, 0 ,  };
static const char  _Fsm_nfa_offsets [] = { 0, 0, 0, 0, 0 ,  };
static const char  _Fsm_nfa_push_actions [] = { 0, 0 ,  };
static const char  _Fsm_nfa_pop_trans [] = { 0, 0 ,  };
static const int  Fsm_start  = 1;
static const int  Fsm_first_final  = 3;
static const int  Fsm_error  = 0;
static const int  Fsm_en_main  = 1;
int Fsm::init( )
{

	{
		cs = ( int ) Fsm_start;
	}
	return 0;
}

int Fsm::execute( LangEl *data, int len )
{
	LangEl *p = data;
	LangEl *pe = data + len;
	LangEl *eof_marker = pe;
	
	{
		int _klen;
		const int  *_keys;
		const char  *_ckeys;
		int _cpc;
		unsigned int _trans = 0;
		unsigned int _cond = 0;
		if ( p == pe  )
		goto _test_eof;
		
		if ( cs == 0  )
		goto _out;
		
		_resume :
		_keys = _Fsm_trans_keys + _Fsm_key_offsets[cs];
		_trans = ( unsigned int  ) _Fsm_index_offsets[cs];
		_klen = ( int ) _Fsm_single_lengths[cs];
		if ( _klen > 0  )
		{
			const int  *_lower;
			const int  *_mid;
			const int  *_upper;
			_lower = _keys;
			_upper = _keys + _klen - 1;
			while ( 1 )
			{
				if ( _upper < _lower  )
				break;
				
				
				_mid = _lower + ((_upper-_lower)>> 1);
				if ( (p->key) < (*( _mid  ))
				)
				_upper = _mid - 1;
				
				else if ( (p->key) > (*( _mid  ))
				)
				_lower = _mid + 1;
				
				else
				{
					_trans += ( unsigned int  ) (_mid - _keys);
					goto _match;
				}
				
			}
			
			_keys += _klen;
			_trans += ( unsigned int  ) _klen;
		}
		
		
		_klen = ( int ) _Fsm_range_lengths[cs];
		if ( _klen > 0  )
		{
			const int  *_lower;
			const int  *_mid;
			const int  *_upper;
			_lower = _keys;
			_upper = _keys + (_klen<<1)- 2;
			while ( 1 )
			{
				if ( _upper < _lower  )
				break;
				
				
				_mid = _lower + (((_upper-_lower)>> 1)& ~1);
				if ( (p->key) < (*( _mid  ))
				)
				_upper = _mid - 2;
				
				else if ( (p->key) > (*( _mid + 1  ))
				)
				_lower = _mid + 2;
				
				else
				{
					_trans += ( unsigned int  ) ((_mid - _keys)>>1);
					goto _match;
				}
				
			}
			
			_trans += ( unsigned int  ) _klen;
		}
		
		
		
		_match :
		_ckeys = _Fsm_cond_keys + _Fsm_trans_offsets[_trans];
		_klen = ( int ) _Fsm_trans_lengths[_trans];
		_cond = ( unsigned int  ) _Fsm_trans_offsets[_trans];
		_cpc = 0;
		{
			const char  *_lower;
			const char  *_mid;
			const char  *_upper;
			_lower = _ckeys;
			_upper = _ckeys + _klen - 1;
			while ( 1 )
			{
				if ( _upper < _lower  )
				break;
				
				
				_mid = _lower + ((_upper-_lower)>> 1);
				if ( _cpc < ( int ) (*( _mid  ))
				)
				_upper = _mid - 1;
				
				else if ( _cpc > ( int ) (*( _mid  ))
				)
				_lower = _mid + 1;
				
				else
				{
					_cond += ( unsigned int  ) (_mid - _ckeys);
					goto _match_cond;
				}
				
			}
			
			cs = 0;
			goto _again;
		}
		
		_match_cond :
		cs = ( int ) _Fsm_cond_targs[_cond];
		if ( _Fsm_cond_actions[_cond]== 0  )
		goto _again;
		
		
		switch ( _Fsm_cond_actions[_cond] ) {
			case 1 :
			{
				cout << p->name << endl;
			}
			
			break;
			
		}
		
		_again :
		if ( cs == 0  )
		goto _out;
		
		p += 1;
		if ( p != pe  )
		goto _resume;
		
		
		_test_eof :
		{}
		if ( p == (eof_marker) )
		{
			switch ( _Fsm_eof_actions[cs] ) {
				case 2 :
				{
					cout << "accept" << endl;
				}
				
				break;
				
			}
		}
		
		
		
		_out :
		{}
		
	}
	if ( cs == Fsm_error )
	return -1;
	if ( cs >= Fsm_first_final )
	return 1;
	return 0;
}

int Fsm::finish( )
{
	if ( cs == Fsm_error )
	return -1;
	if ( cs >= Fsm_first_final )
	return 1;
	return 0;
}

int main( )
{
	static Fsm fsm;
	static LangEl lel[] = { 
		{1, "one"}, 
		{2, "two-a"}, 
		{2, "two-b"}, 
		{2, "two-c"}, 
		{3, "three"}
	};
	
	fsm.init();
	fsm.execute( lel, 5 );
	fsm.finish();
	return 0;
}

