class eofact_java
{







	private static char  _eofact_trans_keys [] = { 1, 0, 3, 7, 2, 2, 4, 4, 4, 4, 5, 5, 3, 3, 2, 2, 6, 6, 2, 2, 0, 0, 1, 0, 1, 0, 0,  };
	private static byte  _eofact_char_class [] = { 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 3, 1, 1, 1, 4, 1, 1, 5, 1, 1, 6, 1, 7, 0 ,  };
	private static byte  _eofact_index_offsets [] = { 0, 0, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 14, 0 ,  };
	private static byte  _eofact_indicies [] = { 0, 1, 1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0 ,  };
	private static byte  _eofact_index_defaults [] = { 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0 ,  };
	private static byte  _eofact_trans_cond_spaces [] = { -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0 ,  };
	private static byte  _eofact_cond_targs [] = { 2, 0, 6, 3, 4, 5, 10, 7, 8, 9, 12, 11, 0 ,  };
	private static byte  _eofact_cond_actions [] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  };
	private static byte  _eofact_eof_actions [] = { 0, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 0, 5, 0 ,  };
	private static byte  _eofact_nfa_targs [] = { 0, 0 ,  };
	private static byte  _eofact_nfa_offsets [] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  };
	private static byte  _eofact_nfa_push_actions [] = { 0, 0 ,  };
	private static byte  _eofact_nfa_pop_trans [] = { 0, 0 ,  };
	private static int  eofact_start  = 1;
	private static int  eofact_first_final  = 10;
	private static int  eofact_error  = 0;
	private static int  eofact_en_main  = 1;
	int cs;
	
	void init()
	{
		{
			cs = (int)eofact_start;
			
		}
	}
	
	void exec( char data[], int len )
	{
		char buffer [] = new char[1024];
		int blen = 0;
		int p = 0;
		int pe = len;
		
		int eof = len;
		String _s;
		{
			int _trans = 0;
			int _keys;
			int _inds;
			int _goto_targ = 0;
			_goto: while ( true ) {
				switch ( _goto_targ ) {
					case 0:
					if ( p == pe  )
					{
						_goto_targ = 3;
						if (true)
						continue _goto;
					}
					
					if ( cs == 0  )
					{
						_goto_targ = 4;
						if (true)
						continue _goto;
					}
					
					case 1:
					_keys = (cs<<1) ;
					_inds = _eofact_index_offsets[cs] ;
					if ( ( data[p ]) <= 116 && ( data[p ]) >= 10  )
					{
						int _ic = (int)_eofact_char_class[(int)( data[p ]) - 10];
						if ( _ic <= (int)_eofact_trans_keys[_keys+1 ]&& _ic >= (int)_eofact_trans_keys[_keys ] )
						_trans = (int)_eofact_indicies[_inds + (int)( _ic - (int)_eofact_trans_keys[_keys ])  ];
						
						else
						_trans = (int)_eofact_index_defaults[cs];
						
						
					}
					
					else
					{
						_trans = (int)_eofact_index_defaults[cs];
						
					}
					
					{
						_goto_targ = 2;
						if (true)
						continue _goto;
					}
					
					case 2:
					cs = (int)_eofact_cond_targs[_trans];
					if ( cs == 0  )
					{
						_goto_targ = 4;
						if (true)
						continue _goto;
					}
					
					p+= 1;
					if ( p != pe  )
					{
						_goto_targ = 1;
						if (true)
						continue _goto;
					}
					
					
					case 3:
					{
					
					}
					if ( p == eof  )
					{
						switch ( _eofact_eof_actions[cs]  ) {
							case 2 :
							{
								System.out.print( "a1\n" );
								
							}
							
							break;
							case 4 :
							{
								System.out.print( "a2\n" );
								
							}
							
							break;
							case 3 :
							{
								System.out.print( "a3\n" );
								
							}
							
							break;
							case 5 :
							{
								System.out.print( "a4\n" );
								
							}
							
							break;
							case 1 :
							{
								System.out.print( "a1\n" );
								
							}
							{
								System.out.print( "a3\n" );
								
							}
							
							break;
							
						}
						
					}
					
					
					case 4:
					{
					
					}
					
					
				}
				break;
			}
			
		}
	}
	
	void finish( )
	{
		if ( cs >= eofact_first_final )
		System.out.println( "ACCEPT" );
		else
		System.out.println( "FAIL" );
	}
	
	static final String inp[] = {
		"",
		"h",
		"hell",
		"hello",
		"hello\n",
		"t",
		"ther",
		"there",
		"friend",
	};
	
	static final int inplen = 9;
	
	public static void main (String[] args)
	{
		eofact_java machine = new eofact_java();
		for ( int i = 0; i < inplen; i++ ) {
			machine.init();
			machine.exec( inp[i].toCharArray(), inp[i].length() );
			machine.finish();
		}
	}
}
