#include <stdio.h>
#include <string.h>
#include <Foundation/Foundation.h>

@interface ErrAct : NSObject
{
	@public
	int cs;
};

// Initialize the machine. Invokes any init statement blocks. Returns 0
// if the machine begins in a non-accepting state and 1 if the machine
// begins in an accepting state.
- (int) initFsm;

// Execute the machine on a block of data. Returns -1 if after processing
// the data, the machine is in the error state and can never accept, 0 if
// the machine is in a non-accepting state and 1 if the machine is in an
// accepting state.
- (void) executeWithData:(const char *)data len:(int)len;

// Indicate that there is no more data. Returns -1 if the machine finishes
// in the error state and does not accept, 0 if the machine finishes
// in any other non-accepting state and 1 if the machine finishes in an
// accepting state.
- (int) finish;

@end

@implementation ErrAct



static const char  _ErrAct_trans_keys [] = { 1, 0, 2, 4, 4, 4, 0, 4, 4, 4, 0, 4, 1, 0, 0 ,  };
static const char  _ErrAct_char_class [] = { 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 3, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0 ,  };
static const char  _ErrAct_index_offsets [] = { 0, 0, 3, 4, 9, 10, 15, 0 ,  };
static const char  _ErrAct_indicies [] = { 1, 0, 2, 2, 5, 4, 4, 6, 2, 7, 5, 3, 3, 3, 7, 0 ,  };
static const char  _ErrAct_index_defaults [] = { 0, 0, 3, 4, 3, 3, 8, 0 ,  };
static const char  _ErrAct_trans_cond_spaces [] = { -1, -1, -1, -1, -1, -1, -1, -1, -1, 0 ,  };
static const char  _ErrAct_cond_targs [] = { 0, 2, 3, 0, 0, 6, 4, 5, 0, 0 ,  };
static const char  _ErrAct_cond_actions [] = { 1, 0, 0, 2, 3, 0, 0, 0, 0, 0 ,  };
static const char  _ErrAct_eof_actions [] = { 0, 1, 2, 3, 2, 2, 0, 0 ,  };
static const char  _ErrAct_nfa_targs [] = { 0, 0 ,  };
static const char  _ErrAct_nfa_offsets [] = { 0, 0, 0, 0, 0, 0, 0, 0 ,  };
static const char  _ErrAct_nfa_push_actions [] = { 0, 0 ,  };
static const char  _ErrAct_nfa_pop_trans [] = { 0, 0 ,  };
static const int  ErrAct_start  = 1;
static const int  ErrAct_first_final  = 6;
static const int  ErrAct_error  = 0;
static const int  ErrAct_en_main  = 1;
- (int) initFsm;
{

	{
		cs = ( int ) ErrAct_start;
	}
	return 1;
}

- (void) executeWithData:(const char *)_data len:(int)_len;
{
	const char *p = _data;
	const char *pe = _data + _len;
	const char *eof = pe;
	
	{
		int _trans = 0;
		const char  *_keys;
		const char  *_inds;
		if ( p == pe  )
		goto _test_eof;
		
		if ( cs == 0  )
		goto _out;
		
		_resume :
		_keys = _ErrAct_trans_keys + (cs<<1);
		_inds = _ErrAct_indicies + _ErrAct_index_offsets[cs];
		if ( ((*( p  ))
		)<= 57 && ((*( p  ))
		)>= 10  )
		{
			int _ic = ( int ) _ErrAct_char_class[( int ) ((*( p  ))
			)- 10];
			if ( _ic <= ( int ) (*( _keys+1  ))
			&& _ic >= ( int ) (*( _keys  ))
			)
			_trans = ( int ) (*( _inds + ( int ) (_ic - ( int ) (*( _keys  ))
			) ))
			;
			
			else
			_trans = ( int ) _ErrAct_index_defaults[cs];
			
		}
		
		else
		{
			_trans = ( int ) _ErrAct_index_defaults[cs];
		}
		
		
		goto _match_cond;
		
		_match_cond :
		cs = ( int ) _ErrAct_cond_targs[_trans];
		if ( _ErrAct_cond_actions[_trans]== 0  )
		goto _again;
		
		
		switch ( _ErrAct_cond_actions[_trans] ) {
			case 1 :
			{
				printf(" DIGIT PLUS MINUS\n"); 
			}
			
			break;
			case 2 :
			{
				printf(" DIGIT\n"); 
			}
			
			break;
			case 3 :
			{
				printf(" DIGIT DECIMAL\n"); 
			}
			
			break;
			
		}
		
		_again :
		if ( cs == 0  )
		goto _out;
		
		p+= 1;
		if ( p != pe  )
		goto _resume;
		
		
		_test_eof :
		{}
		if ( p == eof  )
		{
			switch ( _ErrAct_eof_actions[cs] ) {
				case 1 :
				{
					printf(" DIGIT PLUS MINUS\n"); 
				}
				
				break;
				case 2 :
				{
					printf(" DIGIT\n"); 
				}
				
				break;
				case 3 :
				{
					printf(" DIGIT DECIMAL\n"); 
				}
				
				break;
				
			}
		}
		
		
		
		_out :
		{}
		
	}
}

- (int) finish;
{
	if ( cs == ErrAct_error )
	return -1;
	else if ( cs >= ErrAct_first_final )
	return 1;
	return 0;
}


@end

#define BUFSIZE 1024

void test( char *buf )
{
	ErrAct *errAct = [[ErrAct alloc] init];
	[errAct initFsm];
	[errAct executeWithData:buf len:strlen(buf)];
	if ( [errAct finish] > 0 )
	printf("ACCEPT\n");
	else
	printf("FAIL\n");
}

int main()
{
	test( "1\n" );
	test( "+1\n" );
	test( "-1\n" );
	test( "1.1\n" );
	test( "+1.1\n" );
	test( "-1.1\n" );
	test( "a\n" );
	test( "-\n" );
	test( "+\n" );
	test( "-a\n" );
	test( "+b\n" );
	test( "1.\n" );
	test( "1d\n" );
	test( "1.d\n" );
	test( "1.1d\n" );
	return 0;
}

