package main
import "fmt"







var cs int;
var blen int;
var buffer [1024] byte;

var _erract_actions [] int8  = [] int8  { 0, 2, 0, 1, 2, 1, 2, 2, 1, 3, 4, 0, 4, 1, 5, 4, 1, 2, 5, 6, 4, 1, 3, 5, 7, 0  }
var _erract_key_offsets [] int8  = [] int8  { 0, 0, 1, 2, 3, 4, 5, 6, 0  }
var _erract_trans_keys [] byte  = [] byte  { 104, 101, 108, 108, 111, 10, 0 }
var _erract_single_lengths [] int8  = [] int8  { 0, 1, 1, 1, 1, 1, 1, 0, 0  }
var _erract_range_lengths [] int8  = [] int8  { 0, 0, 0, 0, 0, 0, 0, 0, 0  }
var _erract_index_offsets [] int8  = [] int8  { 0, 0, 2, 4, 6, 8, 10, 12, 0  }
var _erract_trans_cond_spaces [] int8  = [] int8  { -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0  }
var _erract_trans_offsets [] int8  = [] int8  { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0  }
var _erract_trans_lengths [] int8  = [] int8  { 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0  }
var _erract_cond_keys [] int8  = [] int8  { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0  }
var _erract_cond_targs [] int8  = [] int8  { 2, 0, 3, 0, 4, 0, 5, 0, 6, 0, 7, 0, 0, 0  }
var _erract_cond_actions [] int8  = [] int8  { 0, 1, 0, 4, 0, 4, 0, 4, 0, 4, 0, 7, 0, 0  }
var _erract_eof_actions [] int8  = [] int8  { 0, 10, 15, 15, 15, 15, 20, 0, 0  }
var _erract_nfa_targs [] int8  = [] int8  { 0, 0  }
var _erract_nfa_offsets [] int8  = [] int8  { 0, 0, 0, 0, 0, 0, 0, 0, 0  }
var _erract_nfa_push_actions [] int8  = [] int8  { 0, 0  }
var _erract_nfa_pop_trans [] int8  = [] int8  { 0, 0  }
var erract_start  int  = 1
var erract_first_final  int  = 7
var erract_error  int  = 0
var erract_en_main  int  = 1
func prepare() {

	{
		cs = int(erract_start);
	}
}

func exec(data string) {
	var p int = 0
	var pe int = len(data)
	var eof int = pe
	
	{
		var  _klen int 
		var  _trans  uint   = 0
		var  _cond  uint   = 0
		var  _acts int
		var  _nacts uint 
		var  _keys int
		var  _ckeys int
		var  _cpc int 
		if p == pe  {
			goto _test_eof;
			
		}
		if cs == 0  {
			goto _out;
			
		}
		_resume :
		_keys = int(_erract_key_offsets[cs] );
		_trans = uint(_erract_index_offsets[cs]);
		_klen = int(_erract_single_lengths[cs]);
		if _klen > 0  {
			{
				var  _lower int
				var  _mid int
				var  _upper int
				_lower = _keys;
				_upper = _keys + _klen - 1;
				for {
					{
						if _upper < _lower  {
							break;
							
							
						}
						_mid = _lower + ((_upper-_lower) >> 1);
						switch {
							case ( data[p ]) < _erract_trans_keys[_mid ]:
							_upper = _mid - 1;
							
							case ( data[p ]) > _erract_trans_keys[_mid ]:
							_lower = _mid + 1;
							
							default:
							{
								_trans += uint((_mid - _keys));
								goto _match;
							}
							
						}
					}
					
				}
				_keys += _klen;
				_trans += uint(_klen);
			}
			
			
		}
		_klen = int(_erract_range_lengths[cs]);
		if _klen > 0  {
			{
				var  _lower int
				var  _mid int
				var  _upper int
				_lower = _keys;
				_upper = _keys + (_klen<<1) - 2;
				for {
					{
						if _upper < _lower  {
							break;
							
							
						}
						_mid = _lower + (((_upper-_lower) >> 1) & ^1);
						switch {
							case ( data[p ]) < _erract_trans_keys[_mid ]:
							_upper = _mid - 2;
							
							case ( data[p ]) > _erract_trans_keys[_mid + 1 ]:
							_lower = _mid + 2;
							
							default:
							{
								_trans += uint(((_mid - _keys)>>1));
								goto _match;
							}
							
						}
					}
					
				}
				_trans += uint(_klen);
			}
			
			
		}
		
		_match :
		_ckeys = int(_erract_trans_offsets[_trans] );
		_klen = int(_erract_trans_lengths[_trans]);
		_cond = uint(_erract_trans_offsets[_trans]);
		_cpc = 0;
		{
			var  _lower int
			var  _mid int
			var  _upper int
			_lower = _ckeys;
			_upper = _ckeys + _klen - 1;
			for {
				{
					if _upper < _lower  {
						break;
						
						
					}
					_mid = _lower + ((_upper-_lower) >> 1);
					switch {
						case _cpc < int(_erract_cond_keys[_mid ]):
						_upper = _mid - 1;
						
						case _cpc > int(_erract_cond_keys[_mid ]):
						_lower = _mid + 1;
						
						default:
						{
							_cond += uint((_mid - _ckeys));
							goto _match_cond;
						}
						
					}
				}
				
			}
			cs = 0;
			goto _again;
		}
		
		_match_cond :
		cs = int(_erract_cond_targs[_cond]);
		if _erract_cond_actions[_cond] == 0  {
			goto _again;
			
			
		}
		_acts = int(_erract_cond_actions[_cond] );
		_nacts = uint(_erract_actions[_acts ]);
		_acts += 1;
		for _nacts > 0  {
			{
				switch _erract_actions[_acts ] {
					case 0 :
					{fmt.Print( "err_start\n" );}
					
					break;
					case 1 :
					{fmt.Print( "err_all\n" );}
					
					break;
					case 2 :
					{fmt.Print( "err_middle\n" );}
					
					break;
					case 3 :
					{fmt.Print( "err_out\n" );}
					
					break;
					
				}
				_nacts -= 1;
				_acts += 1;
			}
			
			
			
		}
		
		_again :
		if cs == 0  {
			goto _out;
			
		}
		p += 1;
		if p != pe  {
			goto _resume;
			
		}
		
		_test_eof :
		{}
		if p == eof  {
			{
				var  __acts int
				var  __nacts uint 
				__acts = int(_erract_eof_actions[cs] );
				__nacts = uint(_erract_actions[__acts ]);
				__acts += 1;
				for __nacts > 0  {
					{
						switch _erract_actions[__acts ] {
							case 0 :
							{fmt.Print( "err_start\n" );}
							
							break;
							case 1 :
							{fmt.Print( "err_all\n" );}
							
							break;
							case 2 :
							{fmt.Print( "err_middle\n" );}
							
							break;
							case 3 :
							{fmt.Print( "err_out\n" );}
							
							break;
							case 4 :
							{fmt.Print( "eof_start\n" );}
							
							break;
							case 5 :
							{fmt.Print( "eof_all\n" );}
							
							break;
							case 6 :
							{fmt.Print( "eof_middle\n" );}
							
							break;
							case 7 :
							{fmt.Print( "eof_out\n" );}
							
							break;
							
						}
						__nacts -= 1;
						__acts += 1;
					}
					
				}
			}
			
			
		}
		
		_out :
		{}
		
	}
}
func finish() {
	if cs >= erract_first_final {
		fmt.Println("ACCEPT")
	} else {
		fmt.Println("FAIL")
	}
}
var inp []string = []string {
	"",
	"h",
	"x",
	"he",
	"hx",
	"hel",
	"hex",
	"hell",
	"helx",
	"hello",
	"hellx",
	"hello\n",
	"hellox",
};

func main() {
	for _, data := range inp {
		prepare()
		exec(data)
		finish()
	}
}
