class export2
{


	static final char test_ex_c1  = 99;
	static final char test_ex_c2  = 122;
	static final char test_ex_c3  = 116;
	private static byte  _test_key_offsets [] = { 0, 0, 3, 5, 10, 10, 0 ,  };
	private static char  _test_trans_keys [] = { 10, 48, 57, 10, 46, 10, 65, 90, 97, 122, 99, 116, 122, 0,  };
	private static byte  _test_single_lengths [] = { 0, 1, 2, 1, 0, 3, 0 ,  };
	private static byte  _test_range_lengths [] = { 0, 1, 0, 2, 0, 0, 0 ,  };
	private static byte  _test_index_offsets [] = { 0, 0, 3, 6, 10, 11, 0 ,  };
	private static byte  _test_trans_cond_spaces [] = { -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0 ,  };
	private static byte  _test_trans_offsets [] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 0 ,  };
	private static byte  _test_trans_lengths [] = { 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0 ,  };
	private static byte  _test_cond_keys [] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  };
	private static byte  _test_cond_targs [] = { 5, 1, 0, 5, 2, 0, 5, 3, 3, 0, 4, 1, 2, 3, 0, 0 ,  };
	private static byte  _test_cond_actions [] = { 1, 0, 0, 2, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  };
	private static byte  _test_nfa_targs [] = { 0, 0 ,  };
	private static byte  _test_nfa_offsets [] = { 0, 0, 0, 0, 0, 0, 0 ,  };
	private static byte  _test_nfa_push_actions [] = { 0, 0 ,  };
	private static byte  _test_nfa_pop_trans [] = { 0, 0 ,  };
	private static int  test_start  = 4;
	private static int  test_first_final  = 4;
	private static int  test_error  = 0;
	private static int  test_en_commands  = 5;
	private static int  test_en_other  = 4;
	static void test( char data[] )
	{
		int cs = test_en_commands, p = 0, pe = data.length;
		int top;
		
		{
		
		}
		{
			int _klen;
			int _keys;
			int _ckeys;
			int _cpc;
			int _trans;
			int _cond = 0;
			int _have = 0;
			int _cont = 1;
			while ( _cont == 1  )
			{
				if ( cs == 0  )
				_cont = 0;
				
				_have = 0;
				if ( p == pe  )
				{
					if ( _have == 0  )
					_cont = 0;
					
					
				}
				
				if ( _cont == 1  )
				{
					if ( _have == 0  )
					{
						_keys = _test_key_offsets[cs] ;
						_trans = (int )_test_index_offsets[cs];
						_have = 0;
						_klen = (int)_test_single_lengths[cs];
						if ( _klen > 0  )
						{
							int _lower;
							int _mid;
							int _upper;
							_lower = _keys;
							_upper = _keys + _klen - 1;
							while ( _upper >= _lower && _have == 0  )
							{
								_mid = _lower + ((_upper-_lower) >> 1);
								if ( ( data[p ]) < _test_trans_keys[_mid ] )
								_upper = _mid - 1;
								
								else if ( ( data[p ]) > _test_trans_keys[_mid ] )
								_lower = _mid + 1;
								
								else
								{
									_trans += (int )(_mid - _keys);
									_have = 1;
									
								}
								
								
							}
							
							if ( _have == 0  )
							{
								_keys += _klen;
								_trans += (int )_klen;
								
							}
							
							
						}
						
						if ( _have == 0  )
						{
							_klen = (int)_test_range_lengths[cs];
							if ( _klen > 0  )
							{
								int _lower;
								int _mid;
								int _upper;
								_lower = _keys;
								_upper = _keys + (_klen<<1) - 2;
								while ( _have == 0 && _lower <= _upper  )
								{
									_mid = _lower + (((_upper-_lower) >> 1) & ~1);
									if ( ( data[p ]) < _test_trans_keys[_mid ] )
									_upper = _mid - 2;
									
									else if ( ( data[p ]) > _test_trans_keys[_mid + 1 ] )
									_lower = _mid + 2;
									
									else
									{
										_trans += (int )((_mid - _keys)>>1);
										_have = 1;
										
									}
									
									
								}
								
								if ( _have == 0  )
								_trans += (int )_klen;
								
								
							}
							
							
						}
						
						_ckeys = _test_trans_offsets[_trans] ;
						_klen = (int)_test_trans_lengths[_trans];
						_cond = (int )_test_trans_offsets[_trans];
						_have = 0;
						_cpc = 0;
						{
							int _lower;
							int _mid;
							int _upper;
							_lower = _ckeys;
							_upper = _ckeys + _klen - 1;
							while ( _have == 0 && _lower <= _upper  )
							{
								_mid = _lower + ((_upper-_lower) >> 1);
								if ( _cpc < (int)_test_cond_keys[_mid ] )
								_upper = _mid - 1;
								
								else if ( _cpc > (int)_test_cond_keys[_mid ] )
								_lower = _mid + 1;
								
								else
								{
									_cond += (int )(_mid - _ckeys);
									_have = 1;
									
								}
								
								
							}
							
							if ( _have == 0  )
							{
								cs = 0;
								_cont = 0;
								
							}
							
							
						}
						
					}
					
					if ( _cont == 1  )
					{
						cs = (int)_test_cond_targs[_cond];
						switch ( _test_cond_actions[_cond]  ) {
							case 1 :
							{
								System.out.println( "c1" );
							}
							
							break;
							case 3 :
							{
								System.out.println( "c2" );
							}
							
							break;
							case 2 :
							{
								System.out.println( "c3" );
							}
							
							break;
							
						}
						if ( cs == 0  )
						_cont = 0;
						
						if ( _cont == 1  )
						p += 1;
						
						
					}
					
					
				}
				
				
			}
			
			
		}
		if ( cs >= test_first_final )
		System.out.println( "ACCEPT" );
		else
		System.out.println( "FAIL" );
	}
	
	public static void main( String args[] )
	{
		char data[] = { 
			test_ex_c1, '1', '2', '\n', 
			test_ex_c2, 'a', 'b', '\n', 
			test_ex_c3, '.', '.', '\n',
		};
		test( data );
	}
}


