#include <stdio.h>
#include <string.h>

struct forder 
{
	int cs;
};



static const int  forder_start  = 1;
static const int  forder_first_final  = 4;
static const int  forder_error  = 0;
static const int  forder_en_main  = 1;
static const char  _forder_nfa_targs [] = { 0, 0 ,  };
static const char  _forder_nfa_offsets [] = { 0, 0, 0, 0, 0, 0 ,  };
static const char  _forder_nfa_push_actions [] = { 0, 0 ,  };
static const char  _forder_nfa_pop_trans [] = { 0, 0 ,  };
void forder_init( struct forder *fsm )
{

	{
		(fsm->cs) = ( int ) forder_start;
	}
}

void forder_execute( struct forder *fsm, const char *_data, int _len )
{
	const char *p = _data;
	const char *pe = _data+_len;
	
	
	{
		if ( p == pe  )
		goto _test_eof;
		
		switch ( (fsm->cs) ) {
			case 1:
			goto st_case_1;
			case 0:
			goto st_case_0;
			case 2:
			goto st_case_2;
			case 3:
			goto st_case_3;
			case 4:
			goto st_case_4;
			
		}
		goto st_out;
		st_case_1:
		if ( ((*( p  ))
		)== 97  )
		{
			goto ctr0;
		}
		
		{
			goto st0;
		}
		st_case_0:
		st0:
		(fsm->cs) = 0;
		goto _out;
		ctr0:
		{
			printf("finish a\n");
		}
		
		
		goto st2;
		st2:
		p+= 1;
		if ( p == pe  )
		goto _test_eof2;
		
		st_case_2:
		if ( ((*( p  ))
		)== 98  )
		{
			goto ctr2;
		}
		
		{
			goto st0;
		}
		ctr2:
		{
			printf("leave a\n");
		}
		{
			printf("enter b1\n");
		}
		{
			printf("enter b2\n");
		}
		
		
		goto st3;
		st3:
		p+= 1;
		if ( p == pe  )
		goto _test_eof3;
		
		st_case_3:
		if ( ((*( p  ))
		)== 10  )
		{
			goto st4;
		}
		
		{
			goto st0;
		}
		st4:
		p+= 1;
		if ( p == pe  )
		goto _test_eof4;
		
		st_case_4:
		{
			goto st0;
		}
		st_out:
		_test_eof2: (fsm->cs) = 2;
		goto _test_eof; 
		_test_eof3: (fsm->cs) = 3;
		goto _test_eof; 
		_test_eof4: (fsm->cs) = 4;
		goto _test_eof; 
		
		_test_eof: {}
		_out: {}
	}
}

int forder_finish( struct forder *fsm )
{
	if ( fsm->cs == forder_error )
	return -1;
	if ( fsm->cs >= forder_first_final )
	return 1;
	return 0;
}

struct forder fsm;

void test( char *buf )
{
	int len = strlen(buf);
	forder_init( &fsm );
	forder_execute( &fsm, buf, len );
	if ( forder_finish( &fsm ) > 0 )
	printf("ACCEPT\n");
	else
	printf("FAIL\n");
}

int main()
{
	test( "ab\n");
	test( "abx\n");
	test( "" );
	
	test(
	"ab\n"
	"fail after newline\n"
	);
	
	return 0;
}

