#include <string.h>
#include <stdio.h>

char comm ;
int top ;
int stack [32];





static const char  _gotocallret_key_offsets [] = { 0, 0, 1, 2, 3, 4, 8, 10, 14, 14, 18, 0 ,  };
static const char  _gotocallret_trans_keys [] = { 32, 10, 10, 10, 65, 90, 97, 122, 48, 57, 48, 57, 97, 122, 65, 90, 97, 122, 48, 57, 0 ,  };
static const char  _gotocallret_single_lengths [] = { 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0 ,  };
static const char  _gotocallret_range_lengths [] = { 0, 0, 0, 0, 0, 2, 1, 2, 0, 2, 1, 0 ,  };
static const char  _gotocallret_index_offsets [] = { 0, 0, 2, 4, 6, 8, 11, 13, 16, 17, 20, 0 ,  };
static const char  _gotocallret_trans_cond_spaces [] = { -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0 ,  };
static const char  _gotocallret_trans_offsets [] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 0 ,  };
static const char  _gotocallret_trans_lengths [] = { 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0 ,  };
static const char  _gotocallret_cond_keys [] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  };
static const char  _gotocallret_cond_targs [] = { 2, 0, 7, 0, 8, 4, 8, 4, 9, 9, 0, 10, 0, 1, 1, 0, 0, 9, 9, 0, 10, 0, 0 ,  };
static const char  _gotocallret_cond_actions [] = { 2, 1, 3, 1, 6, 5, 7, 0, 0, 0, 8, 0, 8, 9, 9, 1, 0, 0, 0, 8, 0, 8, 0 ,  };
static const char  _gotocallret_eof_actions [] = { 0, 1, 1, 4, 4, 8, 8, 0, 4, 0, 0, 0 ,  };
static const char  _gotocallret_nfa_targs [] = { 0, 0 ,  };
static const char  _gotocallret_nfa_offsets [] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  };
static const char  _gotocallret_nfa_push_actions [] = { 0, 0 ,  };
static const char  _gotocallret_nfa_pop_trans [] = { 0, 0 ,  };
static const int  gotocallret_start  = 7;
static const int  gotocallret_first_final  = 7;
static const int  gotocallret_error  = 0;
static const int  gotocallret_en_garble_line  = 3;
static const int  gotocallret_en_alp_comm  = 5;
static const int  gotocallret_en_dig_comm  = 6;
static const int  gotocallret_en_main  = 7;
int cs;
int blen;
char buffer[1024];

void init()
{

	{
		cs = ( int ) gotocallret_start;
		top = 0;
	}
}

void exec( char *data, int len )
{
	char *p = data;
	char *pe = data + len;
	char *eof = pe;
	
	{
		int _klen;
		const char  *_keys;
		const char  *_ckeys;
		int _cpc;
		unsigned int _trans = 0;
		unsigned int _cond = 0;
		if ( p == pe  )
		goto _test_eof;
		
		if ( cs == 0  )
		goto _out;
		
		_resume :
		_keys = _gotocallret_trans_keys + _gotocallret_key_offsets[cs];
		_trans = ( unsigned int  ) _gotocallret_index_offsets[cs];
		_klen = ( int ) _gotocallret_single_lengths[cs];
		if ( _klen > 0  )
		{
			const char  *_lower;
			const char  *_mid;
			const char  *_upper;
			_lower = _keys;
			_upper = _keys + _klen - 1;
			while ( 1 )
			{
				if ( _upper < _lower  )
				break;
				
				
				_mid = _lower + ((_upper-_lower)>> 1);
				if ( ((*( p  ))
				)< (*( _mid  ))
				)
				_upper = _mid - 1;
				
				else if ( ((*( p  ))
				)> (*( _mid  ))
				)
				_lower = _mid + 1;
				
				else
				{
					_trans += ( unsigned int  ) (_mid - _keys);
					goto _match;
				}
				
			}
			
			_keys += _klen;
			_trans += ( unsigned int  ) _klen;
		}
		
		
		_klen = ( int ) _gotocallret_range_lengths[cs];
		if ( _klen > 0  )
		{
			const char  *_lower;
			const char  *_mid;
			const char  *_upper;
			_lower = _keys;
			_upper = _keys + (_klen<<1)- 2;
			while ( 1 )
			{
				if ( _upper < _lower  )
				break;
				
				
				_mid = _lower + (((_upper-_lower)>> 1)& ~1);
				if ( ((*( p  ))
				)< (*( _mid  ))
				)
				_upper = _mid - 2;
				
				else if ( ((*( p  ))
				)> (*( _mid + 1  ))
				)
				_lower = _mid + 2;
				
				else
				{
					_trans += ( unsigned int  ) ((_mid - _keys)>>1);
					goto _match;
				}
				
			}
			
			_trans += ( unsigned int  ) _klen;
		}
		
		
		
		_match :
		_ckeys = _gotocallret_cond_keys + _gotocallret_trans_offsets[_trans];
		_klen = ( int ) _gotocallret_trans_lengths[_trans];
		_cond = ( unsigned int  ) _gotocallret_trans_offsets[_trans];
		_cpc = 0;
		{
			const char  *_lower;
			const char  *_mid;
			const char  *_upper;
			_lower = _ckeys;
			_upper = _ckeys + _klen - 1;
			while ( 1 )
			{
				if ( _upper < _lower  )
				break;
				
				
				_mid = _lower + ((_upper-_lower)>> 1);
				if ( _cpc < ( int ) (*( _mid  ))
				)
				_upper = _mid - 1;
				
				else if ( _cpc > ( int ) (*( _mid  ))
				)
				_lower = _mid + 1;
				
				else
				{
					_cond += ( unsigned int  ) (_mid - _ckeys);
					goto _match_cond;
				}
				
			}
			
			cs = 0;
			goto _again;
		}
		
		_match_cond :
		cs = ( int ) _gotocallret_cond_targs[_cond];
		if ( _gotocallret_cond_actions[_cond]== 0  )
		goto _again;
		
		
		switch ( _gotocallret_cond_actions[_cond] ) {
			case 5 :
			{
				printf( "%s", "error: garbling line\n" );
				
			}
			
			break;
			case 7 :
			{
				{
					cs = 7;
					
				}
				
			}
			
			break;
			case 8 :
			{
				{
					p = p - 1;
					
				}
				{
					top-= 1;
					cs = stack[top];
					
				}
				
			}
			
			break;
			case 9 :
			{
				comm = (((*( p  ))
				));
				
			}
			
			break;
			case 3 :
			{
				printf( "%s", "correct command\n" );
				
			}
			
			break;
			case 1 :
			{
				{
					p = p - 1;
					
				}
				{
					cs = 3;
					
				}
				
			}
			
			break;
			case 6 :
			{
				printf( "%s", "error: garbling line\n" );
				
			}
			{
				{
					cs = 7;
					
				}
				
			}
			
			break;
			case 2 :
			{
				if ( comm >= 97 )
				{
					{
						stack[top] = cs;
						top += 1;
						cs = 5;
						
					}
				} 
				else {
					{
						stack[top] = cs;
						top += 1;
						cs = 6;
						
					}
				}
				
			}
			{
				printf( "%s", "prints\n" );
				
			}
			
			break;
			
		}
		
		_again :
		if ( cs == 0  )
		goto _out;
		
		p += 1;
		if ( p != pe  )
		goto _resume;
		
		
		_test_eof :
		{}
		if ( p == eof  )
		{
			switch ( _gotocallret_eof_actions[cs] ) {
				case 4 :
				{
					printf( "%s", "error: failed to recover\n" );
					
				}
				
				break;
				case 8 :
				{
					{
						p = p - 1;
						
					}
					{
						top-= 1;
						cs = stack[top];
						
					}
					
				}
				
				break;
				case 1 :
				{
					{
						p = p - 1;
						
					}
					{
						cs = 3;
						
					}
					
				}
				
				break;
				
			}
		}
		
		
		
		_out :
		{}
		
	}
}

void finish( )
{
	if ( cs >= gotocallret_first_final )
	printf( "ACCEPT\n" );
	else
	printf( "FAIL\n" );
}

char *inp[] = {
	"lkajsdf\n",
	"2134\n",
	"(\n",
	"\n",
	"*234234()0909 092 -234aslkf09`1 11\n",
	"1\n",
	"909\n",
	"1 a\n",
	"11 1\n",
	"a 1\n",
	"aa a\n",
	"1 1\n",
	"1 123456\n",
	"a a\n",
	"a abcdef\n",
	"h",
	"a aa1",
};

int inplen = 17;

int main( )
{
	int i;
	for ( i = 0; i < inplen; i++ ) {
		init();
		exec( inp[i], strlen(inp[i]) );
		finish();
	}
	return 0;
}

