static mut comm : u8 = 0;
static mut top : i32 = 0;
static mut stack : [ i32 ; 32] = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ];





static _gotocallret_actions: [i8 ; 23] = [ 0, 1, 0, 1, 1, 1, 2, 1, 3, 1, 5, 1, 7, 1, 8, 2, 0, 1, 2, 4, 6, 0 , 0 ];
static _gotocallret_key_offsets: [i8 ; 13] = [ 0, 0, 1, 2, 3, 4, 8, 10, 14, 14, 18, 0 , 0 ];
static _gotocallret_trans_keys: [u8 ; 22] = [ 32, 10, 10, 10, 65, 90, 97, 122, 48, 57, 48, 57, 97, 122, 65, 90, 97, 122, 48, 57, 0 , 0 ];
static _gotocallret_single_lengths: [i8 ; 13] = [ 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0 , 0 ];
static _gotocallret_range_lengths: [i8 ; 13] = [ 0, 0, 0, 0, 0, 2, 1, 2, 0, 2, 1, 0 , 0 ];
static _gotocallret_index_offsets: [i8 ; 13] = [ 0, 0, 2, 4, 6, 8, 11, 13, 16, 17, 20, 0 , 0 ];
static _gotocallret_trans_cond_spaces: [i8 ; 24] = [ -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0 , 0 ];
static _gotocallret_trans_offsets: [i8 ; 24] = [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 0 , 0 ];
static _gotocallret_trans_lengths: [i8 ; 24] = [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0 , 0 ];
static _gotocallret_cond_keys: [i8 ; 24] = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 , 0 ];
static _gotocallret_cond_targs: [i8 ; 24] = [ 2, 0, 7, 0, 8, 4, 8, 4, 9, 9, 0, 10, 0, 1, 1, 0, 0, 9, 9, 0, 10, 0, 0 , 0 ];
static _gotocallret_cond_actions: [i8 ; 24] = [ 18, 13, 11, 13, 15, 1, 3, 0, 0, 0, 7, 0, 7, 9, 9, 13, 0, 0, 0, 7, 0, 7, 0 , 0 ];
static _gotocallret_eof_actions: [i8 ; 13] = [ 0, 13, 13, 5, 5, 7, 7, 0, 5, 0, 0, 0 , 0 ];
static _gotocallret_nfa_targs: [i8 ; 3] = [ 0, 0 , 0 ];
static _gotocallret_nfa_offsets: [i8 ; 13] = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 , 0 ];
static _gotocallret_nfa_push_actions: [i8 ; 3] = [ 0, 0 , 0 ];
static _gotocallret_nfa_pop_trans: [i8 ; 3] = [ 0, 0 , 0 ];
static gotocallret_start : i32 = 7;
static gotocallret_first_final : i32 = 7;
static gotocallret_error : i32 = 0;
static gotocallret_en_garble_line : i32 = 3;
static gotocallret_en_alp_comm : i32 = 5;
static gotocallret_en_dig_comm : i32 = 6;
static gotocallret_en_main : i32 = 7;
unsafe fn m( s: String )
{
	let data: &[u8] = s.as_bytes();
	let mut p:i32 = 0;
	let mut pe:i32 = s.len() as i32;
	let mut eof:i32 = s.len() as i32;
	let mut cs: i32 = 0;
	let mut buffer = String::new();
	
	
	{
		cs = ( gotocallret_start ) as i32;
		top = 0;
	}
	
	{
		let mut _klen = 0;
		let mut _trans  = 0;
		let mut _cond  = 0;
		let mut _have  = 0;
		let mut _cont  = 1;
		let mut _acts :i32 = 0;
		let mut _nacts = 0;
		let mut _keys :i32 = 0;
		let mut _ckeys :i32 = 0;
		let mut _cpc = 0;
		while ( _cont == 1  )
		{
		
			if ( cs == 0  ) {
				_cont = 0;
				
			}
			_have = 0;
			if ( p == pe  ) {
				{
					if ( p == eof  ) {
						{
							if ( _have == 0  ) {
								{
									let mut __acts :i32 = 0;
									let mut __nacts = 0;
									__acts = ( _gotocallret_eof_actions[(cs) as usize] ) as i32;
									__nacts = ( _gotocallret_actions[(__acts ) as usize]
									) as u32;
									__acts += 1;
									while ( __nacts > 0  )
									{
										match ( _gotocallret_actions[(__acts ) as usize]
										) {
											2  => {
												{print!( "{}", "error: failed to recover\n" );
												}
												
											}
											3  => {
												{{p = p - 1;
													}{top-= 1;
														cs = stack[(top) as usize];
													}}
												
											}
											8  => {
												{{p = p - 1;
													}{cs = 3;
													}}
												
											}
											
											_ => {}
										}
										__nacts -= 1;
										__acts += 1;
									}
									
								}
								
							}
						}
						
						
					}
					if ( _have == 0  ) {
						_cont = 0;
						
					}
				}
				
			}
			if ( _cont == 1  ) {
				{
					if ( _have == 0  ) {
						{
							_keys = ( _gotocallret_key_offsets[(cs) as usize] ) as i32;
							_trans = ( _gotocallret_index_offsets[(cs) as usize] ) as u32;
							_have = 0;
							_klen = ( _gotocallret_single_lengths[(cs) as usize] ) as i32;
							if ( _klen > 0  ) {
								{
									let mut _lower :i32 = 0;
									let mut _mid :i32 = 0;
									let mut _upper :i32 = 0;
									_lower = _keys;
									_upper = _keys + _klen - 1;
									while ( _upper >= _lower && _have == 0  )
									{
										_mid = _lower + ((_upper-_lower) >> 1);
										if ( ( data[(p ) as usize]
										) < _gotocallret_trans_keys[(_mid ) as usize]
										) {
											_upper = _mid - 1;
											
										}
										else if ( ( data[(p ) as usize]
										) > _gotocallret_trans_keys[(_mid ) as usize]
										) {
											_lower = _mid + 1;
											
										}
										else {
											{
												_trans += ( (_mid - _keys) ) as u32;
												_have = 1;
											}
											
										}
									}
									
									if ( _have == 0  ) {
										{
											_keys += _klen;
											_trans += ( _klen ) as u32;
										}
										
									}
								}
								
								
							}
							if ( _have == 0  ) {
								{
									_klen = ( _gotocallret_range_lengths[(cs) as usize] ) as i32;
									if ( _klen > 0  ) {
										{
											let mut _lower :i32 = 0;
											let mut _mid :i32 = 0;
											let mut _upper :i32 = 0;
											_lower = _keys;
											_upper = _keys + (_klen<<1) - 2;
											while ( _have == 0 && _lower <= _upper  )
											{
												_mid = _lower + (((_upper-_lower) >> 1) & !1
												);
												if ( ( data[(p ) as usize]
												) < _gotocallret_trans_keys[(_mid ) as usize]
												) {
													_upper = _mid - 2;
													
												}
												else if ( ( data[(p ) as usize]
												) > _gotocallret_trans_keys[(_mid + 1 ) as usize]
												) {
													_lower = _mid + 2;
													
												}
												else {
													{
														_trans += ( ((_mid - _keys)>>1) ) as u32;
														_have = 1;
													}
													
												}
											}
											
											if ( _have == 0  ) {
												_trans += ( _klen ) as u32;
												
											}
										}
										
									}
								}
								
								
							}
							_ckeys = ( _gotocallret_trans_offsets[(_trans) as usize] ) as i32;
							_klen = ( _gotocallret_trans_lengths[(_trans) as usize] ) as i32;
							_cond = ( _gotocallret_trans_offsets[(_trans) as usize] ) as u32;
							_have = 0;
							_cpc = 0;
							{
								let mut _lower :i32 = 0;
								let mut _mid :i32 = 0;
								let mut _upper :i32 = 0;
								_lower = _ckeys;
								_upper = _ckeys + _klen - 1;
								while ( _have == 0 && _lower <= _upper  )
								{
									_mid = _lower + ((_upper-_lower) >> 1);
									if ( _cpc < ( _gotocallret_cond_keys[(_mid ) as usize]
									) as i32 ) {
										_upper = _mid - 1;
										
									}
									else if ( _cpc > ( _gotocallret_cond_keys[(_mid ) as usize]
									) as i32 ) {
										_lower = _mid + 1;
										
									}
									else {
										{
											_cond += ( (_mid - _ckeys) ) as u32;
											_have = 1;
										}
										
									}
								}
								
								if ( _have == 0  ) {
									{
										cs = 0;
										_cont = 0;
									}
									
								}
							}
						}
						
					}
					if ( _cont == 1  ) {
						{
							cs = ( _gotocallret_cond_targs[(_cond) as usize] ) as i32;
							if ( _gotocallret_cond_actions[(_cond) as usize]!= 0  ) {
								{
									_acts = ( _gotocallret_cond_actions[(_cond) as usize] ) as i32;
									_nacts = ( _gotocallret_actions[(_acts ) as usize]
									) as u32;
									_acts += 1;
									while ( _nacts > 0  )
									{
										match ( _gotocallret_actions[(_acts ) as usize]
										) {
											0  => {
												{print!( "{}", "error: garbling line\n" );
												}
												
											}
											1  => {
												{{cs = 7;
													}}
												
											}
											3  => {
												{{p = p - 1;
													}{top-= 1;
														cs = stack[(top) as usize];
													}}
												
											}
											4  => {
												{if ( comm >= 97 )
													{
														{stack[(top) as usize]
															= cs;
															top += 1;
															cs = 5;
														}} 
													else {
														{stack[(top) as usize]
															= cs;
															top += 1;
															cs = 6;
														}}
												}
												
											}
											5  => {
												{comm = (( data[(p ) as usize]
													));
												}
												
											}
											6  => {
												{print!( "{}", "prints\n" );
												}
												
											}
											7  => {
												{print!( "{}", "correct command\n" );
												}
												
											}
											8  => {
												{{p = p - 1;
													}{cs = 3;
													}}
												
											}
											
											_ => {}
										}
										_nacts -= 1;
										_acts += 1;
									}
									
								}
								
								
							}
							if ( cs == 0  ) {
								_cont = 0;
								
							}
							if ( _cont == 1  ) {
								p += 1;
								
							}
						}
						
					}
				}
				
			}
		}
		
	}
	if ( cs >= gotocallret_first_final ) {
		println!( "ACCEPT" );
	}
	else {
		println!( "FAIL" );
	}
}

fn main()
{
	unsafe { m( "lkajsdf\n".to_string() ); }
	unsafe { m( "2134\n".to_string() ); }
	unsafe { m( "(\n".to_string() ); }
	unsafe { m( "\n".to_string() ); }
	unsafe { m( "*234234()0909 092 -234aslkf09`1 11\n".to_string() ); }
	unsafe { m( "1\n".to_string() ); }
	unsafe { m( "909\n".to_string() ); }
	unsafe { m( "1 a\n".to_string() ); }
	unsafe { m( "11 1\n".to_string() ); }
	unsafe { m( "a 1\n".to_string() ); }
	unsafe { m( "aa a\n".to_string() ); }
	unsafe { m( "1 1\n".to_string() ); }
	unsafe { m( "1 123456\n".to_string() ); }
	unsafe { m( "a a\n".to_string() ); }
	unsafe { m( "a abcdef\n".to_string() ); }
	unsafe { m( "h".to_string() ); }
	unsafe { m( "a aa1".to_string() ); }
}

