using System;
// Disables lots of warnings that appear in the test suite
#pragma warning disable 0168, 0169, 0219, 0162, 0414
namespace Test {
	class Test
	{
		int target;
		int last;
		
		
		
		
		static readonly sbyte  []_next2_actions = { 0, 1, 0, 1, 1, 1, 2, 1, 3, 1, 4, 1, 5, 0,  };
		static readonly char  []_next2_trans_keys = { '\u0001', '\u0000', '\u000f', '\u000f', '\u000d', '\u000d', '\u0008', '\u0008', '\u000d', '\u000d', '\u000b', '\u000b', '\u0006', '\u0006', '\u0005', '\u0005', '\u0009', '\u0009', '\u0008', '\u0008', '\u0006', '\u0006', '\u000c', '\u000c', '\u000e', '\u000e', '\u0009', '\u0009', '\u000c', '\u000c', '\u0007', '\u0007', '\u000a', '\u000a', '\u0006', '\u0006', '\u0006', '\u0006', '\u0000', '\u0004', '\u0001', '\u0000', '\u0001', '\u0000', '\u0001', '\u0000', '\u0001', '\u0000', '\u0000',  };
		static readonly sbyte  []_next2_char_class = { 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 5, 6, 1, 1, 7, 1, 1, 1, 1, 1, 8, 9, 1, 1, 10, 11, 12, 13, 1, 14, 15, 0,  };
		static readonly sbyte  []_next2_index_offsets = { 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 23, 23, 23, 23, 0,  };
		static readonly sbyte  []_next2_indicies = { 0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 0, 1, 19, 20, 21, 0,  };
		static readonly sbyte  []_next2_index_defaults = { 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,  };
		static readonly sbyte  []_next2_trans_cond_spaces = { -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0,  };
		static readonly sbyte  []_next2_cond_targs = { 19, 0, 3, 4, 5, 6, 7, 20, 9, 10, 21, 12, 13, 22, 15, 16, 17, 18, 23, 19, 19, 1, 0,  };
		static readonly sbyte  []_next2_cond_actions = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 3, 0, 0, 0, 0, 5, 7, 9, 11, 0,  };
		static readonly sbyte  []_next2_nfa_targs = { 0, 0,  };
		static readonly sbyte  []_next2_nfa_offsets = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  };
		static readonly sbyte  []_next2_nfa_push_actions = { 0, 0,  };
		static readonly sbyte  []_next2_nfa_pop_trans = { 0, 0,  };
		static readonly int  next2_start  = 19;
		static readonly int  next2_first_final  = 19;
		static readonly int  next2_error  = 0;
		static readonly int  next2_en_unused  = 2;
		static readonly int  next2_en_one  = 8;
		static readonly int  next2_en_two  = 11;
		static readonly int  next2_en_three  = 14;
		static readonly int  next2_en_main  = 19;
		int cs;
		
		void init()
		{
		
			{
				cs = (int)next2_start;
			}
		}
		
		void exec( char[] data, int len )
		{
			int p = 0;
			int pe = len;
			int eof = len;
			string _s;
			char [] buffer = new char [1024];
			int blen = 0;
			
			{
				int _trans = 0;
				int _acts;
				uint _nacts;
				int _keys;
				int _inds;
				if ( p == pe  )
				goto _test_eof;
				
				if ( cs == 0 )
				goto _out;
				
				_resume :
				_keys = (cs<<1) ;
				_inds = _next2_index_offsets[cs] ;
				if ( ( data[p ]) <= 120&& ( data[p ]) >= 10 )
				{
					int _ic = (int)_next2_char_class[(int)( data[p ]) - 10];
					if ( _ic <= (int)_next2_trans_keys[_keys+1]&& _ic >= (int)_next2_trans_keys[_keys ] )
					_trans = (int)_next2_indicies[_inds + (int)( _ic - (int)_next2_trans_keys[_keys ])  ];
					
					else
					_trans = (int)_next2_index_defaults[cs];
					
				}
				
				else
				{
					_trans = (int)_next2_index_defaults[cs];
				}
				
				
				goto _match_cond;
				
				_match_cond :
				cs = (int)_next2_cond_targs[_trans];
				if ( _next2_cond_actions[_trans] == 0 )
				goto _again;
				
				
				_acts = _next2_cond_actions[_trans] ;
				_nacts = (uint )_next2_actions[_acts ];
				_acts += 1;
				while ( _nacts > 0 )
				{
					switch ( _next2_actions[_acts ] ) {
						case 0:
						{Console.Write( "one\n" );target = 19;
							{cs = (target);
							}}
						
						break;
						case 1:
						{Console.Write( "two\n" );target = 19;
							{cs = (target);
							}}
						
						break;
						case 2:
						{Console.Write( "three\n" );target = 19;
							{cs = (target);
							}}
						
						break;
						case 3:
						{target = 8;
							{cs = (target);
							}last = 1;
						}
						
						break;
						case 4:
						{target = 11;
							{cs = (target);
							}last = 2;
						}
						
						break;
						case 5:
						{if ( last == 2 )
							{
								target = 14;
								{cs = (target);
								}
							} 
							last = 3;
						}
						
						break;
						
					}
					_nacts -= 1;
					_acts += 1;
				}
				
				
				
				
				_again :
				if ( cs == 0 )
				goto _out;
				
				p += 1;
				if ( p != pe  )
				goto _resume;
				
				
				_test_eof :
				{}
				
				_out :
				{}
				
			}
		}
		
		void finish( )
		{
			if ( cs >= next2_first_final )
			Console.WriteLine( "ACCEPT" );
			else
			Console.WriteLine( "FAIL" );
		}
		
		static readonly string[] inp = {
			"1one3x2two3three\n",
		};
		
		
		static readonly int inplen = 1;
		
		public static void Main (string[] args)
		{
			Test machine = new Test();
			for ( int i = 0; i < inplen; i++ ) {
				machine.init();
				machine.exec( inp[i].ToCharArray(), inp[i].Length );
				machine.finish();
			}
		}
	}
}
