const _next2_trans_keys = UInt8[1, 0, 15, 15, 13, 13, 8, 8, 13, 13, 11, 11, 6, 6, 5, 5, 9, 9, 8, 8, 6, 6, 12, 12, 14, 14, 9, 9, 12, 12, 7, 7, 10, 10, 6, 6, 6, 6, 0, 4, 1, 0, 1, 0, 1, 0, 1, 0, 0 , ]
const _next2_char_class = Int8[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 5, 6, 1, 1, 7, 1, 1, 1, 1, 1, 8, 9, 1, 1, 10, 11, 12, 13, 1, 14, 15, 0 , ]
const _next2_index_offsets = Int8[0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 23, 23, 23, 23, 0 , ]
const _next2_indicies = Int8[0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 0, 1, 19, 20, 21, 0 , ]
const _next2_index_defaults = Int8[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0 , ]
const _next2_trans_cond_spaces = Int8[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0 , ]
const _next2_cond_targs = Int8[19, 0, 3, 4, 5, 6, 7, 20, 9, 10, 21, 12, 13, 22, 15, 16, 17, 18, 23, 19, 19, 1, 0 , ]
const _next2_cond_actions = Int8[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 3, 4, 5, 6, 0 , ]
const _next2_nfa_targs = Int8[0, 0 , ]
const _next2_nfa_offsets = Int8[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 , ]
const _next2_nfa_push_actions = Int8[0, 0 , ]
const _next2_nfa_pop_trans = Int8[0, 0 , ]
const next2_start  = 19
const next2_first_final  = 19
const next2_error  = 0
const next2_en_unused  = 2
const next2_en_one  = 8
const next2_en_two  = 11
const next2_en_three  = 14
const next2_en_main  = 19
function m( data::AbstractString )
	p = 0
	pe = length(data)
	eof = length(data)
	cs = 0
	buffer = ""
	target = 0;
	last = 0;
	
	cs = convert(Int, next2_start )
	_trans = 0;
	_have = 0;
	_cont = 1;
	_keys = 0;
	_inds = 0;
	while _cont == 1 
		if cs == 0 
			_cont = 0
			
		end
		_have = 0
		if p == pe 
			if _have == 0 
				_cont = 0
				
			end
			
		end
		if _cont == 1 
			if _have == 0 
				_keys = (cs<<1)
				_inds = _next2_index_offsets[1+(cs)]
				if (data[1+(p )])<= 120 && (data[1+(p )])>= 10 
					_ic = convert(Int, _next2_char_class[1+(convert(Int, (data[1+(p )]) )- 10)] );
					if _ic <= convert(Int, _next2_trans_keys[1+(_keys+1 )] )&& _ic >= convert(Int, _next2_trans_keys[1+(_keys )] )
						_trans = convert(UInt, _next2_indicies[1+(_inds + convert(Int, (_ic - convert(Int, _next2_trans_keys[1+(_keys )] )) ))] )
						
					else
						_trans = convert(UInt, _next2_index_defaults[1+(cs)] )
						
					end
					
				else
					_trans = convert(UInt, _next2_index_defaults[1+(cs)] )
					
				end
				
			end
			if _cont == 1 
				cs = convert(Int, _next2_cond_targs[1+(_trans)] )
				if _next2_cond_actions[1+(_trans)] == 1 
					print( "one\n" );
					target = 19;
					{
						cs = (target)
						
					}
					
				elseif _next2_cond_actions[1+(_trans)] == 2 
					print( "two\n" );
					target = 19;
					{
						cs = (target)
						
					}
					
				elseif _next2_cond_actions[1+(_trans)] == 3 
					print( "three\n" );
					target = 19;
					{
						cs = (target)
						
					}
					
				elseif _next2_cond_actions[1+(_trans)] == 4 
					target = 8;
					{
						cs = (target)
						
					}
					last = 1;
					
				elseif _next2_cond_actions[1+(_trans)] == 5 
					target = 11;
					{
						cs = (target)
						
					}
					last = 2;
					
				elseif _next2_cond_actions[1+(_trans)] == 6 
					if ( last == 2 )
						target = 14;
						{
							cs = (target)
							
						}
						
					end
					last = 3;
					
				end
				if cs == 0 
					_cont = 0
					
				end
				if _cont == 1 
					p += 1
					
				end
				
			end
			
		end
		
	end
	if ( cs >= next2_first_final )
		println( "ACCEPT" );
	else
		println( "FAIL" );
	end
end

m( "1one3x2two3three\n" );
