#include <stddef.h>
#include <stdint.h>
#include <stdlib.h> 
#include <stdbool.h>
#include <string.h>
#include <stdio.h>

const char s[4096];

struct nfa_stack
{
	void *data;
	unsigned long sz;
};

struct nfa_bp_rec
{
	long state;
	const char *p;
	long popTrans;
	long q_2;
};



static const char  _atoi_actions [] = { 0, 0, 1, 2, 1, 3, 1, 0, 2, 3, 5, 2, 3, 6, 2, 3, 7, 3, 3, 9, 4, 0 ,  };
static const char  _atoi_key_offsets [] = { 0, 0, 1, 1, 2, 2, 2, 3, 0 ,  };
static const char  _atoi_trans_keys [] = { 97, 46, 59, 0 ,  };
static const char  _atoi_single_lengths [] = { 0, 1, 0, 1, 0, 0, 1, 0, 0 ,  };
static const char  _atoi_range_lengths [] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  };
static const char  _atoi_index_offsets [] = { 0, 0, 2, 3, 5, 6, 7, 9, 0 ,  };
static const char  _atoi_trans_cond_spaces [] = { -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0 ,  };
static const char  _atoi_trans_offsets [] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0 ,  };
static const char  _atoi_trans_lengths [] = { 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0 ,  };
static const char  _atoi_cond_keys [] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  };
static const char  _atoi_cond_targs [] = { 2, 0, 0, 4, 0, 0, 0, 7, 0, 0, 0 ,  };
static const char  _atoi_cond_actions [] = { 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0 ,  };
static const char  _atoi_nfa_targs [] = { 0, 1, 3, 3, 6, 3, 5, 0 ,  };
static const char  _atoi_nfa_offsets [] = { 0, 0, 1, 0, 3, 0, 0, 0, 0 ,  };
static const char  _atoi_nfa_push_actions [] = { 0, 0, 1, 0, 1, 1, 1, 0 ,  };
static const char  _atoi_nfa_pop_trans [] = { 0, 0, 4, 0, 7, 6, 5, 0 ,  };
static const int  atoi_start  = 1;
static const int  atoi_first_final  = 7;
static const int  atoi_error  = 0;
static const int  atoi_en_main  = 1;
int test( const char *p, bool a, bool b )
{
	int len = strlen( p ) + 1;
	const char *pe = p + len;
	int cs;
	
	struct nfa_bp_rec *nfa_bp = (struct nfa_bp_rec*) s;
	long nfa_len = 0;
	long nfa_count = 0;
	
	long q_2 = 0;
	
	printf( "testing: %s %d %d\n", p, a, b );
	
	
	{
		cs = ( int ) atoi_start;
		nfa_len = 0;
	}
	
	{
		int _klen;
		unsigned int _trans = 0;
		unsigned int _cond = 0;
		const char  *_acts;
		unsigned int _nacts;
		const char  *_keys;
		const char  *_ckeys;
		int _cpc;
		if ( p == pe  )
		goto _test_eof;
		
		if ( cs == 0  )
		goto _out;
		
		_resume :
		if ( _atoi_nfa_offsets[cs] )
		{
			int alt = 0; 
			int new_recs = _atoi_nfa_targs[( int ) _atoi_nfa_offsets[cs]];
			while ( alt < new_recs  )
			{ 
				nfa_bp[nfa_len].state 
				= _atoi_nfa_targs[( int ) _atoi_nfa_offsets[cs]+ 1 + alt];
				nfa_bp[nfa_len].p 
				= p;
				nfa_bp[nfa_len].popTrans 
				= ( long ) _atoi_nfa_offsets[cs]+ 1 + alt;
				switch ( _atoi_nfa_push_actions[( int ) _atoi_nfa_offsets[cs]+ 1 + alt] ) {
					case 1 :
					{
						nfa_bp[nfa_len].q_2 = q_2; 
					}
					
					break;
					
				}
				nfa_len += 1;
				alt += 1;
			}
			
		}
		
		_keys = _atoi_trans_keys + _atoi_key_offsets[cs];
		_trans = ( unsigned int  ) _atoi_index_offsets[cs];
		_klen = ( int ) _atoi_single_lengths[cs];
		if ( _klen > 0  )
		{
			const char  *_lower;
			const char  *_mid;
			const char  *_upper;
			_lower = _keys;
			_upper = _keys + _klen - 1;
			while ( 1 )
			{
				if ( _upper < _lower  )
				break;
				
				
				_mid = _lower + ((_upper-_lower)>> 1);
				if ( ((*( p  ))
				)< (*( _mid  ))
				)
				_upper = _mid - 1;
				
				else if ( ((*( p  ))
				)> (*( _mid  ))
				)
				_lower = _mid + 1;
				
				else
				{
					_trans += ( unsigned int  ) (_mid - _keys);
					goto _match;
				}
				
			}
			
			_keys += _klen;
			_trans += ( unsigned int  ) _klen;
		}
		
		
		_klen = ( int ) _atoi_range_lengths[cs];
		if ( _klen > 0  )
		{
			const char  *_lower;
			const char  *_mid;
			const char  *_upper;
			_lower = _keys;
			_upper = _keys + (_klen<<1)- 2;
			while ( 1 )
			{
				if ( _upper < _lower  )
				break;
				
				
				_mid = _lower + (((_upper-_lower)>> 1)& ~1);
				if ( ((*( p  ))
				)< (*( _mid  ))
				)
				_upper = _mid - 2;
				
				else if ( ((*( p  ))
				)> (*( _mid + 1  ))
				)
				_lower = _mid + 2;
				
				else
				{
					_trans += ( unsigned int  ) ((_mid - _keys)>>1);
					goto _match;
				}
				
			}
			
			_trans += ( unsigned int  ) _klen;
		}
		
		
		
		_match :
		_ckeys = _atoi_cond_keys + _atoi_trans_offsets[_trans];
		_klen = ( int ) _atoi_trans_lengths[_trans];
		_cond = ( unsigned int  ) _atoi_trans_offsets[_trans];
		_cpc = 0;
		switch ( _atoi_trans_cond_spaces[_trans] ) {
			case 0 :
			if ( (a) )
			_cpc += 1;
			
			
			break;
			case 1 :
			if ( (a) )
			_cpc += 1;
			
			if ( (b) )
			_cpc += 2;
			
			
			break;
			
		}
		{
			const char  *_lower;
			const char  *_mid;
			const char  *_upper;
			_lower = _ckeys;
			_upper = _ckeys + _klen - 1;
			while ( 1 )
			{
				if ( _upper < _lower  )
				break;
				
				
				_mid = _lower + ((_upper-_lower)>> 1);
				if ( _cpc < ( int ) (*( _mid  ))
				)
				_upper = _mid - 1;
				
				else if ( _cpc > ( int ) (*( _mid  ))
				)
				_lower = _mid + 1;
				
				else
				{
					_cond += ( unsigned int  ) (_mid - _ckeys);
					goto _match_cond;
				}
				
			}
			
			cs = 0;
			goto _again;
		}
		
		_match_cond :
		cs = ( int ) _atoi_cond_targs[_cond];
		if ( _atoi_cond_actions[_cond]== 0  )
		goto _again;
		
		
		_acts = _atoi_actions + _atoi_cond_actions[_cond];
		_nacts = ( unsigned int  ) (*( _acts  ))
		;
		_acts += 1;
		while ( _nacts > 0  )
		{
			switch ( (*( _acts  ))
			) {
				case 0 :
				{
					printf( " --> MATCH\n" ); 
				}
				
				break;
				
			}
			_nacts -= 1;
			_acts += 1;
		}
		
		
		
		
		_again :
		if ( cs == 0  )
		goto _out;
		
		p += 1;
		if ( p != pe  )
		goto _resume;
		
		
		_test_eof :
		{}
		
		_out :
		{}
		
		if ( nfa_len > 0  )
		{
			nfa_count += 1;
			nfa_len -= 1;
			p = nfa_bp[nfa_len].p;
			int _pop_test = 1;
			switch ( _atoi_nfa_pop_trans[nfa_bp[nfa_len].popTrans] ) {
				case 5 :
				_pop_test = (({ q_2 = nfa_bp[nfa_len].q_2; 1; }) );
				if ( !_pop_test  )
				break;
				
				_pop_test = (({ 1; }) );
				
				break;
				case 6 :
				_pop_test = (({ q_2 = nfa_bp[nfa_len].q_2; 1; }) );
				if ( !_pop_test  )
				break;
				
				_pop_test = (({ ++q_2 < 2; }) );
				
				break;
				case 7 :
				_pop_test = (({ q_2 = nfa_bp[nfa_len].q_2; 1; }) );
				if ( !_pop_test  )
				break;
				
				_pop_test = (({ ++q_2 >= 2; }) );
				
				break;
				case 4 :
				_pop_test = (({ q_2 = nfa_bp[nfa_len].q_2; 1; }) );
				if ( !_pop_test  )
				break;
				
				_cpc = 0;
				if ( (a) )
				_cpc += 1;
				
				if ( (b) )
				_cpc += 2;
				
				_pop_test = _cpc == 1 || _cpc == 3;
				if ( !_pop_test  )
				break;
				
				_pop_test = (({  q_2 = 0; 1; }) );
				
				break;
				
			}
			if ( _pop_test  )
			{
				cs = nfa_bp[nfa_len].state;
				goto _resume;
			}
			
			goto _out;
		}
		
	}
	return 0;
}

int main()
{
	test( "a.;", 0, 0 );
	test( "a.;", 0, 1 );
	test( "a.;", 1, 0 );
	test( "a.;", 1, 1 );
	test( "a..;", 0, 0 );
	test( "a..;", 0, 1 );
	test( "a..;", 1, 0 );
	test( "a..;", 1, 1 );
	test( "a...;", 0, 0 );
	test( "a...;", 0, 1 );
	test( "a...;", 1, 0 );
	test( "a...;", 1, 1 );
	return 0;
}

