#include <string.h>
#include <stdio.h>



#define DEF 1

static const char  _atoi_actions [] = { 0, 1, 0, 0 ,  };
static const char  _atoi_nfa_targs [] = { 0, 0 ,  };
static const char  _atoi_nfa_offsets [] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  };
static const char  _atoi_nfa_push_actions [] = { 0, 0 ,  };
static const char  _atoi_nfa_pop_trans [] = { 0, 0 ,  };
static const int  atoi_start  = 1;
static const int  atoi_first_final  = 7;
static const int  atoi_error  = 0;
static const int  atoi_en_main  = 1;
int cs;
int blen;
char buffer[1024];

void init()
{

	{
		cs = ( int ) atoi_start;
	}
}

void exec( char *data, int len )
{
	char *p = data;
	char *pe = data + len;
	
	{
		const char  *_acts;
		unsigned int _nacts;
		
		if ( p == pe  )
		goto _test_eof;
		
		if ( cs == 0  )
		goto _out;
		
		_resume:
		switch ( cs  ) {
			case 1:
			if ( ((*( p  ))
			)== 104  )
			{
				goto ctr0;
			}
			
			{
				goto ctr1;
			}
			case 0:
			goto _out;
			case 2:
			if ( ((*( p  ))
			)== 101  )
			{
				goto ctr2;
			}
			
			{
				goto ctr1;
			}
			case 3:
			if ( ((*( p  ))
			)== 108  )
			{
				goto ctr3;
			}
			
			{
				goto ctr1;
			}
			case 4:
			if ( ((*( p  ))
			)== 108  )
			{
				goto ctr4;
			}
			
			{
				goto ctr1;
			}
			case 5:
			if ( ((*( p  ))
			)== 111  )
			{
				goto ctr5;
			}
			
			{
				goto ctr1;
			}
			case 6:
			if ( ((*( p  ))
			)== 10  )
			{
				goto ctr6;
			}
			
			{
				goto ctr1;
			}
			case 7:
			{
				goto ctr1;
			}
			
		}
		ctr1: cs = 0;
		goto _again;
		ctr0: cs = 2;
		goto _again;
		ctr2: cs = 3;
		goto _again;
		ctr3: cs = 4;
		goto _again;
		ctr4: cs = 5;
		goto _again;
		ctr5: cs = 6;
		goto _again;
		ctr6: cs = 7;
		goto f0;
		
		f0: _acts = _atoi_actions + 1 ;
		goto execFuncs;
		
		execFuncs:
		_nacts = ( unsigned int  ) (*( _acts  ))
		;
		_acts += 1;
		while ( _nacts > 0  )
		{
			switch ( (*( _acts  ))
			) {
				case 0:
				{
					printf( "hello\n" ); 
				}
				
				break;
				
			}
			_acts += 1;
			_nacts -= 1;
		}
		
		
		goto _again;
		
		_again:
		if ( cs == 0  )
		goto _out;
		
		p += 1;
		if ( p != pe  )
		goto _resume;
		
		_test_eof: {}
		_out: {}
	}
}

void finish( )
{
	if ( cs >= atoi_first_final )
	printf( "ACCEPT\n" );
	else
	printf( "FAIL\n" );
}

char *inp[] = {
	"hello\n",
};

int inplen = 9;

int main( )
{
	#ifndef DEF
	printf("DEF not defined -- noignore problem\n" );
	#else
	int i;
	for ( i = 0; i < inplen; i++ ) {
		init();
		exec( inp[i], strlen(inp[i]) );
		finish();
	}
	#endif
	return 0;
}

