package main
import "fmt"

var ts  int ;
var te  int ;
var act  int ;
var token  int ;




var cs int;
var blen int;
var buffer [1024] byte;

var _scanner_actions [] int8  = [] int8  { 0, 1, 2, 1, 3, 1, 6, 1, 7, 1, 8, 1, 9, 1, 10, 1, 11, 1, 12, 1, 13, 2, 0, 1, 2, 3, 4, 2, 3, 5, 0  }
var _scanner_trans_keys [] byte  = [] byte  { 1, 0, 2, 9, 4, 4, 10, 10, 10, 10, 10, 10, 2, 9, 0, 9, 7, 7, 9, 9, 2, 9, 0 }
var _scanner_char_class [] int8  = [] int8  { 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 3, 4, 5, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 6, 7, 8, 9, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 10, 0  }
var _scanner_index_offsets [] int8  = [] int8  { 0, 0, 8, 9, 10, 11, 12, 20, 30, 31, 32, 0  }
var _scanner_indicies [] int8  = [] int8  { 1, 2, 2, 2, 0, 0, 0, 2, 3, 6, 7, 8, 1, 2, 9, 10, 4, 4, 4, 2, 11, 4, 4, 2, 2, 2, 12, 13, 14, 15, 13, 18, 1, 2, 2, 2, 0, 0, 0, 2, 0  }
var _scanner_index_defaults [] int8  = [] int8  { 0, 0, 4, 5, 5, 5, 4, 4, 16, 17, 0, 0  }
var _scanner_trans_cond_spaces [] int8  = [] int8  { -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0  }
var _scanner_cond_targs [] int8  = [] int8  { 7, 7, 1, 9, 0, 7, 4, 5, 7, 10, 10, 7, 7, 8, 2, 6, 7, 7, 3, 0  }
var _scanner_cond_actions [] int8  = [] int8  { 19, 9, 0, 3, 0, 17, 0, 0, 7, 24, 27, 11, 5, 0, 0, 0, 13, 15, 0, 0  }
var _scanner_to_state_actions [] int8  = [] int8  { 0, 0, 0, 0, 0, 0, 0, 21, 0, 0, 0, 0  }
var _scanner_from_state_actions [] int8  = [] int8  { 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0  }
var _scanner_eof_trans [] int8  = [] int8  { 0, 1, 0, 6, 6, 6, 0, 0, 17, 18, 1, 0  }
var _scanner_nfa_targs [] int8  = [] int8  { 0, 0  }
var _scanner_nfa_offsets [] int8  = [] int8  { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0  }
var _scanner_nfa_push_actions [] int8  = [] int8  { 0, 0  }
var _scanner_nfa_pop_trans [] int8  = [] int8  { 0, 0  }
var scanner_start  int  = 7
var scanner_first_final  int  = 7
var scanner_error  int  = 0
var scanner_en_main  int  = 7
func prepare() {

	{
		cs = int(scanner_start);
		ts = 0;
		te = 0;
		act = 0;
	}
}

func exec(data string) {
	var p int = 0
	var pe int = len(data)
	var eof int = pe
	
	{
		var  _trans  uint   = 0
		var  _have  uint   = 0
		var  _cont  uint   = 1
		var  _acts int
		var  _nacts uint 
		var  _keys int
		var  _inds int
		for _cont == 1  {
			{
			
				if cs == 0  {
					_cont = 0;
					
				}
				_have = 0;
				if p == pe  {
					{
						if p == eof  {
							{
								if _scanner_eof_trans[cs] > 0  {
									{
										_trans = uint(_scanner_eof_trans[cs] )- 1;
										_have = 1;
									}
									
								}
								if _have == 0  {
									{
									}
									
								}
							}
							
							
						}
						if _have == 0  {
							_cont = 0;
							
						}
					}
					
				}
				if _cont == 1  {
					{
						if _have == 0  {
							{
								_acts = int(_scanner_from_state_actions[cs] );
								_nacts = uint(_scanner_actions[_acts ]);
								_acts += 1;
								for _nacts > 0  {
									{
										switch _scanner_actions[_acts ] {
											case 2 :
											{{ts = p;
												}}
											
											break;
											
										}
										_nacts -= 1;
										_acts += 1;
									}
									
									
								}
								_keys = int((cs<<1) );
								_inds = int(_scanner_index_offsets[cs] );
								switch {
									case ( data[p ]) <= 120 && ( data[p ]) >= 10 :
									{
										var  _ic  int   = int(_scanner_char_class[int(( data[p ]) )- 10])
										switch {
											case _ic <= int(_scanner_trans_keys[_keys+1 ])&& _ic >= int(_scanner_trans_keys[_keys ]):
											_trans = uint(_scanner_indicies[_inds + int(( _ic - int(_scanner_trans_keys[_keys ]))  )]);
											
											default:
											_trans = uint(_scanner_index_defaults[cs]);
											
										}
									}
									
									default:
									{
										_trans = uint(_scanner_index_defaults[cs]);
									}
									
									
								}
							}
							
						}
						if _cont == 1  {
							{
								cs = int(_scanner_cond_targs[_trans]);
								if _scanner_cond_actions[_trans] != 0  {
									{
										_acts = int(_scanner_cond_actions[_trans] );
										_nacts = uint(_scanner_actions[_acts ]);
										_acts += 1;
										for _nacts > 0  {
											{
												switch _scanner_actions[_acts ] {
													case 3 :
													{{te = p+1;
														}}
													
													break;
													case 4 :
													{{act = 4;
														}}
													
													break;
													case 5 :
													{{act = 5;
														}}
													
													break;
													case 6 :
													{{te = p+1;
															{fmt.Print( "on last     " );if ( p + 1 == te ) {
																	fmt.Print( "yes" );
																}
																fmt.Print( "\n" );}
														}}
													
													break;
													case 7 :
													{{te = p+1;
															{fmt.Print( "on lag      " );if ( p + 1 == te ) {
																	fmt.Print( "yes" );
																}
																fmt.Print( "\n" );}
														}}
													
													break;
													case 8 :
													{{te = p+1;
														}}
													
													break;
													case 9 :
													{{te = p+1;
														}}
													
													break;
													case 10 :
													{{te = p;
															p = p - 1;
															{fmt.Print( "on next     " );if ( p + 1 == te ) {
																	fmt.Print( "yes" );
																}
																fmt.Print( "\n" );}
														}}
													
													break;
													case 11 :
													{{te = p;
															p = p - 1;
															{fmt.Print( "on lag      " );if ( p + 1 == te ) {
																	fmt.Print( "yes" );
																}
																fmt.Print( "\n" );}
														}}
													
													break;
													case 12 :
													{{p = ((te))-1;
															{fmt.Print( "on lag      " );if ( p + 1 == te ) {
																	fmt.Print( "yes" );
																}
																fmt.Print( "\n" );}
														}}
													
													break;
													case 13 :
													{{switch act  {
																case 0 :
																{{cs = 0;
																	}}
																
																break;
																case 4 :
																p = ((te))-1;
																{fmt.Print( "lm switch1  " );if ( p + 1 == te ) {
																		fmt.Print( "yes" );
																	}
																	fmt.Print( "\n" );}
																
																break;
																case 5 :
																p = ((te))-1;
																{fmt.Print( "lm switch2  " );if ( p + 1 == te ) {
																		fmt.Print( "yes" );
																	}
																	fmt.Print( "\n" );}
																
																break;
																
															}
														}
													}
													
													break;
													
												}
												_nacts -= 1;
												_acts += 1;
											}
											
										}
									}
									
									
								}
								_acts = int(_scanner_to_state_actions[cs] );
								_nacts = uint(_scanner_actions[_acts ]);
								_acts += 1;
								for _nacts > 0  {
									{
										switch _scanner_actions[_acts ] {
											case 0 :
											{{ts = 0;
												}}
											
											break;
											case 1 :
											{{act = 0;
												}}
											
											break;
											
										}
										_nacts -= 1;
										_acts += 1;
									}
									
									
								}
								if cs == 0  {
									_cont = 0;
									
								}
								if _cont == 1  {
									p += 1;
									
								}
							}
						}
					}
					
				}
			}
			
		}
	}
}
func finish() {
	if cs >= scanner_first_final {
		fmt.Println("ACCEPT")
	} else {
		fmt.Println("FAIL")
	}
}
var inp []string = []string {
	"abbc1d1d2\n",
};

func main() {
	for _, data := range inp {
		prepare()
		exec(data)
		finish()
	}
}
