#include <string.h>
#include <stdio.h>

char * ts ;
char * te ;
int act ;
int token ;





static const int  scanner_start  = 1;
static const int  scanner_first_final  = 1;
static const int  scanner_error  = -1;
static const int  scanner_en_main  = 1;
static const char  _scanner_nfa_targs [] = { 0, 0 ,  };
static const char  _scanner_nfa_offsets [] = { 0, 0, 0, 0 ,  };
static const char  _scanner_nfa_push_actions [] = { 0, 0 ,  };
static const char  _scanner_nfa_pop_trans [] = { 0, 0 ,  };
int cs;
int blen;
char buffer[1024];

void init()
{

	{
		cs = ( int ) scanner_start;
		ts = 0;
		te = 0;
		act = 0;
	}
}

void exec( char *data, int len )
{
	char *p = data;
	char *pe = data + len;
	char *eof = pe;
	
	{
		if ( p == pe  )
		goto _test_eof;
		
		switch ( cs  ) {
			case 1:
			goto st_case_1;
			case 2:
			goto st_case_2;
			case 0:
			goto st_case_0;
			
		}
		goto st_out;
		ctr7:
		{
			{
				switch ( act  ) {
					case 1 :
					p = ((te))-1;
					{
						printf( "%s", "pat1\n" );
						
					}
					
					break;
					case 3 :
					p = ((te))-1;
					{
						printf( "%s", "any\n" );
						
					}
					
					break;
					
				}
				
			}
			
			
		}
		
		
		goto st1;
		ctr3:
		{
			{
				te = p+1;
				{
					printf( "%s", "pat2\n" );
					
				}
				
			}
			
		}
		
		
		goto st1;
		ctr4:
		{
			{
				te = p+1;
				{
					printf( "%s", "any\n" );
					
				}
				
			}
			
		}
		
		
		goto st1;
		st1:
		{
			{
				ts = 0;
				
			}
			
		}
		
		p+= 1;
		if ( p == pe  )
		goto _test_eof1;
		
		st_case_1:
		{
			{
				ts = p;
				
			}
			
		}
		switch ( ((*( p  ))
		) ) {
			case 97:
			{
				goto ctr5;
			}
			case 98:
			{
				goto ctr6;
			}
			
		}
		{
			goto ctr4;
		}
		ctr5:
		{
			{
				te = p+1;
				
			}
			
		}
		{
			{
				act = 1;
				
			}
			
		}
		
		
		goto st2;
		ctr6:
		{
			{
				te = p+1;
				
			}
			
		}
		{
			{
				act = 3;
				
			}
			
		}
		
		
		goto st2;
		st2:
		p+= 1;
		if ( p == pe  )
		goto _test_eof2;
		
		st_case_2:
		if ( ((*( p  ))
		)== 99  )
		{
			goto ctr3;
		}
		
		if ( 97 <= ((*( p  ))
		)&& ((*( p  ))
		)<= 98  )
		{
			goto st0;
		}
		
		{
			goto ctr7;
		}
		st0:
		p+= 1;
		if ( p == pe  )
		goto _test_eof0;
		
		st_case_0:
		if ( ((*( p  ))
		)== 99  )
		{
			goto ctr3;
		}
		
		if ( 97 <= ((*( p  ))
		)&& ((*( p  ))
		)<= 98  )
		{
			goto st0;
		}
		
		{
			goto ctr7;
		}
		st_out:
		_test_eof1: cs = 1;
		goto _test_eof; 
		_test_eof2: cs = 2;
		goto _test_eof; 
		_test_eof0: cs = 0;
		goto _test_eof; 
		
		_test_eof: {}
		if ( p == eof  )
		{
			switch ( cs  ) {
				case 2:
				goto ctr7;
				case 0:
				goto ctr7;
				
			}
		}
		
		
	}
}

void finish( )
{
	if ( cs >= scanner_first_final )
	printf( "ACCEPT\n" );
	else
	printf( "FAIL\n" );
}

char *inp[] = {
	"a",
};

int inplen = 1;

int main( )
{
	int i;
	for ( i = 0; i < inplen; i++ ) {
		init();
		exec( inp[i], strlen(inp[i]) );
		finish();
	}
	return 0;
}

