using System;
// Disables lots of warnings that appear in the test suite
#pragma warning disable 0168, 0169, 0219, 0162, 0414
namespace Test {
	class Test
	{
	
	
	
	
	
	
		static readonly sbyte  []_state_act_actions = { 0, 1, 2, 1, 3, 1, 4, 1, 5, 1, 6, 2, 0, 2, 2, 1, 3, 0,  };
		static readonly char  []_state_act_trans_keys = { '\u0001', '\u0000', '\u0003', '\u0003', '\u0000', '\u0000', '\u0002', '\u0002', '\u0002', '\u0002', '\u0002', '\u0002', '\u0000',  };
		static readonly sbyte  []_state_act_char_class = { 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 0,  };
		static readonly sbyte  []_state_act_index_offsets = { 0, 0, 1, 2, 3, 4, 0,  };
		static readonly sbyte  []_state_act_indicies = { 0, 2, 3, 3, 3, 0,  };
		static readonly sbyte  []_state_act_index_defaults = { 0, 1, 1, 1, 1, 1, 0,  };
		static readonly sbyte  []_state_act_trans_cond_spaces = { -1, -1, -1, -1, 0,  };
		static readonly sbyte  []_state_act_cond_targs = { 2, 0, 5, 1, 0,  };
		static readonly sbyte  []_state_act_cond_actions = { 0, 0, 9, 0, 0,  };
		static readonly sbyte  []_state_act_to_state_actions = { 0, 0, 5, 1, 11, 1, 0,  };
		static readonly sbyte  []_state_act_from_state_actions = { 0, 0, 7, 3, 14, 3, 0,  };
		static readonly sbyte  []_state_act_nfa_targs = { 0, 0,  };
		static readonly sbyte  []_state_act_nfa_offsets = { 0, 0, 0, 0, 0, 0, 0,  };
		static readonly sbyte  []_state_act_nfa_push_actions = { 0, 0,  };
		static readonly sbyte  []_state_act_nfa_pop_trans = { 0, 0,  };
		static readonly int  state_act_start  = 4;
		static readonly int  state_act_first_final  = 4;
		static readonly int  state_act_error  = 0;
		static readonly int  state_act_en_main  = 4;
		static readonly int  state_act_en_main_line_again  = 3;
		int cs;
		
		void init()
		{
		
			{
				cs = (int)state_act_start;
			}
		}
		
		void exec( char[] data, int len )
		{
			int p = 0;
			int pe = len;
			int eof = len;
			string _s;
			char [] buffer = new char [1024];
			int blen = 0;
			
			{
				uint _trans = 0;
				uint _have = 0;
				uint _cont = 1;
				int _acts;
				uint _nacts;
				int _keys;
				int _inds;
				while ( _cont == 1 )
				{
				
					if ( cs == 0 )
					_cont = 0;
					
					_have = 0;
					if ( p == pe  )
					{
						if ( _have == 0 )
						_cont = 0;
						
					}
					
					if ( _cont == 1 )
					{
						if ( _have == 0 )
						{
							_acts = _state_act_from_state_actions[cs] ;
							_nacts = (uint )_state_act_actions[_acts ];
							_acts += 1;
							while ( _nacts > 0 )
							{
								switch ( _state_act_actions[_acts ] ) {
									case 1:
									{Console.Write( "a2\n" );}
									
									break;
									case 3:
									{Console.Write( "b2\n" );}
									
									break;
									case 5:
									{Console.Write( "c2\n" );}
									
									break;
									
								}
								_nacts -= 1;
								_acts += 1;
							}
							
							
							_keys = (cs<<1) ;
							_inds = _state_act_index_offsets[cs] ;
							if ( ( data[p ]) <= 105&& ( data[p ]) >= 10 )
							{
								int _ic = (int)_state_act_char_class[(int)( data[p ]) - 10];
								if ( _ic <= (int)_state_act_trans_keys[_keys+1]&& _ic >= (int)_state_act_trans_keys[_keys ] )
								_trans = (uint )_state_act_indicies[_inds + (int)( _ic - (int)_state_act_trans_keys[_keys ])  ];
								
								else
								_trans = (uint )_state_act_index_defaults[cs];
								
							}
							
							else
							{
								_trans = (uint )_state_act_index_defaults[cs];
							}
							
							
						}
						
						if ( _cont == 1 )
						{
							cs = (int)_state_act_cond_targs[_trans];
							if ( _state_act_cond_actions[_trans] != 0 )
							{
								_acts = _state_act_cond_actions[_trans] ;
								_nacts = (uint )_state_act_actions[_acts ];
								_acts += 1;
								while ( _nacts > 0 )
								{
									switch ( _state_act_actions[_acts ] ) {
										case 6:
										{{cs = 3;
											}}
										
										break;
										
									}
									_nacts -= 1;
									_acts += 1;
								}
								
							}
							
							
							_acts = _state_act_to_state_actions[cs] ;
							_nacts = (uint )_state_act_actions[_acts ];
							_acts += 1;
							while ( _nacts > 0 )
							{
								switch ( _state_act_actions[_acts ] ) {
									case 0:
									{Console.Write( "a1\n" );}
									
									break;
									case 2:
									{Console.Write( "b1\n" );}
									
									break;
									case 4:
									{Console.Write( "c1\n" );}
									
									break;
									
								}
								_nacts -= 1;
								_acts += 1;
							}
							
							
							if ( cs == 0 )
							_cont = 0;
							
							if ( _cont == 1 )
							p += 1;
							
						}
					}
					
				}
				
			}
		}
		
		void finish( )
		{
			if ( cs >= state_act_first_final )
			Console.WriteLine( "ACCEPT" );
			else
			Console.WriteLine( "FAIL" );
		}
		
		static readonly string[] inp = {
			"hi\nhi\n",
		};
		
		
		static readonly int inplen = 1;
		
		public static void Main (string[] args)
		{
			Test machine = new Test();
			for ( int i = 0; i < inplen; i++ ) {
				machine.init();
				machine.exec( inp[i].ToCharArray(), inp[i].Length );
				machine.finish();
			}
		}
	}
}
