#
# @LANG: ruby
# @GENERATED: true
#








class << self
	attr_accessor :_zlen1_trans_keys 
	private :_zlen1_trans_keys, :_zlen1_trans_keys=
end
self._zlen1_trans_keys = [
1, 0, 1, 0, 0 , 
]

class << self
	attr_accessor :_zlen1_char_class 
	private :_zlen1_char_class, :_zlen1_char_class=
end
self._zlen1_char_class = [
0 , 
]

class << self
	attr_accessor :_zlen1_index_offsets 
	private :_zlen1_index_offsets, :_zlen1_index_offsets=
end
self._zlen1_index_offsets = [
0, 0, 0 , 
]

class << self
	attr_accessor :_zlen1_indicies 
	private :_zlen1_indicies, :_zlen1_indicies=
end
self._zlen1_indicies = [
0 , 
]

class << self
	attr_accessor :_zlen1_index_defaults 
	private :_zlen1_index_defaults, :_zlen1_index_defaults=
end
self._zlen1_index_defaults = [
0, 0, 0 , 
]

class << self
	attr_accessor :_zlen1_trans_cond_spaces 
	private :_zlen1_trans_cond_spaces, :_zlen1_trans_cond_spaces=
end
self._zlen1_trans_cond_spaces = [
-1, 0 , 
]

class << self
	attr_accessor :_zlen1_cond_targs 
	private :_zlen1_cond_targs, :_zlen1_cond_targs=
end
self._zlen1_cond_targs = [
0, 0 , 
]

class << self
	attr_accessor :_zlen1_cond_actions 
	private :_zlen1_cond_actions, :_zlen1_cond_actions=
end
self._zlen1_cond_actions = [
0, 0 , 
]

class << self
	attr_accessor :_zlen1_nfa_targs 
	private :_zlen1_nfa_targs, :_zlen1_nfa_targs=
end
self._zlen1_nfa_targs = [
0, 0 , 
]

class << self
	attr_accessor :_zlen1_nfa_offsets 
	private :_zlen1_nfa_offsets, :_zlen1_nfa_offsets=
end
self._zlen1_nfa_offsets = [
0, 0, 0 , 
]

class << self
	attr_accessor :_zlen1_nfa_push_actions 
	private :_zlen1_nfa_push_actions, :_zlen1_nfa_push_actions=
end
self._zlen1_nfa_push_actions = [
0, 0 , 
]

class << self
	attr_accessor :_zlen1_nfa_pop_trans 
	private :_zlen1_nfa_pop_trans, :_zlen1_nfa_pop_trans=
end
self._zlen1_nfa_pop_trans = [
0, 0 , 
]

class << self
	attr_accessor :zlen1_start 
end
self.zlen1_start  = 1;

class << self
	attr_accessor :zlen1_first_final 
end
self.zlen1_first_final  = 1;

class << self
	attr_accessor :zlen1_error 
end
self.zlen1_error  = 0;

class << self
	attr_accessor :zlen1_en_main 
end
self.zlen1_en_main  = 1;

def run_machine( data )
	p = 0
	pe = data.length
	eof = data.length
	cs = 0;
	_m = 
	_a = 
	buffer = Array.new
	blen = 0
	begin
		cs = zlen1_start;
		
	end
	begin
		_trans = 0;
		_have = 0;
		_cont = 1;
		while ( _cont == 1  )
			begin
				if ( cs == 0  )
					_cont = 0;
					
				end
				_have = 0;
				if ( p == pe  )
					begin
						if ( _have == 0  )
							_cont = 0;
							
						end
						
					end
					
				end
				if ( _cont == 1  )
					begin
						if ( _have == 0  )
							begin
								_trans = _zlen1_index_defaults[cs];
								
							end
							
						end
						if ( _cont == 1  )
							begin
								cs = _zlen1_cond_targs[_trans];
								if ( cs == 0  )
									_cont = 0;
									
								end
								if ( _cont == 1  )
									p += 1;
									
								end
								
							end
							
						end
						
					end
					
				end
				
			end
			
		end
		
	end
	if cs >= zlen1_first_final
		puts "ACCEPT"
		else
		puts "FAIL"
	end
end

inp = [
"",
"x",
]

inplen = 2

inp.each { |str| run_machine(str) }

