#include <stdio.h>

void alph(const char *type)
{
	printf("%s\n", type);
}

struct builtin
{
	int cs;
};



static const char  _builtin_actions [] = { 0, 1, 0, 2, 0, 2, 4, 0, 1, 2, 8, 5, 0, 1, 2, 8, 12, 5, 0, 1, 2, 10, 12, 6, 0, 1, 2, 9, 10, 11, 8, 0, 1, 2, 3, 5, 6, 9, 10, 8, 0, 1, 2, 3, 5, 7, 9, 10, 8, 0, 1, 2, 4, 5, 9, 10, 13, 9, 0, 1, 2, 3, 5, 6, 9, 10, 13, 9, 0, 1, 2, 3, 5, 7, 9, 10, 13, 0 ,  };
static const unsigned int  _builtin_trans_keys [] = { 0u, 9u, 0u,  };
static const char  _builtin_char_class [] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 3, 3, 3, 3, 3, 3, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 3, 3, 3, 3, 0, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 0 ,  };
static const char  _builtin_index_offsets [] = { 0, 0 ,  };
static const char  _builtin_indicies [] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0 ,  };
static const char  _builtin_index_defaults [] = { 10, 0 ,  };
static const char  _builtin_trans_cond_spaces [] = { -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0 ,  };
static const char  _builtin_cond_targs [] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  };
static const char  _builtin_cond_actions [] = { 6, 11, 17, 23, 48, 67, 39, 57, 30, 3, 1, 0 ,  };
static const char  _builtin_nfa_targs [] = { 0, 0 ,  };
static const char  _builtin_nfa_offsets [] = { 0, 0 ,  };
static const char  _builtin_nfa_push_actions [] = { 0, 0 ,  };
static const char  _builtin_nfa_pop_trans [] = { 0, 0 ,  };
static const int  builtin_start  = 0;
static const int  builtin_first_final  = 0;
static const int  builtin_error  = -1;
static const int  builtin_en_main  = 0;
void builtin_init( struct builtin *fsm )
{

	{
		(fsm->cs) = ( int ) builtin_start;
	}
}

void builtin_execute( struct builtin *fsm, const unsigned int *data, int len )
{
	const unsigned int *p = data;
	const unsigned int *pe = data+len;
	
	{
		int _trans = 0;
		const char  *_acts;
		unsigned int _nacts;
		const unsigned int  *_keys;
		const char  *_inds;
		if ( p == pe  )
		goto _test_eof;
		
		_resume :
		_keys = _builtin_trans_keys + ((fsm->cs)<<1);
		_inds = _builtin_indicies + _builtin_index_offsets[(fsm->cs)];
		if ( ((*( p  ))
		)<= 255  )
		{
			int _ic = ( int ) _builtin_char_class[( int ) ((*( p  ))
			)- 0];
			if ( _ic <= ( int ) (*( _keys+1  ))
			&& _ic >= ( int ) (*( _keys  ))
			)
			_trans = ( int ) (*( _inds + ( int ) (_ic - ( int ) (*( _keys  ))
			) ))
			;
			
			else
			_trans = ( int ) _builtin_index_defaults[(fsm->cs)];
			
		}
		
		else
		{
			_trans = ( int ) _builtin_index_defaults[(fsm->cs)];
		}
		
		
		goto _match_cond;
		
		_match_cond :
		(fsm->cs) = ( int ) _builtin_cond_targs[_trans];
		if ( _builtin_cond_actions[_trans]== 0  )
		goto _again;
		
		
		_acts = _builtin_actions + _builtin_cond_actions[_trans];
		_nacts = ( unsigned int  ) (*( _acts  ))
		;
		_acts += 1;
		while ( _nacts > 0  )
		{
			switch ( (*( _acts  ))
			) {
				case 0 :
				{
					alph("any");
				}
				
				break;
				case 1 :
				{
					alph("ascii");
				}
				
				break;
				case 2 :
				{
					alph("extend");
				}
				
				break;
				case 3 :
				{
					alph("alpha");
				}
				
				break;
				case 4 :
				{
					alph("digit");
				}
				
				break;
				case 5 :
				{
					alph("alnum");
				}
				
				break;
				case 6 :
				{
					alph("lower");
				}
				
				break;
				case 7 :
				{
					alph("upper");
				}
				
				break;
				case 8 :
				{
					alph("cntrl");
				}
				
				break;
				case 9 :
				{
					alph("graph");
				}
				
				break;
				case 10 :
				{
					alph("print");
				}
				
				break;
				case 11 :
				{
					alph("punct");
				}
				
				break;
				case 12 :
				{
					alph("space");
				}
				
				break;
				case 13 :
				{
					alph("xdigit");
				}
				
				break;
				
			}
			_nacts -= 1;
			_acts += 1;
		}
		
		
		
		
		_again :
		p += 1;
		if ( p != pe  )
		goto _resume;
		
		
		_test_eof :
		{}
		
	}
}

int builtin_finish( struct builtin *fsm )
{
	if ( fsm->cs == builtin_error )
	return -1;
	else if ( fsm->cs >= builtin_first_final )
	return 1;
	return 0;
}

#include <stdio.h>
#define BUFSIZE 2048

struct builtin fsm;
char buf[BUFSIZE];
unsigned int i;

int test( const unsigned int *data, int len )
{
	builtin_init( &fsm );
	builtin_execute( &fsm, data, len );
	if ( builtin_finish( &fsm ) > 0 )
	printf("ACCEPT\n");
	else
	printf("FAIL\n");
	return 0;
}

#define DLEN 258
unsigned int data[DLEN] = {
	-1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
	20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
	39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
	58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76,
	77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
	96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
	112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
	127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141,
	142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
	157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171,
	172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186,
	187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201,
	202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216,
	217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231,
	232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
	247, 248, 249, 250, 251, 252, 253, 254, 255, 256
};

int main()
{
	test( data, DLEN );
	return 0;
}

