package main
import "fmt"

var return_to  int ;




var cs int;
var blen int;
var buffer [1024] byte;

var _targs1_key_offsets [] int8  = [] int8  { 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 15, 15, 15, 0  }
var _targs1_trans_keys [] byte  = [] byte  { 117, 110, 117, 115, 101, 100, 111, 110, 101, 116, 119, 111, 10, 49, 50, 0 }
var _targs1_single_lengths [] int8  = [] int8  { 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 0, 0, 0, 0  }
var _targs1_range_lengths [] int8  = [] int8  { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0  }
var _targs1_index_offsets [] int8  = [] int8  { 0, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 28, 29, 30, 0  }
var _targs1_trans_cond_spaces [] int8  = [] int8  { -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0  }
var _targs1_trans_offsets [] int8  = [] int8  { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 0  }
var _targs1_trans_lengths [] int8  = [] int8  { 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0  }
var _targs1_cond_keys [] int8  = [] int8  { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0  }
var _targs1_cond_targs [] int8  = [] int8  { 2, 0, 3, 0, 4, 0, 5, 0, 6, 0, 14, 0, 8, 0, 9, 0, 15, 0, 11, 0, 12, 0, 16, 0, 13, 13, 13, 0, 0, 0, 0, 0  }
var _targs1_cond_actions [] int8  = [] int8  { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 3, 4, 0, 0, 0, 0, 0  }
var _targs1_nfa_targs [] int8  = [] int8  { 0, 0  }
var _targs1_nfa_offsets [] int8  = [] int8  { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0  }
var _targs1_nfa_push_actions [] int8  = [] int8  { 0, 0  }
var _targs1_nfa_pop_trans [] int8  = [] int8  { 0, 0  }
var targs1_start  int  = 13
var targs1_first_final  int  = 13
var targs1_error  int  = 0
var targs1_en_unused  int  = 1
var targs1_en_one  int  = 7
var targs1_en_two  int  = 10
var targs1_en_main  int  = 13
func prepare() {

	{
		cs = int(targs1_start);
	}
}

func exec(data string) {
	var p int = 0
	var pe int = len(data)
	
	{
		var  _klen int 
		var  _keys int
		var  _ckeys int
		var  _cpc int 
		var  _trans uint 
		var  _cond  uint   = 0
		var  _have  uint   = 0
		var  _cont  uint   = 1
		for _cont == 1  {
			{
			
				if cs == 0  {
					_cont = 0;
					
				}
				_have = 0;
				if p == pe  {
					{
						if _have == 0  {
							_cont = 0;
							
						}
					}
					
				}
				if _cont == 1  {
					{
						if _have == 0  {
							{
								_keys = int(_targs1_key_offsets[cs] );
								_trans = uint(_targs1_index_offsets[cs]);
								_have = 0;
								_klen = int(_targs1_single_lengths[cs]);
								if _klen > 0  {
									{
										var  _lower int
										var  _mid int
										var  _upper int
										_lower = _keys;
										_upper = _keys + _klen - 1;
										for _upper >= _lower && _have == 0  {
											{
												_mid = _lower + ((_upper-_lower) >> 1);
												switch {
													case ( data[p ]) < _targs1_trans_keys[_mid ]:
													_upper = _mid - 1;
													
													case ( data[p ]) > _targs1_trans_keys[_mid ]:
													_lower = _mid + 1;
													
													default:
													{
														_trans += uint((_mid - _keys));
														_have = 1;
													}
													
												}
											}
											
										}
										if _have == 0  {
											{
												_keys += _klen;
												_trans += uint(_klen);
											}
											
										}
									}
									
									
								}
								if _have == 0  {
									{
										_klen = int(_targs1_range_lengths[cs]);
										if _klen > 0  {
											{
												var  _lower int
												var  _mid int
												var  _upper int
												_lower = _keys;
												_upper = _keys + (_klen<<1) - 2;
												for _have == 0 && _lower <= _upper  {
													{
														_mid = _lower + (((_upper-_lower) >> 1) & ^1);
														switch {
															case ( data[p ]) < _targs1_trans_keys[_mid ]:
															_upper = _mid - 2;
															
															case ( data[p ]) > _targs1_trans_keys[_mid + 1 ]:
															_lower = _mid + 2;
															
															default:
															{
																_trans += uint(((_mid - _keys)>>1));
																_have = 1;
															}
															
														}
													}
													
												}
												if _have == 0  {
													_trans += uint(_klen);
													
												}
											}
											
										}
									}
									
									
								}
								_ckeys = int(_targs1_trans_offsets[_trans] );
								_klen = int(_targs1_trans_lengths[_trans]);
								_cond = uint(_targs1_trans_offsets[_trans]);
								_have = 0;
								_cpc = 0;
								{
									var  _lower int
									var  _mid int
									var  _upper int
									_lower = _ckeys;
									_upper = _ckeys + _klen - 1;
									for _have == 0 && _lower <= _upper  {
										{
											_mid = _lower + ((_upper-_lower) >> 1);
											switch {
												case _cpc < int(_targs1_cond_keys[_mid ]):
												_upper = _mid - 1;
												
												case _cpc > int(_targs1_cond_keys[_mid ]):
												_lower = _mid + 1;
												
												default:
												{
													_cond += uint((_mid - _ckeys));
													_have = 1;
												}
												
											}
										}
										
									}
									if _have == 0  {
										{
											cs = 0;
											_cont = 0;
										}
										
									}
								}
							}
							
						}
						if _cont == 1  {
							{
								cs = int(_targs1_cond_targs[_cond]);
								switch _targs1_cond_actions[_cond]  {
									case 1 :
									{fmt.Print( "one\n" );{cs = (return_to);
										}
										
									}
									
									break;
									case 2 :
									{fmt.Print( "two\n" );{cs = (return_to);
										}
										
									}
									
									break;
									case 3 :
									{return_to = (cs);
										{cs = 7;
										}}
									
									break;
									case 4 :
									{return_to = (cs);
										{cs = 10;
										}}
									
									break;
									
								}
								if cs == 0  {
									_cont = 0;
									
								}
								if _cont == 1  {
									p += 1;
									
								}
							}
						}
					}
					
				}
			}
			
		}
	}
}
func finish() {
	if cs >= targs1_first_final {
		fmt.Println("ACCEPT")
	} else {
		fmt.Println("FAIL")
	}
}
var inp []string = []string {
	"1one2two1one\n",
};

func main() {
	for _, data := range inp {
		prepare()
		exec(data)
		finish()
	}
}
