#!/bin/bash
#

#
# FIXME: not enabled
#

wk=working
test -d $wk || mkdir $wk

SH=working/process1.sh
OUT=working/process1.out
LOG=working/process1.log
DIFF=working/process1.diff

rm -f $SH
echo echo executing ./src/process1 >> $SH
#echo ./src/process1 '>' $OUT '2>' $LOG >> $SH
#echo diff expected $OUT '>' $DIFF >> $SH

echo cat '>' $DIFF >> $SH

echo $SH
