#!/bin/bash
#

#
# FIXME: not enabled
#

wk=working
test -d $wk || mkdir $wk

SH=working/kern1.sh
OUT=working/kern1.out
LOG=working/kern1.log
DIFF=working/kern1.diff

rm -f $SH
echo echo executing ./src/kern1 >> $SH
#echo ./src/kern1 '>' $OUT '2>' $LOG >> $SH
#echo diff expected $OUT '>' $DIFF >> $SH

echo cat '>' $DIFF >> $SH

echo $SH
