#!/bin/bash

read -d '' DIRS <<EOF
	aapl.d
	ragel.d
	pcre-ragel.d
	colm.d
	rlhc.d
	trans.d
	rlparse.d
EOF

for D in $DIRS; do
	cd $D
	echo "---- $D ----"

	ARGS=""
	if [ $D = ragel.d ]; then
		ARGS=" -n -T0 --integral-tables -K any1.rl"
	elif [ $D = pcre-ragel.d ]; then
		ARGS="pcre-011.case"
	elif [ $D = colm.d ]; then
		ARGS="ref1.lm"
	elif [ $D = rlhc.d ]; then
		ARGS="case/zlen1_go.go-Z-T1--var-backend.in"
	elif [ $D = trans.d ]; then
		ARGS="case/scan4.rl"
	elif [ $D = aapl.d ]; then
		ARGS="test_string"
	fi

	./gentests $ARGS | xargs -n1 -P4 bash
	
	WORKING="$WORKING $D/working"
	cd ..
done

echo ----  cases   ------
find $WORKING -name *.sh -not -size 0 | wc -l

echo ---- failures ------
find $WORKING -name *.diff -not -size 0 | wc -l
find $WORKING -name *.diff -not -size 0 

#echo ---- warnings ------
#find $WORKING -name *.log -not -size 0 | wc -l
