#
# @LANG: ruby
# @GENERATED: true
#






class << self
	attr_accessor :_foo_actions 
	private :_foo_actions, :_foo_actions=
end
self._foo_actions = [
0, 1, 0, 1, 1, 0 , 
]

class << self
	attr_accessor :_foo_key_offsets 
	private :_foo_key_offsets, :_foo_key_offsets=
end
self._foo_key_offsets = [
0, 0, 2, 4, 7, 0 , 
]

class << self
	attr_accessor :_foo_trans_keys 
	private :_foo_trans_keys, :_foo_trans_keys=
end
self._foo_trans_keys = [
48, 57, 48, 57, 10, 48, 57, 0 , 
]

class << self
	attr_accessor :_foo_single_lengths 
	private :_foo_single_lengths, :_foo_single_lengths=
end
self._foo_single_lengths = [
0, 0, 0, 1, 0, 0 , 
]

class << self
	attr_accessor :_foo_range_lengths 
	private :_foo_range_lengths, :_foo_range_lengths=
end
self._foo_range_lengths = [
0, 1, 1, 1, 0, 0 , 
]

class << self
	attr_accessor :_foo_index_offsets 
	private :_foo_index_offsets, :_foo_index_offsets=
end
self._foo_index_offsets = [
0, 0, 2, 4, 7, 0 , 
]

class << self
	attr_accessor :_foo_trans_cond_spaces 
	private :_foo_trans_cond_spaces, :_foo_trans_cond_spaces=
end
self._foo_trans_cond_spaces = [
-1, -1, 0, -1, 0, 0, -1, -1, 0 , 
]

class << self
	attr_accessor :_foo_trans_offsets 
	private :_foo_trans_offsets, :_foo_trans_offsets=
end
self._foo_trans_offsets = [
0, 1, 2, 4, 5, 6, 7, 8, 0 , 
]

class << self
	attr_accessor :_foo_trans_lengths 
	private :_foo_trans_lengths, :_foo_trans_lengths=
end
self._foo_trans_lengths = [
1, 1, 2, 1, 1, 1, 1, 1, 0 , 
]

class << self
	attr_accessor :_foo_cond_keys 
	private :_foo_cond_keys, :_foo_cond_keys=
end
self._foo_cond_keys = [
0, 0, 0, 1, 0, 0, 1, 0, 0, 0 , 
]

class << self
	attr_accessor :_foo_cond_targs 
	private :_foo_cond_targs, :_foo_cond_targs=
end
self._foo_cond_targs = [
2, 0, 3, 2, 0, 4, 3, 0, 0, 0 , 
]

class << self
	attr_accessor :_foo_cond_actions 
	private :_foo_cond_actions, :_foo_cond_actions=
end
self._foo_cond_actions = [
3, 0, 3, 1, 0, 0, 1, 0, 0, 0 , 
]

class << self
	attr_accessor :_foo_nfa_targs 
	private :_foo_nfa_targs, :_foo_nfa_targs=
end
self._foo_nfa_targs = [
0, 0 , 
]

class << self
	attr_accessor :_foo_nfa_offsets 
	private :_foo_nfa_offsets, :_foo_nfa_offsets=
end
self._foo_nfa_offsets = [
0, 0, 0, 0, 0, 0 , 
]

class << self
	attr_accessor :_foo_nfa_push_actions 
	private :_foo_nfa_push_actions, :_foo_nfa_push_actions=
end
self._foo_nfa_push_actions = [
0, 0 , 
]

class << self
	attr_accessor :_foo_nfa_pop_trans 
	private :_foo_nfa_pop_trans, :_foo_nfa_pop_trans=
end
self._foo_nfa_pop_trans = [
0, 0 , 
]

class << self
	attr_accessor :foo_start 
end
self.foo_start  = 1;

class << self
	attr_accessor :foo_first_final 
end
self.foo_first_final  = 4;

class << self
	attr_accessor :foo_error 
end
self.foo_error  = 0;

class << self
	attr_accessor :foo_en_main 
end
self.foo_en_main  = 1;

def run_machine( data )
	p = 0
	pe = data.length
	eof = data.length
	cs = 0;
	_m = 
	_a = 
	buffer = Array.new
	blen = 0
	i = 1
	c = 1
	begin
		cs = foo_start;
		
	end
	begin
		_klen= 0
		;
		_trans = 0;
		_cond = 0;
		_have = 0;
		_cont = 1;
		_acts = 0;
		_nacts= 0
		;
		_keys = 0;
		_ckeys = 0;
		_cpc= 0
		;
		while ( _cont == 1  )
			begin
				if ( cs == 0  )
					_cont = 0;
					
				end
				_have = 0;
				if ( p == pe  )
					begin
						if ( _have == 0  )
							_cont = 0;
							
						end
						
					end
					
				end
				if ( _cont == 1  )
					begin
						if ( _have == 0  )
							begin
								_keys = _foo_key_offsets[cs] ;
								_trans = _foo_index_offsets[cs];
								_have = 0;
								_klen = _foo_single_lengths[cs];
								if ( _klen > 0  )
									begin
										_lower = 0;
										_mid = 0;
										_upper = 0;
										_lower = _keys;
										_upper = _keys + _klen - 1;
										while ( _upper >= _lower && _have == 0  )
											begin
												_mid = _lower + ((_upper-_lower) >> 1);
												if ( ( data[p ].ord) < _foo_trans_keys[_mid ] )
													_upper = _mid - 1;
													
													elsif ( ( data[p ].ord) > _foo_trans_keys[_mid ] )
													_lower = _mid + 1;
													
													else
													begin
														_trans += (_mid - _keys);
														_have = 1;
														
													end
													
												end
												
											end
											
										end
										if ( _have == 0  )
											begin
												_keys += _klen;
												_trans += _klen;
												
											end
											
										end
										
									end
									
								end
								if ( _have == 0  )
									begin
										_klen = _foo_range_lengths[cs];
										if ( _klen > 0  )
											begin
												_lower = 0;
												_mid = 0;
												_upper = 0;
												_lower = _keys;
												_upper = _keys + (_klen<<1) - 2;
												while ( _have == 0 && _lower <= _upper  )
													begin
														_mid = _lower + (((_upper-_lower) >> 1) & ~1);
														if ( ( data[p ].ord) < _foo_trans_keys[_mid ] )
															_upper = _mid - 2;
															
															elsif ( ( data[p ].ord) > _foo_trans_keys[_mid + 1 ] )
															_lower = _mid + 2;
															
															else
															begin
																_trans += ((_mid - _keys)>>1);
																_have = 1;
																
															end
															
														end
														
													end
													
												end
												if ( _have == 0  )
													_trans += _klen;
													
												end
												
											end
											
										end
										
									end
									
								end
								_ckeys = _foo_trans_offsets[_trans] ;
								_klen = _foo_trans_lengths[_trans];
								_cond = _foo_trans_offsets[_trans];
								_have = 0;
								_cpc = 0;
								case  _foo_trans_cond_spaces[_trans]  
								when -2 then
								begin
								end
								when 0  then
								begin
									if ( (i > 0) )
										_cpc += 1;
										
									end
									
									
								end
							end
							begin
								_lower = 0;
								_mid = 0;
								_upper = 0;
								_lower = _ckeys;
								_upper = _ckeys + _klen - 1;
								while ( _have == 0 && _lower <= _upper  )
									begin
										_mid = _lower + ((_upper-_lower) >> 1);
										if ( _cpc < _foo_cond_keys[_mid ] )
											_upper = _mid - 1;
											
											elsif ( _cpc > _foo_cond_keys[_mid ] )
											_lower = _mid + 1;
											
											else
											begin
												_cond += (_mid - _ckeys);
												_have = 1;
												
											end
											
										end
										
									end
									
								end
								if ( _have == 0  )
									begin
										cs = 0;
										_cont = 0;
										
									end
									
								end
								
							end
							
						end
						
					end
					if ( _cont == 1  )
						begin
							cs = _foo_cond_targs[_cond];
							if ( _foo_cond_actions[_cond] != 0  )
								begin
									_acts = _foo_cond_actions[_cond] ;
									_nacts = _foo_actions[_acts ];
									_acts += 1;
									while ( _nacts > 0  )
										begin
											case  _foo_actions[_acts ] 
											when -2 then
											begin
											end
											when 0  then
											begin
												begin
													i = i - 1;
													c = ( ( data[p ].ord) )
													;
													print( "item: " );
													print( c );
													print( "\n" );
													
												end
												
											end
											when 1  then
											begin
												begin
													i = ( ( data[p ].ord) - 48 )
													;
													print( "count: " );
													print( i );
													print( "\n" );
													
												end
												
												
											end
										end
										_nacts -= 1;
										_acts += 1;
										
									end
									
								end
								
							end
							
						end
						if ( cs == 0  )
							_cont = 0;
							
						end
						if ( _cont == 1  )
							p += 1;
							
						end
						
					end
					
				end
				
			end
			
		end
		
	end
	
end

end
if 	cs >= foo_first_final
	puts "ACCEPT"
	else
	puts "FAIL"
end
end
	
	inp = [
	"00\n",
	"019\n",
	"190\n",
	"1719\n",
	"1040000\n",
	"104000a\n",
	"104000\n",
	]
	
	inplen = 7
	
	inp.each { |str| run_machine(str) }
	
