#include <stdio.h>
#define BUFSIZE 2048

struct errintrans
{
	int cs;
};



static const char  _errintrans_trans_keys [] = { 1, 0, 0, 2, 0, 2, 0 ,  };
static const char  _errintrans_char_class [] = { 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0 ,  };
static const char  _errintrans_index_offsets [] = { 0, 0, 3, 0 ,  };
static const char  _errintrans_indicies [] = { 1, 0, 2, 1, 0, 2, 0 ,  };
static const char  _errintrans_index_defaults [] = { 0, 0, 0, 0 ,  };
static const char  _errintrans_trans_cond_spaces [] = { -1, -1, -1, 0 ,  };
static const char  _errintrans_cond_targs [] = { 1, 2, 0, 0 ,  };
static const char  _errintrans_cond_actions [] = { 0, 0, 0, 0 ,  };
static const char  _errintrans_nfa_targs [] = { 0, 0 ,  };
static const char  _errintrans_nfa_offsets [] = { 0, 0, 0, 0 ,  };
static const char  _errintrans_nfa_push_actions [] = { 0, 0 ,  };
static const char  _errintrans_nfa_pop_trans [] = { 0, 0 ,  };
static const int  errintrans_start  = 1;
static const int  errintrans_first_final  = 2;
static const int  errintrans_error  = 0;
static const int  errintrans_en_main  = 1;
void errintrans_init( struct errintrans *fsm )
{

	{
		(fsm->cs) = ( int ) errintrans_start;
	}
}

void errintrans_execute( struct errintrans *fsm, const char *_data, int _len )
{
	const char *p = _data;
	const char *pe = _data+_len;
	
	
	{
		unsigned int _trans = 0;
		unsigned int _have = 0;
		unsigned int _cont = 1;
		const char  *_keys;
		const char  *_inds;
		while ( _cont == 1  )
		{
		
			if ( (fsm->cs) == 0  )
			_cont = 0;
			
			_have = 0;
			if ( p == pe  )
			{
				if ( _have == 0  )
				_cont = 0;
				
			}
			
			if ( _cont == 1  )
			{
				if ( _have == 0  )
				{
					_keys = _errintrans_trans_keys + ((fsm->cs)<<1);
					_inds = _errintrans_indicies + _errintrans_index_offsets[(fsm->cs)];
					if ( ((*( p  ))
					)<= 57 && ((*( p  ))
					)>= 10  )
					{
						int _ic = ( int ) _errintrans_char_class[( int ) ((*( p  ))
						)- 10];
						if ( _ic <= ( int ) (*( _keys+1  ))
						&& _ic >= ( int ) (*( _keys  ))
						)
						_trans = ( unsigned int  ) (*( _inds + ( int ) (_ic - ( int ) (*( _keys  ))
						) ))
						;
						
						else
						_trans = ( unsigned int  ) _errintrans_index_defaults[(fsm->cs)];
						
					}
					
					else
					{
						_trans = ( unsigned int  ) _errintrans_index_defaults[(fsm->cs)];
					}
					
					
				}
				
				if ( _cont == 1  )
				{
					(fsm->cs) = ( int ) _errintrans_cond_targs[_trans];
					if ( (fsm->cs) == 0  )
					_cont = 0;
					
					if ( _cont == 1  )
					p += 1;
					
				}
			}
			
		}
		
	}
}

int errintrans_finish( struct errintrans *fsm )
{
	if ( fsm->cs == errintrans_error )
	return -1;
	if ( fsm->cs >= errintrans_first_final )
	return 1;
	return 0;
}


struct errintrans fsm;
#include <string.h>

void test( char *buf )
{
	int len = strlen( buf );
	errintrans_init( &fsm );
	errintrans_execute( &fsm, buf, len );
	if ( errintrans_finish( &fsm ) > 0 )
	printf("ACCEPT\n");
	else
	printf("FAIL\n");
}


int main()
{
	test(
	"good, does not have numbers\n"
	);
	
	test(
	"bad, has numbers 666\n"
	);
	
	return 0;
}

