const _patact_key_offsets = Int8[0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 25, 28, 32, 35, 41, 43, 45, 53, 56, 60, 63, 0 , ]
const _patact_trans_keys = UInt8[102, 111, 105, 108, 102, 111, 105, 108, 102, 111, 105, 108, 102, 111, 105, 108, 10, 32, 33, 50, 59, 48, 57, 97, 122, 32, 48, 57, 32, 50, 48, 57, 32, 97, 122, 10, 32, 48, 57, 97, 122, 48, 57, 97, 122, 10, 32, 33, 50, 48, 57, 97, 122, 32, 48, 57, 32, 50, 48, 57, 32, 97, 122, 59, 0 , ]
const _patact_single_lengths = Int8[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 5, 1, 2, 1, 2, 0, 0, 4, 1, 2, 1, 1, 0 , ]
const _patact_range_lengths = Int8[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 0, 0 , ]
const _patact_index_offsets = Int8[0, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 40, 43, 47, 50, 55, 57, 59, 66, 69, 73, 76, 0 , ]
const _patact_trans_cond_spaces = Int8[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0 , ]
const _patact_trans_offsets = Int8[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 0 , ]
const _patact_trans_lengths = Int8[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0 , ]
const _patact_cond_keys = Int8[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 , ]
const _patact_cond_targs = Int8[2, 17, 3, 17, 4, 17, 17, 17, 6, 17, 7, 17, 8, 17, 17, 17, 10, 24, 11, 24, 12, 24, 24, 24, 14, 24, 15, 24, 16, 24, 24, 24, 17, 17, 17, 19, 17, 18, 20, 0, 1, 18, 17, 1, 18, 18, 17, 5, 20, 17, 21, 21, 22, 23, 0, 22, 21, 23, 21, 24, 24, 24, 26, 25, 27, 0, 9, 25, 24, 9, 25, 25, 24, 13, 27, 24, 28, 0, 17, 17, 17, 17, 17, 17, 17, 17, 24, 24, 24, 24, 24, 24, 24, 24, 17, 17, 17, 21, 21, 24, 24, 24, 0 , ]
const _patact_cond_actions = Int8[0, 1, 0, 1, 0, 1, 2, 1, 0, 3, 0, 3, 0, 3, 4, 3, 0, 5, 0, 5, 0, 5, 6, 5, 0, 7, 0, 7, 0, 7, 8, 7, 11, 11, 12, 13, 14, 13, 15, 0, 0, 13, 1, 0, 17, 13, 16, 0, 15, 18, 19, 19, 0, 0, 0, 0, 20, 0, 21, 22, 22, 23, 24, 24, 15, 0, 0, 24, 5, 0, 26, 24, 25, 0, 15, 27, 28, 0, 1, 1, 1, 1, 3, 3, 3, 3, 5, 5, 5, 5, 7, 7, 7, 7, 1, 16, 18, 20, 21, 5, 25, 27, 0 , ]
const _patact_to_state_actions = Int8[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 9, 0, 0, 9, 0, 0, 0, 9, 0 , ]
const _patact_from_state_actions = Int8[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 0, 0, 0, 10, 0, 0, 10, 0, 0, 0, 10, 0 , ]
const _patact_eof_trans_indexed = Int8[0, 18, 18, 18, 18, 20, 20, 20, 20, 36, 36, 36, 36, 38, 38, 38, 38, 0, 18, 25, 26, 0, 32, 33, 0, 36, 42, 43, 0, 0 , ]
const _patact_eof_trans_direct = Int8[0, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 0, 95, 96, 97, 0, 98, 99, 0, 100, 101, 102, 0, 0 , ]
const _patact_nfa_targs = Int8[0, 0 , ]
const _patact_nfa_offsets = Int8[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 , ]
const _patact_nfa_push_actions = Int8[0, 0 , ]
const _patact_nfa_pop_trans = Int8[0, 0 , ]
const patact_start  = 17
const patact_first_final  = 17
const patact_error  = 0
const patact_en_other  = 21
const patact_en_exec_test  = 24
const patact_en_semi  = 28
const patact_en_main  = 17
function m( data::AbstractString )
	p = 0
	pe = length(data)
	eof = length(data)
	cs = 0
	buffer = ""
	comm = 0;
	top = 0;
	stack = Int [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ];
	ts = 0;
	te = 0;
	act = 0;
	value = 0;
	
	cs = convert(Int, patact_start )
	ts = 0
	te = 0
	act = 0
	_klen= 0
	;
	_keys = 0;
	_ckeys = 0;
	_cpc= 0
	;
	_trans= 0
	;
	_cond = 0;
	_have = 0;
	_cont = 1;
	while _cont == 1 
		if cs == 0 
			_cont = 0
			
		end
		_have = 0
		if p == pe 
			if p == eof 
				if _patact_eof_trans_direct[1+(cs)]> 0 
					_trans = convert(UInt, _patact_eof_trans_direct[1+(cs)] )- 1
					_cond = convert(UInt, _patact_trans_offsets[1+(_trans)] )
					_have = 1
					
				end
				if _have == 0 
					
				end
				
			end
			if _have == 0 
				_cont = 0
				
			end
			
		end
		if _cont == 1 
			if _have == 0 
				if _patact_from_state_actions[1+(cs)] == 10 
					{
						ts = p
						
					}
					
				end
				_keys = _patact_key_offsets[1+(cs)]
				_trans = convert(UInt, _patact_index_offsets[1+(cs)] )
				_have = 0
				_klen = convert(Int, _patact_single_lengths[1+(cs)] )
				if _klen > 0 
					_lower = 0;
					_mid = 0;
					_upper = 0;
					_lower = _keys
					_upper = _keys + _klen - 1
					while _upper >= _lower && _have == 0 
						_mid = _lower + ((_upper-_lower)>> 1)
						if (data[1+(p )])< _patact_trans_keys[1+(_mid )]
							_upper = _mid - 1
							
						elseif (data[1+(p )])> _patact_trans_keys[1+(_mid )]
							_lower = _mid + 1
							
						else
							_trans += convert(UInt, (_mid - _keys) )
							_have = 1
							
						end
						
					end
					if _have == 0 
						_keys += _klen
						_trans += convert(UInt, _klen )
						
					end
					
				end
				if _have == 0 
					_klen = convert(Int, _patact_range_lengths[1+(cs)] )
					if _klen > 0 
						_lower = 0;
						_mid = 0;
						_upper = 0;
						_lower = _keys
						_upper = _keys + (_klen<<1)- 2
						while _have == 0 && _lower <= _upper 
							_mid = _lower + (((_upper-_lower)>> 1)& ~1)
							if (data[1+(p )])< _patact_trans_keys[1+(_mid )]
								_upper = _mid - 2
								
							elseif (data[1+(p )])> _patact_trans_keys[1+(_mid + 1 )]
								_lower = _mid + 2
								
							else
								_trans += convert(UInt, ((_mid - _keys)>>1) )
								_have = 1
								
							end
							
						end
						if _have == 0 
							_trans += convert(UInt, _klen )
							
						end
						
					end
					
				end
				_ckeys = _patact_trans_offsets[1+(_trans)]
				_klen = convert(Int, _patact_trans_lengths[1+(_trans)] )
				_cond = convert(UInt, _patact_trans_offsets[1+(_trans)] )
				_have = 0
				_cpc = 0
				_lower = 0;
				_mid = 0;
				_upper = 0;
				_lower = _ckeys
				_upper = _ckeys + _klen - 1
				while _have == 0 && _lower <= _upper 
					_mid = _lower + ((_upper-_lower)>> 1)
					if _cpc < convert(Int, _patact_cond_keys[1+(_mid )] )
						_upper = _mid - 1
						
					elseif _cpc > convert(Int, _patact_cond_keys[1+(_mid )] )
						_lower = _mid + 1
						
					else
						_cond += convert(UInt, (_mid - _ckeys) )
						_have = 1
						
					end
					
				end
				if _have == 0 
					cs = 0
					_cont = 0
					
				end
				
			end
			if _cont == 1 
				cs = convert(Int, _patact_cond_targs[1+(_cond)] )
				if _patact_cond_actions[1+(_cond)] == 15 
					{
						te = p+1
						
					}
					
				elseif _patact_cond_actions[1+(_cond)] == 19 
					{
						te = p+1
						print( "space\n" );
						
					}
					
				elseif _patact_cond_actions[1+(_cond)] == 21 
					{
						te = p
						p = p - 1
						print( "word\n" );
						
					}
					
				elseif _patact_cond_actions[1+(_cond)] == 20 
					{
						te = p
						p = p - 1
						print( "num\n" );
						
					}
					
				elseif _patact_cond_actions[1+(_cond)] == 8 
					{
						te = p+1
						print( "word (c/lbh)\n" );
						
					}
					
				elseif _patact_cond_actions[1+(_cond)] == 22 
					{
						te = p+1
						print( "space\n" );
						
					}
					
				elseif _patact_cond_actions[1+(_cond)] == 6 
					{
						te = p+1
						print( "num (c/switch)\n" );
						
					}
					
				elseif _patact_cond_actions[1+(_cond)] == 23 
					{
						te = p+1
						
					}
					
				elseif _patact_cond_actions[1+(_cond)] == 27 
					{
						te = p
						p = p - 1
						print( "word (w/lbh)\n" );
						{
							p = ((te-1))-1
							
						}
						
						{
							cs = 21
							
						}
						
					}
					
				elseif _patact_cond_actions[1+(_cond)] == 25 
					{
						te = p
						p = p - 1
						print( "num (w/switch)\n" );
						{
							p = ((te-1))-1
							
						}
						
						{
							cs = 21
							
						}
						
					}
					
				elseif _patact_cond_actions[1+(_cond)] == 7 
					{
						p = ((te))-1
						print( "word (w/lbh)\n" );
						{
							p = ((te-1))-1
							
						}
						
						{
							cs = 21
							
						}
						
					}
					
				elseif _patact_cond_actions[1+(_cond)] == 5 
					{
						if act  == 7 
							p = ((te))-1
							print( "num (w/switch)\n" );
							
						elseif act  == 8 
							p = ((te))-1
							print( "num (w/switch)\n" );
							{
								p = ((te-1))-1
								
							}
							
							{
								cs = 21
								
							}
							
						end
						
					}
					
					
				elseif _patact_cond_actions[1+(_cond)] == 28 
					{
						te = p+1
						print( "in semi\n" );
						{
							cs = 17
							
						}
						
					}
					
				elseif _patact_cond_actions[1+(_cond)] == 4 
					{
						te = p+1
						print( "word (c/lbh)\n" );
						
					}
					
				elseif _patact_cond_actions[1+(_cond)] == 11 
					{
						te = p+1
						print( "space\n" );
						
					}
					
				elseif _patact_cond_actions[1+(_cond)] == 2 
					{
						te = p+1
						print( "num (c/switch)\n" );
						
					}
					
				elseif _patact_cond_actions[1+(_cond)] == 14 
					{
						te = p+1
						print( "going to semi\n" );
						{
							p = p - 1
							
						}
						{
							cs = 28
							
						}
						
					}
					
				elseif _patact_cond_actions[1+(_cond)] == 12 
					{
						te = p+1
						print( "immdiate\n" );
						{
							cs = 24
							
						}
						
					}
					
				elseif _patact_cond_actions[1+(_cond)] == 18 
					{
						te = p
						p = p - 1
						print( "word (w/lbh)\n" );
						{
							p = p - 1
							
						}
						{
							cs = 21
							
						}
						
					}
					
				elseif _patact_cond_actions[1+(_cond)] == 16 
					{
						te = p
						p = p - 1
						print( "num (w/switch)\n" );
						{
							p = p - 1
							
						}
						{
							cs = 21
							
						}
						
					}
					
				elseif _patact_cond_actions[1+(_cond)] == 3 
					{
						p = ((te))-1
						print( "word (w/lbh)\n" );
						{
							p = p - 1
							
						}
						{
							cs = 21
							
						}
						
					}
					
				elseif _patact_cond_actions[1+(_cond)] == 1 
					{
						if act  == 15 
							p = ((te))-1
							print( "num (w/switch)\n" );
							
						elseif act  == 16 
							p = ((te))-1
							print( "num (w/switch)\n" );
							{
								p = p - 1
								
							}
							{
								cs = 21
								
							}
							
						end
						
					}
					
					
				elseif _patact_cond_actions[1+(_cond)] == 26 
					{
						te = p+1
						
					}
					{
						act = 7
						
					}
					
				elseif _patact_cond_actions[1+(_cond)] == 24 
					{
						te = p+1
						
					}
					{
						act = 8
						
					}
					
				elseif _patact_cond_actions[1+(_cond)] == 17 
					{
						te = p+1
						
					}
					{
						act = 15
						
					}
					
				elseif _patact_cond_actions[1+(_cond)] == 13 
					{
						te = p+1
						
					}
					{
						act = 16
						
					}
					
				end
				if _patact_to_state_actions[1+(cs)] == 9 
					{
						ts = 0
						
					}
					
				end
				if cs == 0 
					_cont = 0
					
				end
				if _cont == 1 
					p += 1
					
				end
				
			end
			
		end
		
	end
	if ( cs >= patact_first_final )
		println( "ACCEPT" );
	else
		println( "FAIL" );
	end
end

m( "abcd foix\n" );
m( "abcd\nanother\n" );
m( "123 foix\n" );
m( "!abcd foix\n" );
m( "!abcd\nanother\n" );
m( "!123 foix\n" );
m( ";" );
