const _rangei_trans_keys = UInt8[1, 0, 1, 2, 1, 2, 0, 3, 1, 5, 1, 4, 0, 5, 1, 0, 0 , ]
const _rangei_char_class = Int8[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 3, 3, 3, 4, 4, 4, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 5, 5, 5, 0 , ]
const _rangei_index_offsets = Int8[0, 0, 2, 4, 8, 13, 17, 23, 0 , ]
const _rangei_indicies = Int8[0, 0, 2, 2, 3, 3, 3, 3, 4, 4, 1, 4, 4, 5, 1, 5, 5, 6, 6, 6, 6, 6, 6, 0 , ]
const _rangei_index_defaults = Int8[0, 1, 1, 1, 1, 1, 1, 1, 0 , ]
const _rangei_trans_cond_spaces = Int8[-1, -1, -1, -1, -1, -1, -1, 0 , ]
const _rangei_cond_targs = Int8[2, 0, 3, 4, 5, 6, 7, 0 , ]
const _rangei_cond_actions = Int8[0, 0, 0, 0, 0, 0, 0, 0 , ]
const _rangei_nfa_targs = Int8[0, 0 , ]
const _rangei_nfa_offsets = Int8[0, 0, 0, 0, 0, 0, 0, 0, 0 , ]
const _rangei_nfa_push_actions = Int8[0, 0 , ]
const _rangei_nfa_pop_trans = Int8[0, 0 , ]
const rangei_start  = 1
const rangei_first_final  = 7
const rangei_error  = 0
const rangei_en_main  = 1
function m( data::AbstractString )
	p = 0
	pe = length(data)
	eof = length(data)
	cs = 0
	buffer = ""
	
	cs = convert(Int, rangei_start )
	_trans = 0;
	_have = 0;
	_cont = 1;
	_keys = 0;
	_inds = 0;
	while _cont == 1 
		if cs == 0 
			_cont = 0
			
		end
		_have = 0
		if p == pe 
			if _have == 0 
				_cont = 0
				
			end
			
		end
		if _cont == 1 
			if _have == 0 
				_keys = (cs<<1)
				_inds = _rangei_index_offsets[1+(cs)]
				if (data[1+(p )])<= 125 && (data[1+(p )])>= 60 
					_ic = convert(Int, _rangei_char_class[1+(convert(Int, (data[1+(p )]) )- 60)] );
					if _ic <= convert(Int, _rangei_trans_keys[1+(_keys+1 )] )&& _ic >= convert(Int, _rangei_trans_keys[1+(_keys )] )
						_trans = convert(UInt, _rangei_indicies[1+(_inds + convert(Int, (_ic - convert(Int, _rangei_trans_keys[1+(_keys )] )) ))] )
						
					else
						_trans = convert(UInt, _rangei_index_defaults[1+(cs)] )
						
					end
					
				else
					_trans = convert(UInt, _rangei_index_defaults[1+(cs)] )
					
				end
				
			end
			if _cont == 1 
				cs = convert(Int, _rangei_cond_targs[1+(_trans)] )
				if cs == 0 
					_cont = 0
					
				end
				if _cont == 1 
					p += 1
					
				end
				
			end
			
		end
		
	end
	if ( cs >= rangei_first_final )
		println( "ACCEPT" );
	else
		println( "FAIL" );
	end
end

m( "AaBbAa" );
m( "Aa`bAa" );
m( "AaB@Aa" );
m( "AaBbMa" );
m( "AaBbma" );
