static _rangei_trans_keys: [u8 ; 18] = [ 1, 0, 1, 2, 1, 2, 0, 3, 1, 5, 1, 4, 0, 5, 1, 0, 0 , 0 ];
static _rangei_char_class: [i8 ; 68] = [ 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 3, 3, 3, 4, 4, 4, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 5, 5, 5, 0 , 0 ];
static _rangei_index_offsets: [i8 ; 10] = [ 0, 0, 2, 4, 8, 13, 17, 23, 0 , 0 ];
static _rangei_indicies: [i8 ; 25] = [ 0, 0, 2, 2, 3, 3, 3, 3, 4, 4, 1, 4, 4, 5, 1, 5, 5, 6, 6, 6, 6, 6, 6, 0 , 0 ];
static _rangei_index_defaults: [i8 ; 10] = [ 0, 1, 1, 1, 1, 1, 1, 1, 0 , 0 ];
static _rangei_trans_cond_spaces: [i8 ; 9] = [ -1, -1, -1, -1, -1, -1, -1, 0 , 0 ];
static _rangei_cond_targs: [i8 ; 9] = [ 2, 0, 3, 4, 5, 6, 7, 0 , 0 ];
static _rangei_cond_actions: [i8 ; 9] = [ 0, 0, 0, 0, 0, 0, 0, 0 , 0 ];
static _rangei_nfa_targs: [i8 ; 3] = [ 0, 0 , 0 ];
static _rangei_nfa_offsets: [i8 ; 10] = [ 0, 0, 0, 0, 0, 0, 0, 0, 0 , 0 ];
static _rangei_nfa_push_actions: [i8 ; 3] = [ 0, 0 , 0 ];
static _rangei_nfa_pop_trans: [i8 ; 3] = [ 0, 0 , 0 ];
static rangei_start : i32 = 1;
static rangei_first_final : i32 = 7;
static rangei_error : i32 = 0;
static rangei_en_main : i32 = 1;
unsafe fn m( s: String )
{
	let data: &[u8] = s.as_bytes();
	let mut p:i32 = 0;
	let mut pe:i32 = s.len() as i32;
	let mut eof:i32 = s.len() as i32;
	let mut cs: i32 = 0;
	let mut buffer = String::new();
	
	
	{
		cs = ( rangei_start ) as i32;
	}
	
	{
		let mut _trans  = 0;
		let mut _have  = 0;
		let mut _cont  = 1;
		let mut _keys :i32 = 0;
		let mut _inds :i32 = 0;
		while ( _cont == 1  )
		{
		
			if ( cs == 0  ) {
				_cont = 0;
				
			}
			_have = 0;
			if ( p == pe  ) {
				{
					if ( _have == 0  ) {
						_cont = 0;
						
					}
				}
				
			}
			if ( _cont == 1  ) {
				{
					if ( _have == 0  ) {
						{
							_keys = ( (cs<<1)  ) as i32;
							_inds = ( _rangei_index_offsets[(cs) as usize] ) as i32;
							if ( ( data[(p ) as usize]
							) <= 125 && ( data[(p ) as usize]
							) >= 60  ) {
								{
									let mut _ic  = ( _rangei_char_class[(( ( data[(p ) as usize]
									)  ) as i32- 60) as usize] ) as i32;
									if ( _ic <= ( _rangei_trans_keys[(_keys+1 ) as usize]
									) as i32&& _ic >= ( _rangei_trans_keys[(_keys ) as usize]
									) as i32 ) {
										_trans = ( _rangei_indicies[(_inds + ( ( _ic - ( _rangei_trans_keys[(_keys ) as usize]
										) as i32)   ) as i32) as usize]
										) as u32;
										
									}
									else {
										_trans = ( _rangei_index_defaults[(cs) as usize] ) as u32;
										
									}
								}
								
							}
							else {
								{
									_trans = ( _rangei_index_defaults[(cs) as usize] ) as u32;
								}
								
								
							}
						}
						
					}
					if ( _cont == 1  ) {
						{
							cs = ( _rangei_cond_targs[(_trans) as usize] ) as i32;
							if ( cs == 0  ) {
								_cont = 0;
								
							}
							if ( _cont == 1  ) {
								p += 1;
								
							}
						}
					}
				}
				
			}
		}
		
	}
	if ( cs >= rangei_first_final ) {
		println!( "ACCEPT" );
	}
	else {
		println!( "FAIL" );
	}
}

fn main()
{
	unsafe { m( "AaBbAa".to_string() ); }
	unsafe { m( "Aa`bAa".to_string() ); }
	unsafe { m( "AaB@Aa".to_string() ); }
	unsafe { m( "AaBbMa".to_string() ); }
	unsafe { m( "AaBbma".to_string() ); }
}

