import crack.io cout;
import crack.lang Buffer;







const array[int16 ] _rangei_key_offsets = [ 0, 0, 4, 8, 12, 16, 22, 24, 0 ,  ];
const array[byte ] _rangei_trans_keys = [ 65, 90, 97, 122, 65, 90, 97, 122, 60, 93, 97, 122, 65, 90, 94, 125, 65, 69, 86, 101, 118, 122, 60, 125, 0,  ];
const array[int16 ] _rangei_single_lengths = [ 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  ];
const array[int16 ] _rangei_range_lengths = [ 0, 2, 2, 2, 2, 3, 1, 0, 0 ,  ];
const array[int16 ] _rangei_index_offsets = [ 0, 0, 3, 6, 9, 12, 16, 18, 0 ,  ];
const array[int16 ] _rangei_trans_cond_spaces = [ -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0 ,  ];
const array[int16 ] _rangei_trans_offsets = [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 0 ,  ];
const array[int16 ] _rangei_trans_lengths = [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0 ,  ];
const array[int16 ] _rangei_cond_keys = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  ];
const array[int16 ] _rangei_cond_targs = [ 2, 2, 0, 3, 3, 0, 4, 4, 0, 5, 5, 0, 6, 6, 6, 0, 7, 0, 0, 0 ,  ];
const array[int16 ] _rangei_cond_actions = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  ];
const array[int16 ] _rangei_nfa_targs = [ 0, 0 ,  ];
const array[int16 ] _rangei_nfa_offsets = [ 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  ];
const array[int16 ] _rangei_nfa_push_actions = [ 0, 0 ,  ];
const array[int16 ] _rangei_nfa_pop_trans = [ 0, 0 ,  ];
const int  rangei_start  = 1;
const int  rangei_first_final  = 7;
const int  rangei_error  = 0;
const int  rangei_en_main  = 1;
void m( String s )
{
	byteptr data = s.buffer;
	int p = 0;
	int pe = s.size;
	int cs;
	String buffer;
	
	if ( 1 ) {
		cs = int ( rangei_start );
		
	}
	if ( 1 ) {
		int _klen;
		int _keys = 0;
		int _ckeys = 0;
		int _cpc;
		uint32 _trans;
		uint32 _cond = 0;
		uint32 _have = 0;
		uint32 _cont = 1;
		while ( _cont == 1  )
		{
			if ( cs == 0  )
			_cont = 0;
			
			_have = 0;
			if ( p == pe  )
			{
				if ( _have == 0  )
				_cont = 0;
				
				
			}
			
			if ( _cont == 1  )
			{
				if ( _have == 0  )
				{
					_keys = _rangei_key_offsets[cs];
					_trans = uint32  ( _rangei_index_offsets[cs] );
					_have = 0;
					_klen = int ( _rangei_single_lengths[cs] );
					if ( _klen > 0  )
					{
						int _lower = 0;
						int _mid = 0;
						int _upper = 0;
						_lower = _keys;
						_upper = _keys + _klen - 1;
						while ( _upper >= _lower && _have == 0  )
						{
							_mid = _lower + ((_upper-_lower)>> 1);
							if ( (data[p ])< _rangei_trans_keys[_mid ] )
							_upper = _mid - 1;
							
							else if ( (data[p ])> _rangei_trans_keys[_mid ] )
							_lower = _mid + 1;
							
							else
							{
								_trans += uint32  ( (_mid - _keys) );
								_have = 1;
								
							}
							
							
						}
						
						if ( _have == 0  )
						{
							_keys += _klen;
							_trans += uint32  ( _klen );
							
						}
						
						
					}
					
					if ( _have == 0  )
					{
						_klen = int ( _rangei_range_lengths[cs] );
						if ( _klen > 0  )
						{
							int _lower = 0;
							int _mid = 0;
							int _upper = 0;
							_lower = _keys;
							_upper = _keys + (_klen<<1)- 2;
							while ( _have == 0 && _lower <= _upper  )
							{
								_mid = _lower + (((_upper-_lower)>> 1)& ~1);
								if ( (data[p ])< _rangei_trans_keys[_mid ] )
								_upper = _mid - 2;
								
								else if ( (data[p ])> _rangei_trans_keys[_mid + 1 ] )
								_lower = _mid + 2;
								
								else
								{
									_trans += uint32  ( ((_mid - _keys)>>1) );
									_have = 1;
									
								}
								
								
							}
							
							if ( _have == 0  )
							_trans += uint32  ( _klen );
							
							
						}
						
						
					}
					
					_ckeys = _rangei_trans_offsets[_trans];
					_klen = int ( _rangei_trans_lengths[_trans] );
					_cond = uint32  ( _rangei_trans_offsets[_trans] );
					_have = 0;
					_cpc = 0;
					if ( 1 ) {
						int _lower = 0;
						int _mid = 0;
						int _upper = 0;
						_lower = _ckeys;
						_upper = _ckeys + _klen - 1;
						while ( _have == 0 && _lower <= _upper  )
						{
							_mid = _lower + ((_upper-_lower)>> 1);
							if ( _cpc < int ( _rangei_cond_keys[_mid ] ) )
							_upper = _mid - 1;
							
							else if ( _cpc > int ( _rangei_cond_keys[_mid ] ) )
							_lower = _mid + 1;
							
							else
							{
								_cond += uint32  ( (_mid - _ckeys) );
								_have = 1;
								
							}
							
							
						}
						
						if ( _have == 0  )
						{
							cs = 0;
							_cont = 0;
							
						}
						
						
					}
					
				}
				
				if ( _cont == 1  )
				{
					cs = int ( _rangei_cond_targs[_cond] );
					if ( cs == 0  )
					_cont = 0;
					
					if ( _cont == 1  )
					p += 1;
					
					
				}
				
				
			}
			
			
		}
		
		
	}
	if ( cs >= rangei_first_final ) {
		cout `ACCEPT\n`;
	}
	else {
		cout `FAIL\n`;
	}
}

void main()
{
	m( "AaBbAa" );
	m( "Aa`bAa" );
	m( "AaB@Aa" );
	m( "AaBbMa" );
	m( "AaBbma" );
}

main();
