const _scanner_actions = Int8[0, 1, 2, 1, 3, 1, 6, 1, 7, 1, 8, 1, 9, 1, 10, 1, 11, 1, 12, 1, 13, 2, 0, 1, 2, 3, 4, 2, 3, 5, 0 , ]
const _scanner_key_offsets = Int8[0, 0, 4, 5, 6, 7, 8, 14, 21, 22, 23, 0 , ]
const _scanner_trans_keys = UInt8[46, 100, 48, 57, 49, 120, 120, 120, 46, 49, 50, 100, 48, 57, 10, 97, 98, 99, 100, 48, 57, 98, 100, 46, 100, 48, 57, 0 , ]
const _scanner_single_lengths = Int8[0, 2, 1, 1, 1, 1, 4, 5, 1, 1, 2, 0 , ]
const _scanner_range_lengths = Int8[0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0 , ]
const _scanner_index_offsets = Int8[0, 0, 4, 6, 8, 10, 12, 18, 25, 27, 29, 0 , ]
const _scanner_trans_cond_spaces = Int8[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0 , ]
const _scanner_trans_offsets = Int8[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 0 , ]
const _scanner_trans_lengths = Int8[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0 , ]
const _scanner_cond_keys = Int8[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 , ]
const _scanner_cond_targs = Int8[7, 1, 1, 7, 9, 0, 4, 7, 5, 7, 7, 7, 7, 10, 10, 1, 1, 0, 7, 7, 8, 2, 6, 1, 0, 8, 7, 3, 7, 7, 1, 1, 7, 7, 7, 7, 7, 7, 7, 7, 0 , ]
const _scanner_cond_actions = Int8[9, 0, 0, 19, 3, 0, 0, 17, 0, 17, 7, 17, 9, 24, 27, 0, 0, 0, 11, 5, 0, 0, 0, 0, 0, 0, 13, 0, 15, 9, 0, 0, 19, 19, 17, 17, 17, 13, 15, 19, 0 , ]
const _scanner_to_state_actions = Int8[0, 0, 0, 0, 0, 0, 0, 21, 0, 0, 0, 0 , ]
const _scanner_from_state_actions = Int8[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0 , ]
const _scanner_eof_trans_indexed = Int8[0, 8, 0, 10, 10, 10, 0, 0, 14, 15, 8, 0 , ]
const _scanner_eof_trans_direct = Int8[0, 34, 0, 35, 36, 37, 0, 0, 38, 39, 40, 0 , ]
const _scanner_nfa_targs = Int8[0, 0 , ]
const _scanner_nfa_offsets = Int8[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 , ]
const _scanner_nfa_push_actions = Int8[0, 0 , ]
const _scanner_nfa_pop_trans = Int8[0, 0 , ]
const scanner_start  = 7
const scanner_first_final  = 7
const scanner_error  = 0
const scanner_en_main  = 7
function m( data::AbstractString )
	p = 0
	pe = length(data)
	eof = length(data)
	cs = 0
	buffer = ""
	ts = 0;
	te = 0;
	act = 0;
	token = 0;
	
	cs = convert(Int, scanner_start )
	ts = 0
	te = 0
	act = 0
	_klen= 0
	;
	_trans = 0;
	_cond = 0;
	_have = 0;
	_cont = 1;
	_acts = 0;
	_nacts= 0
	;
	_keys = 0;
	_ckeys = 0;
	_cpc= 0
	;
	while _cont == 1 
		if cs == 0 
			_cont = 0
			
		end
		_have = 0
		if p == pe 
			if p == eof 
				if _scanner_eof_trans_direct[1+(cs)]> 0 
					_trans = convert(UInt, _scanner_eof_trans_direct[1+(cs)] )- 1
					_cond = convert(UInt, _scanner_trans_offsets[1+(_trans)] )
					_have = 1
					
				end
				if _have == 0 
					
				end
				
			end
			if _have == 0 
				_cont = 0
				
			end
			
		end
		if _cont == 1 
			if _have == 0 
				_acts = _scanner_from_state_actions[1+(cs)]
				_nacts = convert(UInt, _scanner_actions[1+(_acts )] )
				_acts += 1
				while _nacts > 0 
					if _scanner_actions[1+(_acts )] == 2 
						{
							ts = p
							
						}
						
					end
					_nacts -= 1
					_acts += 1
					
				end
				_keys = _scanner_key_offsets[1+(cs)]
				_trans = convert(UInt, _scanner_index_offsets[1+(cs)] )
				_have = 0
				_klen = convert(Int, _scanner_single_lengths[1+(cs)] )
				if _klen > 0 
					_lower = 0;
					_mid = 0;
					_upper = 0;
					_lower = _keys
					_upper = _keys + _klen - 1
					while _upper >= _lower && _have == 0 
						_mid = _lower + ((_upper-_lower)>> 1)
						if (data[1+(p )])< _scanner_trans_keys[1+(_mid )]
							_upper = _mid - 1
							
						elseif (data[1+(p )])> _scanner_trans_keys[1+(_mid )]
							_lower = _mid + 1
							
						else
							_trans += convert(UInt, (_mid - _keys) )
							_have = 1
							
						end
						
					end
					if _have == 0 
						_keys += _klen
						_trans += convert(UInt, _klen )
						
					end
					
				end
				if _have == 0 
					_klen = convert(Int, _scanner_range_lengths[1+(cs)] )
					if _klen > 0 
						_lower = 0;
						_mid = 0;
						_upper = 0;
						_lower = _keys
						_upper = _keys + (_klen<<1)- 2
						while _have == 0 && _lower <= _upper 
							_mid = _lower + (((_upper-_lower)>> 1)& ~1)
							if (data[1+(p )])< _scanner_trans_keys[1+(_mid )]
								_upper = _mid - 2
								
							elseif (data[1+(p )])> _scanner_trans_keys[1+(_mid + 1 )]
								_lower = _mid + 2
								
							else
								_trans += convert(UInt, ((_mid - _keys)>>1) )
								_have = 1
								
							end
							
						end
						if _have == 0 
							_trans += convert(UInt, _klen )
							
						end
						
					end
					
				end
				_ckeys = _scanner_trans_offsets[1+(_trans)]
				_klen = convert(Int, _scanner_trans_lengths[1+(_trans)] )
				_cond = convert(UInt, _scanner_trans_offsets[1+(_trans)] )
				_have = 0
				_cpc = 0
				_lower = 0;
				_mid = 0;
				_upper = 0;
				_lower = _ckeys
				_upper = _ckeys + _klen - 1
				while _have == 0 && _lower <= _upper 
					_mid = _lower + ((_upper-_lower)>> 1)
					if _cpc < convert(Int, _scanner_cond_keys[1+(_mid )] )
						_upper = _mid - 1
						
					elseif _cpc > convert(Int, _scanner_cond_keys[1+(_mid )] )
						_lower = _mid + 1
						
					else
						_cond += convert(UInt, (_mid - _ckeys) )
						_have = 1
						
					end
					
				end
				if _have == 0 
					cs = 0
					_cont = 0
					
				end
				
			end
			if _cont == 1 
				cs = convert(Int, _scanner_cond_targs[1+(_cond)] )
				if _scanner_cond_actions[1+(_cond)]!= 0 
					_acts = _scanner_cond_actions[1+(_cond)]
					_nacts = convert(UInt, _scanner_actions[1+(_acts )] )
					_acts += 1
					while _nacts > 0 
						if _scanner_actions[1+(_acts )] == 3 
							{
								te = p+1
								
							}
							
						elseif _scanner_actions[1+(_acts )] == 4 
							{
								act = 4
								
							}
							
						elseif _scanner_actions[1+(_acts )] == 5 
							{
								act = 5
								
							}
							
						elseif _scanner_actions[1+(_acts )] == 6 
							{
								te = p+1
								print( "on last     " );
								if ( p + 1 == te )
									print( "yes" );
									
								end
								print( "\n" );
								
							}
							
						elseif _scanner_actions[1+(_acts )] == 7 
							{
								te = p+1
								print( "on lag      " );
								if ( p + 1 == te )
									print( "yes" );
									
								end
								print( "\n" );
								
							}
							
						elseif _scanner_actions[1+(_acts )] == 8 
							{
								te = p+1
								
							}
							
						elseif _scanner_actions[1+(_acts )] == 9 
							{
								te = p+1
								
							}
							
						elseif _scanner_actions[1+(_acts )] == 10 
							{
								te = p
								p = p - 1
								print( "on next     " );
								if ( p + 1 == te )
									print( "yes" );
									
								end
								print( "\n" );
								
							}
							
						elseif _scanner_actions[1+(_acts )] == 11 
							{
								te = p
								p = p - 1
								print( "on lag      " );
								if ( p + 1 == te )
									print( "yes" );
									
								end
								print( "\n" );
								
							}
							
						elseif _scanner_actions[1+(_acts )] == 12 
							{
								p = ((te))-1
								print( "on lag      " );
								if ( p + 1 == te )
									print( "yes" );
									
								end
								print( "\n" );
								
							}
							
						elseif _scanner_actions[1+(_acts )] == 13 
							{
								if act  == 0 
									{
										cs = 0
										
									}
									
								elseif act  == 4 
									p = ((te))-1
									print( "lm switch1  " );
									if ( p + 1 == te )
										print( "yes" );
										
									end
									print( "\n" );
									
								elseif act  == 5 
									p = ((te))-1
									print( "lm switch2  " );
									if ( p + 1 == te )
										print( "yes" );
										
									end
									print( "\n" );
									
								end
								
							}
							
							
						end
						_nacts -= 1
						_acts += 1
						
					end
					
				end
				_acts = _scanner_to_state_actions[1+(cs)]
				_nacts = convert(UInt, _scanner_actions[1+(_acts )] )
				_acts += 1
				while _nacts > 0 
					if _scanner_actions[1+(_acts )] == 0 
						{
							ts = 0
							
						}
						
					elseif _scanner_actions[1+(_acts )] == 1 
						{
							act = 0
							
						}
						
					end
					_nacts -= 1
					_acts += 1
					
				end
				if cs == 0 
					_cont = 0
					
				end
				if _cont == 1 
					p += 1
					
				end
				
			end
			
		end
		
	end
	if ( cs >= scanner_first_final )
		println( "ACCEPT" );
	else
		println( "FAIL" );
	end
end

m( "abbc1d1d2\n" );
